// angular-material/src/app/dashboard/project-management/working-schedule/working-schedule.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { CarouselModule, OwlOptions } from 'ngx-owl-carousel-o';
import { MatNativeDateModule } from '@angular/material/core';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-working-schedule',
    imports: [MatCardModule, MatDatepickerModule, CarouselModule, MatNativeDateModule],
    templateUrl: './working-schedule.component.html',
    styleUrl: './working-schedule.component.scss'
})
export class WorkingScheduleComponent {

	// Owl Carousel
    upcomingEventsSlides: OwlOptions = {
        items: 1,
		nav: false,
		loop: true,
		margin: 25,
		dots: true,
		autoplay: true,
		smartSpeed: 500,
		autoplayHoverPause: true,
		navText: [
			"<i class='ri-arrow-left-line'></i>",
			"<i class='ri-arrow-right-line'></i>"
		]
    }

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="working-schedule-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Working Schedule
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <mat-calendar></mat-calendar>
        <div class="upcoming-events">
            <span class="title d-block fw-medium">
                Upcoming Events:
            </span>
            <owl-carousel-o [options]="upcomingEventsSlides">
                <ng-template carouselSlide>
                    <div class="event-item position-relative">
                        <h6 class="fw-semibold">
                            Pythons Unleashed: A Development Expedition
                        </h6>
                        <span>
                            <span class="text-primary">
                                15 April 2024
                            </span>
                            -  12.00 PM - 6.00 PM
                        </span>
                    </div>
                </ng-template>
                <ng-template carouselSlide>
                    <div class="event-item position-relative">
                        <h6 class="fw-semibold">
                            Pythons Unleashed: A Development Expedition
                        </h6>
                        <span>
                            <span class="text-primary">
                                15 April 2024
                            </span>
                            -  12.00 PM - 6.00 PM
                        </span>
                    </div>
                </ng-template>
                <ng-template carouselSlide>
                    <div class="event-item position-relative">
                        <h6 class="fw-semibold">
                            Pythons Unleashed: A Development Expedition
                        </h6>
                        <span>
                            <span class="text-primary">
                                15 April 2024
                            </span>
                            -  12.00 PM - 6.00 PM
                        </span>
                    </div>
                </ng-template>
            </owl-carousel-o>
        </div>
    </mat-card-content>
</mat-card>

// laravel-vue/resources/components/Dashboard/ProjectManagement/WorkingSchedule.vue
<template>
    <v-card
        class="working-schedule-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Working Schedule</h5>
        </div>
        <div class="schedule-card-content">
            <CalendarContent />
            <div class="upcoming-events">
                <span class="title d-block fw-medium"> Upcoming Events: </span>
                <Carousel
                    v-bind="settings"
                    :autoplay="3000"
                    :wrap-around="true"
                >
                    <Slide v-for="slide in items" :key="slide.id">
                        <div class="event-item position-relative">
                            <h6 class="fw-semibold">
                                Pythons Unleashed: {{ slide.title }}
                            </h6>
                            <span>
                                <span class="text-primary">
                                    {{ slide.date }}
                                </span>
                                - {{ slide.startTime }} - {{ slide.endTime }}
                            </span>
                        </div>
                    </Slide>

                    <template #addons>
                        <Pagination />
                    </template>
                </Carousel>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";
import CalendarContent from "../../Common/CalendarContent.vue";

import { Carousel, Slide, Pagination } from "vue3-carousel";

import "vue3-carousel/dist/carousel.css";

export default defineComponent({
    name: "WorkingSchedule",
    components: {
        CalendarContent,
        Carousel,
        Slide,
        Pagination,
    },
    data: () => ({
        settings: {
            itemsToShow: 1,
            snapAlign: "center",
        },
        items: [
            {
                id: 1,
                title: "A Development Expedition",
                date: "June 25, 2024",
                startTime: "12.00 PM",
                endTime: "6.00 PM",
            },
            {
                id: 2,
                title: "A Development Expedition",
                date: "June 25, 2024",
                startTime: "12.00 PM",
                endTime: "6.00 PM",
            },
            {
                id: 3,
                title: "A Development Expedition",
                date: "June 25, 2024",
                startTime: "12.00 PM",
                endTime: "6.00 PM",
            },
        ],
    }),
});
</script>

<style lang="scss" scoped>
.working-schedule-card {
    .schedule-card-content {
        position: relative;

        .upcoming-events {
            margin-top: 30px;

            .title {
                margin-bottom: 15px;
            }
            .event-item {
                padding-left: 14px;

                h6 {
                    font-size: 13px;
                    margin-bottom: 5px;
                }
                span {
                    font-size: 12px;
                }
                &::before {
                    left: 0;
                    top: 3px;
                    width: 7px;
                    content: "";
                    height: 7px;
                    position: absolute;
                    border-radius: 2px;
                    background: var(--primaryColor);
                }
            }
        }
    }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
    .working-schedule-card {
        .schedule-card-content {
            .upcoming-events {
                margin-top: 10px;

                .title {
                    margin-bottom: 12px;
                }
                .event-item {
                    h6 {
                        margin-bottom: 6px;
                    }
                }
            }
        }
    }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
    .working-schedule-card {
        .schedule-card-content {
            .upcoming-events {
                margin-top: 12px;

                .title {
                    margin-bottom: 13px;
                }
            }
        }
    }
}
</style>
