// vuejs-vuetify/src/components/Modules/Forms/BasicElements/BasicForm.vue
<template>
  <div class="row">
    <div class="col-md-6">
      <v-card
        class="mb-25 trezo-card border-radius d-block bg-white border-0 shadow-none"
      >
        <div class="v-card-header">
          <h5 class="mb-0">Basic Form</h5>
        </div>
        <div class="basic-form">
          <form>
            <div class="trezo-form-group">
              <v-label class="d-block fw-medium text-black"> Name </v-label>
              <v-text-field label="Enter name"></v-text-field>
            </div>
            <div class="trezo-form-group">
              <v-label class="d-block fw-medium text-black">
                Email Address
              </v-label>
              <v-text-field label="Enter email address"></v-text-field>
            </div>
            <div class="trezo-form-group">
              <v-label class="d-block fw-medium text-black"> Password </v-label>
              <v-text-field label="Enter your password"></v-text-field>
            </div>
            <div class="info d-flex justify-content-between align-items-center">
              <v-checkbox label="Remember me"> </v-checkbox>
              <RouterLink
                to="/authentication/forgot-password"
                class="d-inline-block text-primary"
              >
                Forgot Password?
              </RouterLink>
            </div>
            <button class="btn" type="submit">Sign In</button>
          </form>
        </div>
      </v-card>
    </div>
  </div>
</template>

<script>
export default {
  name: "BasicForm",
};
</script>

<style lang="scss" scoped>
.basic-form {
  form {
    .btn {
      width: 100%;
      height: auto;
      display: block;
      min-width: auto;
      margin-top: 25px;
      padding: 12px 25px;
      border-radius: 7px;
      color: var(--whiteColor);
      background-color: var(--primaryColor);
      font: {
        size: 16px;
        weight: 500;
      }
    }
    .v-checkbox.v-input {
      margin: -18px -9px -40px -10px;
    }
    .v-input__details {
      display: none !important;
    }
    .v-selection-control__input {
      width: 0 !important;
      height: 0 !important;
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .basic-form {
    form {
      .btn {
        padding: 12px 25px;
        margin-top: 17px;
        font-size: 13px;
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .basic-form {
    form {
      .btn {
        margin-top: 20px;
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .basic-form {
    form {
      .btn {
        font-size: 14px;
        padding: 12px 25px;
      }
    }
  }
}

/* Min width 992px to Max width 1199px */
@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .basic-form {
    form {
      .btn {
        font-size: 15px;
      }
    }
  }
}
</style>

// angular-material/src/app/forms/basic-elements/basic-form/basic-form.component.ts
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatNativeDateModule } from '@angular/material/core';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { RouterLink } from '@angular/router';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-basic-form',
    imports: [RouterLink, MatCardModule, MatInputModule, MatFormFieldModule, MatSelectModule, MatNativeDateModule, MatCheckboxModule, MatButtonModule],
    templateUrl: './basic-form.component.html',
    styleUrl: './basic-form.component.scss'
})
export class BasicFormComponent {

    // Password Hide
    hide = true;

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<div
    class="basic-form"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <form>
        <div class="form-group">
            <label class="main-label d-block fw-medium text-black">
                Name
            </label>
            <mat-form-field>
                <mat-label>
                    Enter name
                </mat-label>
                <input matInput type="email">
            </mat-form-field>
        </div>
        <div class="form-group">
            <label class="main-label d-block fw-medium text-black">
                Email Address
            </label>
            <mat-form-field>
                <mat-label>
                    Enter email address
                </mat-label>
                <input matInput type="email">
            </mat-form-field>
        </div>
        <div class="form-group">
            <label class="main-label d-block fw-medium text-black">
                Password
            </label>
            <mat-form-field>
                <mat-label>
                    Enter your password
                </mat-label>
                <input matInput [type]="hide ? 'password' : 'text'" id="password" formControlName="password">
                <button mat-icon-button matSuffix (click)="hide = !hide" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hide">
                    <span class="material-symbols-outlined">
                        {{hide ? 'visibility_off' : 'visibility'}}
                    </span>
                </button>
            </mat-form-field>
        </div>
        <div class="info d-flex justify-content-between align-items-center">
            <mat-checkbox>
                Remember me
            </mat-checkbox>
            <a routerLink="." class="d-inline-block text-primary">
                Forgot Password?
            </a>
        </div>
        <button mat-button class="btn" type="submit">
            Sign In
        </button>
    </form>
</div>
