// nextjs-react-bootstrap/src/components/eCommerce/Orders/OrderDetails/DeliveryDetails.js
"use client";

import React from "react";
import Card from "react-bootstrap/Card";

const DeliveryDetails = () => {
  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <h3 className="mb-3">Delivery Details</h3>

          <div className="d-flex align-items-center mb-2">
            <span className="text-secondary">XYZ Delivery</span>
          </div>
          
          <div className="d-flex align-items-center mb-2">
            <span className="text-secondary">Order ID:</span>
            <span className="ms-1">XXXXXX1004</span>
          </div>

          <div className="d-flex align-items-center mb-2">
            <span className="text-secondary">Payment Method:</span>
            <span className="ms-1">Master Card</span>
          </div>

          <div className="d-flex align-items-center mb-0">
            <span className="text-secondary">Email:</span>
            <span className="ms-1">example@trezo.com</span>
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default DeliveryDetails;

// nuxtjs-tailwindcss/components/Pages/Ecommerce/OrderDetails/DeliveryDetails.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
  >
    <div
      class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between"
    >
      <div class="trezo-card-title">
        <h5 class="mb-0">Delivery Details</h5>
      </div>
    </div>
    <div class="trezo-card-content">
      <ul>
        <li class="mb-[12px] last:mb-0">
          <span class="text-black dark:text-white font-medium">
            XYZ Delivery
          </span>
        </li>
        <li class="mb-[12px] last:mb-0">
          <span class="text-black dark:text-white font-medium">
            Order ID:
          </span>
          XXXXXX1004
        </li>
        <li class="mb-[12px] last:mb-0">
          <span class="text-black dark:text-white font-medium">
            Payment Method:
          </span>
          Master Card
        </li>
        <li class="mb-[12px] last:mb-0">
          <span class="text-black dark:text-white font-medium"> Email: </span>
          example@trezo.com
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "DeliveryDetails",
});
</script>
