// react-bootstrap/src/components/Dashboard/HRM/EmployeeLeaveRequest/index.js
"use client";

import { useState, useEffect } from "react";
import { Card, Table, Form, Button } from "react-bootstrap";

// Example dynamic data (could be fetched from an API)
const mockLeaveRequests = [
  {
    id: 1,
    name: "John Doe",
    department: "Marketing",
    leaveType: "Vacation",
    days: 3,
    status: "Approved",
    imageUrl: "/images/user-1.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    department: "HR",
    leaveType: "Sick Leave",
    days: 2,
    status: "Pending",
    imageUrl: "/images/user-2.jpg",
  },
  {
    id: 3,
    name: "Alex Johnson",
    department: "Developer",
    leaveType: "Maternity Leave",
    days: 4,
    status: "Rejected",
    imageUrl: "/images/user-3.jpg",
  },
  {
    id: 4,
    name: "Emily Davis",
    department: "UX Designer",
    leaveType: "Vacation",
    days: 2,
    status: "Approved",
    imageUrl: "/images/user-4.jpg",
  },
  {
    id: 5,
    name: "Michael Brown",
    department: "Finance",
    leaveType: "Personal Leave",
    days: 1,
    status: "Pending",
    imageUrl: "/images/user-5.jpg",
  },
  {
    id: 6,
    name: "Chris Evans",
    department: "IT",
    leaveType: "Vacation",
    days: 5,
    status: "Approved",
    imageUrl: "/images/user-6.jpg",
  },
  {
    id: 7,
    name: "Natasha Romanoff",
    department: "Operations",
    leaveType: "Sick Leave",
    days: 3,
    status: "Pending",
    imageUrl: "/images/user-7.jpg",
  },
  {
    id: 8,
    name: "Jhonson Jhon",
    department: "Web Developer",
    leaveType: "Sick Leave",
    days: 5,
    status: "Approved",
    imageUrl: "/images/user-8.jpg",
  },
  {
    id: 9,
    name: "Alex Lee",
    department: "Developer",
    leaveType: "Maternity Leave",
    days: 4,
    status: "Rejected",
    imageUrl: "/images/user-9.jpg",
  },
  {
    id: 10,
    name: "Emily Jhon",
    department: "UX Designer",
    leaveType: "Vacation",
    days: 2,
    status: "Approved",
    imageUrl: "/images/user-10.jpg",
  },
];

const EmployeeLeaveRequest = () => {
  const [leaveRequests, setLeaveRequests] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  useEffect(() => {
    // Simulate fetching data
    setLeaveRequests(mockLeaveRequests);
  }, []);

  const totalPages = Math.ceil(leaveRequests.length / itemsPerPage);

  const handlePageChange = (page) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  const paginatedData = leaveRequests.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  return (
    <Card className="bg-white border-0 rounded-3 mb-4">
      <Card.Body className="p-0">
        <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 custom-padding-30 border-bottom pb-4">
          <h3 className="mb-0">Employee Leave Request</h3>

          <Form.Select
            className="month-select form-control w-135 bg-border-color border-color bg-transparent"
            aria-label="Default select example"
          >
            <option>This Month</option>
            <option value="0">This Week</option>
            <option value="1">This Year</option>
          </Form.Select>
        </div>

        <div className="default-table-area style-three employee-leave-request">
          <div className="table-responsive">
            <Table className="align-middle border-0">
              <thead className="border-bottom">
                <tr>
                  <th scope="col" className="bg-transparent">
                    Employee
                  </th>
                  <th scope="col" className="bg-transparent">
                    Leave Type
                  </th>
                  <th scope="col" className="bg-transparent">
                    Days
                  </th>
                  <th scope="col" className="bg-transparent">
                    Status
                  </th>
                  <th scope="col" className="bg-transparent">
                    Action
                  </th>
                </tr>
              </thead>
              <tbody>
                {paginatedData.length === 0 ? (
                  <tr>
                    <td colSpan="5" className="text-center">
                      No leave requests found.
                    </td>
                  </tr>
                ) : (
                  paginatedData.map((request) => (
                    <tr key={request.id}>
                      <td>
                        <div className="d-flex align-items-center">
                          <div className="flex-shrink-0">
                            <img
                              src={request.imageUrl}
                              className="rounded-circle"
                              alt="user"
                              width={40}
                              height={40}
                            />
                          </div>
                          <div className="flex-grow-1 ms-2">
                            <h4 className="fs-14 fw-medium mb-0">
                              {request.name}
                            </h4>
                            <span className="fs-12 text-body">
                              {request.department}
                            </span>
                          </div>
                        </div>
                      </td>
                      <td className="fw-medium">{request.leaveType}</td>
                      <td className="fw-medium">{request.days}</td>
                      <td>
                        <span
                          className={`badge ${
                            request.status === "Approved"
                              ? "bg-success bg-opacity-10 text-success"
                              : request.status === "Pending"
                              ? "bg-warning bg-opacity-10 text-warning"
                              : "bg-danger bg-opacity-10 text-danger"
                          } p-2 fs-12 fw-medium`}
                        >
                          {request.status}
                        </span>
                      </td>
                      <td>
                        <div className="d-flex align-items-center gap-2">
                          <button className="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
                            <i className="material-symbols-outlined fs-18 text-primary">
                              visibility
                            </i>
                          </button>
                          <button className="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
                            <i className="material-symbols-outlined fs-18 text-primary-div">
                              edit
                            </i>
                          </button>
                          <button className="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
                            <i className="material-symbols-outlined fs-18 text-danger">
                              delete
                            </i>
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </Table>
          </div>

          <div className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 custom-padding-30 pt-4">
            <span className="fs-12 fw-medium">
              Showing {(currentPage - 1) * itemsPerPage + 1}-
              {Math.min(currentPage * itemsPerPage, leaveRequests.length)} of{" "}
              {leaveRequests.length} Results
            </span>

            <nav aria-label="Page navigation example">
              <ul className="pagination mb-0 justify-content-center">
                <li className="page-item">
                  <Button
                    className="page-link icon"
                    onClick={() => handlePageChange(currentPage - 1)}
                  >
                    <i className="material-symbols-outlined">
                      keyboard_arrow_left
                    </i>
                  </Button>
                </li>
                {Array.from({ length: totalPages }, (_, index) => (
                  <li key={index} className="page-item">
                    <Button
                      className={`page-link ${
                        currentPage === index + 1 ? "active" : ""
                      }`}
                      onClick={() => handlePageChange(index + 1)}
                    >
                      {index + 1}
                    </Button>
                  </li>
                ))}
                <li className="page-item">
                  <Button
                    className="page-link icon"
                    onClick={() => handlePageChange(currentPage + 1)}
                  >
                    <i className="material-symbols-outlined">
                      keyboard_arrow_right
                    </i>
                  </Button>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </Card.Body>
    </Card>
  );
};

export default EmployeeLeaveRequest;

// vuejs-bootstrap/src/components/Dashboard/HRM/EmployeeLeaveRequest.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-0">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 custom-padding-30 border-bottom pb-4"
      >
        <h3 class="mb-0 fw-semibold">Employee Leave Request</h3>
        <div class="dropdown select-dropdown">
          <button
            class="dropdown-toggle bg-transparent border text-body rounded-2"
            style="padding-right: 35px"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            This Month
          </button>
          <ul
            class="dropdown-menu dropdown-menu-end bg-white border-0 box-shadow py-3"
          >
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                This Day
              </button>
            </li>
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                This Week
              </button>
            </li>
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                This Month
              </button>
            </li>
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                This Year
              </button>
            </li>
          </ul>
        </div>
      </div>

      <div class="default-table-area style-three employee-leave-request">
        <div class="table-responsive">
          <table class="table align-middle border-0">
            <thead class="border-bottom">
              <tr>
                <th scope="col" class="bg-transparent fw-normal">Employee</th>
                <th scope="col" class="bg-transparent fw-normal">Leave Type</th>
                <th scope="col" class="bg-transparent fw-normal">Days</th>
                <th scope="col" class="bg-transparent fw-normal">Status</th>
                <th scope="col" class="bg-transparent fw-normal">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(leave, index) in leaveRequests" :key="index">
                <td>
                  <div class="d-flex align-items-center">
                    <div class="flex-shrink-0">
                      <img
                        :src="leave.image"
                        class="rounded-circle"
                        alt="user"
                      />
                    </div>
                    <div class="flex-grow-1 ms-2">
                      <h4 class="fs-14 fw-medium mb-0">{{ leave.name }}</h4>
                      <span class="fs-12 text-body">{{
                        leave.department
                      }}</span>
                    </div>
                  </div>
                </td>
                <td class="fs-14 fw-medium">{{ leave.leaveType }}</td>
                <td class="fs-14 fw-medium">{{ leave.days }}</td>
                <td>
                  <span
                    :class="['badge p-2 fs-12 fw-normal', leave.statusClass]"
                  >
                    {{ leave.status }}
                  </span>
                </td>
                <td>
                  <div class="d-flex align-items-center gap-2">
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-18 text-primary">
                        visibility
                      </i>
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i
                        class="material-symbols-outlined fs-18 text-primary-div-50"
                      >
                        border_color
                      </i>
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-18 text-danger">
                        delete
                      </i>
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <Pagination class="custom-padding-30 border-0" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import Pagination from "@/components/Common/Pagination.vue";

export default defineComponent({
  name: "EmployeeLeaveRequest",
  components: {
    Pagination,
  },
  setup() {
    const leaveRequests = ref([
      {
        image: require("@/assets/images/user-151.png"),
        name: "John Doe",
        department: "Marketing",
        leaveType: "Vacation",
        days: 3,
        status: "Approved",
        statusClass: "bg-success-80 text-success-50",
      },
      {
        image: require("@/assets/images/user-152.png"),
        name: "Jane Smith",
        department: "HR",
        leaveType: "Sick Leave",
        days: 2,
        status: "Pending",
        statusClass: "bg-primary-div-60 text-primary-div-50",
      },
      {
        image: require("@/assets/images/user-153.png"),
        name: "Alex Johnson",
        department: "Developer",
        leaveType: "Maternity Leave",
        days: 4,
        status: "Rejected",
        statusClass: "bg-danger-70 text-danger-60",
      },
      {
        image: require("@/assets/images/user-154.png"),
        name: "Emily Davis",
        department: "UX Designer",
        leaveType: "Vacation",
        days: 2,
        status: "Approved",
        statusClass: "bg-success-80 text-success-50",
      },
      {
        image: require("@/assets/images/user-155.png"),
        name: "Michael Brown",
        department: "Finance",
        leaveType: "Personal Leave",
        days: 1,
        status: "Pending",
        statusClass: "bg-primary-div-60 text-primary-div-50",
      },
    ]);

    return { leaveRequests };
  },
});
</script>

<style lang="scss" scoped>
.custom-padding-30 {
  padding: 30px !important;
}
</style>
