// react-material-ui/src/components/Dashboard/School/SchoolOverview/index.js
"use client";

import React from "react";
import { Grid, Box, Typography } from "@mui/material";
import Stats from "./Stats";
import UpcomingEvents from "../UpcomingEvents";

const SchoolOverview = () => {
  const today = new Date();
  const formattedDate = today.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <>
      <Box sx={{ mb: "25px" }}>
        <Box
          sx={{
            display: { xs: "block", md: "flex" },
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <Box>
            <Typography
              variant="h5"
              sx={{
                mb: { xs: "6px", md: "3px" },
                fontWeight: 600,
                fontSize: "20px",
              }}
            >
              School Overview Dashboard
            </Typography>

            <Typography>
              Manage Students, Teachers, and School Data Seamlessly!
            </Typography>
          </Box>

          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              mt: { xs: "12px", lg: 0 },
            }}
          >
            <Box
              sx={{
                borderRadius: "7px",
                display: "flex",
                alignItems: "center",
                color: "primary.500",
                py: "3.5px",
                px: "15px",
                bgcolor: "primary.50",
                border: "1px solid",
                borderColor: "primary.100",
                gap: "5px",
              }}
            >
              <i className="ri-calendar-line" style={{ fontSize: "16px" }}></i>
              Today - {formattedDate}
            </Box>
          </Box>
        </Box>
      </Box>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid item xs={12} sm={12} md={12} lg={8} xl={8}>
          <Stats />
        </Grid>

        <Grid item xs={12} sm={12} md={12} lg={4} xl={4}>
          <UpcomingEvents />
        </Grid>
      </Grid>
    </>
  );
};

export default SchoolOverview;

// nuxtjs-tailwindcss/components/Dashboard/School/SchoolOverview.vue
<template>
  <div class="trezo-card mb-[25px]">
    <div class="trezo-card-content lg:flex justify-between items-center">
      <div>
        <h5 class="mb-[6px] md:mb-[3px] font-semibold text-[20px]">
          School Overview Dashboard
        </h5>
        <p>Manage Students, Teachers, and School Data Seamlessly!</p>
      </div>
      <div class="flex items-center gap-[10px] mt-[12px] lg:mt-0">
        <div
          class="rounded-md inline-block text-primary-500 py-[3.5px] px-[15px] bg-primary-50 dark:bg-[#0a0e19] border border-primary-100 dark:border-[#172036]"
          id="currentDayDate"
        >
          <span class="inline-block relative ltr:pl-[24px] rtl:pr-[24px]">
            <i
              class="ri-calendar-line absolute text-[16px] top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0"
            ></i>
            Today - <span id="currentDate"></span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "SchoolOverview",
});
</script>
