// angular-material/src/app/apps/file-manager/projects/projects.component.ts
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatMenuModule } from '@angular/material/menu';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-projects',
    imports: [MatCardModule, MatMenuModule, MatButtonModule, MatCheckboxModule],
    templateUrl: './projects.component.html',
    styleUrl: './projects.component.scss'
})
export class ProjectsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<div
    class="row"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-primary lh-1">
                        <img src="images/icons/png.png" alt="png-image">
                    </div>
                    <h6 class="mb-0">
                        ET Template
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        159 Files
                    </span>
                    <span class="d-block text-black">
                        4.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-secondary lh-1">
                        <img src="images/icons/jpg.png" alt="jpg-image">
                    </div>
                    <h6 class="mb-0">
                        React Template
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        522 Files
                    </span>
                    <span class="d-block text-black">
                        5.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-success lh-1">
                        <img src="images/icons/txt.png" alt="txt-image">
                    </div>
                    <h6 class="mb-0">
                        Material UI
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        995 Files
                    </span>
                    <span class="d-block text-black">
                        7.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-danger lh-1">
                        <img src="images/icons/pdf.png" alt="pdf-image">
                    </div>
                    <h6 class="mb-0">
                        WP Themes
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        39 Files
                    </span>
                    <span class="d-block text-black">
                        3.8 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-warning lh-1">
                        <img src="images/icons/xl4.png" alt="xl4-image">
                    </div>
                    <h6 class="mb-0">
                        Personal Photos
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        75 Files
                    </span>
                    <span class="d-block text-black">
                        2.2 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-info lh-1">
                        <img src="images/icons/doc.png" alt="doc-image">
                    </div>
                    <h6 class="mb-0">
                        Mobile Apps
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        357 Files
                    </span>
                    <span class="d-block text-black">
                        8.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-purple lh-1">
                        <img src="images/icons/png.png" alt="png-image">
                    </div>
                    <h6 class="mb-0">
                        Important Files
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        159 Files
                    </span>
                    <span class="d-block text-black">
                        4.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-dark lh-1">
                        <img src="images/icons/jpg.png" alt="jpg-image">
                    </div>
                    <h6 class="mb-0">
                        Angular Template
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        522 Files
                    </span>
                    <span class="d-block text-black">
                        5.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-orange lh-1">
                        <img src="images/icons/txt.png" alt="txt-image">
                    </div>
                    <h6 class="mb-0">
                        Projects
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        995 Files
                    </span>
                    <span class="d-block text-black">
                        7.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-primary lh-1">
                        <img src="images/icons/pdf.png" alt="pdf-image">
                    </div>
                    <h6 class="mb-0">
                        Documents
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        39 Files
                    </span>
                    <span class="d-block text-black">
                        3.8 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon text-secondary lh-1">
                        <img src="images/icons/xl4.png" alt="xl4-image">
                    </div>
                    <h6 class="mb-0">
                        Media
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        75 Files
                    </span>
                    <span class="d-block text-black">
                        2.2 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
    <div class="col-xxxl-3 col-md-4 col-sm-6">
        <mat-card class="project-folder-card mb-25 border-radius d-block bg-white border-0 shadow-none">
            <mat-card-content>
                <div class="d-flex align-items-center justify-content-between">
                    <mat-checkbox></mat-checkbox>
                    <div class="action">
                        <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                            <i class="ri-more-fill"></i>
                        </button>
                        <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                            <ul class="p-0 mt-0 mb-0 list-unstyled">
                                <li>
                                    <button mat-menu-item>
                                        Edit
                                    </button>
                                </li>
                                <li>
                                    <button mat-menu-item>
                                        Delete
                                    </button>
                                </li>
                            </ul>
                        </mat-menu>
                    </div>
                </div>
                <div class="title d-flex align-items-center">
                    <div class="icon lh-1">
                        <img src="images/icons/jpg.png" alt="jpg-image">
                    </div>
                    <h6 class="mb-0">
                        Applications
                    </h6>
                </div>
                <div class="info d-flex align-items-center justify-content-between">
                    <span class="d-block text-black">
                        357 Files
                    </span>
                    <span class="d-block text-black">
                        8.5 GB
                    </span>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
</div>

// nuxtjs-vuetify/components/Apps/FileManager/Projects/index.vue
<template>
  <v-row>
    <v-col
      cols="12"
      lg="3"
      md="4"
      sm="6"
      v-for="(folder, index) in folders"
      :key="index"
    >
      <v-card
        class="project-folder-card border-radius d-block bg-white border-0 shadow-none"
      >
        <div class="folder-card-content">
          <div class="d-flex align-items-center justify-space-between">
            <v-checkbox color="primary"></v-checkbox>
            <div class="action">
              <v-menu>
                <template v-slot:activator="{ props }">
                  <button
                    type="button"
                    v-bind="props"
                    class="dot-menu p-0 d-inline-block border-radius-0"
                  >
                    <i class="ri-more-fill"></i>
                  </button>
                </template>
                <v-list class="card-header-menu menu-content">
                  <button type="button">Edit</button>
                  <button type="button">Delete</button>
                </v-list>
              </v-menu>
            </div>
          </div>
          <div class="title d-flex align-items-center">
            <div :class="['icon', folder.iconClass, 'lh-1']">
              <v-img :src="folder.iconSrc" :alt="folder.iconAlt" />
            </div>
            <h6 class="mb-0">{{ folder.title }}</h6>
          </div>
          <div class="info d-flex align-items-center justify-space-between">
            <span class="d-block text-black">
              {{ folder.fileCount }} Files
            </span>
            <span class="d-block text-black"> {{ folder.size }} GB </span>
          </div>
        </div>
      </v-card>
    </v-col>
  </v-row>
</template>

<script setup lang="ts">
import { ref } from "vue";

import icon1 from "~/assets/images/icons/png.png";
import icon2 from "~/assets/images/icons/jpg.png";
import icon3 from "~/assets/images/icons/txt.png";
import icon4 from "~/assets/images/icons/pdf.png";
import icon5 from "~/assets/images/icons/xl4.png";
import icon6 from "~/assets/images/icons/doc.png";

const folders = ref([
  {
    iconClass: "text-primary",
    iconSrc: icon1,
    iconAlt: "png-image",
    title: "ET Template",
    fileCount: 159,
    size: "4.5 GB",
  },
  {
    iconClass: "text-secondary",
    iconSrc: icon2,
    iconAlt: "jpg-image",
    title: "React Template",
    fileCount: 522,
    size: "5.5 GB",
  },
  {
    iconClass: "text-success",
    iconSrc: icon3,
    iconAlt: "txt-image",
    title: "Material UI",
    fileCount: 995,
    size: "7.5 GB",
  },
  {
    iconClass: "text-danger",
    iconSrc: icon4,
    iconAlt: "pdf-image",
    title: "WP Themes",
    fileCount: 39,
    size: "3.8 GB",
  },
  {
    iconClass: "text-warning",
    iconSrc: icon5,
    iconAlt: "xl4-image",
    title: "Personal Photos",
    fileCount: 75,
    size: "2.2 GB",
  },
  {
    iconClass: "text-info",
    iconSrc: icon6,
    iconAlt: "doc-image",
    title: "Mobile Apps",
    fileCount: 357,
    size: "8.5 GB",
  },
  {
    iconClass: "text-purple",
    iconSrc: icon1,
    iconAlt: "png-image",
    title: "Important Files",
    fileCount: 159,
    size: "4.5 GB",
  },
  {
    iconClass: "text-dark",
    iconSrc: icon2,
    iconAlt: "jpg-image",
    title: "Angular Template",
    fileCount: 522,
    size: "5.5 GB",
  },
  {
    iconClass: "text-orange",
    iconSrc: icon3,
    iconAlt: "txt-image",
    title: "Projects",
    fileCount: 995,
    size: "7.5 GB",
  },
  {
    iconClass: "text-primary",
    iconSrc: icon4,
    iconAlt: "pdf-image",
    title: "Documents",
    fileCount: 39,
    size: "3.8 GB",
  },
  {
    iconClass: "text-secondary",
    iconSrc: icon5,
    iconAlt: "xl4-image",
    title: "Media",
    fileCount: 75,
    size: "2.2 GB",
  },
  {
    iconClass: "lh-1",
    iconSrc: icon2,
    iconAlt: "jpg-image",
    title: "Applications",
    fileCount: 357,
    size: "8.5 GB",
  },
]);
</script>

<style lang="scss" scoped>
.project-folder-card {
  .folder-card-content {
    .v-checkbox.v-input {
      margin: -40px -10px -56px -10px;
    }
    .dot-menu {
      height: 21.59px;
      min-width: auto;
      margin-right: -2px;
      i {
        line-height: 21.59px;
        color: var(--bodyColor);
        font-size: 26px;
      }

      &:hover {
        color: var(--primaryColor);
      }
    }
    .title {
      margin-top: 35px;
    }
    .icon {
      margin-right: 12px;
      color: #ffb264;

      i {
        font-size: 45px;
      }
    }
    .info {
      margin-top: 40px;

      span {
        font-size: 13px;
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .assets-folder-card {
    .folder-card-content {
      .title {
        margin-top: 22px;
      }
      .icon {
        i {
          font-size: 40px;
        }
      }
      .info {
        margin-top: 20px;
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .assets-folder-card {
    .folder-card-content {
      .title {
        margin-top: 35px;
      }
      .icon {
        i {
          font-size: 40px;
        }
      }
      .info {
        margin-top: 35px;
      }
    }
  }
}

/* Min width 992px to Max width 1199px */
@media only screen and (min-width: 992px) and (max-width: 1199px) {
}

/* Min width 1200px to Max width 1399px */
@media only screen and (min-width: 1200px) and (max-width: 1399px) {
}

/* Min width 1600px */
@media only screen and (min-width: 1600px) {
}
</style>
