// react-bootstrap/src/components/Dashboard/Crypto/Exchange/index.js
"use client";

import { Dropdown, Card, Form, Button } from "react-bootstrap";

const Exchange = () => {
  return (
    <>
      <Card
        className="p-0 border-0 rounded-3 mb-4 exchange-for-dark"
        style={{ backgroundColor: "#F3E8FF" }}
      >
        <div
          className="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-4 p-3 px-4"
          style={{ borderBottom: "1px solid #D5D9E2" }}
        >
          <div>
            <h3 className="mb-0">Exchange</h3>
          </div>
          <Button
            type="button"
            className="p-0 border-0 bg-transparent position-relative top-3 text-black"
          >
            <span className="material-symbols-outlined fs-24">replay</span>
          </Button>
        </div>

        <Form className="p-4 pt-0">
          <div className="mb-30">
            <div className="d-flex justify-content-between align-items-center mb-3">
              <span>SELLING</span>
              <span>MAX 4,238</span>
            </div>

            <Dropdown className="action-opt mb-3">
              <Dropdown.Toggle className="bg-transparent p-0 d-flex justify-content-between align-items-center w-100">
                <div className="d-flex align-items-center gap-2">
                  <img
                    src="/images/ethereum.png"
                    alt="cardano"
                    width={42}
                    height={42}
                  />
                  <span className="fs-14 fw-semibold text-secondary">
                    ETHEREUM (ETH)
                  </span>
                </div>
                <span className="material-symbols-outlined">
                  keyboard_arrow_down
                </span>
              </Dropdown.Toggle>

              <Dropdown.Menu className="dropdown-menu-end bg-white border box-shadow w-100">
                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/ethereum.png"
                    alt="ethereum"
                    width={24}
                    height={24}
                  />
                  <span>Ethereum (BTC)</span>
                </Dropdown.Item>

                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/solana.png"
                    alt="solana"
                    width={24}
                    height={24}
                  />
                  <span>Solana (SOL)</span>
                </Dropdown.Item>

                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/binance.png"
                    alt="binance"
                    width={24}
                    height={24}
                  />
                  <span>Binance (BNB)</span>
                </Dropdown.Item>

                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/bitcoin.png"
                    alt="binance"
                    width={24}
                    height={24}
                  />
                  <span>Cardano (ADA)</span>
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>

            <div className="position-relative z-0">
              <Form.Control
                type="text"
                className="h-55 bg-white border-0"
                placeholder="1 ETH"
              />
              <span className="fs-14 position-absolute top-50 end-0 translate-middle-y pe-3">
                $1750
              </span>
            </div>
          </div>

          <div className="mb-30">
            <div className="d-flex justify-content-between align-items-center mb-3">
              <span>SELLING</span>
              <span>MAX 4,238</span>
            </div>

            <Dropdown className="action-opt mb-3">
              <Dropdown.Toggle className="bg-transparent p-0 d-flex justify-content-between align-items-center w-100">
                <div className="d-flex align-items-center gap-2">
                  <img
                    src="/images/solana.png"
                    alt="solana"
                    width={42}
                    height={42}
                  />
                  <span className="fs-14 fw-semibold text-secondary">
                    SOLANA (SOL)
                  </span>
                </div>
                <span className="material-symbols-outlined">
                  keyboard_arrow_down
                </span>
              </Dropdown.Toggle>

              <Dropdown.Menu className="dropdown-menu-end bg-white border box-shadow w-100">
                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/ethereum.png"
                    alt="ethereum"
                    width={24}
                    height={24}
                  />
                  <span>Ethereum (BTC)</span>
                </Dropdown.Item>

                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/solana.png"
                    alt="solana"
                    width={24}
                    height={24}
                  />
                  <span>Solana (SOL)</span>
                </Dropdown.Item>

                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/binance.png"
                    alt="binance"
                    width={24}
                    height={24}
                  />
                  <span>Binance (BNB)</span>
                </Dropdown.Item>

                <Dropdown.Item
                  className="text-secondary d-flex align-items-center gap-2"
                  href="#"
                >
                  <img
                    src="/images/bitcoin.png"
                    alt="binance"
                    width={24}
                    height={24}
                  />
                  <span>Cardano (ADA)</span>
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>

            <div className="position-relative z-0">
              <Form.Control
                type="text"
                className="h-55 bg-white border-0"
                placeholder="75 SOL"
              />
              <span className="fs-14 position-absolute top-50 end-0 translate-middle-y pe-3">
                $35
              </span>
            </div>
          </div>

          <Button type="submit" className="btn-primary py-2 px-4 w-100">
            <span className="d-inline-block py-1">Exchange</span>
          </Button>
        </Form>
      </Card>
    </>
  );
};

export default Exchange;

// angular-bootstrap/src/app/dashboard/crypto/exchange/exchange.component.ts
import { Component, HostListener } from '@angular/core';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';
import { NgIf } from '@angular/common';

@Component({
    selector: 'app-exchange',
    imports: [NgIf],
    templateUrl: './exchange.component.html',
    styleUrl: './exchange.component.scss'
})
export class ExchangeComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

    // Card Header Menu
    isCryptocurrencyTypesOpen1 = false;
    isCryptocurrencyTypesOpen2 = false;
    toggleCryptocurrencyTypesMenu1() {
        this.isCryptocurrencyTypesOpen1 = !this.isCryptocurrencyTypesOpen1;
    }
    toggleCryptocurrencyTypesMenu2() {
        this.isCryptocurrencyTypesOpen2 = !this.isCryptocurrencyTypesOpen2;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.cryptocurrency-types.one')) {
            this.isCryptocurrencyTypesOpen1 = false;
        }
        if (!target.closest('.cryptocurrency-types.two')) {
            this.isCryptocurrencyTypesOpen2 = false;
        }
    }

}
<div
    class="crypto-exchange-card trezo-card mb-25 border-radius d-block border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
    [class.component-dark-theme]="themeService.isDark()"
>
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Exchange
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <button type="button" class="button bg-transparent p-0 border-0 lh-1 transition">
                <i class="material-symbols-outlined">
                    refresh
                </i>
            </button>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="item">
            <div class="title d-flex justify-content-between align-items-center">
                <span class="d-block text-body text-uppercase">
                    Selling
                </span>
                <span class="d-block text-body text-uppercase">
                    Max 4,238
                </span>
            </div>
            <div class="cryptocurrency-types one position-relative">
                <button class="button d-block w-100 p-0 border-0 bg-transparent text-black position-relative text-uppercase fw-medium" (click)="toggleCryptocurrencyTypesMenu1()">
                    <span class="d-flex align-items-center">
                        <img src="images/cryptocurrencies/big-ethereum.svg" alt="ethereum">
                        Ethereum
                        <span class="fw-normal text-body">(ETH)</span>
                    </span>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCryptocurrencyTypesOpen1">
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/ethereum.svg" alt="ethereum">
                            Ethereum
                            <span class="fw-normal text-body">(ETH)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/bitcoin.svg" alt="bitcoin">
                            Bitcoin
                            <span class="fw-normal text-body">(BTC)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/solana.svg" alt="solana">
                            Solana
                            <span class="fw-normal text-body">(SOL)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/cardano.png" alt="cardano">
                            Cardano
                            <span class="fw-normal text-body">(ADA)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/binance.svg" alt="binance">
                            Binance
                            <span class="fw-normal text-body">(BNB)</span>
                        </button>
                    </li>
                </ul>
            </div>
            <div class="form-floating position-relative">
                <input type="email" class="form-control fw-bold" id="floatingInput" value="1">
                <label for="floatingInput">ETH</label>
                <span class="d-inline-block value text-body">
                    $1750
                </span>
            </div>
        </div>
        <div class="item">
            <div class="title d-flex justify-content-between align-items-center">
                <span class="d-block text-body text-uppercase">
                    Buying
                </span>
            </div>
            <div class="cryptocurrency-types two position-relative">
                <button class="button d-block w-100 p-0 border-0 bg-transparent text-black position-relative text-uppercase fw-medium" (click)="toggleCryptocurrencyTypesMenu2()">
                    <span class="d-flex align-items-center">
                        <img src="images/cryptocurrencies/big-solana.svg" alt="solana">
                        Solana
                        <span class="fw-normal text-body">(SOL)</span>
                    </span>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCryptocurrencyTypesOpen2">
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/ethereum.svg" alt="ethereum">
                            Ethereum
                            <span class="fw-normal text-body">(ETH)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/bitcoin.svg" alt="bitcoin">
                            Bitcoin
                            <span class="fw-normal text-body">(BTC)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/solana.svg" alt="solana">
                            Solana
                            <span class="fw-normal text-body">(SOL)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/cardano.png" alt="cardano">
                            Cardano
                            <span class="fw-normal text-body">(ADA)</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-flex align-items-center w-100 position-relative transition">
                            <img src="images/cryptocurrencies/binance.svg" alt="binance">
                            Binance
                            <span class="fw-normal text-body">(BNB)</span>
                        </button>
                    </li>
                </ul>
            </div>
            <div class="form-floating position-relative">
                <input type="email" class="form-control fw-bold" id="floatingInput" value="75">
                <label for="floatingInput">SOL</label>
                <span class="d-inline-block value text-body">
                    $35
                </span>
            </div>
        </div>
        <button type="button" class="exchange-btn d-block w-100 fw-medium border-0 border-radius bg-primary text-white">
            Exchange
        </button>
    </div>
</div>
