// vuejs-bootstrap/src/components/Pages/Ecommerce/SellerDetails/ProductsList.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-4">
      <ul
        class="nav nav-tabs border-0 gap-3 mb-lg-4 mb-3 seller-tabs"
        id="myTab"
        role="tablist"
      >
        <li class="nav-item" role="presentation">
          <button
            class="nav-link border-0 bg-body-bg text-secondary fw-medium fs-16 rounded-3 py- px-md-5 px-4 active"
            id="all-tab"
            data-bs-toggle="tab"
            data-bs-target="#all-tab-pane"
            type="button"
            role="tab"
            aria-controls="all-tab-pane"
            aria-selected="true"
          >
            <span class="d-inline-block py-1">All Products</span>
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button
            class="nav-link border-0 bg-body-bg text-secondary fw-medium fs-16 rounded-3 py- px-md-5 px-4"
            id="published-tab"
            data-bs-toggle="tab"
            data-bs-target="#published-tab-pane"
            type="button"
            role="tab"
            aria-controls="published-tab-pane"
            aria-selected="false"
          >
            <span class="d-inline-block py-1">Published Products</span>
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button
            class="nav-link border-0 bg-body-bg text-secondary fw-medium fs-16 rounded-3 py- px-md-5 px-4"
            id="draft-tab"
            data-bs-toggle="tab"
            data-bs-target="#draft-tab-pane"
            type="button"
            role="tab"
            aria-controls="draft-tab-pane"
            aria-selected="false"
          >
            <span class="d-inline-block py-1">Draft Products</span>
          </button>
        </li>
      </ul>

      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-lg-4 mb-3"
      >
        <form class="position-relative table-src-form me-0" @submit.prevent>
          <input
            type="text"
            class="form-control"
            placeholder="Search here"
            v-model="searchTerm"
          />
          <i
            class="material-symbols-outlined position-absolute top-50 start-0 translate-middle-y"
          >
            search
          </i>
        </form>

        <RouterLink
          to="/ecommerce/create-product"
          class="btn btn-outline-primary py-1 px-2 px-sm-4 fs-14 fw-medium rounded-3 hover-bg"
        >
          <span class="py-sm-1 d-block">
            <i class="ri-add-line d-none d-sm-inline-block fs-18 me-1"></i>
            <span>Add New Product</span>
          </span>
        </RouterLink>
      </div>

      <div class="tab-content" id="myTabContent">
        <div
          class="tab-pane fade show active"
          id="all-tab-pane"
          role="tabpanel"
          aria-labelledby="all-tab"
          tabindex="0"
        >
          <div class="default-table-area all-products">
            <div class="table-responsive">
              <table class="table align-middle">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Product</th>
                    <th scope="col">Category</th>
                    <th scope="col">Price</th>
                    <th scope="col">Order</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Rating</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="item in filteredItems" :key="item.id">
                    <td class="text-body">
                      {{ item.id }}
                    </td>
                    <td>
                      <RouterLink
                        to="/ecommerce/product-details"
                        class="d-flex align-items-center"
                      >
                        <img
                          :src="item.product.image"
                          class="wh-40 rounded-3"
                          alt="product-1"
                        />
                        <div class="ms-2 ps-1">
                          <h6 class="fw-medium fs-14">
                            {{ item.product.title }}
                          </h6>
                          <span class="fs-12 text-body">
                            {{ item.product.date }}
                          </span>
                        </div>
                      </RouterLink>
                    </td>
                    <td class="text-secondary">
                      {{ item.category }}
                    </td>
                    <td class="text-secondary">${{ item.price }}</td>
                    <td class="text-secondary">
                      {{ item.order }}
                    </td>
                    <td class="text-secondary">
                      {{ item.stock.count }}
                    </td>
                    <td class="text-secondary">${{ item.amount }}</td>
                    <td class="text-secondary">
                      {{ item.rating }}
                    </td>
                    <td>
                      <span
                        class="badge bg-opacity-10 p-2 fs-12 fw-normal"
                        :class="computeClass(item.status)"
                      >
                        {{ item.status }}
                      </span>
                    </td>
                    <td>
                      <div class="d-flex align-items-center gap-1">
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i
                            class="material-symbols-outlined fs-16 text-primary"
                          >
                            {{ item.action.view }}
                          </i>
                        </button>
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i class="material-symbols-outlined fs-16 text-body">
                            {{ item.action.edit }}
                          </i>
                        </button>
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i
                            class="material-symbols-outlined fs-16 text-danger"
                          >
                            {{ item.action.delete }}
                          </i>
                        </button>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <PaginationTwo items="10" :total="items.length" />
          </div>
        </div>
        <div
          class="tab-pane fade"
          id="published-tab-pane"
          role="tabpanel"
          aria-labelledby="published-tab"
          tabindex="0"
        >
          <div class="default-table-area all-products">
            <div class="table-responsive">
              <table class="table align-middle">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Product</th>
                    <th scope="col">Category</th>
                    <th scope="col">Price</th>
                    <th scope="col">Order</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Rating</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="item in publishedItems" :key="item.id">
                    <td class="text-body">
                      {{ item.id }}
                    </td>
                    <td>
                      <RouterLink
                        to="/ecommerce/product-details"
                        class="d-flex align-items-center"
                      >
                        <img
                          :src="item.product.image"
                          class="wh-40 rounded-3"
                          alt="product-1"
                        />
                        <div class="ms-2 ps-1">
                          <h6 class="fw-medium fs-14">
                            {{ item.product.title }}
                          </h6>
                          <span class="fs-12 text-body">
                            {{ item.product.date }}
                          </span>
                        </div>
                      </RouterLink>
                    </td>
                    <td class="text-secondary">
                      {{ item.category }}
                    </td>
                    <td class="text-secondary">${{ item.price }}</td>
                    <td class="text-secondary">
                      {{ item.order }}
                    </td>
                    <td class="text-secondary">
                      {{ item.stock.count }}
                    </td>
                    <td class="text-secondary">${{ item.amount }}</td>
                    <td class="text-secondary">
                      {{ item.rating }}
                    </td>
                    <td>
                      <span
                        class="badge bg-opacity-10 p-2 fs-12 fw-normal"
                        :class="computeClass(item.status)"
                      >
                        {{ item.status }}
                      </span>
                    </td>
                    <td>
                      <div class="d-flex align-items-center gap-1">
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i
                            class="material-symbols-outlined fs-16 text-primary"
                          >
                            {{ item.action.view }}
                          </i>
                        </button>
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i class="material-symbols-outlined fs-16 text-body">
                            {{ item.action.edit }}
                          </i>
                        </button>
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i
                            class="material-symbols-outlined fs-16 text-danger"
                          >
                            {{ item.action.delete }}
                          </i>
                        </button>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <CommonPaginationTwo items="10" :total="publishedItems.length" />
          </div>
        </div>
        <div
          class="tab-pane fade"
          id="draft-tab-pane"
          role="tabpanel"
          aria-labelledby="draft-tab"
          tabindex="0"
        >
          <div class="default-table-area all-products">
            <div class="table-responsive">
              <table class="table align-middle">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Product</th>
                    <th scope="col">Category</th>
                    <th scope="col">Price</th>
                    <th scope="col">Order</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Rating</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="item in draftItems" :key="item.id">
                    <td class="text-body">
                      {{ item.id }}
                    </td>
                    <td>
                      <RouterLink
                        to="/ecommerce/product-details"
                        class="d-flex align-items-center"
                      >
                        <img
                          :src="item.product.image"
                          class="wh-40 rounded-3"
                          alt="product-1"
                        />
                        <div class="ms-2 ps-1">
                          <h6 class="fw-medium fs-14">
                            {{ item.product.title }}
                          </h6>
                          <span class="fs-12 text-body">
                            {{ item.product.date }}
                          </span>
                        </div>
                      </RouterLink>
                    </td>
                    <td class="text-secondary">
                      {{ item.category }}
                    </td>
                    <td class="text-secondary">${{ item.price }}</td>
                    <td class="text-secondary">
                      {{ item.order }}
                    </td>
                    <td class="text-secondary">
                      {{ item.stock.count }}
                    </td>
                    <td class="text-secondary">${{ item.amount }}</td>
                    <td class="text-secondary">
                      {{ item.rating }}
                    </td>
                    <td>
                      <span
                        class="badge bg-opacity-10 p-2 fs-12 fw-normal"
                        :class="computeClass(item.status)"
                      >
                        {{ item.status }}
                      </span>
                    </td>
                    <td>
                      <div class="d-flex align-items-center gap-1">
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i
                            class="material-symbols-outlined fs-16 text-primary"
                          >
                            {{ item.action.view }}
                          </i>
                        </button>
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i class="material-symbols-outlined fs-16 text-body">
                            {{ item.action.edit }}
                          </i>
                        </button>
                        <button
                          class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                        >
                          <i
                            class="material-symbols-outlined fs-16 text-danger"
                          >
                            {{ item.action.delete }}
                          </i>
                        </button>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <CommonPaginationTwo items="10" total="30" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";
import PaginationTwo from "@/components/Common/PaginationTwo.vue";

export default defineComponent({
  name: "ProductsList",
  components: {
    PaginationTwo,
  },
  setup() {
    const items = ref([
      {
        id: "#JAN-999",
        product: {
          image: require("@/assets/images/product-1.jpg"),
          title: "Smart Band",
          date: "08 Jun 2024",
        },
        category: "Watch",
        price: "35.00",
        order: 75,
        stock: {
          count: "750",
          className: false,
        },
        amount: "2,625",
        rating: "5.00 (141 reviews)",
        status: "Published",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-998",
        product: {
          image: require("@/assets/images/product-2.jpg"),
          title: "Headphone",
          date: "07 Jun 2024",
        },
        category: "Electronics",
        price: "49.00",
        order: 25,
        stock: {
          count: "825",
          className: false,
        },
        amount: "1,225",
        rating: "5.00 (69 reviews)",
        status: "Draft",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-997",
        product: {
          image: require("@/assets/images/product-3.jpg"),
          title: "iPhone 15 Plus",
          date: "06 Jun 2024",
        },
        category: "Apple",
        price: "99.00",
        order: 55,
        stock: {
          count: "Stock Out",
          className: true,
        },
        amount: "5,445",
        rating: "5.00 (99 reviews)",
        status: "Published",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-996",
        product: {
          image: require("@/assets/images/product-4.jpg"),
          title: "Bluetooth Speaker",
          date: "05 Jun 2024",
        },
        category: "Google",
        price: "59.00",
        order: 40,
        stock: {
          count: "535",
          className: false,
        },
        amount: "2,360",
        rating: "4.00 (75 reviews)",
        status: "Published",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-995",
        product: {
          image: require("@/assets/images/product-5.jpg"),
          title: "Airbuds 2nd Gen",
          date: "04 Jun 2024",
        },
        category: "Headphone",
        price: "79.00",
        order: 56,
        stock: {
          count: "460",
          className: false,
        },
        amount: "4,424",
        rating: "5.00 (158 reviews)",
        status: "Draft",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-999",
        product: {
          image: require("@/assets/images/product-1.jpg"),
          title: "Smart Band",
          date: "08 Jun 2024",
        },
        category: "Watch",
        price: "35.00",
        order: 75,
        stock: {
          count: "750",
          className: false,
        },
        amount: "2,625",
        rating: "5.00 (141 reviews)",
        status: "Published",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-998",
        product: {
          image: require("@/assets/images/product-2.jpg"),
          title: "Headphone",
          date: "07 Jun 2024",
        },
        category: "Electronics",
        price: "49.00",
        order: 25,
        stock: {
          count: "825",
          className: false,
        },
        amount: "1,225",
        rating: "5.00 (69 reviews)",
        status: "Draft",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-997",
        product: {
          image: require("@/assets/images/product-3.jpg"),
          title: "iPhone 15 Plus",
          date: "06 Jun 2024",
        },
        category: "Apple",
        price: "99.00",
        order: 55,
        stock: {
          count: "Stock Out",
          className: true,
        },
        amount: "5,445",
        rating: "5.00 (99 reviews)",
        status: "Published",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-996",
        product: {
          image: require("@/assets/images/product-4.jpg"),
          title: "Bluetooth Speaker",
          date: "05 Jun 2024",
        },
        category: "Google",
        price: "59.00",
        order: 40,
        stock: {
          count: "535",
          className: false,
        },
        amount: "2,360",
        rating: "4.00 (75 reviews)",
        status: "Published",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#JAN-995",
        product: {
          image: require("@/assets/images/product-5.jpg"),
          title: "Airbuds 2nd Gen",
          date: "04 Jun 2024",
        },
        category: "Headphone",
        price: "79.00",
        order: 56,
        stock: {
          count: "460",
          className: false,
        },
        amount: "4,424",
        rating: "5.00 (158 reviews)",
        status: "Draft",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
    ]);

    const searchTerm = ref("");

    const filteredItems = computed(() => {
      return items.value.filter(
        (item: {
          id: string;
          product: { title: string; date: string };
          category: string;
          price: string;
          stock: { count: string };
          amount: string;
          rating: string;
          status: string;
        }) =>
          item.id.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.product.title
            .toLowerCase()
            .includes(searchTerm.value.toLowerCase()) ||
          item.product.date
            .toLowerCase()
            .includes(searchTerm.value.toLowerCase()) ||
          item.category
            .toLowerCase()
            .includes(searchTerm.value.toLowerCase()) ||
          item.price.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.stock.count
            .toLowerCase()
            .includes(searchTerm.value.toLowerCase()) ||
          item.amount.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.rating.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.status.toLowerCase().includes(searchTerm.value.toLowerCase())
      );
    });

    const publishedItems = computed(() =>
      filteredItems.value.filter(
        (item: { status: string }) => item.status === "Published"
      )
    );

    const draftItems = computed(() =>
      filteredItems.value.filter(
        (item: { status: string }) => item.status === "Draft"
      )
    );

    const computeClass = (classValue: string) => {
      return {
        published: classValue === "Published",
        draft: classValue === "Draft",
      };
    };

    return {
      items,
      searchTerm,
      filteredItems,
      publishedItems,
      draftItems,
      computeClass,
    };
  },
});
</script>

// nextjs-material-ui/src/components/eCommerce/ProductsList/index.tsx
"use client";

import * as React from "react";
import Image from "next/image";
import {
  Card,
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableFooter,
  TablePagination,
  TableRow,
  Paper,
  IconButton,
  TableHead,
  Button,
} from "@mui/material";
import Link from "next/link";
import { useTheme } from "@mui/material/styles";
import KeyboardArrowLeft from "@mui/icons-material/KeyboardArrowLeft";
import KeyboardArrowRight from "@mui/icons-material/KeyboardArrowRight";
import styles from "@/components/eCommerce/Search.module.css";
import AddIcon from "@mui/icons-material/Add";
import NavList from "./NavList";

interface TablePaginationActionsProps {
  count: number;
  page: number;
  rowsPerPage: number;
  onPageChange: (
    event: React.MouseEvent<HTMLButtonElement>,
    newPage: number
  ) => void;
}

function TablePaginationActions(props: TablePaginationActionsProps) {
  const theme = useTheme();
  const { count, page, rowsPerPage, onPageChange } = props;

  const handleBackButtonClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    onPageChange(event, page - 1);
  };

  const handleNextButtonClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    onPageChange(event, page + 1);
  };

  return (
    <Box
      sx={{
        flexShrink: 0,
        display: "flex",
        gap: "10px",
        padding: "14px 20px",
      }}
    >
      <IconButton
        onClick={handleBackButtonClick}
        disabled={page === 0}
        aria-label="previous page"
        sx={{
          borderRadius: "4px",
          padding: "6px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowRight />
        ) : (
          <KeyboardArrowLeft />
        )}
      </IconButton>

      <IconButton
        onClick={handleNextButtonClick}
        disabled={page >= Math.ceil(count / rowsPerPage) - 1}
        aria-label="next page"
        sx={{
          borderRadius: "4px",
          padding: "6px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowLeft />
        ) : (
          <KeyboardArrowRight />
        )}
      </IconButton>
    </Box>
  );
}

function createData(
  orderID: string,
  productImage: string,
  productName: string,
  date: string,
  category: string,
  price: string,
  order: number,
  stock: string,
  amount: string,
  rating: string,
  status: string,
  detailsLink: string
) {
  return {
    orderID,
    productImage,
    productName,
    date,
    category,
    price,
    order,
    stock,
    amount,
    rating,
    status,
    detailsLink,
  };
}

const rows = [
  createData(
    "#JAN-999",
    "/images/products/product1.jpg",
    "Smart Band",
    "08 Jun 2024",
    "Watch",
    "$35.00",
    75,
    "750",
    "$2,625",
    "5.00 (141 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-998",
    "/images/products/product2.jpg",
    "Headphone",
    "07 Jun 2024",
    "Electronics",
    "$49.00",
    25,
    "825",
    "$1,225",
    "5.00 (69 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-997",
    "/images/products/product3.jpg",
    "iPhone 15 Plus",
    "06 Jun 2024",
    "Apple",
    "$99.00",
    55,
    "Stock Out",
    "$5,445",
    "5.00 (99 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-996",
    "/images/products/product4.jpg",
    "Bluetooth Speaker",
    "05 Jun 2024",
    "Google",
    "$59.00",
    40,
    "535",
    "$2,360",
    "4.00 (75 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-995",
    "/images/products/product5.jpg",
    "Airbuds 2nd Gen",
    "04 Jun 2024",
    "Headphone",
    "$79.00",
    56,
    "460",
    "$4,424",
    "5.00 (158 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-994",
    "/images/products/product1.jpg",
    "Smart Band",
    "08 Jun 2024",
    "Watch",
    "$35.00",
    75,
    "750",
    "$2,625",
    "5.00 (141 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-993",
    "/images/products/product2.jpg",
    "Headphone",
    "07 Jun 2024",
    "Electronics",
    "$49.00",
    25,
    "825",
    "$1,225",
    "5.00 (69 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-992",
    "/images/products/product3.jpg",
    "iPhone 15 Plus",
    "06 Jun 2024",
    "Apple",
    "$99.00",
    55,
    "Stock Out",
    "$5,445",
    "5.00 (99 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-991",
    "/images/products/product4.jpg",
    "Bluetooth Speaker",
    "05 Jun 2024",
    "Google",
    "$59.00",
    40,
    "535",
    "$2,360",
    "4.00 (75 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-990",
    "/images/products/product5.jpg",
    "Airbuds 2nd Gen",
    "04 Jun 2024",
    "Headphone",
    "$79.00",
    56,
    "460",
    "$4,424",
    "5.00 (158 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-989",
    "/images/products/product1.jpg",
    "Smart Band",
    "08 Jun 2024",
    "Watch",
    "$35.00",
    75,
    "750",
    "$2,625",
    "5.00 (141 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-988",
    "/images/products/product2.jpg",
    "Headphone",
    "07 Jun 2024",
    "Electronics",
    "$49.00",
    25,
    "825",
    "$1,225",
    "5.00 (69 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-987",
    "/images/products/product3.jpg",
    "iPhone 15 Plus",
    "06 Jun 2024",
    "Apple",
    "$99.00",
    55,
    "Stock Out",
    "$5,445",
    "5.00 (99 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-986",
    "/images/products/product4.jpg",
    "Bluetooth Speaker",
    "05 Jun 2024",
    "Google",
    "$59.00",
    40,
    "535",
    "$2,360",
    "4.00 (75 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-985",
    "/images/products/product5.jpg",
    "Airbuds 2nd Gen",
    "04 Jun 2024",
    "Headphone",
    "$79.00",
    56,
    "460",
    "$4,424",
    "5.00 (158 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-984",
    "/images/products/product1.jpg",
    "Smart Band",
    "08 Jun 2024",
    "Watch",
    "$35.00",
    75,
    "750",
    "$2,625",
    "5.00 (141 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-983",
    "/images/products/product2.jpg",
    "Headphone",
    "07 Jun 2024",
    "Electronics",
    "$49.00",
    25,
    "825",
    "$1,225",
    "5.00 (69 reviews)",
    "Draft",
    "/products-list/details/"
  ),
  createData(
    "#JAN-982",
    "/images/products/product3.jpg",
    "iPhone 15 Plus",
    "06 Jun 2024",
    "Apple",
    "$99.00",
    55,
    "Stock Out",
    "$5,445",
    "5.00 (99 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-981",
    "/images/products/product4.jpg",
    "Bluetooth Speaker",
    "05 Jun 2024",
    "Google",
    "$59.00",
    40,
    "535",
    "$2,360",
    "4.00 (75 reviews)",
    "Published",
    "/products-list/details/"
  ),
  createData(
    "#JAN-980",
    "/images/products/product5.jpg",
    "Airbuds 2nd Gen",
    "04 Jun 2024",
    "Headphone",
    "$79.00",
    56,
    "460",
    "$4,424",
    "5.00 (158 reviews)",
    "Draft",
    "/products-list/details/"
  ),
].sort((b, a) => (a.orderID < b.orderID ? -1 : 1));

const ProductsList: React.FC = () => {
  // Table
  const [page, setPage] = React.useState(0);
  const [rowsPerPage, setRowsPerPage] = React.useState(10);

  // Avoid a layout jump when reaching the last page with empty rows.
  const emptyRows =
    page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;

  const handleChangePage = (
    event: React.MouseEvent<HTMLButtonElement> | null,
    newPage: number
  ) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <NavList />

        <Box>
          <Box
            sx={{
              display: { xs: "block", sm: "flex" },
              alignItems: "center",
              justifyContent: "space-between",
              mb: "25px",
            }}
          >
            <Box
              component="form"
              className={styles.searchBox}
              sx={{
                width: "265px",
              }}
            >
              <label>
                <i className="material-symbols-outlined">search</i>
              </label>
              <input
                type="text"
                className={styles.inputSearch}
                placeholder="Search product here....."
              />
            </Box>

            <Link href="/ecommerce/create-product">
              <Button
                variant="outlined"
                sx={{
                  textTransform: "capitalize",
                  borderRadius: "7px",
                  fontWeight: "500",
                  fontSize: "13px",
                  padding: "6px 13px",
                }}
                color="primary"
              >
                <AddIcon sx={{ position: "relative", top: "-1px" }} /> Add New
                Product
              </Button>
            </Link>
          </Box>

          {/* Table */}
          <TableContainer
            component={Paper}
            sx={{
              boxShadow: "none",
              borderRadius: "7px",
            }}
            className="rmui-table border"
          >
            <Table sx={{ minWidth: 1250 }} aria-label="Table">
              <TableHead className="bg-f6f7f9">
                <TableRow>
                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    ID
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Product
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Category
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Price
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Order
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Stock
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Amount
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Rating
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Status
                  </TableCell>

                  <TableCell
                    sx={{
                      fontWeight: "500",
                      padding: "10px 20px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    Action
                  </TableCell>
                </TableRow>
              </TableHead>

              <TableBody>
                {(rowsPerPage > 0
                  ? rows.slice(
                      page * rowsPerPage,
                      page * rowsPerPage + rowsPerPage
                    )
                  : rows
                ).map((row) => (
                  <TableRow key={row.orderID}>
                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="border-bottom"
                    >
                      {row.orderID}
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="border-bottom"
                    >
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                          gap: "13px",
                        }}
                      >
                        <Box sx={{ flexShrink: "0" }}>
                          <Image
                            src={row.productImage}
                            alt="Product"
                            width={40}
                            height={40}
                            style={{ borderRadius: "7px" }}
                          />
                        </Box>

                        <Box>
                          <Link href={row.detailsLink}>
                            <Typography
                              sx={{
                                fontSize: "15px",
                                fontWeight: "500",
                              }}
                              className="text-black"
                            >
                              {row.productName}
                            </Typography>
                          </Link>

                          <Typography
                            sx={{
                              fontSize: "13px",
                            }}
                            className="text-body"
                          >
                            {row.date}
                          </Typography>
                        </Box>
                      </Box>
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      {row.category}
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      {row.price}
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      {row.order}
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      {row.stock}
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      {row.amount}
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      {row.rating}
                    </TableCell>

                    <TableCell
                      sx={{
                        borderBottom: "1px solid #eceef2",
                        padding: "14px 20px",
                      }}
                      className="border-bottom"
                    >
                      <div className={`pro.io-badge ${row.status}`}>
                        {row.status}
                      </div>
                    </TableCell>

                    <TableCell
                      sx={{
                        padding: "14px 20px",
                      }}
                      className="border-bottom"
                    >
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <Link href={row.detailsLink}>
                          <IconButton
                            aria-label="view"
                            color="primary"
                            sx={{ padding: "5px" }}
                          >
                            <i
                              className="material-symbols-outlined"
                              style={{ fontSize: "16px" }}
                            >
                              visibility
                            </i>
                          </IconButton>
                        </Link>

                        <IconButton
                          aria-label="edit"
                          color="secondary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            edit
                          </i>
                        </IconButton>

                        <IconButton
                          aria-label="delete"
                          color="error"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            delete
                          </i>
                        </IconButton>
                      </Box>
                    </TableCell>
                  </TableRow>
                ))}
                {emptyRows > 0 && (
                  <TableRow style={{ height: 53 * emptyRows }}>
                    <TableCell colSpan={10} />
                  </TableRow>
                )}
              </TableBody>

              <TableFooter>
                <TableRow>
                  <TablePagination
                    rowsPerPageOptions={[
                      5,
                      10,
                      25,
                      { label: "All", value: -1 },
                    ]}
                    colSpan={10}
                    count={rows.length}
                    rowsPerPage={rowsPerPage}
                    page={page}
                    slotProps={{
                      select: {
                        inputProps: {
                          "aria-label": "rows per page",
                        },
                        native: true,
                      },
                    }}
                    onPageChange={handleChangePage}
                    onRowsPerPageChange={handleChangeRowsPerPage}
                    ActionsComponent={TablePaginationActions}
                    sx={{
                      border: "none",
                    }}
                  />
                </TableRow>
              </TableFooter>
            </Table>
          </TableContainer>
        </Box>
      </Card>
    </>
  );
};

export default ProductsList;
