// react-bootstrap/src/components/Dashboard/SaaS/LatestTransaction/index.js
"use client";

import { useState } from "react";
import { Card, Form, Table, Button } from "react-bootstrap";

// Mock data for transactions (replace with data from an API or a state variable)
const transactionData = [
  // Add your mock transaction items here
  {
    id: "#001",
    client: {
      name: "Johhna Loren",
      email: "loren123@gmail.com",
      image: "/images/user-81.png",
    },
    amount: "$6240",
    plan: "Pro",
    paymentMethod: { name: "Paypal", icon: "/images/paypal.png" },
    status: { label: "Completed", className: "bg-success" },
  },
  {
    id: "#002",
    client: {
      name: "Skyler White",
      email: "skyqueen@gmail.com",
      image: "/images/user-82.png",
    },
    amount: "$5135",
    plan: "Enterprise",
    paymentMethod: { name: "Wise", icon: "/images/wise.png" },
    status: { label: "Pending", className: "bg-primary-div" },
  },
  {
    id: "#003",
    client: {
      name: "Jonathon Watson",
      email: "jona2134@gmail.com",
      image: "/images/user-83.png",
    },
    amount: "$4321",
    plan: "Startup",
    paymentMethod: { name: "Bank", icon: "/images/bank.png" },
    status: { label: "Failed", className: "bg-danger" },
  },
  {
    id: "#004",
    client: {
      name: "Walter White",
      email: "Puzzleworld",
      image: "/images/user-84.png",
    },
    amount: "$3124",
    plan: "Pro",
    paymentMethod: { name: "Skrill", icon: "/images/skrill.png" },
    status: { label: "Completed", className: "bg-success" },
  },
  {
    id: "#005",
    client: {
      name: "David Carlen",
      email: "Liveslong",
      image: "/images/user-85.png",
    },
    amount: "$2137",
    plan: "Basic",
    paymentMethod: { name: "Paypal", icon: "/images/paypal.png" },
    status: { label: "Pending", className: "bg-primary-div" },
  },
  {
    id: "#006",
    client: {
      name: "Skyler White",
      email: "skyqueen@gmail.com",
      image: "/images/user-82.png",
    },
    amount: "$5135",
    plan: "Enterprise",
    paymentMethod: { name: "Wise", icon: "/images/wise.png" },
    status: { label: "Pending", className: "bg-primary-div" },
  },
  {
    id: "#007",
    client: {
      name: "Walter White",
      email: "Puzzleworld",
      image: "/images/user-84.png",
    },
    amount: "$3124",
    plan: "Pro",
    paymentMethod: { name: "Skrill", icon: "/images/skrill.png" },
    status: { label: "Completed", className: "bg-success" },
  },
  {
    id: "#008",
    client: {
      name: "Jonathon Watson",
      email: "jona2134@gmail.com",
      image: "/images/user-83.png",
    },
    amount: "$4321",
    plan: "Startup",
    paymentMethod: { name: "Bank", icon: "/images/bank.png" },
    status: { label: "Failed", className: "bg-danger" },
  },
  {
    id: "#009",
    client: {
      name: "David Carlen",
      email: "Liveslong",
      image: "/images/user-85.png",
    },
    amount: "$2137",
    plan: "Basic",
    paymentMethod: { name: "Paypal", icon: "/images/paypal.png" },
    status: { label: "Pending", className: "bg-primary-div" },
  },
  {
    id: "#010",
    client: {
      name: "Johhna Loren",
      email: "loren123@gmail.com",
      image: "/images/user-81.png",
    },
    amount: "$6240",
    plan: "Pro",
    paymentMethod: { name: "Paypal", icon: "/images/paypal.png" },
    status: { label: "Completed", className: "bg-success" },
  },
];

const ITEMS_PER_PAGE = 5;

const LatestTransaction = () => {
  const [currentPage, setCurrentPage] = useState(1);

  // Calculate the data to be displayed on the current page
  const indexOfLastItem = currentPage * ITEMS_PER_PAGE;
  const indexOfFirstItem = indexOfLastItem - ITEMS_PER_PAGE;
  const currentItems = transactionData.slice(indexOfFirstItem, indexOfLastItem);
  const totalPages = Math.ceil(transactionData.length / ITEMS_PER_PAGE);

  const handlePrevPage = () => setCurrentPage((prev) => Math.max(prev - 1, 1));
  const handleNextPage = () =>
    setCurrentPage((prev) => Math.min(prev + 1, totalPages));

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3">
            <h3 className="mb-0">Latest Transaction</h3>
            <Form.Select
              className="month-select form-control w-135 bg-border-color border-color"
              aria-label="Default select example"
            >
              <option value="0">Monthly</option>
              <option value="1">Yearly</option>
            </Form.Select>
          </div>

          <div className="default-table-area style-two campaigns-table latest-transaction-table">
            <div className="table-responsive">
              <Table className="align-middle border-0">
                <thead>
                  <tr className="border-bottom">
                    <th className="bg-transparent text-body fw-medium">
                      <span className="fs-12">ID</span>
                    </th>
                    <th className="bg-transparent text-body fw-medium">
                      <span className="fs-12">CLIENT</span>
                    </th>
                    <th className="bg-transparent text-body fw-medium">
                      <span className="fs-12">AMOUNT</span>
                    </th>
                    <th className="bg-transparent text-body fw-medium">
                      <span className="fs-12">SUBSCRIPTION PLAN</span>
                    </th>
                    <th className="bg-transparent text-body fw-medium">
                      <span className="fs-12">PAYMENT METHOD</span>
                    </th>
                    <th className="text-end bg-transparent text-body fw-medium">
                      <span className="fs-12">STATUS</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {currentItems.map((transaction) => (
                    <tr key={transaction.id}>
                      <td className="fs-12 fw-semibold text-body">
                        {transaction.id}
                      </td>
                      <td>
                        <div className="d-flex align-items-center">
                          <div className="flex-shrink-0">
                            <img
                              src={transaction.client.image}
                              className="rounded-circle"
                              alt="client"
                              width={40}
                              height={40}
                            />
                          </div>
                          <div className="flex-grow-1 ms-2">
                            <h4 className="fs-14 fw-semibold mb-0">
                              {transaction.client.name}
                            </h4>
                            <span className="fs-12">
                              {transaction.client.email}
                            </span>
                          </div>
                        </div>
                      </td>
                      <td className="fs-12 fw-semibold text-body">
                        {transaction.amount}
                      </td>
                      <td className="fs-12 fw-semibold text-body">
                        {transaction.plan}
                      </td>
                      <td>
                        <div className="d-flex align-items-center gap-1">
                          <img
                            src={transaction.paymentMethod.icon}
                            alt={transaction.paymentMethod.name}
                            width={24}
                            height={24}
                          />
                          <span className="ms-2">
                            {transaction.paymentMethod.name}
                          </span>
                        </div>
                      </td>
                      <td className="text-end">
                        <span
                          className={`d-inline-block px-2 ${
                            transaction.status.className
                          } bg-opacity-10 text-${
                            transaction.status.className.split("-")[1]
                          } border border-${
                            transaction.status.className.split("-")[1]
                          } rounded-pill fs-12 fw-medium`}
                        >
                          {transaction.status.label}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            </div>

            <div className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap mt-4">
              <span className="fs-12 fw-medium">
                Showing {currentItems.length} of {transactionData.length}{" "}
                Results
              </span>

              <nav aria-label="Page navigation example">
                <ul className="pagination mb-0 justify-content-center">
                  <li className="page-item">
                    <Button
                      onClick={handlePrevPage}
                      className={`page-link icon ${
                        currentPage === 1 && "disabled"
                      }`}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_left
                      </i>
                    </Button>
                  </li>

                  <li className="page-item">
                    <Button
                      onClick={handleNextPage}
                      className={`page-link icon ${
                        currentPage === totalPages && "disabled"
                      }`}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_right
                      </i>
                    </Button>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default LatestTransaction;

// nuxtjs-vuetify/components/Dashboard/SaaS/LatestTransaction.vue
<template>
  <v-card
    class="latest-transaction-card trezo-card border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header mb-4">
      <h5 class="mb-0">Latest Transaction</h5>
      <div class="d-flex align-items-center">
        <v-menu>
          <template v-slot:activator="{ props }">
            <button
              type="button"
              v-bind="props"
              class="card-header-menu d-inline-block border-radius"
            >
              Monthly
            </button>
          </template>
          <v-list class="menu-content">
            <button type="button" class="bg-transparent border-none">
              Monthly
            </button>
            <button type="button" class="bg-transparent border-none">
              Yearly
            </button>
          </v-list>
        </v-menu>
      </div>
    </div>

    <div
      class="default-table-area style-two campaigns-table latest-transaction-table"
    >
      <div class="table-responsive">
        <table
          class="table align-middle border-0"
          border="0"
          cellspacing="0"
          cellpadding="0"
        >
          <thead>
            <tr>
              <th class="bg-transparent border-bottom text-body fw-medium">
                <span class="fs-12">ID</span>
              </th>
              <th class="bg-transparent border-bottom text-body fw-medium">
                <span class="fs-12">CLIENT</span>
              </th>
              <th class="bg-transparent border-bottom text-body fw-medium">
                <span class="fs-12">AMOUNT</span>
              </th>
              <th class="bg-transparent border-bottom text-body fw-medium">
                <span class="fs-12">SUBSCRIPTION PLAN</span>
              </th>
              <th class="bg-transparent border-bottom text-body fw-medium">
                <span class="fs-12">PAYMENT METHOD</span>
              </th>
              <th
                class="text-end bg-transparent border-bottom text-body fw-medium"
              >
                <span class="fs-12">STATUS</span>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="border-bottom fs-12 fw-semibold text-body">#001</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center">
                  <div class="flex-shrink-0">
                    <v-img
                      src="@/assets/images/user-81.png"
                      class="rounded-circle"
                      style="width: 40px; height: 40px"
                      alt="nft"
                    />
                  </div>
                  <div class="flex-grow-1 ms-2">
                    <h4 class="fs-14 fw-semibold mb-0">Johhna Loren</h4>
                    <span class="fs-12 text-body">loren123@gmail.com</span>
                  </div>
                </div>
              </td>
              <td class="border-bottom fs-12 fw-semibold text-body">$6240</td>
              <td class="border-bottom fs-12 fw-semibold text-body">Pro</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center ga-1">
                  <v-img src="~/assets/images/paypal.png" alt="paypal" />
                  <span class="ms-2 text-body">Paypal</span>
                </div>
              </td>
              <td class="border-bottom text-end">
                <span
                  class="d-inline-block px-2 bg-success bg-opacity-10 text-success border border-success rounded-pill fs-12 fw-medium"
                >
                  Completed
                </span>
              </td>
            </tr>
            <tr>
              <td class="border-bottom fs-12 fw-semibold text-body">#002</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center">
                  <div class="flex-shrink-0">
                    <v-img
                      src="@/assets/images/user-82.png"
                      class="rounded-circle"
                      style="width: 40px; height: 40px"
                      alt="nft"
                    />
                  </div>
                  <div class="flex-grow-1 ms-2">
                    <h4 class="fs-14 fw-semibold mb-0">Skyler White</h4>
                    <span class="fs-12 text-body">skyqueen@gmail.com</span>
                  </div>
                </div>
              </td>
              <td class="border-bottom fs-12 fw-semibold text-body">$5135</td>
              <td class="border-bottom fs-12 fw-semibold text-body">
                Enterprise
              </td>
              <td class="border-bottom">
                <div class="d-flex align-items-center ga-1">
                  <v-img src="~/assets/images/wise.png" alt="paypal" />
                  <span class="ms-2 text-body">Wise</span>
                </div>
              </td>
              <td class="border-bottom text-end">
                <span
                  class="d-inline-block px-2 bg-primary-div bg-opacity-10 text-primary-div border border-primary-div rounded-pill fs-12 fw-medium"
                >
                  Pending
                </span>
              </td>
            </tr>
            <tr>
              <td class="border-bottom fs-12 fw-semibold text-body">#003</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center">
                  <div class="flex-shrink-0">
                    <v-img
                      src="@/assets/images/user-83.png"
                      class="rounded-circle"
                      style="width: 40px; height: 40px"
                      alt="nft"
                    />
                  </div>
                  <div class="flex-grow-1 ms-2">
                    <h4 class="fs-14 fw-semibold mb-0">Jonathon Watson</h4>
                    <span class="fs-12 text-body">jona2134@gmail.com</span>
                  </div>
                </div>
              </td>
              <td class="border-bottom fs-12 fw-semibold text-body">$4321</td>
              <td class="border-bottom fs-12 fw-semibold text-body">Startup</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center ga-1">
                  <v-img src="~/assets/images/bank.png" alt="bank" />
                  <span class="ms-2 text-body">Bank</span>
                </div>
              </td>
              <td class="border-bottom text-end">
                <span
                  class="d-inline-block px-2 bg-danger bg-opacity-10 text-danger border border-danger rounded-pill fs-12 fw-medium"
                >
                  Failed
                </span>
              </td>
            </tr>
            <tr>
              <td class="border-bottom fs-12 fw-semibold text-body">#004</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center">
                  <div class="flex-shrink-0">
                    <v-img
                      src="@/assets/images/user-84.png"
                      class="rounded-circle"
                      style="width: 40px; height: 40px"
                      alt="nft"
                    />
                  </div>
                  <div class="flex-grow-1 ms-2">
                    <h4 class="fs-14 fw-semibold mb-0">Walter White</h4>
                    <span class="fs-12 text-body">Puzzleworld</span>
                  </div>
                </div>
              </td>
              <td class="border-bottom fs-12 fw-semibold text-body">$3124</td>
              <td class="border-bottom fs-12 fw-semibold text-body">Pro</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center ga-1">
                  <v-img src="~/assets/images/skrill.png" alt="skrill" />
                  <span class="ms-2 text-body">Skrill</span>
                </div>
              </td>
              <td class="border-bottom text-end">
                <span
                  class="d-inline-block px-2 bg-success bg-opacity-10 text-success border border-success rounded-pill fs-12 fw-medium"
                >
                  Completed
                </span>
              </td>
            </tr>
            <tr>
              <td class="border-bottom fs-12 fw-semibold text-body">#005</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center">
                  <div class="flex-shrink-0">
                    <v-img
                      src="@/assets/images/user-85.png"
                      class="rounded-circle"
                      style="width: 40px; height: 40px"
                      alt="nft"
                    />
                  </div>
                  <div class="flex-grow-1 ms-2">
                    <h4 class="fs-14 fw-semibold mb-0">David Carlen</h4>
                    <span class="fs-12 text-body">Liveslong</span>
                  </div>
                </div>
              </td>
              <td class="border-bottom fs-12 fw-semibold text-body">$2137</td>
              <td class="border-bottom fs-12 fw-semibold text-body">Basic</td>
              <td class="border-bottom">
                <div class="d-flex align-items-center ga-1">
                  <v-img src="~/assets/images/paypal.png" alt="paypal" />
                  <span class="ms-2 text-body">Paypal</span>
                </div>
              </td>
              <td class="border-bottom text-end">
                <span
                  class="d-inline-block px-2 bg-primary-div bg-opacity-10 text-primary-div border border-primary-div rounded-pill fs-12 fw-medium"
                >
                  Pending
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <PaginationTwo items="05" total="30" class="pb-0 pt-3 border-none" />
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import PaginationTwo from "../../Common/PaginationTwo.vue";

export default defineComponent({
  name: "LatestTransaction",
  components: {
    PaginationTwo,
  },
});
</script>

<style lang="scss" scoped>
.latest-transaction-card {
  .bg-success {
    background-color: rgba(55, 216, 10, 0.1) !important;
  }
  .bg-primary-div {
    background-color: rgba(173, 99, 246, 0.1) !important;
  }
  .text-primary-div {
    color: rgb(173 99 246) !important;
  }
  .bg-danger {
    background-color: rgba(253, 88, 18, 0.1) !important;
  }
}
</style>
