// react-material-ui/src/components/HelpDesk/TicketDetails/Ticket/index.js
"use client";

import React, { useState } from "react";

import {
  Card,
  Box,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Paper,
  IconButton,
  Link,
} from "@mui/material";

function createData(
  id,
  ticketTitle,
  requester,
  assignedTo,
  createdDate,
  dueDate,
  priority,
  status,
  viewDetails
) {
  return {
    id,
    ticketTitle,
    requester,
    assignedTo,
    createdDate,
    dueDate,
    priority,
    status,
    viewDetails,
  };
}

const rows = [
  createData(
    "#JAN-854",
    "Network Infrastructure",
    "Walter Frazier",
    "Oliver Clark",
    "20 Apr 2024",
    "30 Apr 2024",
    "High",
    "finished",
    "/helpdesk/tickets/details"
  ),
].sort((b, a) => (a.id < b.id ? -1 : 1));

const Ticket = () => {
  const [page] = useState(0);
  const [rowsPerPage] = useState(10);

  const emptyRows =
    page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        {/* Table */}
        <TableContainer
          component={Paper}
          sx={{
            boxShadow: "none",
            borderRadius: "7px",
          }}
          className="rmui-table border"
        >
          <Table sx={{ minWidth: 1100 }} aria-label="Table">
            <TableBody>
              {(rowsPerPage > 0
                ? rows.slice(
                    page * rowsPerPage,
                    page * rowsPerPage + rowsPerPage
                  )
                : rows
              ).map((row) => (
                <TableRow
                  key={row.id}
                  sx={{
                    td: {
                      padding: "15px 20px",
                      fontSize: "14px",
                    },
                  }}
                >
                  <TableCell className="border-bottom">{row.id}</TableCell>

                  <TableCell className="border-bottom">
                    {row.ticketTitle}
                  </TableCell>

                  <TableCell className="border-bottom">
                    {row.requester}
                  </TableCell>

                  <TableCell className="border-bottom">
                    {row.assignedTo}
                  </TableCell>

                  <TableCell className="border-bottom">
                    {row.createdDate}
                  </TableCell>

                  <TableCell className="border-bottom">{row.dueDate}</TableCell>

                  <TableCell className="border-bottom">
                    {row.priority}
                  </TableCell>

                  <TableCell className="border-bottom">
                    <div
                      className={`trezo-badge ${row.status}`}
                      style={{ textTransform: "capitalize" }}
                    >
                      {row.status}
                    </div>
                  </TableCell>

                  <TableCell className="border-bottom">
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                      }}
                    >
                      <Link href={row.viewDetails}>
                        <IconButton
                          aria-label="view"
                          color="primary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            visibility
                          </i>
                        </IconButton>

                        <IconButton
                          aria-label="edit"
                          color="secondary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            edit
                          </i>
                        </IconButton>
                      </Link>

                      <IconButton
                        aria-label="delete"
                        color="error"
                        sx={{ padding: "5px" }}
                      >
                        <i
                          className="material-symbols-outlined"
                          style={{ fontSize: "16px" }}
                        >
                          delete
                        </i>
                      </IconButton>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
              {emptyRows > 0 && (
                <TableRow style={{ height: 53 * emptyRows }}>
                  <TableCell className="border-bottom" colSpan={9} />
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      </Card>
    </>
  );
};

export default Ticket;

// nuxtjs-vuetify/components/Pages/HelpDesk/TicketDetails/Ticket.vue
<template>
  <v-card
    class="all-tickets-card trezo-card border-radius mb-25 d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Ticket</h5>
    </div>
    <div class="trezo-table-content">
      <div class="trezo-table">
        <v-table>
          <thead>
            <tr>
              <th class="text-start">ID</th>
              <th class="text-start">Ticket Title</th>
              <th class="text-start">Requester</th>
              <th class="text-start">Assigned To</th>
              <th class="text-start">Created Date</th>
              <th class="text-start">Due Date</th>
              <th class="text-start">Priority</th>
              <th class="text-start">Status</th>
              <th class="text-start">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in items" :key="item.id">
              <td class="text-start">
                <NuxtLink to="/dashboard" class="text-body">
                  {{ item.id }}
                </NuxtLink>
              </td>
              <td>
                <NuxtLink
                  to="/helpdesk/ticket-details"
                  class="project-name fw-medium"
                >
                  {{ item.ticketTitle }}
                </NuxtLink>
              </td>
              <td>{{ item.requester }}</td>
              <td>{{ item.assignedTo }}</td>
              <td class="text-body">{{ item.createdDate }}</td>
              <td>{{ item.dueDate }}</td>
              <td>{{ item.priority }}</td>
              <td>
                <span
                  class="trezo-status-badge"
                  :class="computeClass(item.status)"
                >
                  {{ item.status }}
                </span>
              </td>
              <td>
                <div class="action-buttons d-flex align-items-center">
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.view }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.edit }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.delete }}
                    </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </v-table>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  name: "Ticket",
  setup() {
    const items = ref([
      {
        id: "#JAN-854",
        ticketTitle: "Network Infrastructure",
        requester: "Walter Frazier",
        assignedTo: "Oliver Clark",
        createdDate: "20 Apr 2024",
        dueDate: "30 Apr 2024",
        priority: "High",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
    ]);

    // const wordFinished = ref("Finished");
    const wordPending = ref("Pending");
    const wordInProgress = ref("In Progress");
    const wordCancelled = ref("Cancelled");

    const computeClass = (classValue: string) => {
      return {
        // finished: wordFinished.value === classValue,
        pending: wordPending.value === classValue,
        inProgress: wordInProgress.value === classValue,
        cancelled: wordCancelled.value === classValue,
      };
    };

    return {
      items,
      computeClass,
    };
  },
});
</script>

<style lang="scss" scoped>
.all-tickets-card {
  .trezo-table-content {
    .trezo-table {
      .pagination-content {
        margin-top: 0;
        padding: 15px 20px;
        border-radius: 0 0 7px 7px;
        color: var(--blackColor) !important;
        background-color: transparent !important;
        border-left: 1px solid #eceef2;
        border-right: 1px solid #eceef2;
        border-bottom: 1px solid #eceef2;
      }
    }
  }
}
</style>
