// react-nextjs-tailwindcss/src/components/Dashboard/RealEstate/LatestTransactions.tsx
"use client";

import React, { useState } from "react";
import Image from "next/image";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";

// Sample data for transactions
const initialTransactionsData = [
  {
    id: "TRE0015",
    customerName: "Sarah Johnson",
    image: "/images/users/user1.jpg",
    property: "Industrial",
    date: "30 Apr 2024",
    price: "$500,000",
    status: "Completed",
    paymentMethod: "Master Card",
  },
  {
    id: "TRE0016",
    customerName: "Michael Smith",
    image: "/images/users/user2.jpg",
    property: "Office",
    date: "29 Apr 2024",
    price: "$1,200,000",
    status: "Pending",
    paymentMethod: "Paypal",
  },
  {
    id: "TRE0017",
    customerName: "Emily Brown",
    image: "/images/users/user3.jpg",
    property: "Multi-Family",
    date: "28 Apr 2024",
    price: "$350,000",
    status: "Cancel",
    paymentMethod: "Wise",
  },
  {
    id: "TRE0018",
    customerName: "Jason Lee",
    image: "/images/users/user4.jpg",
    property: "Residential",
    date: "27 Apr 2024",
    price: "$220,000",
    status: "Completed",
    paymentMethod: "Payoneer",
  },
  {
    id: "TRE0019",
    customerName: "Ashley Davis",
    image: "/images/users/user5.jpg",
    property: "Commercial",
    date: "26 Apr 2024",
    price: "$1,500,000",
    status: "Rejected",
    paymentMethod: "Credit Card",
  },
  {
    id: "TRE0020",
    customerName: "Emily Brown",
    image: "/images/users/user3.jpg",
    property: "Multi-Family",
    date: "28 Apr 2024",
    price: "$350,000",
    status: "Cancel",
    paymentMethod: "Wise",
  },
  {
    id: "TRE0021",
    customerName: "Sarah Johnson",
    image: "/images/users/user1.jpg",
    property: "Industrial",
    date: "30 Apr 2024",
    price: "$500,000",
    status: "Completed",
    paymentMethod: "Master Card",
  },
  {
    id: "TRE0022",
    customerName: "Ashley Davis",
    image: "/images/users/user5.jpg",
    property: "Commercial",
    date: "26 Apr 2024",
    price: "$1,500,000",
    status: "Rejected",
    paymentMethod: "Credit Card",
  },
  {
    id: "TRE0023",
    customerName: "Michael Smith",
    image: "/images/users/user2.jpg",
    property: "Office",
    date: "29 Apr 2024",
    price: "$1,200,000",
    status: "Pending",
    paymentMethod: "Paypal",
  },
  {
    id: "TRE0024",
    customerName: "Jason Lee",
    image: "/images/users/user4.jpg",
    property: "Residential",
    date: "27 Apr 2024",
    price: "$220,000",
    status: "Completed",
    paymentMethod: "Payoneer",
  },
];

const ITEMS_PER_PAGE = 5; // Number of transactions per page

const LatestTransactions: React.FC = () => {
  const [selectedOption, setSelectedOption] = useState<string>("Last 30 Days");
  const [transactions, setTransactions] = useState(initialTransactionsData);
  const [currentPage, setCurrentPage] = useState(1);

  const handleSelect = (option: string) => {
    setSelectedOption(option);
    console.log(`Selected option: ${option}`);
  };

  // Handle row deletion
  const handleDelete = (id: string) => {
    setTransactions((prevTransactions) =>
      prevTransactions.filter((transaction) => transaction.id !== id)
    );
  };

  // Pagination logic
  const totalPages = Math.ceil(transactions.length / ITEMS_PER_PAGE);
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
  const endIndex = startIndex + ITEMS_PER_PAGE;
  const currentTransactions = transactions.slice(startIndex, endIndex);

  // Handle page change
  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  return (
    <>
      <div className="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
        <div className="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
          <div className="trezo-card-title">
            <h5 className="mb-0">Latest Transactions</h5>
          </div>

          <div className="trezo-card-subtitle">
            <Menu as="div" className="trezo-card-dropdown relative">
              <MenuButton className="trezo-card-dropdown-btn inline-block transition-all hover:text-primary-500">
                <span className="inline-block relative ltr:pr-[17px] ltr:md:pr-[20px] rtl:pl-[17px] rtl:ml:pr-[20px]">
                  {selectedOption}
                  <i className="ri-arrow-down-s-line text-lg absolute ltr:-right-[3px] rtl:-left-[3px] top-1/2 -translate-y-1/2"></i>
                </span>
              </MenuButton>

              <MenuItems
                transition
                className="transition-all bg-white shadow-3xl rounded-md top-full py-[15px] absolute ltr:right-0 rtl:left-0 w-[195px] z-[50] dark:bg-dark dark:shadow-none data-[closed]:scale-95 data-[closed]:transform data-[closed]:opacity-0 data-[enter]:duration-100 data-[leave]:duration-75 data-[enter]:ease-out data-[leave]:ease-in"
              >
                {["Last 7 Days", "Last 15 Days", "Last 30 Days"].map(
                  (option) => (
                    <MenuItem
                      key={option}
                      as="div"
                      className={`block w-full transition-all text-black cursor-pointer ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black ${
                        selectedOption === option ? "font-semibold" : ""
                      }`}
                      onClick={() => handleSelect(option)}
                    >
                      {option}
                    </MenuItem>
                  )
                )}
              </MenuItems>
            </Menu>
          </div>
        </div>

        <div className="trezo-card-content -mx-[20px] md:-mx-[25px]">
          <div className="table-responsive overflow-x-auto">
            <table className="w-full">
              <thead className="text-black dark:text-white">
                <tr>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Customer ID
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Customer Name
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Property
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Date
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Price
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Status
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Payment
                  </th>
                  <th className="font-normal ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Action
                  </th>
                </tr>
              </thead>

              <tbody className="text-black dark:text-white">
                {currentTransactions.map((transaction) => (
                  <tr key={transaction.id}>
                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <div className="flex items-center gap-[15px]">
                        <div className="form-check relative top-[1.5px]">
                          <input type="checkbox" className="cursor-pointer" />
                        </div>
                        <span className="text-gray-500 dark:text-gray-400">
                          #{transaction.id}
                        </span>
                      </div>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <div className="flex items-center">
                        <div className="rounded-md w-[40px]">
                          <Image
                            src={transaction.image}
                            className="inline-block rounded-md"
                            alt="product-image"
                            width={40}
                            height={40}
                          />
                        </div>
                        <div className="ltr:ml-[12px] rtl:mr-[12px]">
                          <span className="block font-medium">
                            {transaction.customerName}
                          </span>
                        </div>
                      </div>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <span className="text-gray-500 dark:text-gray-400">
                        {transaction.property}
                      </span>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <span className="text-gray-500 dark:text-gray-400">
                        {transaction.date}
                      </span>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      {transaction.price}
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <span
                        className={`px-[8px] py-[3px] inline-block rounded-sm font-medium text-xs ${
                          transaction.status === "Completed"
                            ? "bg-success-50 dark:bg-[#15203c] text-success-600"
                            : transaction.status === "Pending"
                            ? "bg-secondary-50 dark:bg-[#15203c] text-secondary-600"
                            : transaction.status === "Cancel"
                            ? "bg-orange-50 dark:bg-[#15203c] text-orange-600"
                            : "bg-danger-50 dark:bg-[#15203c] text-danger-600"
                        }`}
                      >
                        {transaction.status}
                      </span>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <span className="text-gray-500 dark:text-gray-400">
                        {transaction.paymentMethod}
                      </span>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <div className="flex items-center gap-[9px]">
                        <div className="relative group">
                          <button
                            type="button"
                            className="text-primary-500 leading-none"
                          >
                            <i className="material-symbols-outlined !text-md">
                              visibility
                            </i>
                          </button>

                          {/* Tooltip */}
                          <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs rounded px-2 py-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            View
                            {/* Arrow */}
                            <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-white dark:border-[#172036] border-t-gray-800 dark:border-t-gray-800"></div>
                          </div>
                        </div>

                        <div className="relative group">
                          <button
                            type="button"
                            className="text-gray-500 leading-none"
                          >
                            <i className="material-symbols-outlined !text-md">
                              edit
                            </i>
                          </button>

                          {/* Tooltip */}
                          <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs rounded px-2 py-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            Edit
                            {/* Arrow */}
                            <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-white dark:border-[#172036] border-t-gray-800 dark:border-t-gray-800"></div>
                          </div>
                        </div>

                        <div className="relative group">
                          <button
                            type="button"
                            className="text-danger-500 leading-none"
                            onClick={() => handleDelete(transaction.id)}
                          >
                            <i className="material-symbols-outlined !text-md">
                              delete
                            </i>
                          </button>

                          {/* Tooltip */}
                          <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs rounded px-2 py-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            Delete
                            {/* Arrow */}
                            <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-white dark:border-[#172036] border-t-gray-800 dark:border-t-gray-800"></div>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="px-[20px] md:px-[25px] pt-[12px] md:pt-[14px] sm:flex sm:items-center justify-between">
            <p className="mb-0 text-sm">
              Showing {startIndex + 1} to{" "}
              {Math.min(endIndex, transactions.length)} of {transactions.length}{" "}
              results
            </p>

            <ol className="mt-[10px] sm:mt-0">
              <li className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                <button
                  className="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500"
                  onClick={() => handlePageChange(currentPage - 1)}
                  disabled={currentPage === 1}
                >
                  <span className="opacity-0">0</span>
                  <i className="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                    chevron_left
                  </i>
                </button>
              </li>
              {Array.from({ length: totalPages }, (_, index) => (
                <li
                  key={index + 1}
                  className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0"
                >
                  <button
                    className={`w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border ${
                      currentPage === index + 1
                        ? "border-primary-500 bg-primary-500 text-white"
                        : "border-gray-100 dark:border-[#172036] hover:bg-primary-500 hover:text-white hover:border-primary-500"
                    }`}
                    onClick={() => handlePageChange(index + 1)}
                  >
                    {index + 1}
                  </button>
                </li>
              ))}
              <li className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                <button
                  className="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500"
                  onClick={() => handlePageChange(currentPage + 1)}
                  disabled={currentPage === totalPages}
                >
                  <span className="opacity-0">0</span>
                  <i className="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                    chevron_right
                  </i>
                </button>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </>
  );
};

export default LatestTransactions;

// angular-bootstrap/src/app/dashboard/real-estate/latest-transactions/latest-transactions.component.ts
import { Component, HostListener } from '@angular/core';
import { NgIf } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-latest-transactions',
    imports: [NgIf, RouterLink],
    templateUrl: './latest-transactions.component.html',
    styleUrl: './latest-transactions.component.scss'
})
export class LatestTransactionsComponent {

    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-header-menu')) {
            this.isCardHeaderOpen = false;
        }
    }
}
<div class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Latest Transactions
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-header-menu position-relative">
                <button class="menu-btn without-border transition d-inline-block bg-transparent border-radius" (click)="toggleCardHeaderMenu()">
                    <span class="d-block position-relative">
                        Last 30 Days
                    </span>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            Last 7 Days
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            Last 15 Days
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            Last 30 Days
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="table-style-two">
            <div class="basic-table table-responsive">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th scope="col" class="fw-medium">
                                Customer ID
                            </th>
                            <th scope="col" class="fw-medium">
                                Customer Name
                            </th>
                            <th scope="col" class="fw-medium">
                                Property
                            </th>
                            <th scope="col" class="fw-medium">
                                Date
                            </th>
                            <th scope="col" class="fw-medium">
                                Price
                            </th>
                            <th scope="col" class="fw-medium">
                                Status
                            </th>
                            <th scope="col" class="fw-medium">
                                Payment
                            </th>
                            <th scope="col" class="fw-medium">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TRE0015
                                    </span>
                                </div>
                            </td>
                            <td>
                                <div class="customer-info d-flex align-items-center">
                                    <div class="img">
                                        <img alt="user-image" src="images/users/user1.jpg">
                                    </div>
                                    <span class="d-block fw-medium">
                                        Sarah Johnson
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                Industrial
                            </td>
                            <td class="text-body">
                                30 Apr 2024
                            </td>
                            <td>
                                $500,000
                            </td>
                            <td>
                                <span class="trezo-badge shipped">
                                    Completed
                                </span>
                            </td>
                            <td class="text-body">
                                Master Card
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TRE0099
                                    </span>
                                </div>
                            </td>
                            <td>
                                <div class="customer-info d-flex align-items-center">
                                    <div class="img">
                                        <img alt="user-image" src="images/users/user2.jpg">
                                    </div>
                                    <span class="d-block fw-medium">
                                        Michael Smith
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                Office
                            </td>
                            <td class="text-body">
                                29 Apr 2024
                            </td>
                            <td>
                                $1,200,000
                            </td>
                            <td>
                                <span class="trezo-badge sPending">
                                    Pending
                                </span>
                            </td>
                            <td class="text-body">
                                Paypal
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TRE0145
                                    </span>
                                </div>
                            </td>
                            <td>
                                <div class="customer-info d-flex align-items-center">
                                    <div class="img">
                                        <img alt="user-image" src="images/users/user3.jpg">
                                    </div>
                                    <span class="d-block fw-medium">
                                        Emily Brown
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                Multi-Family
                            </td>
                            <td class="text-body">
                                28 Apr 2024
                            </td>
                            <td>
                                $350,000
                            </td>
                            <td>
                                <span class="trezo-badge cancelled">
                                    Cancel
                                </span>
                            </td>
                            <td class="text-body">
                                Wise
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TRE0247
                                    </span>
                                </div>
                            </td>
                            <td>
                                <div class="customer-info d-flex align-items-center">
                                    <div class="img">
                                        <img alt="user-image" src="images/users/user4.jpg">
                                    </div>
                                    <span class="d-block fw-medium">
                                        Jason Lee
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                Residential
                            </td>
                            <td class="text-body">
                                27 Apr 2024
                            </td>
                            <td>
                                $220,000
                            </td>
                            <td>
                                <span class="trezo-badge shipped">
                                    Completed
                                </span>
                            </td>
                            <td class="text-body">
                                Payoneer
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TRE0299
                                    </span>
                                </div>
                            </td>
                            <td>
                                <div class="customer-info d-flex align-items-center">
                                    <div class="img">
                                        <img alt="user-image" src="images/users/user5.jpg">
                                    </div>
                                    <span class="d-block fw-medium">
                                        Ashley Davis
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                Commercial
                            </td>
                            <td class="text-body">
                                26 Apr 2024
                            </td>
                            <td>
                                $1,500,000
                            </td>
                            <td>
                                <span class="trezo-badge rejected">
                                    Rejected
                                </span>
                            </td>
                            <td class="text-body">
                                Credit Card
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="trezo-card-pagination">
                <div class="d-md-flex align-items-center justify-content-between">
                    <p class="mb-0">
                        Showing 5 of 36 results
                    </p>
                    <ol class="list-unstyled mb-0 p-0">
                        <li class="d-inline-block">
                            <a class="prev" routerLink=".">
                                <span class="opacity-0">
                                    0
                                </span>
                                <i class="material-symbols-outlined">
                                    chevron_left
                                </i>
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink="." class="active">
                                1
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                2
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                3
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                4
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a class="next" routerLink=".">
                                <span class="opacity-0">
                                    0
                                </span>
                                <i class="material-symbols-outlined">
                                    chevron_right
                                </i>
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
