// vuejs-tailwindcss/src/components/Apps/Calendar/WorkingSchedule.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md"
  >
    <div
      class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between"
    >
      <div class="trezo-card-title">
        <h5 class="mb-0">Working Schedule</h5>
      </div>
    </div>
    <div class="trezo-card-content relative">
      <CalendarContent />

      <div class="mt-[19px] relative" id="upcomingEventsSlides">
        <span class="block mb-[14px] font-medium"> Upcoming Events: </span>
        <Swiper
          :slidesPerView="1"
          :loop="true"
          :autoplay="{
            delay: 8000,
            disableOnInteraction: true,
          }"
          :pagination="{
            el: '.swiper-pagination',
            clickable: true,
          }"
          :modules="modules"
          class="mySwiper"
        >
          <SwiperSlide class="cursor" v-for="item in items" :key="item.id">
            <div class="relative ltr:pl-[14px] rtl:pr-[14px]">
              <div
                class="absolute ltr:left-0 rtl:right-0 top-[4px] w-[7px] h-[7px] rounded-sm bg-primary-500"
              ></div>
              <h6 class="text-sm mb-[5px] font-semibold">
                Pythons Unleashed: {{ item.title }}
              </h6>
              <span class="text-xs">
                <span class="text-primary-500">
                  {{ item.date }}
                </span>
                - {{ item.startTime }} - {{ item.endTime }}
              </span>
            </div>
          </SwiperSlide>
        </Swiper>
        <div class="swiper-pagination"></div>
      </div>
      <div class="ltr:text-right rtl:text-left">
        <button
          type="button"
          class="inline-block transition-all rounded-md font-medium px-[13px] py-[6px] text-primary-500 border border-primary-500 hover:bg-primary-500 hover:text-white mt-[20px] md:mt-[25px]"
          @click="stateStoreInstance.activeBtn"
        >
          <span class="inline-block relative ltr:pl-[22px] rtl:pr-[22px]">
            <i
              class="material-symbols-outlined !text-[22px] absolute ltr:-left-[4px] rtl:-right-[4px] top-1/2 -translate-y-1/2"
            >
              add
            </i>
            Add New Event
          </span>
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Autoplay, Pagination } from "swiper/modules";
import stateStore from "@/utils/store";

import CalendarContent from "@/components/Common/CalendarContent.vue";

export default defineComponent({
  name: "WorkingSchedule",
  components: {
    CalendarContent,
    Swiper,
    SwiperSlide,
  },
  data() {
    return {
      items: [
        {
          id: 1,
          title: "A Development Expedition",
          date: "June 25, 2025",
          startTime: "12.00 PM",
          endTime: "6.00 PM",
        },
        {
          id: 2,
          title: "A Development Expedition",
          date: "June 25, 2025",
          startTime: "12.00 PM",
          endTime: "6.00 PM",
        },
        {
          id: 3,
          title: "A Development Expedition",
          date: "June 25, 2025",
          startTime: "12.00 PM",
          endTime: "6.00 PM",
        },
      ],
    };
  },
  setup() {
    const stateStoreInstance = stateStore;

    return {
      stateStoreInstance,
      modules: [Autoplay, Pagination],
    };
  },
});
</script>

// angular-tailwindcss/src/app/dashboard/project-management/working-schedule/working-schedule.component.ts
import { Component } from '@angular/core';
import { CarouselModule, OwlOptions } from 'ngx-owl-carousel-o';
import { NgClass, NgFor, NgIf } from '@angular/common';

@Component({
    selector: 'app-working-schedule',
    imports: [CarouselModule, NgFor, NgIf, NgClass],
    templateUrl: './working-schedule.component.html',
    styleUrl: './working-schedule.component.scss'
})
export class WorkingScheduleComponent {

	// Owl Carousel
    upcomingEventsSlides: OwlOptions = {
        items: 1,
		nav: false,
		loop: true,
		margin: 25,
		dots: true,
		autoplay: false,
		smartSpeed: 500,
		autoplayHoverPause: true,
		navText: [
			"<i class='ri-arrow-left-line'></i>",
			"<i class='ri-arrow-right-line'></i>"
		]
    }

    // Calendar
    currentMonth!: number;
    currentYear!: number;
    currentDay!: number; // Current day
    today!: { year: number; month: number; day: number }; // Today's date
    weekdays: string[] = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    monthNames: string[] = [
        'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'
    ];
    daysInMonth: (number | null)[] = []; // Allow null values
    ngOnInit() {
        const today = new Date();
        this.currentMonth = today.getMonth(); // 0-based index
        this.currentYear = today.getFullYear();
        this.currentDay = today.getDate(); // Get current day of the month
        this.today = {
            year: this.currentYear,
            month: this.currentMonth,
            day: this.currentDay
        };
        this.generateCalendar();
    }
    generateCalendar() {
        this.daysInMonth = [];
        const firstDay = new Date(this.currentYear, this.currentMonth, 1).getDay();
        const numberOfDays = new Date(this.currentYear, this.currentMonth + 1, 0).getDate();
        for (let i = 0; i < firstDay; i++) {
            this.daysInMonth.push(null); // Placeholder for days before the first of the month
        }
        for (let i = 1; i <= numberOfDays; i++) {
            this.daysInMonth.push(i);
        }
    }
    previousMonth() {
        this.currentMonth--;
        if (this.currentMonth < 0) {
            this.currentMonth = 11;
            this.currentYear--;
        }
        this.generateCalendar();
    }
    nextMonth() {
        this.currentMonth++;
        if (this.currentMonth > 11) {
            this.currentMonth = 0;
            this.currentYear++;
        }
        this.generateCalendar();
    }
    isToday(day: number | null): boolean {
        if (day === null) return false;
        return (
            this.today.year === this.currentYear &&
            this.today.month === this.currentMonth &&
            this.today.day === day
        );
    }

}
<div class="trezo-card working-schedule-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Working Schedule
            </h5>
        </div>
    </div>
    <div class="trezo-card-content relative">
        <div class="calendar">
            <div class="header flex items-center justify-between mb-[20px]">
                <button (click)="previousMonth()" class="transition-all text-black bg-gray-100 dark:text-white dark:bg-[#172036] flex items-center justify-center rounded-full w-[30px] h-[30px] hover:bg-primary-500 hover:text-white">
                    <i class="material-symbols-outlined rtl:-scale-x-[1]">
                        chevron_left
                    </i>
                </button>
                <span class="block font-medium text-black dark:text-white">
                    {{ monthNames[currentMonth] }} {{ currentYear }}
                </span>
                <button (click)="nextMonth()" class="transition-all text-black bg-gray-100 dark:text-white dark:bg-[#172036] flex items-center justify-center rounded-full w-[30px] h-[30px] hover:bg-primary-500 hover:text-white">
                    <i class="material-symbols-outlined rtl:-scale-x-[1]">
                        chevron_right
                    </i>
                </button>
            </div>
            <div class="weekdays grid grid-cols-7 mb-[6px] text-center">
                <div class="text-black dark:text-white font-medium" *ngFor="let day of weekdays">
                    {{ day }}
                </div>
            </div>
            <div class="days grid grid-cols-7 text-center">
                <div
                    *ngFor="let day of daysInMonth"
                    class="w-[32px] h-[32px] cursor-pointer leading-[31px] rounded-full mt-[7px] mx-auto mb-[7px]"
                    [ngClass]="{ 'current-day': isToday(day) }"
                >
                    <span *ngIf="day !== null">
                        {{ day }}
                    </span>
                    <span *ngIf="day === null">
                        &nbsp;
                    </span> <!-- Placeholder for empty days -->
                </div>
            </div>
        </div>
        <div class="mt-[19px] relative">
            <span class="block mb-[14px] font-medium">
                Upcoming Events:
            </span>
            <owl-carousel-o [options]="upcomingEventsSlides">
                <ng-template carouselSlide>
                    <div class="relative ltr:pl-[14px] rtl:pr-[14px]">
                        <div class="absolute ltr:left-0 rtl:right-0 top-[4px] w-[7px] h-[7px] rounded-sm bg-primary-500"></div>
                        <h6 class="text-sm mb-[5px] font-semibold">
                            Pythons Unleashed: A Development Expedition
                        </h6>
                        <span class="text-xs">
                            <span class="text-primary-500">
                                15 April 2024
                            </span>
                            - 12.00 PM - 6.00 PM 
                        </span>
                    </div>
                </ng-template>
                <ng-template carouselSlide>
                    <div class="relative ltr:pl-[14px] rtl:pr-[14px]">
                        <div class="absolute ltr:left-0 rtl:right-0 top-[4px] w-[7px] h-[7px] rounded-sm bg-primary-500"></div>
                        <h6 class="text-sm mb-[5px] font-semibold">
                            Pythons Unleashed: A Development Expedition
                        </h6>
                        <span class="text-xs">
                            <span class="text-primary-500">
                                15 April 2024
                            </span>
                            - 12.00 PM - 6.00 PM 
                        </span>
                    </div>
                </ng-template>
                <ng-template carouselSlide>
                    <div class="relative ltr:pl-[14px] rtl:pr-[14px]">
                        <div class="absolute ltr:left-0 rtl:right-0 top-[4px] w-[7px] h-[7px] rounded-sm bg-primary-500"></div>
                        <h6 class="text-sm mb-[5px] font-semibold">
                            Pythons Unleashed: A Development Expedition
                        </h6>
                        <span class="text-xs">
                            <span class="text-primary-500">
                                15 April 2024
                            </span>
                            - 12.00 PM - 6.00 PM 
                        </span>
                    </div>
                </ng-template>
            </owl-carousel-o>
        </div>
    </div>
</div>
