// nuxtjs-tailwindcss/components/Modules/Authentication/SignIn/index.vue
<template>
  <div class="bg-white dark:bg-[#0a0e19] py-[60px] md:py-[80px] lg:py-[135px]">
    <div
      class="mx-auto px-[12.5px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1255px]"
    >
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-[25px] items-center">
        <div
          class="xl:ltr:-mr-[25px] xl:rtl:-ml-[25px] 2xl:ltr:-mr-[45px] 2xl:rtl:-ml-[45px] rounded-[25px] order-2 lg:order-1"
        >
          <img
            src="@/assets/images/sign-in.jpg"
            alt="sign-in-image"
            class="rounded-[25px]"
          />
        </div>
        <div
          class="xl:ltr:pl-[90px] xl:rtl:pr-[90px] 2xl:ltr:pl-[120px] 2xl:rtl:pr-[120px] order-1 lg:order-2"
        >
          <img
            src="@/assets/images/logo-big.svg"
            alt="logo"
            class="inline-block dark:hidden"
          />
          <img
            src="@/assets/images/white-logo-big.svg"
            alt="logo"
            class="hidden dark:inline-block"
          />
          <div class="my-[17px] md:my-[25px]">
            <h1
              class="font-semibold text-[22px] md:text-xl lg:text-2xl mb-[5px] md:mb-[7px]"
            >
              Welcome back to Trezo!
            </h1>
            <p class="font-medium lg:text-md text-[#445164] dark:text-gray-400">
              Sign In with social account or enter your details
            </p>
          </div>
          <div
            class="flex items-center justify-between mb-[20px] md:mb-[23px] gap-[12px]"
          >
            <div class="grow">
              <button
                type="button"
                class="block text-center w-full rounded-md transition-all py-[8px] md:py-[10.5px] px-[15px] md:px-[25px] text-black dark:text-white border border-[#D6DAE1] bg-white dark:bg-[#0a0e19] dark:border-[#172036] shadow-sm hover:border-primary-500"
              >
                <img
                  src="@/assets/images/icons/google.svg"
                  class="inline-block"
                  alt="google"
                />
              </button>
            </div>
            <div class="grow">
              <button
                type="button"
                class="block text-center w-full rounded-md transition-all py-[8px] md:py-[10.5px] px-[15px] md:px-[25px] text-black dark:text-white border border-[#D6DAE1] bg-white dark:bg-[#0a0e19] dark:border-[#172036] shadow-sm hover:border-primary-500"
              >
                <img
                  src="@/assets/images/icons/facebook2.svg"
                  class="inline-block"
                  alt="google"
                />
              </button>
            </div>
            <div class="grow">
              <button
                type="button"
                class="block text-center w-full rounded-md transition-all py-[8px] md:py-[10.5px] px-[15px] md:px-[25px] text-black dark:text-white border border-[#D6DAE1] bg-white dark:bg-[#0a0e19] dark:border-[#172036] shadow-sm hover:border-primary-500"
              >
                <img
                  src="@/assets/images/icons/apple.svg"
                  class="inline-block"
                  alt="google"
                />
              </button>
            </div>
          </div>
          <div class="mb-[15px] relative">
            <label
              class="mb-[10px] md:mb-[12px] text-black dark:text-white font-medium block"
            >
              Email Address
            </label>
            <input
              type="text"
              class="h-[55px] rounded-md text-black dark:text-white border border-gray-200 dark:border-[#172036] bg-white dark:bg-[#0c1427] px-[17px] block w-full outline-0 transition-all placeholder:text-gray-500 dark:placeholder:text-gray-400 focus:border-primary-500"
              placeholder="example@trezo.com"
            />
          </div>
          <div class="mb-[15px] relative" id="passwordHideShow">
            <label
              class="mb-[10px] md:mb-[12px] text-black dark:text-white font-medium block"
            >
              Password
            </label>
            <input
              type="password"
              class="h-[55px] rounded-md text-black dark:text-white border border-gray-200 dark:border-[#172036] bg-white dark:bg-[#0c1427] px-[17px] block w-full outline-0 transition-all placeholder:text-gray-500 dark:placeholder:text-gray-400 focus:border-primary-500"
              id="password"
              placeholder="Type password"
            />
            <button
              class="absolute text-lg ltr:right-[20px] rtl:left-[20px] bottom-[12px] transition-all hover:text-primary-500"
              id="toggleButton"
              type="button"
            >
              <i class="ri-eye-off-line"></i>
            </button>
          </div>
          <NuxtLink
            to="/authentication/forgot-password"
            class="inline-block text-primary-500 transition-all font-semibold hover:underline"
          >
            Forgot Password?
          </NuxtLink>
          <button
            type="submit"
            class="md:text-md block w-full text-center transition-all rounded-md font-medium mt-[20px] md:mt-[25px] py-[12px] px-[25px] text-white bg-primary-500 hover:bg-primary-400"
          >
            <span class="flex items-center justify-center gap-[5px]">
              <i class="material-symbols-outlined"> login </i>
              Sign In
            </span>
          </button>

          <p class="mt-[15px] md:mt-[20px]">
            Don’t have an account.
            <NuxtLink
              to="/authentication/sign-up"
              class="text-primary-500 transition-all font-semibold hover:underline"
            >
              Sign Up
            </NuxtLink>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "SignIn",
};
</script>

// angular-tailwindcss/src/app/authentication/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgClass } from '@angular/common';
import { ToggleService } from '../../common/header/toggle.service';

@Component({
    selector: 'app-sign-in',
    imports: [RouterLink, NgClass],
    templateUrl: './sign-in.component.html',
    styleUrl: './sign-in.component.scss'
})
export class SignInComponent {

    constructor(
        public toggleService: ToggleService
    ) {}

    ngOnInit(): void {
        // Initialize theme and direction on component load
        this.toggleService.initializeTheme();
    }

    // Toggle theme between light and dark
    toggleTheme() {
        this.toggleService.toggleTheme();
    }

    // Toggle direction between LTR and RTL
    toggleDirection() {
        this.toggleService.toggleDirection();
    }

    // Password Show/Hide
    password: string = '';
    isPasswordVisible: boolean = false;
    togglePasswordVisibility(): void {
        this.isPasswordVisible = !this.isPasswordVisible;
    }
    onPasswordInput(event: Event): void {
        const inputElement = event.target as HTMLInputElement;
        this.password = inputElement.value;
    }

}
<!-- Light/Dark Mode Button -->
<button type="button" class="light-dark-toggle leading-none inline-block transition-all text-[#fe7a36] absolute top-[20px] md:top-[25px] ltr:right-[20px] rtl:left-[20px] ltr:md:right-[25px] rtl:md:left-[25px]" (click)="toggleTheme()">
    <i class="material-symbols-outlined !text-[20px] md:!text-[22px]">
        light_mode
    </i>
</button>

<!-- Sign In -->
<div class="bg-white dark:bg-[#0a0e19] py-[60px] md:py-[80px] lg:py-[135px]">
    <div class="mx-auto px-[12.5px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1255px]">
        <div class="grid lg:grid-cols-2 gap-[25px] items-center">
            <div class="xl:ltr:-mr-[25px] xl:rtl:-ml-[25px] 2xl:ltr:-mr-[45px] 2xl:rtl:-ml-[45px] rounded-[25px] order-2 lg:order-1">
                <img src="images/sign-in.jpg" alt="sign-in-image" class="rounded-[25px]">
            </div>
            <div class="xl:ltr:pl-[90px] xl:rtl:pr-[90px] 2xl:ltr:pl-[120px] 2xl:rtl:pr-[120px] order-1 lg:order-2">
                <img src="images/logo-big.svg" alt="logo" class="inline-block dark:hidden">
                <img src="images/white-logo-big.svg" alt="logo" class="hidden dark:inline-block">
                <div class="my-[17px] md:my-[25px]">
                    <h1 class="font-semibold text-[22px] md:text-xl lg:text-2xl mb-[5px] md:mb-[7px]">
                        Welcome back to Trezo!
                    </h1>
                    <p class="font-medium lg:text-md text-[#445164] dark:text-gray-400">
                        Sign In with social account or enter your details
                    </p>
                </div>
                <div class="flex items-center justify-between mb-[20px] md:mb-[23px] gap-[12px]">
                    <div class="grow">
                        <button type="button" class="block text-center w-full rounded-md transition-all py-[8px] md:py-[10.5px] px-[15px] md:px-[25px] text-black dark:text-white border border-[#D6DAE1] bg-white dark:bg-[#0a0e19] dark:border-[#172036] shadow-sm hover:border-primary-500">
                            <img src="images/icons/google.svg" class="inline-block" alt="google">
                        </button>
                    </div>
                    <div class="grow">
                        <button type="button" class="block text-center w-full rounded-md transition-all py-[8px] md:py-[10.5px] px-[15px] md:px-[25px] text-black dark:text-white border border-[#D6DAE1] bg-white dark:bg-[#0a0e19] dark:border-[#172036] shadow-sm hover:border-primary-500">
                            <img src="images/icons/facebook2.svg" class="inline-block" alt="google">
                        </button>
                    </div>
                    <div class="grow">
                        <button type="button" class="block text-center w-full rounded-md transition-all py-[8px] md:py-[10.5px] px-[15px] md:px-[25px] text-black dark:text-white border border-[#D6DAE1] bg-white dark:bg-[#0a0e19] dark:border-[#172036] shadow-sm hover:border-primary-500">
                            <img src="images/icons/apple.svg" class="inline-block" alt="google">
                        </button>
                    </div>
                </div>
                <div class="mb-[15px] relative">
                    <label class="mb-[10px] md:mb-[12px] text-black dark:text-white font-medium block">
                        Email Address
                    </label>
                    <input type="text" class="h-[55px] rounded-md text-black dark:text-white border border-gray-200 dark:border-[#172036] bg-white dark:bg-[#0c1427] px-[17px] block w-full outline-0 transition-all placeholder:text-gray-500 dark:placeholder:text-gray-400 focus:border-primary-500" placeholder="example@trezo.com">
                </div>
                <div class="mb-[15px] relative" id="passwordHideShow">
                    <label class="mb-[10px] md:mb-[12px] text-black dark:text-white font-medium block">
                        Password
                    </label>
                    <input [type]="isPasswordVisible ? 'text' : 'password'" [value]="password" (input)="onPasswordInput($event)" class="h-[55px] rounded-md text-black dark:text-white border border-gray-200 dark:border-[#172036] bg-white dark:bg-[#0c1427] px-[17px] block w-full outline-0 transition-all placeholder:text-gray-500 dark:placeholder:text-gray-400 focus:border-primary-500" id="password" placeholder="Type password">
                    <button class="absolute text-lg ltr:right-[20px] rtl:left-[20px] bottom-[12px] transition-all hover:text-primary-500" (click)="togglePasswordVisibility()" type="button">
                        <i [ngClass]="isPasswordVisible ? 'ri-eye-line' : 'ri-eye-off-line'"></i>
                    </button>
                </div>
                <a routerLink="/authentication/forgot-password" class="inline-block text-primary-500 transition-all font-semibold hover:underline">
                    Forgot Password?
                </a>
                <button type="submit" class="md:text-md block w-full text-center transition-all rounded-md font-medium mt-[20px] md:mt-[25px] py-[12px] px-[25px] text-white bg-primary-500 hover:bg-primary-400">
                    <span class="flex items-center justify-center gap-[5px]">
                        <i class="material-symbols-outlined">
                            login
                        </i>
                        Sign In
                    </span>
                </button>
                <p class="mt-[15px] md:mt-[20px]">
                    Don’t have an account. <a routerLink="/authentication/sign-up" class="text-primary-500 transition-all font-semibold hover:underline">Sign Up</a>
                </p>
            </div>
        </div>
    </div>
</div>
