// nuxtjs-tailwindcss/components/Apps/FileManager/Personal/index.vue
<template>
  <div
    class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-[25px] mb-[25px]"
  >
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/txt.png" alt="png-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Projects</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">995 Files</div>
          <div class="block text-sm text-black dark:text-white">7.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/pdf.png" alt="pdf-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Documents</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">39 Files</div>
          <div class="block text-sm text-black dark:text-white">3.8 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/xl4.png" alt="xl4-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Media</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">75 Files</div>
          <div class="block text-sm text-black dark:text-white">2.2 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/jpg.png" alt="jpg-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Applications</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">357 Files</div>
          <div class="block text-sm text-black dark:text-white">8.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/png.png" alt="png-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">ET Template</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">159 Files</div>
          <div class="block text-sm text-black dark:text-white">4.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/jpg.png" alt="jpg-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">React Template</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">522 Files</div>
          <div class="block text-sm text-black dark:text-white">5.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/txt.png" alt="txt-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Material UI</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">995 Files</div>
          <div class="block text-sm text-black dark:text-white">7.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/pdf.png" alt="pdf-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">WP Themes</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">39 Files</div>
          <div class="block text-sm text-black dark:text-white">3.8 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/xl4.png" alt="xl4-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Personal Photos</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">75 Files</div>
          <div class="block text-sm text-black dark:text-white">2.2 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/doc.png" alt="doc-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Mobile Apps</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">357 Files</div>
          <div class="block text-sm text-black dark:text-white">8.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/png.png" alt="png-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Important Files</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">159 Files</div>
          <div class="block text-sm text-black dark:text-white">4.5 GB</div>
        </div>
      </div>
    </div>
    <div
      class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
    >
      <div class="trezo-card-content">
        <div class="form-check">
          <input type="checkbox" class="cursor-pointer" />
        </div>
        <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
          <img src="@/assets/images/icons/jpg.png" alt="jpg-image" />
          <h6 class="mb-0 text-[15px] mt-[18px]">Angular Template</h6>
        </div>
        <div
          class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between"
        >
          <div class="block text-sm text-black dark:text-white">522 Files</div>
          <div class="block text-sm text-black dark:text-white">5.5 GB</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Personal",
});
</script>

// angular-tailwindcss/src/app/apps/file-manager/personal/personal.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-personal',
    imports: [],
    templateUrl: './personal.component.html',
    styleUrl: './personal.component.scss'
})
export class PersonalComponent {}
<div class="grid sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-[25px] mb-[25px]">
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/txt.png" alt="png-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Projects
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    995 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    7.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/pdf.png" alt="pdf-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Documents
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    39 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    3.8 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/xl4.png" alt="xl4-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Media
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    75 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    2.2 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/jpg.png" alt="jpg-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Applications
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    357 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    8.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/png.png" alt="png-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    ET Template
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    159 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    4.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/jpg.png" alt="jpg-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    React Template
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    522 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    5.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/txt.png" alt="txt-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Material UI
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    995 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    7.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/pdf.png" alt="pdf-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    WP Themes
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    39 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    3.8 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/xl4.png" alt="xl4-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Personal Photos
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    75 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    2.2 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/doc.png" alt="doc-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Mobile Apps
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    357 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    8.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/png.png" alt="png-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Important Files
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    159 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    4.5 GB
                </div>
            </div>
        </div>
    </div>
    <div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div class="trezo-card-content">
            <div class="form-check">
                <input type="checkbox" class="cursor-pointer">
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px]">
                <img src="images/icons/jpg.png" alt="jpg-image">
                <h6 class="mb-0 text-[15px] mt-[18px]">
                    Angular Template
                </h6>
            </div>
            <div class="mt-[20px] md:mt-[30px] lg:mt-[40px] flex items-center justify-between">
                <div class="block text-sm text-black dark:text-white">
                    522 Files
                </div>
                <div class="block text-sm text-black dark:text-white">
                    5.5 GB
                </div>
            </div>
        </div>
    </div>
</div>
