// vuejs-vuetify/src/components/Others/MyProfile/TotalProjects.vue
<template>
  <v-card
    class="total-projects-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="total-projects-content">
      <span class="d-block"> Total Projects </span>
      <h5 class="mb-0">22.5k</h5>
      <div
        class="icon ml-auto mr-auto text-secondary bg-secondary-100 rounded-circle mx-auto d-flex align-items-center justify-content-center"
      >
        <i class="material-symbols-outlined"> auto_stories </i>
      </div>
      <div class="info d-flex align-items-center justify-space-between">
        <span class="d-block"> This Month </span>
        <span class="lh-1 text-success">
          <i class="material-symbols-outlined"> trending_up </i>
        </span>
      </div>
    </div>
  </v-card>
</template>

<script>
export default {
  name: "TotalProjects",
};
</script>

<style lang="scss" scoped>
.total-projects-card {
  .total-projects-content {
    h5 {
      font-size: 20px;
      margin-top: 5px;
    }
    .icon {
      width: 77px;
      height: 77px;
      margin: {
        top: 15px;
        bottom: 15px;
      }
      i {
        font-size: 32px;
      }
    }
    .info {
      span {
        font-size: 13px;

        i {
          font-size: 20px;
        }
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .total-projects-card {
    .total-projects-content {
      h5 {
        font-size: 18px;
        margin-top: 7px;
      }
      .icon {
        width: 60px;
        height: 60px;
        margin: {
          top: 10px;
          bottom: 10px;
        }
        i {
          font-size: 28px;
        }
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .total-projects-card {
    .total-projects-content {
      h5 {
        font-size: 19px;
        margin-top: 7px;
      }
      .icon {
        width: 75px;
        height: 75px;
      }
    }
  }
}
</style>

// nextjs-react-bootstrap/src/components/MyProfile/TotalProjects.js
"use client";

import React from "react";
import Card from "react-bootstrap/Card";
import { MaterialSymbol } from "react-material-symbols";
import "react-material-symbols/rounded";

const TotalProjects = () => {
  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <span>Total Projects</span>

          <h3 className="mb-0 fs-20">22.5k+</h3>

          <div className="py-3">
            <div className="wh-77 lh-97 text-center m-auto bg-primary bg-opacity-25 rounded-circle">
              <MaterialSymbol
                icon="auto_stories"
                size={32}
                className="text-primary"
              />
            </div>
          </div>

          <div className="d-flex justify-content-between align-items-center">
            <span className="fs-12">This Month</span>
            <MaterialSymbol icon="timeline" size={24} className="text-success" />
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default TotalProjects;
