// vuejs-bootstrap/src/components/Dashboard/RealEstate/TopProperty.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-4"
      >
        <h3 class="mb-0">Top Property</h3>

        <div class="dropdown action-opt">
          <button
            class="btn bg-transparent p-0"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i data-feather="more-horizontal"></i>
          </button>
          <ul
            class="dropdown-menu dropdown-menu-end bg-white border box-shadow"
          >
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="clock"></i>
                Today
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="pie-chart"></i>
                Last 7 Days
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="rotate-cw"></i>
                Last Month
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="calendar"></i>
                Last 1 Year
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="bar-chart"></i>
                All Time
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="eye"></i>
                View
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <i data-feather="trash"></i>
                Delete
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="d-flex align-items-center mb-4">
        <div class="flex-shrink-0">
          <img
            src="@/assets/images/property-1.png"
            class="rounded-3"
            style="width: 40px; height: 40px"
            alt="property"
          />
        </div>
        <div class="flex-grow-1 ms-2">
          <h4 class="fs-16 mb-0">Industrial</h4>
          <span>36 Clay Street Indianapolis</span>
        </div>
      </div>
      <div class="d-flex align-items-center mb-4">
        <div class="flex-shrink-0">
          <img
            src="@/assets/images/property-2.png"
            class="rounded-3"
            style="width: 40px; height: 40px"
            alt="property"
          />
        </div>
        <div class="flex-grow-1 ms-2">
          <h4 class="fs-16 mb-0">Office</h4>
          <span>07 Maple Street Los Angeles</span>
        </div>
      </div>
      <div class="d-flex align-items-center mb-4">
        <div class="flex-shrink-0">
          <img
            src="@/assets/images/property-3.png"
            class="rounded-3"
            style="width: 40px; height: 40px"
            alt="property"
          />
        </div>
        <div class="flex-grow-1 ms-2">
          <h4 class="fs-16 mb-0">Multi-Family</h4>
          <span>94 Brooke Street Houston</span>
        </div>
      </div>
      <div class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <img
            src="@/assets/images/property-4.png"
            class="rounded-3"
            style="width: 40px; height: 40px"
            alt="property"
          />
        </div>
        <div class="flex-grow-1 ms-2">
          <h4 class="fs-16 mb-0">Retail</h4>
          <span>84 Pick Street Centennial</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TopProperty",
});
</script>

// react-bootstrap/src/components/Dashboard/RealEstate/TopProperty/index.js
"use client";

import { Card, Dropdown } from "react-bootstrap";

const TopProperty = () => {
  const properties = [
    {
      type: "Industrial",
      address: "36 Clay Street Indianapolis",
      image: "/images/property-1.png",
    },
    {
      type: "Office",
      address: "07 Maple Street Los Angeles",
      image: "/images/property-2.png",
    },
    {
      type: "Multi-Family",
      address: "94 Brooke Street Houston",
      image: "/images/property-3.png",
    },
    {
      type: "Retail",
      address: "84 Pick Street Centennial",
      image: "/images/property-4.png",
    },
  ];

  return (
    <Card className="bg-white border-0 rounded-3 mb-4">
      <Card.Body className="p-4">
        <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-4">
          <h3 className="mb-0">Top Property</h3>

          <Dropdown className="action-opt text-center">
            <Dropdown.Toggle className="btn bg-transparent p-0">
              <i className="ri-more-fill"></i>
            </Dropdown.Toggle>
            <Dropdown.Menu className="bg-white border-0 box-shadow">
              <Dropdown.Item>
                <i className="ri-pie-chart-line"></i> Today
              </Dropdown.Item>
              <Dropdown.Item>
                <i className="ri-restart-line"></i> Last 7 Days
              </Dropdown.Item>
              <Dropdown.Item>
                <i className="ri-restart-line"></i> Last Month
              </Dropdown.Item>
              <Dropdown.Item>
                <i className="ri-calendar-2-line"></i> Last 1 Year
              </Dropdown.Item>
              <Dropdown.Item>
                <i className="ri-eye-line"></i> View
              </Dropdown.Item>
              <Dropdown.Item>
                <i className="ri-delete-bin-6-line"></i> Delete
              </Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </div>

        {properties.map((property, index) => (
          <div className="d-flex align-items-center mb-4 lcbmp-none" key={index}>
            <div className="flex-shrink-0">
              <img
                src={property.image}
                className="rounded-3"
                alt={property.type.toLowerCase()}
                width={40}
                height={40}
              />
            </div>
            <div className="flex-grow-1 ms-2">
              <h4 className="fs-16 mb-0">{property.type}</h4>
              <span>{property.address}</span>
            </div>
          </div>
        ))}
      </Card.Body>
    </Card>
  );
};

export default TopProperty;
