// nuxtjs-tailwindcss/components/Dashboard/Shipment/TotalShipment.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
  >
    <div class="trezo-card-content">
      <div class="flex justify-between">
        <div>
          <span
            class="inline-block px-[8.5px] text-success-600 border border-success-300 bg-success-100 text-sm rounded-[100px] text-xs"
          >
            +45%
          </span>
        </div>
        <div class="ltr:text-right rtl:text-left">
          <span class="block text-xs mb-px"> Last 30 days </span>
          <span class="block font-bold text-purple-500 text-xs"> +20,300 </span>
        </div>
      </div>
      <div class="mt-[20px] md:mt-[25px] flex items-end justify-between">
        <div>
          <span class="block mb-[4px]"> Total Shipment </span>
          <h3 class="mb-0 text-[20px] text-black dark:text-white">175,950</h3>
        </div>
        <div
          class="w-[55px] lg:w-[60px] h-[55px] lg:h-[60px] flex items-center justify-center rounded-full text-white bg-purple-500"
        >
          <i class="material-symbols-outlined !text-[28px]"> local_shipping </i>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TotalShipment",
});
</script>

// angular-bootstrap/src/app/dashboard/shipment/total-shipment/total-shipment.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-total-shipment',
    imports: [],
    templateUrl: './total-shipment.component.html',
    styleUrl: './total-shipment.component.scss'
})
export class TotalShipmentComponent {}
<div class="total-shipment-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-content">
        <div class="d-flex justify-content-between">
            <div>
                <span class="info-badge d-inline-block">
                    +45%
                </span>
            </div>
            <div class="text-end">
                <span class="d-block text-xs">
                    Last 30 days
                </span>
                <h6 class="mb-0 text-purple">
                    +20,300
                </h6>
            </div>
        </div>
        <div class="info d-flex align-items-end justify-content-between">
            <div>
                <span class="d-block">
                    Total Shipment
                </span>
                <h3 class="mb-0">
                    175,950
                </h3>
            </div>
            <div class="icon bg-purple text-white rounded-circle d-flex align-items-center justify-content-center">
                <i class="material-symbols-outlined">
                    local_shipping
                </i>
            </div>
        </div>
    </div>
</div>
