// nuxtjs-vuetify/components/Dashboard/RealEstate/MostSalesLocation.vue
<template>
  <v-card
    class="most-sales-location-card trezo-card mb-25 border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Most Sales Location</h5>
      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-fill"></i>
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="image" style="margin: 33px 0">
      <v-img src="~/assets/images/map.svg" alt="map" />
    </div>

    <ul class="ps-0 mb-0 list-unstyled sales_by_locations mt-4">
      <li class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <v-img
            src="@/assets/images/usa.svg"
            class="wh-30 rounded-circle"
            alt="usa"
          />
        </div>
        <div class="flex-grow-1 ms-3">
          <span class="fw-medium d-block mb-2">United States</span>
          <div
            class="progress"
            role="progressbar"
            aria-label="Example with label"
            aria-valuenow="85"
            aria-valuemin="0"
            aria-valuemax="100"
          >
            <div class="progress-bar bg-primary" style="width: 85%">
              <span class="count fw-medium text-body">85%</span>
            </div>
          </div>
        </div>
      </li>
      <li class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <v-img
            src="@/assets/images/germany.svg"
            class="wh-30 rounded-circle"
            alt="germany"
          />
        </div>
        <div class="flex-grow-1 ms-3">
          <span class="fw-medium d-block mb-2">Germany</span>
          <div
            class="progress"
            role="progressbar"
            aria-label="Example with label"
            aria-valuenow="75"
            aria-valuemin="0"
            aria-valuemax="100"
          >
            <div class="progress-bar bg-danger" style="width: 75%">
              <span class="count fw-medium text-body">75%</span>
            </div>
          </div>
        </div>
      </li>
      <li class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <v-img
            src="@/assets/images/united-kingdom.svg"
            class="wh-30 rounded-circle"
            alt="united-kingdom"
          />
        </div>
        <div class="flex-grow-1 ms-3">
          <span class="fw-medium d-block mb-2">United Kingdom</span>
          <div
            class="progress"
            role="progressbar"
            aria-label="Example with label"
            aria-valuenow="40"
            aria-valuemin="0"
            aria-valuemax="100"
          >
            <div class="progress-bar bg-success" style="width: 40%">
              <span class="count fw-medium text-body">40%</span>
            </div>
          </div>
        </div>
      </li>
      <li class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <v-img
            src="@/assets/images/canada.svg"
            class="wh-30 rounded-circle"
            alt="canada"
          />
        </div>
        <div class="flex-grow-1 ms-3">
          <span class="fw-medium d-block mb-2">Canada</span>
          <div
            class="progress"
            role="progressbar"
            aria-label="Example with label"
            aria-valuenow="10"
            aria-valuemin="0"
            aria-valuemax="100"
          >
            <div class="progress-bar bg-primary-div" style="width: 10%">
              <span class="count fw-medium text-body">10%</span>
            </div>
          </div>
        </div>
      </li>
      <li class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <v-img
            src="@/assets/images/portugal.svg"
            class="wh-30 rounded-circle"
            alt="portugal"
          />
        </div>
        <div class="flex-grow-1 ms-3">
          <span class="fw-medium d-block mb-2">Portugal</span>
          <div
            class="progress"
            role="progressbar"
            aria-label="Example with label"
            aria-valuenow="05"
            aria-valuemin="0"
            aria-valuemax="100"
          >
            <div class="progress-bar bg-primary" style="width: 05%">
              <span class="count fw-medium text-body">05%</span>
            </div>
          </div>
        </div>
      </li>
      <li class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <v-img
            src="@/assets/images/spain.svg"
            class="wh-30 rounded-circle"
            alt="spain"
          />
        </div>
        <div class="flex-grow-1 ms-3">
          <span class="fw-medium d-block mb-2">Spain</span>
          <div
            class="progress"
            role="progressbar"
            aria-label="Example with label"
            aria-valuenow="15"
            aria-valuemin="0"
            aria-valuemax="100"
          >
            <div
              class="progress-bar bg-secondary bg-opacity-50"
              style="width: 15%"
            >
              <span class="count fw-medium text-body">15%</span>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import feather from "feather-icons";

export default defineComponent({
  name: "MostSalesLocation",
  setup() {
    onMounted(() => {
      feather.replace();
    });
  },
});
</script>

<style lang="scss" scoped>
.most-sales-location-card {
  .image {
    .v-responsive {
      justify-content: center;
    }
  }
  .progress {
    display: flex;
    .bg-primary {
      background-color: var(--primaryColor) !important;
    }
  }
}
</style>

// angular-bootstrap/src/app/dashboard/real-estate/most-sales-location/most-sales-location.component.ts
import { Component, HostListener } from '@angular/core';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';
import { NgIf } from '@angular/common';

@Component({
    selector: 'app-most-sales-location',
    imports: [NgIf],
    templateUrl: './most-sales-location.component.html',
    styleUrl: './most-sales-location.component.scss'
})
export class MostSalesLocationComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}
    
    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-header-menu')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div class="most-sales-location-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Most Sales Location
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-header-menu position-relative">
                <button class="dot-menu p-0 border-0 bg-transparent d-inline-block transition lh-1" (click)="toggleCardHeaderMenu()">
                    <i class="ri-more-fill"></i>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Day
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Week
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Month
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Year
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="image text-center">
            <img src="images/vector-map.png" alt="vector-map">
        </div>
        <ul class="p-0 mb-0 list-unstyled">
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/usa.svg" alt="usa">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        United States
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 85%"></div>
                        </div>
                        <span class="d-block percentage">
                            85%
                        </span>
                    </div>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/germany.svg" alt="germany">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        Germany
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 75%"></div>
                        </div>
                        <span class="d-block percentage">
                            75%
                        </span>
                    </div>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/uk.svg" alt="uk">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        United Kingdom
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 40%"></div>
                        </div>
                        <span class="d-block percentage">
                            40%
                        </span>
                    </div>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/canada.svg" alt="canada">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        Canada
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 10%"></div>
                        </div>
                        <span class="d-block percentage">
                            10%
                        </span>
                    </div>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/portugal.svg" alt="portugal">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        Portugal
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="6" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 6%"></div>
                        </div>
                        <span class="d-block percentage">
                            05%
                        </span>
                    </div>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/spain.svg" alt="spain">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        Spain
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 15%"></div>
                        </div>
                        <span class="d-block percentage">
                            15%
                        </span>
                    </div>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <div class="flag flex-shrink-0">
                    <img src="images/flags/france.svg" alt="france">
                </div>
                <div class="flex-grow-1">
                    <span class="title d-block fw-medium">
                        France
                    </span>
                    <div class="progressbar d-flex align-items-center">
                        <div class="progress trezo-progress w-100" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar" style="width: 25%"></div>
                        </div>
                        <span class="d-block percentage">
                            25%
                        </span>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
