// angular-bootstrap/src/app/dashboard/finance/accounts-receivable/accounts-receivable.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-accounts-receivable',
    imports: [],
    templateUrl: './accounts-receivable.component.html',
    styleUrl: './accounts-receivable.component.scss'
})
export class AccountsReceivableComponent {}
<div class="accounts-receivable-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-content">
        <div class="info d-flex justify-content-between">
            <div>
                <span class="d-block">
                    Accounts Receivable
                </span>
                <h3 class="mb-0">
                    $15,990
                </h3>
            </div>
            <div class="icon text-primary rounded-circle d-flex align-items-center justify-content-center">
                <i class="material-symbols-outlined">
                    money_bag
                </i>
            </div>
        </div>
        <div class="gap-10 d-flex align-items-center">
            <span class="info-badge down d-inline-block">
                -5.8%
            </span>
            <span class="d-block text-xs">
                Last 30 days
            </span>
        </div>
    </div>
</div>

// vuejs-bootstrap/src/components/Dashboard/Finance/AccountsReceivable.vue
<template>
  <div class="card border-0 rounded-3 bg-white mb-4">
    <div class="card-body p-4">
      <div class="d-flex mb-4">
        <div class="flex-grow-1">
          <span class="d-block mb-1">Accounts Receivable</span>
          <h4 class="fs-20 mb-0">$15,990</h4>
        </div>
        <div class="flex-shrink-0 ms-3">
          <i
            class="ri-shopping-bag-2-line fs-24 text-primary for dark-bg d-inline-block text-center rounded-circle"
            style="
              width: 60px;
              height: 60px;
              line-height: 60px;
              background-color: #ecf0ff;
            "
          ></i>
        </div>
      </div>
      <div class="d-flex align-items-center">
        <span
          class="d-inline-block px-3 bg-danger bg-opacity-10 text-danger border border-danger rounded-pill fs-12 fw-medium"
        >
          -5.8%
        </span>
        <span class="ms-2 fs-12">Last 30 days</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "AccountsReceivable",
});
</script>
