// angular-bootstrap/src/app/dashboard/finance/transaction-history/transaction-history.component.ts
import { NgIf } from '@angular/common';
import { Component, HostListener } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-transaction-history',
    imports: [NgIf, RouterLink],
    templateUrl: './transaction-history.component.html',
    styleUrl: './transaction-history.component.scss'
})
export class TransactionHistoryComponent {
    
    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-header-menu')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Transaction History
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-header-menu position-relative">
                <button class="menu-btn transition d-inline-block bg-transparent border-radius" (click)="toggleCardHeaderMenu()">
                    <span class="d-block position-relative">
                        Last 30 Days
                    </span>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            Last 7 Days
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            Last 15 Days
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            Last 30 Days
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="table-style-two">
            <div class="basic-table table-responsive">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th scope="col" class="fw-medium">
                                Transaction ID
                            </th>
                            <th scope="col" class="fw-medium">
                                Date
                            </th>
                            <th scope="col" class="fw-medium">
                                Description
                            </th>
                            <th scope="col" class="fw-medium">
                                Amount
                            </th>
                            <th scope="col" class="fw-medium">
                                Type
                            </th>
                            <th scope="col" class="fw-medium">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0015
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                30 Apr 2024
                            </td>
                            <td>
                                Payment from Client
                            </td>
                            <td class="text-primary">
                                $5,000
                            </td>
                            <td class="text-body">
                                Income
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0099
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                29 Apr 2024
                            </td>
                            <td>
                                Office Supplies
                            </td>
                            <td class="text-primary">
                                $10,000
                            </td>
                            <td class="text-body">
                                Expense
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0145
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                28 Apr 2024
                            </td>
                            <td>
                                Website Maintenance
                            </td>
                            <td class="text-primary">
                                $35,000
                            </td>
                            <td class="text-body">
                                Expense
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0247
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                27 Apr 2024
                            </td>
                            <td>
                                Payment from Client
                            </td>
                            <td class="text-primary">
                                $2,000
                            </td>
                            <td class="text-body">
                                Income
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0299
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                26 Apr 2024
                            </td>
                            <td>
                                Advertising Campaign
                            </td>
                            <td class="text-primary">
                                $15,500
                            </td>
                            <td class="text-body">
                                Expense
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0015
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                25 Apr 2024
                            </td>
                            <td>
                                Payment from Client
                            </td>
                            <td class="text-primary">
                                $5,000
                            </td>
                            <td class="text-body">
                                Income
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">
                                <div class="d-flex align-items-center" style="gap: 10px;">
                                    <div class="form-check mb-0 position-relative">
                                        <input class="form-check-input" type="checkbox">
                                    </div>
                                    <span class="d-block">
                                        #TID0099
                                    </span>
                                </div>
                            </td>
                            <td class="text-body">
                                24 Apr 2024
                            </td>
                            <td>
                                Office Supplies
                            </td>
                            <td class="text-primary">
                                $10,000
                            </td>
                            <td class="text-body">
                                Expense
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="trezo-card-pagination">
                <div class="d-md-flex align-items-center justify-content-between">
                    <p class="mb-0">
                        Showing 7 of 36 results
                    </p>
                    <ol class="list-unstyled mb-0 p-0">
                        <li class="d-inline-block">
                            <a class="prev" routerLink=".">
                                <span class="opacity-0">
                                    0
                                </span>
                                <i class="material-symbols-outlined">
                                    chevron_left
                                </i>
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink="." class="active">
                                1
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                2
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                3
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                4
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a class="next" routerLink=".">
                                <span class="opacity-0">
                                    0
                                </span>
                                <i class="material-symbols-outlined">
                                    chevron_right
                                </i>
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

// vuejs-bootstrap/src/components/Dashboard/Finance/TransactionHistory.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-0">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 p-4"
      >
        <h3 class="mb-0">Transaction History</h3>
        <select
          class="form-select month-select form-control w-135 bg-border-color border-color bg-transparent"
          aria-label="Default select example"
        >
          <option selected>Last 30 days</option>
          <option value="1">Last 90 days</option>
          <option value="1">Last 1 year</option>
        </select>
      </div>

      <div class="default-table-area style-two transaction-history">
        <div class="table-responsive">
          <table class="table align-middle">
            <thead>
              <tr>
                <th scope="col">
                  <div class="d-flex align-items-center">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault"
                      />
                    </div>
                    <span class="ms-1"
                      ><span class="fs-12 fw-bold">Transaction</span> ID</span
                    >
                  </div>
                </th>
                <th scope="col">Date</th>
                <th scope="col">Description</th>
                <th scope="col">Amount</th>
                <th scope="col">Type</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault2"
                      />
                    </div>
                    <span class="ms-1 text-secondary">#TID0015</span>
                  </div>
                </td>
                <td>2024-10-01</td>
                <td>Payment from Client</td>
                <td class="text-primary">$5,000</td>
                <td>Income</td>
                <td>
                  <div class="d-flex align-items-center gap-1">
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-primary"
                        >visibility</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-body"
                        >edit</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-danger"
                        >delete</i
                      >
                    </button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault2"
                      />
                    </div>
                    <span class="ms-1 text-secondary">#TID0099</span>
                  </div>
                </td>
                <td>2024-09-28</td>
                <td>Office Supplies</td>
                <td class="text-primary">$10,000</td>
                <td>Expense</td>
                <td>
                  <div class="d-flex align-items-center gap-1">
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-primary"
                        >visibility</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-body"
                        >edit</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-danger"
                        >delete</i
                      >
                    </button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault2"
                      />
                    </div>
                    <span class="ms-1 text-secondary">#TID0145</span>
                  </div>
                </td>
                <td>2024-09-25</td>
                <td>Website Maintenance</td>
                <td class="text-primary">$35,000</td>
                <td>Expense</td>
                <td>
                  <div class="d-flex align-items-center gap-1">
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-primary"
                        >visibility</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-body"
                        >edit</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-danger"
                        >delete</i
                      >
                    </button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault2"
                      />
                    </div>
                    <span class="ms-1 text-secondary">#TID0247</span>
                  </div>
                </td>
                <td>2024-09-22</td>
                <td>Payment from Client</td>
                <td class="text-primary">$2,000</td>
                <td>Income</td>
                <td>
                  <div class="d-flex align-items-center gap-1">
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-primary"
                        >visibility</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-body"
                        >edit</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-danger"
                        >delete</i
                      >
                    </button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault2"
                      />
                    </div>
                    <span class="ms-1 text-secondary">#TID0299</span>
                  </div>
                </td>
                <td>2024-09-20</td>
                <td>Advertising Campaign</td>
                <td class="text-primary">$15,500</td>
                <td>Expense</td>
                <td>
                  <div class="d-flex align-items-center gap-1">
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-primary"
                        >visibility</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-body"
                        >edit</i
                      >
                    </button>
                    <button
                      class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                    >
                      <i class="material-symbols-outlined fs-16 text-danger"
                        >delete</i
                      >
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <Pagination items="05" total="30" class="p-4" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Pagination from "../../Common/Pagination.vue";

export default defineComponent({
  name: "TransactionHistory",
  components: {
    Pagination,
  },
});
</script>
