// react-nextjs-tailwindcss/src/components/Tables/DataTable.tsx
"use client";

import React, { useState, useEffect } from "react";

// Define the data type for better code readability
interface Person {
  id: number;
  name: string;
  age: number;
  city: string;
  country: string;
}

const DataTable: React.FC = () => {
  // State for the table data
  const [data, setData] = useState<Person[]>([]);
  const [searchTerm, setSearchTerm] = useState<string>("");

  // State for sorting
  const [sortConfig, setSortConfig] = useState<{
    key: keyof Person;
    direction: "asc" | "desc";
  }>({
    key: "id", // default sorting key
    direction: "asc", // default sorting direction
  });

  // Simulate fetching dynamic data (replace with an actual API call)
  useEffect(() => {
    const fetchData = async () => {
      const dynamicData: Person[] = [
        { id: 1, name: "John Doe", age: 25, city: "New York", country: "USA" },
        { id: 2, name: "Jane Smith", age: 30, city: "London", country: "UK" },
        {
          id: 3,
          name: "Samuel Green",
          age: 22,
          city: "Toronto",
          country: "Canada",
        },
        {
          id: 4,
          name: "Emily Brown",
          age: 27,
          city: "Sydney",
          country: "Australia",
        },
        {
          id: 5,
          name: "Michael Johnson",
          age: 29,
          city: "Auckland",
          country: "New Zealand",
        },
        {
          id: 6,
          name: "Alice Williams",
          age: 35,
          city: "Paris",
          country: "France",
        },
        {
          id: 7,
          name: "David Lee",
          age: 40,
          city: "Berlin",
          country: "Germany",
        },
        {
          id: 8,
          name: "Sophia Davis",
          age: 33,
          city: "Los Angeles",
          country: "USA",
        },
        {
          id: 9,
          name: "Oliver Harris",
          age: 28,
          city: "Tokyo",
          country: "Japan",
        },
        { id: 10, name: "Mia Clark", age: 31, city: "Rome", country: "Italy" },
      ];
      setData(dynamicData);
    };

    fetchData();
  }, []);

  // Handle search input change
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(e.target.value);
  };

  // Filter data based on the search term
  const filteredData = data.filter((person) => {
    return (
      person.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      person.city.toLowerCase().includes(searchTerm.toLowerCase()) ||
      person.country.toLowerCase().includes(searchTerm.toLowerCase())
    );
  });

  // Sorting function
  const sortedData = React.useMemo(() => {
    const sortableData = [...filteredData];
    sortableData.sort((a, b) => {
      if (a[sortConfig.key] < b[sortConfig.key]) {
        return sortConfig.direction === "asc" ? -1 : 1;
      }
      if (a[sortConfig.key] > b[sortConfig.key]) {
        return sortConfig.direction === "asc" ? 1 : -1;
      }
      return 0;
    });
    return sortableData;
  }, [filteredData, sortConfig]);

  // Handle column header click for sorting
  const handleSort = (key: keyof Person) => {
    setSortConfig((prevConfig) => {
      if (prevConfig.key === key) {
        return {
          ...prevConfig,
          direction: prevConfig.direction === "asc" ? "desc" : "asc", // Toggle sort direction
        };
      }
      return { key, direction: "asc" }; // Default to ascending for new column
    });
  };

  return (
    <>
      <div className="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
        <div className="trezo-card-header mb-[20px] md:mb-[25px] sm:flex sm:items-center sm:justify-between">
          <div className="trezo-card-title">
            <h5 className="mb-0">Data Table</h5>
          </div>
          <div className="trezo-card-subtitle sm:flex sm:items-center">
            <form className="relative sm:w-[320px] mt-[13px] sm:mt-0">
              <label className="leading-none absolute ltr:left-[13px] rtl:right-[13px] text-black dark:text-white mt-px top-1/2 -translate-y-1/2">
                <i className="material-symbols-outlined !text-[20px]">search</i>
              </label>
              <input
                type="text"
                placeholder="Search here....."
                className="bg-gray-50 border border-gray-50 h-[36px] text-xs rounded-md w-full block text-black pt-[11px] pb-[12px] ltr:pl-[38px] rtl:pr-[38px] ltr:pr-[13px] ltr:md:pr-[16px] rtl:pl-[13px] rtl:md:pl-[16px] placeholder:text-gray-500 outline-0 dark:bg-[#15203c] dark:text-white dark:border-[#15203c] dark:placeholder:text-gray-400"
                value={searchTerm}
                onChange={handleSearchChange}
              />
            </form>
          </div>
        </div>

        <div className="trezo-card-content" id="dataTable">
          <div className="table-responsive overflow-x-auto">
            <table className="w-full">
              <thead className="text-black dark:text-white">
                <tr>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md cursor-pointer relative">
                    <button type="button" onClick={() => handleSort("id")}>
                      ID
                      <i
                        className={`ri-expand-up-down-fill text-gray-500 dark:text-gray-400 ${
                          sortConfig.key === "id"
                            ? sortConfig.direction === "asc"
                              ? "rotate-180"
                              : ""
                            : ""
                        }`}
                      ></i>
                    </button>
                  </th>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md cursor-pointer relative">
                    <button type="button" onClick={() => handleSort("name")}>
                      Name
                      <i
                        className={`ri-expand-up-down-fill text-gray-500 dark:text-gray-400 ${
                          sortConfig.key === "name"
                            ? sortConfig.direction === "asc"
                              ? "rotate-180"
                              : ""
                            : ""
                        }`}
                      ></i>
                    </button>
                  </th>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md cursor-pointer relative">
                    <button type="button" onClick={() => handleSort("age")}>
                      Age
                      <i
                        className={`ri-expand-up-down-fill text-gray-500 dark:text-gray-400 ${
                          sortConfig.key === "age"
                            ? sortConfig.direction === "asc"
                              ? "rotate-180"
                              : ""
                            : ""
                        }`}
                      ></i>
                    </button>
                  </th>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md cursor-pointer relative">
                    <button type="button" onClick={() => handleSort("city")}>
                      City
                      <i
                        className={`ri-expand-up-down-fill text-gray-500 dark:text-gray-400 ${
                          sortConfig.key === "city"
                            ? sortConfig.direction === "asc"
                              ? "rotate-180"
                              : ""
                            : ""
                        }`}
                      ></i>
                    </button>
                  </th>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md cursor-pointer relative">
                    <button type="button" onClick={() => handleSort("country")}>
                      Country
                      <i
                        className={`ri-expand-up-down-fill text-gray-500 dark:text-gray-400 ${
                          sortConfig.key === "country"
                            ? sortConfig.direction === "asc"
                              ? "rotate-180"
                              : ""
                            : ""
                        }`}
                      ></i>
                    </button>
                  </th>
                </tr>
              </thead>

              <tbody className="text-black dark:text-white">
                {sortedData.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="text-center py-[15px]">
                      No data available
                    </td>
                  </tr>
                ) : (
                  sortedData.map((person) => (
                    <tr key={person.id}>
                      <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        {person.id}
                      </td>

                      <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        {person.name}
                      </td>

                      <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        {person.age}
                      </td>

                      <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        {person.city}
                      </td>

                      <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        {person.country}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
};

export default DataTable;

// vuejs-tailwindcss/src/components/Modules/Tables/DataTable.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md"
  >
    <div
      class="trezo-card-header mb-[20px] md:mb-[25px] sm:flex sm:items-center sm:justify-between"
    >
      <div class="trezo-card-title">
        <h5 class="mb-0">Data Table</h5>
      </div>
      <div class="trezo-card-subtitle sm:flex sm:items-center">
        <form class="relative sm:w-[320px] mt-[13px] sm:mt-0">
          <label
            class="leading-none absolute ltr:left-[13px] rtl:right-[13px] text-black dark:text-white mt-px top-1/2 -translate-y-1/2"
          >
            <i class="material-symbols-outlined !text-[20px]">search</i>
          </label>
          <input
            v-model="searchQuery"
            type="text"
            placeholder="Search here....."
            class="bg-gray-50 border border-gray-50 h-[36px] text-xs rounded-md w-full block text-black pt-[11px] pb-[12px] ltr:pl-[38px] rtl:pr-[38px] ltr:pr-[13px] ltr:md:pr-[16px] rtl:pl-[13px] rtl:md:pl-[16px] placeholder:text-gray-500 outline-0 dark:bg-[#15203c] dark:text-white dark:border-[#15203c] dark:placeholder:text-gray-400"
          />
        </form>
      </div>
    </div>

    <div class="trezo-card-content">
      <div class="table-responsive overflow-x-auto">
        <table class="w-full">
          <thead class="text-black dark:text-white">
            <tr>
              <th
                v-for="header in tableHeaders"
                :key="header.key"
                @click="sortTable(header.key)"
                class="font-medium px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] text-left cursor-pointer"
              >
                {{ header.label }}
                <i
                  class="ri-expand-up-down-fill text-gray-500 dark:text-gray-400"
                ></i>
              </th>
            </tr>
          </thead>
          <tbody class="text-black dark:text-white">
            <tr v-for="(row, index) in filteredRows" :key="index">
              <td
                v-for="(value, key) in row"
                :key="key"
                class="whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036]"
              >
                {{ value }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";

const searchQuery = ref("");
const tableHeaders = [
  { key: "id", label: "ID" },
  { key: "name", label: "Name" },
  { key: "age", label: "Age" },
  { key: "city", label: "City" },
  { key: "country", label: "Country" },
];
const rows = ref([
  { id: 1, name: "John Doe", age: 25, city: "New York", country: "USA" },
  { id: 2, name: "Jane Smith", age: 30, city: "London", country: "UK" },
  { id: 3, name: "Samuel Green", age: 22, city: "Toronto", country: "Canada" },
  { id: 4, name: "Emily Brown", age: 27, city: "Sydney", country: "Australia" },
  {
    id: 5,
    name: "Michael Johnson",
    age: 29,
    city: "Auckland",
    country: "New Zealand",
  },
  { id: 6, name: "Sarah White", age: 24, city: "Chicago", country: "USA" },
  {
    id: 7,
    name: "William Black",
    age: 35,
    city: "Vancouver",
    country: "Canada",
  },
  { id: 8, name: "Olivia Green", age: 31, city: "Manchester", country: "UK" },
  { id: 9, name: "Sophia Brown", age: 28, city: "Paris", country: "France" },
]);

// Sort state
const sortKey = ref(null);
const sortDirection = ref("asc");

// Filtered rows with search and sort functionality
const filteredRows = computed(() => {
  let filtered = rows.value;

  // Filter by search query
  if (searchQuery.value) {
    filtered = filtered.filter((row) =>
      Object.values(row).some((value) =>
        String(value).toLowerCase().includes(searchQuery.value.toLowerCase())
      )
    );
  }

  // Sort rows
  if (sortKey.value) {
    filtered.sort((a, b) => {
      if (a[sortKey.value] < b[sortKey.value]) {
        return sortDirection.value === "asc" ? -1 : 1;
      }
      if (a[sortKey.value] > b[sortKey.value]) {
        return sortDirection.value === "asc" ? 1 : -1;
      }
      return 0;
    });
  }

  return filtered;
});

// Sort table by key
const sortTable = (key) => {
  if (sortKey.value === key) {
    sortDirection.value = sortDirection.value === "asc" ? "desc" : "asc";
  } else {
    sortKey.value = key;
    sortDirection.value = "asc";
  }
};
</script>
