// react-material-ui/src/components/Dashboard/SaaS/TopRefers/index.js
"use client";

import * as React from "react";
import { Card, Box, Typography, Link } from "@mui/material";

const TopRefers = () => {
  const channelData = [
    {
      name: "Facebook",
      type: "Community",
      icon: "/images/icons/facebook3.svg",
      progress: 50,
      color: "primary",
    },
    {
      name: "Dribbble",
      type: "Community",
      icon: "/images/icons/dribbble2.svg",
      progress: 75,
      color: "secondary",
    },
    {
      name: "Instagram",
      type: "Reels",
      icon: "/images/icons/instagram2.svg",
      progress: 30,
      color: "orange",
    },
    {
      name: "Behance",
      type: "Community",
      icon: "/images/icons/behance.svg",
      progress: 80,
      color: "purple",
    },
    {
      name: "Google",
      type: "SEO & PPC",
      icon: "/images/icons/google3.svg",
      progress: 20,
      color: "success",
    },
  ];

  return (
    <Card
      sx={{
        boxShadow: "none",
        borderRadius: "7px",
        mb: "25px",
        padding: { xs: "18px", sm: "20px", lg: "25px" },
      }}
      className="rmui-card"
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: "25px",
        }}
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
          }}
          className="text-black"
        >
          Channels
        </Typography>

        <Link
          href="#"
          sx={{
            display: "inline-block",
            position: "relative",
            lineHeight: "none",
            color: "text.primary",

            "&:hover": {
              color: "primary.main",
            },
          }}
        >
          Browse All{" "}
          <i className="ri-arrow-right-s-line absolute top-1/2 -translate-y-1/2 ltr:-right-[8px] rtl:-left-[8px] text-[23px] -mt-px"></i>
        </Link>
      </Box>

      <Box>
        {channelData.map((channel, index) => (
          <Box
            key={index}
            className="lcbpm-none border-bottom"
            sx={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              pb: "15px",
              mb: "14px",
            }}
          >
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: "12px",
              }}
            >
              <img
                src={channel.icon}
                alt={channel.name}
                width={26}
                height={26}
              />
              <Box>
                <Typography
                  component="span"
                  className="text-black"
                  sx={{
                    display: "block",
                    fontWeight: "600",
                  }}
                >
                  {channel.name}
                </Typography>
                <Typography sx={{ display: "block", fontSize: "12px" }}>
                  {channel.type}
                </Typography>
              </Box>
            </Box>

            <Box sx={{ width: "150px" }}>
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                  lineHeight: "none",
                }}
              >
                <Box
                  className={`bg-${channel.color}-100`}
                  sx={{
                    display: "flex",
                    width: "100%",
                    height: "8px",
                    overflow: "hidden",
                    borderRadius: "10px",
                  }}
                >
                  <Box
                    className={`bg-${channel.color}`}
                    style={{ width: `${channel.progress}%` }}
                    sx={{
                      display: "flex",
                      flexDirection: "column",
                      justifyContent: "center",
                      overflow: "hidden",
                      borderRadius: "10px",
                    }}
                  ></Box>
                </Box>
                <Typography component="span" sx={{ display: "block" }}>
                  {channel.progress}%
                </Typography>
              </Box>
            </Box>
          </Box>
        ))}
      </Box>
    </Card>
  );
};

export default TopRefers;

// nuxtjs-tailwindcss/components/Dashboard/SaaS/TopRefers.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
  >
    <div
      class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between"
    >
      <div class="trezo-card-title">
        <h5 class="mb-0">Top Refers</h5>
      </div>
      <div class="trezo-card-subtitle">
        <a
          href="#"
          class="inline-block relative ltr:pr-[13px] rtl:pl-[13px] leading-none transition-all hover:text-primary-500"
        >
          Browse All
          <i
            class="ri-arrow-right-s-line absolute top-1/2 -translate-y-1/2 ltr:-right-[8px] rtl:-left-[8px] text-[23px] -mt-px"
          ></i>
        </a>
      </div>
    </div>
    <div class="trezo-card-content">
      <div
        class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[14px] mb-[14px] last:border-none last:mb-0 last:pb-0"
      >
        <div class="flex items-center gap-[15px]">
          <img src="@/assets/images/icons/facebook3.svg" alt="facebook" />
          <div>
            <span class="block font-semibold text-gray-900 dark:text-gray-400">
              Facebook
            </span>
            <span class="block text-xs mt-px"> Community </span>
          </div>
        </div>
        <div class="w-[150px]">
          <div class="leading-none flex items-center gap-[12px]">
            <div
              class="flex w-full h-[8px] overflow-hidden rounded-md bg-primary-100 dark:bg-[#172036]"
            >
              <div
                class="flex flex-col justify-center overflow-hidden bg-primary-400 rounded-md"
                style="width: 50%"
              ></div>
            </div>
            <span class="block text-xs"> 50% </span>
          </div>
        </div>
      </div>
      <div
        class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[14px] mb-[14px] last:border-none last:mb-0 last:pb-0"
      >
        <div class="flex items-center gap-[15px]">
          <img src="@/assets/images/icons/dribbble2.svg" alt="dribbble" />
          <div>
            <span class="block font-semibold text-gray-900 dark:text-gray-400">
              Dribbble
            </span>
            <span class="block text-xs mt-px"> Community </span>
          </div>
        </div>
        <div class="w-[150px]">
          <div class="leading-none flex items-center gap-[12px]">
            <div
              class="flex w-full h-[8px] overflow-hidden rounded-md bg-secondary-100 dark:bg-[#172036]"
            >
              <div
                class="flex flex-col justify-center overflow-hidden bg-secondary-400 rounded-md"
                style="width: 75%"
              ></div>
            </div>
            <span class="block text-xs"> 75% </span>
          </div>
        </div>
      </div>
      <div
        class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[14px] mb-[14px] last:border-none last:mb-0 last:pb-0"
      >
        <div class="flex items-center gap-[15px]">
          <img src="@/assets/images/icons/instagram2.svg" alt="instagram" />
          <div>
            <span class="block font-semibold text-gray-900 dark:text-gray-400">
              Instagram
            </span>
            <span class="block text-xs mt-px"> Reels </span>
          </div>
        </div>
        <div class="w-[150px]">
          <div class="leading-none flex items-center gap-[12px]">
            <div
              class="flex w-full h-[8px] overflow-hidden rounded-md bg-orange-100 dark:bg-[#172036]"
            >
              <div
                class="flex flex-col justify-center overflow-hidden bg-orange-400 rounded-md"
                style="width: 30%"
              ></div>
            </div>
            <span class="block text-xs"> 30% </span>
          </div>
        </div>
      </div>
      <div
        class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[14px] mb-[14px] last:border-none last:mb-0 last:pb-0"
      >
        <div class="flex items-center gap-[15px]">
          <img src="@/assets/images/icons/behance.svg" alt="behance" />
          <div>
            <span class="block font-semibold text-gray-900 dark:text-gray-400">
              Behance
            </span>
            <span class="block text-xs mt-px"> Community </span>
          </div>
        </div>
        <div class="w-[150px]">
          <div class="leading-none flex items-center gap-[12px]">
            <div
              class="flex w-full h-[8px] overflow-hidden rounded-md bg-purple-100 dark:bg-[#172036]"
            >
              <div
                class="flex flex-col justify-center overflow-hidden bg-purple-400 rounded-md"
                style="width: 80%"
              ></div>
            </div>
            <span class="block text-xs"> 80% </span>
          </div>
        </div>
      </div>
      <div
        class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[14px] mb-[14px] last:border-none last:mb-0 last:pb-0"
      >
        <div class="flex items-center gap-[15px]">
          <img src="@/assets/images/icons/google3.svg" alt="google" />
          <div>
            <span class="block font-semibold text-gray-900 dark:text-gray-400">
              Google
            </span>
            <span class="block text-xs mt-px"> SEO & PPC </span>
          </div>
        </div>
        <div class="w-[150px]">
          <div class="leading-none flex items-center gap-[12px]">
            <div
              class="flex w-full h-[8px] overflow-hidden rounded-md bg-success-100 dark:bg-[#172036]"
            >
              <div
                class="flex flex-col justify-center overflow-hidden bg-success-400 rounded-md"
                style="width: 20%"
              ></div>
            </div>
            <span class="block text-xs"> 20% </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TopRefers",
});
</script>
