// nextjs-react-bootstrap/src/components/Members/Pagination.js
"use client";

import React from "react";
import Link from "next/link";
import { MaterialSymbol } from "react-material-symbols";
import "react-material-symbols/rounded";

const Pagination = () => {
  return (
    <>
      <div className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap p-4">
        <span className="fs-12 fw-medium">Showing 5 of 30 Results</span>

        <nav aria-label="Page navigation example">
          <ul className="pagination mb-0 justify-content-center">
            <li className="page-item">
              <Link
                className="page-link icon"
                href="#"
                aria-label="Previous"
              >
                <MaterialSymbol icon="keyboard_arrow_left" />
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link active" href="#">
                1
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="#">
                2
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="#">
                3
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="#">
                4
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link icon" href="#" aria-label="Next">
                <MaterialSymbol icon="keyboard_arrow_right" />
              </Link>
            </li>
          </ul>
        </nav>
      </div>
    </>
  );
};

export default Pagination;

// nuxtjs-bootstrap/components/Common/Pagination.vue
<template>
  <div
    class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap"
  >
    <span class="fs-12 fw-medium">
      Showing {{ items }} of {{ total }} Results
    </span>

    <nav aria-label="Page navigation example">
      <ul class="pagination mb-0 justify-content-center">
        <li class="page-item">
          <a class="page-link icon" href="#" aria-label="Previous">
            <i class="material-symbols-outlined">keyboard_arrow_left</i>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link active" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link icon" href="#" aria-label="Next">
            <i class="material-symbols-outlined"> keyboard_arrow_right </i>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Pagination",
  props: ["items", "total"],
});
</script>
