// react-nextjs-tailwindcss/src/components/Dashboard/Marketing/ClickThroughRate.tsx
"use client";

import React from "react";
import Image from "next/image";

const ClickThroughRate: React.FC = () => {
  return (
    <>
      <div className="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
        <div className="trezo-card-content">
          <div className="flex items-center justify-between mb-[10px]">
            <div>
              <span className="block mb-[6px]">Click Through Rate</span>
              <h3 className="leading-none text-xl md:text-2xl lg:text-3xl mb-0">
                $2.95
              </h3>
            </div>
            <Image
              src="/images/icons/ads2.gif"
              className="w-[60px] ltr:-mr-[10px] rtl:-ml-[10px]"
              alt="ads2"
              width={60}
              height={60}
            />
          </div>
          <span className="inline-block px-[9px] text-success-700 border border-success-300 bg-success-100 text-sm rounded-[100px]">
            +7%
          </span>
          <span className="block text-xs mt-[10px]">vs previous 30 days</span>
        </div>
      </div>
    </>
  );
};

export default ClickThroughRate;

// angular-tailwindcss/src/app/dashboard/marketing/click-through-rate/click-through-rate.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-click-through-rate',
    imports: [],
    templateUrl: './click-through-rate.component.html',
    styleUrl: './click-through-rate.component.scss'
})
export class ClickThroughRateComponent {}
<div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-content">
        <div class="flex items-center justify-between mb-[10px]">
            <div>
                <span class="block mb-[6px]">
                    Click Through Rate
                </span>
                <h3 class="leading-none text-xl md:text-2xl lg:text-3xl mb-0">
                    $2.95
                </h3>
            </div>
            <img src="images/icons/ads2.gif" class="w-[60px] ltr:-mr-[10px] rtl:-ml-[10px]" alt="ads2">
        </div>
        <span class="inline-block text-xs px-[9px] text-success-700 border border-success-300 bg-success-100 text-sm rounded-[100px]">
            +7%
        </span>
        <span class="block text-xs mt-[10px]">
            vs previous 30 days
        </span>
    </div>
</div>
