// laravel-vue/resources/components/Pages/Ecommerce/OrderTracking/index.vue
<template>
  <div class="row">
    <div class="col-lg-8">
      <v-card
        class="order-tracking-card trezo-card border-radius d-block bg-white border-0 shadow-none"
      >
        <div class="v-card-header justify-space-between">
          <h5 class="mb-0">Order ID #2435679</h5>
          <h5 class="mb-0">Tracking ID #1004216609</h5>
        </div>
        <div class="order-tracking-card-content">
          <span class="text d-block"> IBAN: EST6049283742809 </span>
          <span class="text d-block"> Date: 26 Mar 2024 </span>
          <div
            class="numbers position-relative z-1 d-md-flex justify-space-between"
          >
            <div class="box">
              <div class="rounded-circle text-center fw-semibold text-black">
                01
              </div>
              <span class="fw-semibold text-black d-block"> Order Placed </span>
              <span class="d-block"> 22 Mar 2024 - 11:35AM </span>
            </div>
            <div class="box">
              <div class="rounded-circle text-center fw-semibold text-black">
                02
              </div>
              <span class="fw-semibold text-black d-block"> Packed </span>
              <span class="d-block"> 23 Mar 2024 - 10:35AM </span>
            </div>
            <div class="box">
              <div class="rounded-circle text-center fw-semibold text-black">
                03
              </div>
              <span class="fw-semibold text-black d-block"> Shipped </span>
              <span class="d-block"> 24 Mar 2024 - 3:45PM </span>
            </div>
            <div class="box active">
              <div class="rounded-circle text-center fw-semibold text-black">
                04
              </div>
              <span class="fw-semibold text-black d-block"> Delivered </span>
              <span class="d-block"> 25 Mar 2024 - 2:21PM </span>
            </div>
          </div>
          <span class="title text-black d-block fw-semibold">
            View Details:
          </span>
          <span class="text text-black d-block">
            <span class="text-body">25 Mar 2024 - 2:21PM:</span> Your order
            delivered.
          </span>
          <span class="text text-black d-block">
            <span class="text-body">24 Mar 2024 - 3:45PM:</span> Your order
            shipped.
          </span>
          <span class="text text-black d-block">
            <span class="text-body">23 Mar 2024 - 10:35AM:</span> Your order is
            on the way for deliver.
          </span>
          <span class="text text-black d-block">
            <span class="text-body">22 Mar 2024 - 11:35AM:</span> Your order is
            now on warehouse. It’s being ready for shipped.
          </span>
        </div>
      </v-card>
    </div>
    <div class="col-lg-4">
      <v-card
        class="trezo-card border-radius d-block bg-white border-0 shadow-none"
      >
        <div class="v-card-header">
          <h5 class="mb-0">Order Summary</h5>
        </div>
        <div class="trezo-table-content">
          <div class="trezo-table basic-table">
            <v-table>
              <thead>
                <tr>
                  <th class="fw-medium">Description</th>
                  <th class="fw-medium text-end">Price</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="text-body">Grand Total :</td>
                  <td class="text-body text-end">$1,105.00</td>
                </tr>
                <tr>
                  <td class="text-body">Discount :</td>
                  <td class="text-body text-end">-$105.00</td>
                </tr>
                <tr>
                  <td class="text-body">Tax :</td>
                  <td class="text-body text-end">$75.00</td>
                </tr>
                <tr>
                  <td class="fw-medium">Subtotal :</td>
                  <td class="text-body text-end">$1,000.00</td>
                </tr>
                <tr>
                  <td class="text-body">Shipping Charge :</td>
                  <td class="text-body text-end">$80.00</td>
                </tr>
                <tr>
                  <td class="text-body">Coupon Charge :</td>
                  <td class="text-body text-end">$20.00</td>
                </tr>
                <tr>
                  <td class="fw-medium">Total :</td>
                  <td class="text-body text-end">$900.00</td>
                </tr>
              </tbody>
            </v-table>
          </div>
        </div>
      </v-card>
    </div>
  </div>
</template>

<script>
export default {
  name: "OrderTracking",
};
</script>

<style lang="scss" scoped>
.order-tracking-card {
  .order-tracking-card-content {
    .text {
      margin-bottom: 15px;
      line-height: 1.1;
      color: var(--bodyColor);

      &:last-child {
        margin-bottom: 0;
      }
    }
    .numbers {
      margin: {
        top: 50px;
        bottom: 50px;
      }
      .box {
        div {
          width: 50px;
          height: 50px;
          line-height: 48px;
          background-color: var(--whiteColor);
          border: 1px dashed var(--primaryColor);
        }
        span {
          margin-top: 20px;
          font-size: 16px;
          line-height: 1.1;
          color: var(--bodyColor);

          &:last-child {
            margin-top: 10px;
            font-size: 14px;
          }
        }
        &.active {
          div {
            color: var(--whiteColor) !important;
            background-color: var(--primaryColor);
          }
        }
      }
      &::before {
        left: 0;
        right: 0;
        top: 25px;
        content: "";
        z-index: -1;
        position: absolute;
        border: {
          left: 0px dashed var(--primaryColor);
          top: 1px dashed var(--primaryColor);
        }
      }
    }
    .title {
      margin-bottom: 15px;
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .order-tracking-card {
    .order-tracking-card-content {
      .text {
        margin-bottom: 12px;
      }
      .numbers {
        margin: {
          top: 25px;
          bottom: 25px;
        }
        .box {
          span {
            padding-left: 45px;
            margin-top: 15px;
            font-size: 14px;

            &:last-child {
              font-size: 13px;
              margin: {
                top: 8px;
                bottom: 15px;
              }
            }
          }
        }
        &::before {
          top: 0;
          bottom: 0;
          left: 25px;
          right: auto;
          border-left-width: 1px;
        }
      }
      .title {
        margin-bottom: 12px;
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .order-tracking-card {
    .order-tracking-card-content {
      .numbers {
        margin: {
          top: 40px;
          bottom: 40px;
        }
        .box {
          span {
            font-size: 15px;

            &:last-child {
              font-size: 13px;
            }
          }
        }
      }
    }
  }
}
</style>

// react-nextjs-tailwindcss/src/app/ecommerce/OrderTracking/index.tsx
"use client";

import React from "react";

const OrderTracking: React.FC = () => {
  return (
    <>
      <div className="lg:grid lg:grid-cols-3 gap-[25px]">
        <div className="lg:col-span-2">
          <div className="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
            <div className="trezo-card-header mb-[20px] md:mb-[25px] sm:flex items-center justify-between">
              <div className="trezo-card-title">
                <h5 className="mb-0">Order ID #2435679</h5>
              </div>

              <div className="trezo-card-subtitle mt-[15px] sm:mt-0">
                <h5 className="mb-0">Tracking ID #1004216609</h5>
              </div>
            </div>

            <div className="trezo-card-content">
              <span className="block mb-[10px] last:mb-0">
                IBAN: EST6049283742809
              </span>

              <span className="block mb-[10px] last:mb-0">
                Date: 26 Mar 2024
              </span>

              <div className="my-[25px] md:my-[45px] md:flex z-[1] relative justify-between">
                <span className="block absolute bottom-0 md:bottom-auto ltr:left-[25px] ltr:md:left-0 ltr:md:right-0 rtl:right-[25px] rtl:md:right-0 rtl:md:left-0 top-[25px] -z-[1] border-t border-dashed border-primary-500 ltr:border-l ltr:md:border-l-0 rtl:border-l rtl:md:border-l-0"></span>
                <div>
                  <div className="rounded-full text-center font-semibold text-black dark:text-white w-[50px] h-[50px] leading-[48px] bg-white dark:bg-[#0c1427] border border-dashed border-primary-500">
                    01
                  </div>
                  <span className="block text-md mt-[17px] font-semibold text-black dark:text-white ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    Order Placed
                  </span>
                  <span className="block mb-[15px] md:mb-0 mt-[7px] ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    22 Mar 2024 - 11:35AM
                  </span>
                </div>

                <div>
                  <div className="rounded-full text-center font-semibold text-black dark:text-white w-[50px] h-[50px] leading-[48px] bg-white dark:bg-[#0c1427] border border-dashed border-primary-500">
                    02
                  </div>
                  <span className="block text-md mt-[17px] font-semibold text-black dark:text-white ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    Packed
                  </span>
                  <span className="block mb-[15px] md:mb-0 mt-[7px] ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    23 Mar 2024 - 10:35AM
                  </span>
                </div>

                <div>
                  <div className="rounded-full text-center font-semibold text-black dark:text-white w-[50px] h-[50px] leading-[48px] bg-white dark:bg-[#0c1427] border border-dashed border-primary-500">
                    03
                  </div>
                  <span className="block text-md mt-[17px] font-semibold text-black dark:text-white ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    Shipped
                  </span>
                  <span className="block mb-[15px] md:mb-0 mt-[7px] ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    24 Mar 2024 - 3:45PM
                  </span>
                </div>

                <div>
                  <div className="rounded-full text-center font-semibold text-white w-[50px] h-[50px] leading-[48px] bg-primary-500 border border-dashed border-primary-500">
                    04
                  </div>
                  <span className="block text-md mt-[17px] font-semibold text-black dark:text-white ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    Delivered
                  </span>
                  <span className="block mb-[15px] md:mb-0 mt-[7px] ltr:pl-[45px] rtl:pr-[45px] md:!p-0">
                    25 Mar 2024 - 2:21PM
                  </span>
                </div>
              </div>

              <span className="block font-semibold text-black dark:text-white mb-[10px] last:mb-0">
                View Details:
              </span>

              <span className="block mb-[10px] last:mb-0">
                25 Mar 2024 - 2:21PM:{" "}
                <span className="text-black dark:text-white">
                  Your order delivered.
                </span>
              </span>

              <span className="block mb-[10px] last:mb-0">
                24 Mar 2024 - 3:45PM:{" "}
                <span className="text-black dark:text-white">
                  Your order shipped.
                </span>
              </span>

              <span className="block mb-[10px] last:mb-0">
                23 Mar 2024 - 10:35AM:{" "}
                <span className="text-black dark:text-white">
                  Your order is on the way for deliver.
                </span>
              </span>

              <span className="block mb-[10px] last:mb-0">
                22 Mar 2024 - 11:35AM:{" "}
                <span className="text-black dark:text-white">
                  Your order is now on warehouse. It’s being ready for shipped.
                </span>
              </span>
            </div>
          </div>
        </div>

        <div className="lg:col-span-1">
          <div className="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
            <div className="trezo-card-header mb-[20px] md:mb-[25px] sm:flex items-center justify-between">
              <div className="trezo-card-title">
                <h5 className="mb-0">Order Summary</h5>
              </div>
            </div>

            <div className="trezo-card-content">
              <div className="table-responsive overflow-x-auto">
                <table className="w-full">
                  <thead className="text-black dark:text-white">
                    <tr>
                      <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md">
                        Description
                      </th>
                      <th className="font-medium ltr:text-right rtl:text-left px-[20px] py-[11px] bg-gray-50 dark:bg-[#15203c] whitespace-nowrap first:rounded-tl-md">
                        Price
                      </th>
                    </tr>
                  </thead>
                  
                  <tbody className="text-black dark:text-white">
                    <tr>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Grand Total :
                      </td>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        $1,105.00
                      </td>
                    </tr>
                    <tr>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Discount :
                      </td>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        -$105.00
                      </td>
                    </tr>
                    <tr>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Tax :
                      </td>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        $75.00
                      </td>
                    </tr>
                    <tr>
                      <td className="font-medium ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Subtotal :
                      </td>
                      <td className="font-medium ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        $1,000.00
                      </td>
                    </tr>
                    <tr>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Shipping Charge :
                      </td>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        $80.00
                      </td>
                    </tr>
                    <tr>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Coupon Charge :
                      </td>
                      <td className="text-gray-500 dark:text-gray-400 ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        $20.00
                      </td>
                    </tr>
                    <tr>
                      <td className="font-medium ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        Total :
                      </td>
                      <td className="font-medium ltr:text-right rtl:text-left whitespace-nowrap px-[20px] py-[15px] border-b border-gray-100 dark:border-[#172036] ltr:first:border-l ltr:last:border-r rtl:first:border-r rtl:last:border-l">
                        $900.00
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default OrderTracking;
