// nextjs-react-bootstrap/src/components/Dashboard/Analytics/DeviceSessions/index.js
"use client";

import React, { useEffect, useState } from "react";
import { Row, Col, Card, Form } from "react-bootstrap";

const DeviceSessions = () => {
  const [Chart, setChart] = useState();
  useEffect(() => {
    import("react-apexcharts").then((mod) => {
      setChart(() => mod.default);
    });
  }, []);

  const series = [55, 44, 30, 12];

  const options = {
    labels: ["Desktop", "Mobile", "Tablet", "Other"],
    colors: ["#37D80A", "#605DFF", "#AD63F6", "#FD5812"],
    dataLabels: {
      enabled: false,
    },
    plotOptions: {
      pie: {
        expandOnClick: false,
      },
    },
    stroke: {
      width: 1,
      show: true,
      colors: ["#ffffff"],
    },
    legend: {
      show: false,
      fontSize: "12px",
      position: "bottom",
      horizontalAlign: "center",
      itemMargin: {
        horizontal: 8,
        vertical: 7,
      },
      labels: {
        colors: "#64748B",
      },
      markers: {
        width: 9,
        radius: 2,
        height: 9,
        offsetX: -2,
        offsetY: -0.1,
        shape: "diamond",
      },
    },
    tooltip: {
      enabled: true,
      y: {
        formatter: function (val) {
          return val + "%";
        },
      },
    },
  };

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 pb-4">
            <h3 className="mb-0">Device Sessions</h3>

            <Form.Select className="form-select month-select form-control p-0 h-auto border-0 pe-4 w-auto">
              <option defaultValue="0">Last Week</option>
              <option defaultValue="1">Last Month</option>
              <option defaultValue="2">
                Last Year
              </option>
            </Form.Select>
          </div>

          <Row className="align-items-center">
            <Col sm={5}>
              {Chart && (
                <Chart
                  options={options}
                  series={series}
                  type="pie"
                  height={200}
                />
              )}
            </Col>

            <Col sm={7}>
              <ul className="ps-0 mb-0 list-unstyled ms-plus-21 border-top pt-1">
                <li className="d-flex justify-content-between align-items-center border-bottom pb-1 mb-1">
                  <div className="d-flex align-items-center">
                    <span
                      className="d-inline-block bg-success rounded-circle"
                      style={{ width: "10px", height: "10px" }}
                    ></span>
                    <div className="ps-3">
                      <span className="fs-12 text-secondary d-block mb-1">
                        Desktop
                      </span>
                      <h4 className="fw-semibold fs-16 mb-0">45.2%</h4>
                    </div>
                  </div>
                  <div>
                    <span className="text-body d-block mb-1 fs-12">
                      Sessions
                    </span>
                    <h4 className="text-body mb-0 fw-semibold">8,732</h4>
                  </div>
                </li>

                <li className="d-flex justify-content-between align-items-center border-bottom pb-1 mb-1">
                  <div className="d-flex align-items-center">
                    <span
                      className="d-inline-block bg-primary rounded-circle"
                      style={{ width: "10px", height: "10px" }}
                    ></span>
                    <div className="ps-3">
                      <span className="fs-12 text-secondary d-block mb-1">
                        Mobile
                      </span>
                      <h4 className="fw-semibold fs-16 mb-0">48.7%</h4>
                    </div>
                  </div>
                  <div>
                    <span className="text-body d-block mb-1 fs-12">
                      Sessions
                    </span>
                    <h4 className="text-body mb-0 fw-semibold">9,416</h4>
                  </div>
                </li>

                <li className="d-flex justify-content-between align-items-center border-bottom pb-1 mb-1">
                  <div className="d-flex align-items-center">
                    <span
                      className="d-inline-block bg-primary-div rounded-circle"
                      style={{ width: "10px", height: "10px" }}
                    ></span>
                    <div className="ps-3">
                      <span className="fs-12 text-secondary d-block mb-1">
                        Tablet
                      </span>
                      <h4 className="fw-semibold fs-16 mb-0">32.3%</h4>
                    </div>
                  </div>
                  <div>
                    <span className="text-body d-block mb-1 fs-12">
                      Sessions
                    </span>
                    <h4 className="text-body mb-0 fw-semibold">1,042</h4>
                  </div>
                </li>

                <li className="d-flex justify-content-between align-items-center border-bottom pb-1 mb-1">
                  <div className="d-flex align-items-center">
                    <span
                      className="d-inline-block bg-danger rounded-circle"
                      style={{ width: "10px", height: "10px" }}
                    ></span>
                    <div className="ps-3">
                      <span className="fs-12 text-secondary d-block mb-1">
                        Other
                      </span>
                      <h4 className="fw-semibold fs-16 mb-0">45.2%</h4>
                    </div>
                  </div>
                  <div>
                    <span className="text-body d-block mb-1 fs-12">
                      Sessions
                    </span>
                    <h4 className="text-body mb-0 fw-semibold">135</h4>
                  </div>
                </li>
              </ul>
            </Col>
          </Row>

          <p className="fs-12 lh-16 mt-3 pt-2">
            This data helps you understand which devices are most commonly used
            and how engagement metrics vary between them.
          </p>
        </Card.Body>
      </Card>
    </>
  );
};

export default DeviceSessions;

// angular-bootstrap/src/app/dashboard/analytics/device-sessions/device-sessions.component.ts
import { Component, HostListener } from '@angular/core';
import { DeviceSessionsService } from './device-sessions.service';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';
import { NgIf } from '@angular/common';

@Component({
    selector: 'app-device-sessions',
    imports: [NgIf],
    templateUrl: './device-sessions.component.html',
    styleUrl: './device-sessions.component.scss'
})
export class DeviceSessionsComponent {

    constructor(
        public themeService: CustomizerSettingsService,
        private deviceSessionsService: DeviceSessionsService
    ) {}

    selectedTimeframe: string = 'Last Week'; // Default dropdown text

    ngOnInit(): void {
        const initialData = this.getChartData('Last Week');
        this.deviceSessionsService.initializeChart(initialData);
    }

    onTimeframeChange(timeframe: string): void {
        this.selectedTimeframe = timeframe; // Update button text
        const { series, labels } = this.getChartData(timeframe);
        this.deviceSessionsService.updateChartData(series, labels);
    }

    private getChartData(timeframe: string): { series: number[]; labels: string[] } {
        switch (timeframe) {
            case 'Last Day':
                return {
                    series: [60, 30, 5, 5],
                    labels: ["Desktop", "Mobile", "Tablet", "Others"]
                };
            case 'Last Week':
                return {
                    series: [55, 44, 30, 12],
                    labels: ["Desktop", "Mobile", "Tablet", "Others"]
                };
            case 'Last Month':
                return {
                    series: [50, 40, 20, 10],
                    labels: ["Desktop", "Mobile", "Tablet", "Others"]
                };
            case 'Last Year':
                return {
                    series: [45, 35, 15, 5],
                    labels: ["Desktop", "Mobile", "Tablet", "Others"]
                };
            default:
                return { series: [], labels: [] };
        }
    }

    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-header-menu')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div
    class="device-sessions-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Device Sessions
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-header-menu position-relative">
                <button class="menu-btn without-border transition d-inline-block bg-transparent border-radius" (click)="toggleCardHeaderMenu()">
                    <span class="d-block position-relative">
                        {{ selectedTimeframe }}
                    </span>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition" (click)="onTimeframeChange('Last Day')">
                            Last Day
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition" (click)="onTimeframeChange('Last Week')">
                            Last Week
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition" (click)="onTimeframeChange('Last Month')">
                            Last Month
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition" (click)="onTimeframeChange('Last Year')">
                            Last Year
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="chart">
                    <div id="device_sessions_chart"></div>
                </div>
            </div>
            <div class="col-lg-6">
                <ul class="content p-0 list-unstyled">
                    <li class="d-flex justify-content-between position-relative">
                        <div class="dot rounded-circle dekstop"></div>
                        <div>
                            <span class="d-block">
                                Desktop
                            </span>
                            <h6 class="mb-0 fw-semibold">
                                45.2%
                            </h6>
                        </div>
                        <div>
                            <span class="d-block">
                                Sessions
                            </span>
                            <h6 class="mb-0 fw-semibold text-body">
                                8,732
                            </h6>
                        </div>
                    </li>
                    <li class="d-flex justify-content-between position-relative">
                        <div class="dot rounded-circle mobile"></div>
                        <div>
                            <span class="d-block">
                                Mobile
                            </span>
                            <h6 class="mb-0 fw-semibold">
                                48.7%
                            </h6>
                        </div>
                        <div>
                            <span class="d-block">
                                Sessions
                            </span>
                            <h6 class="mb-0 fw-semibold text-body">
                                9,416
                            </h6>
                        </div>
                    </li>
                    <li class="d-flex justify-content-between position-relative">
                        <div class="dot rounded-circle tablet"></div>
                        <div>
                            <span class="d-block">
                                Tablet
                            </span>
                            <h6 class="mb-0 fw-semibold">
                                32.3%
                            </h6>
                        </div>
                        <div>
                            <span class="d-block">
                                Sessions
                            </span>
                            <h6 class="mb-0 fw-semibold text-body">
                                1,042
                            </h6>
                        </div>
                    </li>
                    <li class="d-flex justify-content-between position-relative">
                        <div class="dot rounded-circle others"></div>
                        <div>
                            <span class="d-block">
                                Others
                            </span>
                            <h6 class="mb-0 fw-semibold">
                                15.4%
                            </h6>
                        </div>
                        <div>
                            <span class="d-block">
                                Sessions
                            </span>
                            <h6 class="mb-0 fw-semibold text-body">
                                135
                            </h6>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <p class="info">
            This data helps you understand which devices are most commonly used and how engagement metrics vary between them.
        </p>
    </div>
</div>
