// nuxtjs-bootstrap/components/Modules/Widgets/TotalEnrolled.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-4">
      <span>Total Enrolled</span>
      <h3 class="mb-0 fs-20">75k+</h3>
      <div class="py-3">
        <div
          class="wh-77 lh-97 text-center m-auto bg-primary-div bg-opacity-25 rounded-circle"
        >
          <i class="material-symbols-outlined fs-32 text-primary-div">
            collections_bookmark
          </i>
        </div>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <span class="fs-12">This Month</span>
        <i class="material-symbols-outlined text-danger">trending_down</i>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TotalEnrolled",
});
</script>

// nextjs-react-bootstrap/src/components/Widgets/TotalEnrolled.js
"use client";

import React from "react";
import Card from "react-bootstrap/Card";
import { MaterialSymbol } from "react-material-symbols";
import "react-material-symbols/rounded";

const TotalEnrolled = () => {
  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <span>Total Enrolled</span>

          <h3 className="mb-0 fs-20">75k+</h3>

          <div className="py-3">
            <div className="wh-77 lh-97 text-center m-auto bg-primary-div bg-opacity-25 rounded-circle">
              <MaterialSymbol
                icon="collections_bookmark"
                size={32}
                className="text-primary-div"
              />
            </div>
          </div>

          <div className="d-flex justify-content-between align-items-center">
            <span className="fs-12">This Month</span>
            <MaterialSymbol icon="trending_down" size={24} className="text-danger" />
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default TotalEnrolled;
