// vuejs-tailwindcss/src/components/Dashboard/Finance/AccountPayable.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md"
  >
    <div class="trezo-card-content">
      <div class="flex justify-between">
        <div>
          <span class="block"> Account Payable </span>
          <h5 class="mb-0 mt-[3px] text-[20px]">$14,580</h5>
        </div>
        <div
          class="w-[55px] lg:w-[60px] h-[55px] lg:h-[60px] flex items-center justify-center rounded-full text-secondary-600 bg-secondary-50 dark:bg-[#0a0e19]"
        >
          <i class="material-symbols-outlined"> payments </i>
        </div>
      </div>
      <div class="mt-[15px] md:mt-[20px] flex items-center gap-[10px]">
        <span
          class="inline-block px-[8.5px] text-success-700 border border-success-300 bg-success-100 text-sm rounded-[100px] text-xs"
        >
          +10.1%
        </span>
        <span class="block text-xs"> Last 30 days </span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "AccountPayable",
});
</script>

// react-material-ui/src/components/Dashboard/Finance/AccountPayable/index.js
"use client";

import { Box, Typography, Card } from "@mui/material";

const AccountPayable = () => {
  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <Box>
            <Typography component={"span"} sx={{ display: "block" }}>
              Account Payable
            </Typography>

            <Typography
              component={"h5"}
              sx={{ mb: "0", mt: "3px", fontSize: "20px", fontWeight: "700" }}
            >
              $14,580
            </Typography>
          </Box>

          <Box
            sx={{
              width: { xs: "55px", md: "60px" },
              height: { xs: "55px", md: "60px" },
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              borderRadius: "100%",
              color: "primary.600",
              bgcolor: "primary.50",
            }}
          >
            <i className="material-symbols-outlined">payments</i>
          </Box>
        </Box>

        <Box
          sx={{
            mt: { xs: "15px", md: "20px" },
            display: "flex",
            alignItems: "center",
            gap: "10px",
          }}
        >
          <Box
            sx={{
              display: "inline-block",
              px: "8.5px",
              color: "success.700",
              border: "1px solid",
              borderColor: "success.300",
              bgcolor: "success.100",
              borderRadius: "100px",
              fontSize: "12px",
            }}
          >
            +10.1%
          </Box>

          <Box sx={{ fontSize: "12px" }}>Last 30 days</Box>
        </Box>
      </Card>
    </>
  );
};

export default AccountPayable;
