// angular-bootstrap/src/app/pages/lms-page/l-course-details/course-instructor/course-instructor.component.ts
import { Component } from '@angular/core';
import { CustomizerSettingsService } from '../../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-course-instructor',
    imports: [],
    templateUrl: './course-instructor.component.html',
    styleUrl: './course-instructor.component.scss'
})
export class CourseInstructorComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<div
    class="course-instructor-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Course Instructor
            </h5>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="course-instructor d-flex align-items-center">
            <div class="image">
                <img src="images/users/user7.jpg" class="rounded-circle" alt="user-image">
            </div>
            <div class="title">
                <span class="d-block fw-medium text-black">
                    Aliva Cohen
                </span>
                <span class="d-block text-body">
                    aliva&#64;trezo.com
                </span>
            </div>
        </div>
        <div class="course-content">
            <span class="title text-black fw-medium d-block">
                Course Description
            </span>
            <p>
                This course is designed for beginners who want to learn the fundamentals of the Python programming language. The course covers basic syntax, data types, control structures, and an introduction to object-oriented programming. Participants will have hands-on coding exercises to reinforce their learning.
            </p>
            <span class="title text-black fw-medium d-block">
                Course Schedule
            </span>
            <p>
                Start Date: 01 August 2025
                <br>
                End Date: 30 December 2025
            </p>
            <span class="title text-black fw-medium d-block">
                Status
            </span>
            <p>
                The course is currently in progress. Students are actively engaged in the learning materials, and the instructor is providing guidance and support.
            </p>
        </div>
    </div>
</div>

// vuejs-tailwindcss/src/components/Pages/LMS/CourseDetails/CourseInstructor.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md"
  >
    <div
      class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between"
    >
      <div class="trezo-card-title">
        <h5 class="mb-0">Course Instructor</h5>
      </div>
    </div>
    <div class="trezo-card-content">
      <div class="flex items-center">
        <img
          src="@/assets/images/users/user7.jpg"
          alt="user-image"
          class="rounded-full w-[100px]"
        />
        <div class="ltr:ml-[15px] rtl:mr-[15px]">
          <span
            class="block text-black dark:text-white text-[17px] mb-[2px] font-medium"
          >
            Aliva Cohen
          </span>
          <span class="block"> aliva@trezo.com </span>
        </div>
      </div>
      <span
        class="text-black dark:text-white font-medium block mb-[7px] mt-[22px]"
      >
        Course Description
      </span>
      <p>
        This course is designed for beginners who want to learn the fundamentals
        of the Python programming language. The course covers basic syntax, data
        types, control structures, and an introduction to object-oriented
        programming. Participants will have hands-on coding exercises to
        reinforce their learning.
      </p>
      <span
        class="text-black dark:text-white font-medium block mb-[7px] mt-[22px]"
      >
        Course Schedule
      </span>
      <p>
        Start Date: 01 August 2024
        <br />
        End Date: 30 December 2024
      </p>
      <span
        class="text-black dark:text-white font-medium block mb-[7px] mt-[22px]"
      >
        Status
      </span>
      <p>
        The course is currently in progress. Students are actively engaged in
        the learning materials, and the instructor is providing guidance and
        support.
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CourseInstructor",
});
</script>
