// nextjs-react-bootstrap/src/components/Events/EventsDetails/EventInfo.js
"use client";

import React from "react";
import Card from "react-bootstrap/Card";

const EventInfo = () => {
  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <h3 className="mb-3 mb-lg-4">Event Info</h3>

          <span className="d-block mb-3">
            <span className="text-secondary">08:00 AM</span> - Registration
          </span>

          <span className="d-block mb-3">
            <span className="text-secondary">09:00 AM</span> - Opening Keynote
          </span>

          <span className="d-block mb-3">
            <span className="text-secondary">10:30 AM</span> - Panel Discussion:
            Future Trends
          </span>

          <span className="d-block mb-3">
            <span className="text-secondary">12:00 PM</span> - Lunch Break
          </span>

          <span className="d-block mb-3">
            <span className="text-secondary">02:00 PM</span> - Interactive
            Workshops
          </span>

          <span className="d-block mb-3">
            <span className="text-secondary">04:30 PM</span> - Networking
            Reception
          </span>

          <h3 className="mb-3 mb-lg-3 pt-2">Registration Information</h3>
          <span className="d-block mb-2">
            Early Bird Registration Deadline: 15 November 2024
          </span>
          
          <span className="d-block mb-2">
            Standard Registration Deadline: 30 November 2024
          </span>
        </Card.Body>
      </Card>
    </>
  );
};

export default EventInfo;

// vuejs-vuetify/src/components/Pages/Events/EventDetails/EventInfo.vue
<template>
  <v-card
    class="event-details-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Event Info</h5>
    </div>
    <div class="event-details-content">
      <ul class="list pl-0 mb-0 mt-0 list-unstyled">
        <li><span class="text-black">08:00 AM</span> - Registration</li>
        <li><span class="text-black">09:00 AM</span> - Opening Keynote</li>
        <li>
          <span class="text-black">10:30 AM</span> - Panel Discussion: Future
          Trends
        </li>
        <li><span class="text-black">12:00 PM</span> - Lunch Break</li>
        <li>
          <span class="text-black">02:00 PM</span> - Interactive Workshops
        </li>
        <li><span class="text-black">04:30 PM</span> - Networking Reception</li>
      </ul>
      <h5>Registration Information</h5>
      <ul class="list pl-0 mb-0 mt-0 list-unstyled">
        <li>Early Bird Registration Deadline: 15 November 2024</li>
        <li>Standard Registration Deadline: 30 November 2024</li>
      </ul>
    </div>
  </v-card>
</template>

<script>
export default {
  name: "EventInfo",
};
</script>
