// react-nextjs-tailwindcss/src/components/Dashboard/PosSystem/OrderDetails.tsx
"use client";

import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";

type Product = {
  id: number;
  name: string;
  image: string;
  price: number;
  viewLink: string;
};

const OrderDetails: React.FC = () => {
  // Product data
  const [products] = useState<Product[]>([
    {
      id: 1,
      name: "Maybelline Lash",
      image: "/images/products/product15.jpg",
      price: 29,
      viewLink: "/ecommerce/product-details/",
    },
    {
      id: 2,
      name: "Apple iPhone 16",
      image: "/images/products/product16.jpg",
      price: 799,
      viewLink: "/ecommerce/product-details/",
    },
    {
      id: 3,
      name: "Adidas Woman",
      image: "/images/products/product17.jpg",
      price: 85,
      viewLink: "/ecommerce/product-details/",
    },
  ]);

  // Quantity state for each product
  const [quantities, setQuantities] = useState<{ [key: number]: number }>({
    1: 1,
    2: 2,
    3: 1,
  });

  // Payment method state
  const [selectedPaymentMethod, setSelectedPaymentMethod] =
    useState<string>("card");

  // Handle quantity increase
  const handleIncrease = (productId: number) => {
    setQuantities((prev) => ({
      ...prev,
      [productId]: prev[productId] + 1,
    }));
  };

  // Handle quantity decrease
  const handleDecrease = (productId: number) => {
    if (quantities[productId] > 1) {
      setQuantities((prev) => ({
        ...prev,
        [productId]: prev[productId] - 1,
      }));
    }
  };

  // Handle payment method selection
  const handlePaymentMethodChange = (method: string) => {
    setSelectedPaymentMethod(method);
  };

  // Calculate subtotal
  const subtotal = products.reduce(
    (total, product) => total + product.price * quantities[product.id],
    0
  );

  // Calculate tax (10%)
  const tax = subtotal * 0.1;

  // Calculate total
  const total = subtotal + tax;

  return (
    <div className="trezo-card bg-gray-50 dark:bg-[#0c1427] rounded-md border border-gray-100 dark:border-[#172036]">
      <div className="trezo-card-header py-[15px] px-[20px] md:px-[25px] flex items-center justify-between">
        <div className="trezo-card-title">
          <h5 className="mb-0 text-md md:text-[20px] font-medium">
            Order Details
          </h5>
        </div>
        <div className="trezo-card-subtitle">
          <button
            type="button"
            className="block leading-none text-primary-500 transition-all hover:rotate-90"
          >
            <i className="material-symbols-outlined">autorenew</i>
          </button>
        </div>
      </div>

      <div className="trezo-card-content bg-white dark:bg-dark p-[20px] md:p-[25px] rounded-md border-t border-gray-100 dark:border-[#172036]">
        {/* Dynamically render products */}
        {products.map((product) => (
          <div
            key={product.id}
            className="sm:flex items-center justify-between border-t border-gray-100 dark:border-[#172036] first:border-t-0 pt-[17px] first:pt-0 mt-[17px] first:mt-0"
          >
            <Link
              href={product.viewLink}
              className="flex items-center gap-[10px] text-black dark:text-white transition-all hover:text-primary-500"
            >
              <Image
                src={product.image}
                className="w-[40px] rounded-md"
                alt="product-image"
                width={40}
                height={40}
              />
              <span className="block font-medium leading-[1.2] lg:max-w-[80px]">
                {product.name}
              </span>
            </Link>
            <div className="mt-[12px] sm:mt-0 flex items-center gap-[15px]">
              <div
                className="counter-container relative w-[90px]"
                id="inputCounter"
              >
                <button
                  className="decrease-btn top-1/2 -translate-y-1/2 absolute text-[20px] ltr:left-[12px] rtl:right-[12px] text-gray-500 dark:text-gray-400 transition-all hover:text-primary-500"
                  onClick={() => handleDecrease(product.id)}
                >
                  -
                </button>
                <input
                  type="text"
                  className="counter text-base h-[34px] rounded-md text-center block w-full bg-gray-50 dark:bg-[#15203c] text-black outline-0 font-medium dark:text-white"
                  value={quantities[product.id]}
                  readOnly
                />
                <button
                  className="increase-btn top-1/2 -translate-y-1/2 absolute text-[20px] ltr:right-[12px] rtl:left-[12px] text-gray-500 dark:text-gray-400 transition-all hover:text-primary-500"
                  onClick={() => handleIncrease(product.id)}
                >
                  +
                </button>
              </div>
              <div className="leading-none font-medium sm:w-[45px] text-lg text-primary-500">
                ${product.price * quantities[product.id]}
              </div>
            </div>
          </div>
        ))}
 
        {/* Order summary */}
        <div className="bg-gray-50 dark:bg-dark rounded-md mt-[20px] md:mt-[25px] p-[15px] md:p-[20px]">
          <div className="flex items-center justify-between mb-[5px]">
            <span className="block">Total:</span>
            <span className="block">
              {products.reduce(
                (total, product) => total + quantities[product.id],
                0
              )}{" "}
              Items
            </span>
          </div>
          <div className="flex items-center justify-between mb-[5px]">
            <span className="block text-black dark:text-white font-medium">
              Subtotal:
            </span>
            <span className="block text-black dark:text-white font-medium">
              ${subtotal.toFixed(2)}
            </span>
          </div>
          <div className="flex items-center justify-between mb-[5px]">
            <span className="block text-black dark:text-white font-medium">
              Shipping:
            </span>
            <span className="block text-black dark:text-white font-medium">
              $0.00
            </span>
          </div>
          <div className="flex items-center justify-between mb-[5px]">
            <span className="block text-black dark:text-white font-medium">
              Tax (10%):
            </span>
            <span className="block text-black dark:text-white font-medium">
              ${tax.toFixed(2)}
            </span>
          </div>
          <div className="flex items-center justify-between mt-[18px]">
            <span className="block text-lg md:text-[20px] text-black dark:text-white font-medium">
              Payable Total:
            </span>
            <span className="block text-lg md:text-[20px] text-black dark:text-white font-medium">
              ${total.toFixed(2)}
            </span>
          </div>
        </div>

        {/* Payment method */}
        <h4 className="font-medium mb-[15px] text-[20px] mt-[25px]">
          Payment Method
        </h4>
        <div className="payment-method flex items-center gap-[20px] md:gap-[25px]">
          {["cash", "card", "eWallet"].map((method) => (
            <div
              key={method}
              className={`text-center relative w-[82px] h-[66px] pt-[7px] rounded-md bg-gray-50 dark:bg-dark border ${
                selectedPaymentMethod === method
                  ? "border-primary-500"
                  : "border-primary-100 dark:border-[#172036]"
              } transition-all`}
              onClick={() => handlePaymentMethodChange(method)}
            >
              <i className="material-symbols-outlined !text-2xl text-primary-500">
                {method === "cash"
                  ? "paid"
                  : method === "card"
                  ? "credit_card"
                  : "wallet"}
              </i>
              <span className="block -mt-[2px] md:-mt-[4px]">
                {method === "eWallet"
                  ? "E-Wallet"
                  : method.charAt(0).toUpperCase() + method.slice(1)}
              </span>
              <input
                type="radio"
                name="paymentMethod"
                id={`${method}Type`}
                defaultChecked={selectedPaymentMethod === method}
                className="top-0 left-0 z-[1] w-full h-full m-0 absolute cursor-pointer opacity-0"
              />
            </div>
          ))}
        </div>

        {/* Place order button */}
        <button
          type="button"
          className="mt-[20px] md:mt-[25px] font-medium block w-full transition-all rounded-md md:text-md py-[10px] md:py-[11px] px-[20px] md:px-[22px] bg-primary-500 text-white hover:bg-primary-400"
        >
          Place Order
        </button>
      </div>
    </div>
  );
};

export default OrderDetails;

// nuxtjs-bootstrap/components/Dashboard/POSSystem/OrderDetails.vue
<template>
  <div
    class="card custom-shadow for-dark-rounded-bg rounded-3 border mb-4 bg-body-bg"
  >
    <div
      class="d-flex justify-content-between align-items-center flex-wrap gap-3"
      style="padding: 8.5px 25px"
    >
      <h3 class="mb-0 fs-20 fw-medium text-secondary">Order Details</h3>

      <button class="bg-transparent p-0 border-0 text-primary-50 fs-24">
        <i class="ri-refresh-line"></i>
      </button>
    </div>

    <div class="card-body bg-white py-4 px-0 rounded-3 border-top">
      <div class="last-child-none">
        <div
          class="d-flex justify-content-between align-items-center child border-bottom px-3 px-sm-4"
          style="padding-bottom: 20px; margin-bottom: 20px"
        >
          <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
              <img
                src="@/assets/images/product-45.jpg"
                style="width: 40px; height: 28px"
                class="rounded-1"
                alt="product"
              />
            </div>
            <div class="flex-grow-1 ms-10">
              <h3 class="fs-14 fw-medium mb-0" style="max-width: 78px">
                Maybelline Lash
              </h3>
            </div>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <div class="product-quantity border-0 bg-body-bg rounded-2">
              <QuantityCounter />
            </div>

            <span class="fs-18 fw-medium text-primary ms-2 ms-sm-4">$29</span>
          </div>
        </div>
        <div
          class="d-flex justify-content-between align-items-center child border-bottom px-3 px-sm-4"
          style="padding-bottom: 20px; margin-bottom: 20px"
        >
          <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
              <img
                src="@/assets/images/product-46.jpg"
                style="width: 40px; height: 28px"
                class="rounded-1"
                alt="product"
              />
            </div>
            <div class="flex-grow-1 ms-10">
              <h3 class="fs-14 fw-medium mb-0" style="max-width: 78px">
                Apple iPhone 16
              </h3>
            </div>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <div class="product-quantity border-0 bg-body-bg rounded-2">
              <QuantityCounter />
            </div>

            <span class="fs-18 fw-medium text-primary ms-2 ms-sm-4">$799</span>
          </div>
        </div>
        <div
          class="d-flex justify-content-between align-items-center child border-bottom px-3 px-sm-4"
          style="padding-bottom: 20px; margin-bottom: 20px"
        >
          <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
              <img
                src="@/assets/images/product-47.jpg"
                style="width: 40px; height: 28px"
                class="rounded-1"
                alt="product"
              />
            </div>
            <div class="flex-grow-1 ms-10">
              <h3 class="fs-14 fw-medium mb-0" style="max-width: 78px">
                Adidas Woman
              </h3>
            </div>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <div class="product-quantity border-0 bg-body-bg rounded-2">
              <QuantityCounter />
            </div>

            <span class="fs-18 fw-medium text-primary ms-2 ms-sm-4">$85</span>
          </div>
        </div>
      </div>

      <div class="p-4 pb-0">
        <div class="bg-body-bg p-20 rounded-3 mb-30">
          <ul class="ps-0 mb-3 list-unstyled last-child-none">
            <li
              class="d-flex justify-content-between align-items-center"
              style="margin-bottom: 7px"
            >
              <span>Total</span>
              <span>3 Items</span>
            </li>
            <li
              class="d-flex justify-content-between align-items-center"
              style="margin-bottom: 7px"
            >
              <span class="text-secondary fw-medium">Subtotal:</span>
              <span class="text-secondary fw-medium">$913.00</span>
            </li>
            <li
              class="d-flex justify-content-between align-items-center"
              style="margin-bottom: 7px"
            >
              <span class="text-secondary fw-medium">Shipping:</span>
              <span class="text-secondary fw-medium">$0.00</span>
            </li>
            <li
              class="d-flex justify-content-between align-items-center"
              style="margin-bottom: 7px"
            >
              <span class="text-secondary fw-medium">Tax (10%):</span>
              <span class="text-secondary fw-medium">$91.30</span>
            </li>
          </ul>
          <div class="d-flex justify-content-between align-items-center">
            <h3 class="fs-20 fw-medium mb-0">Payable Total</h3>
            <h3 class="fs-20 fw-medium mb-0">$1004.30</h3>
          </div>
        </div>

        <h3 class="fs-20 fw-medium mb-3">Payment Method</h3>

        <div
          class="d-flex flex-wrap gap-2 justify-content-between align-items-center payment-method mb-30"
        >
          <div>
            <input
              type="radio"
              class="btn-check"
              name="options-base"
              id="option5"
              autocomplete="off"
            />
            <label
              class="btn"
              for="option5"
              style="
                width: 81px;
                height: 66px;
                background-color: #f6f7f9;
                border: 1px solid #dde4ff;
                padding: 9px 0;
              "
            >
              <img src="@/assets/images/cash.svg" alt="cash" />
              <span class="d-block text-secondary">Cash</span>
            </label>
          </div>

          <div class="">
            <input
              type="radio"
              class="btn-check"
              name="options-base"
              id="option6"
              autocomplete="off"
              checked
            />
            <label
              class="btn"
              for="option6"
              style="
                width: 81px;
                height: 66px;
                background-color: #f6f7f9;
                border: 1px solid #dde4ff;
                padding: 9px 0;
              "
            >
              <img src="@/assets/images/card.svg" alt="cash" />
              <span class="d-block text-secondary">Card</span>
            </label>
          </div>

          <div class="">
            <input
              type="radio"
              class="btn-check"
              name="options-base"
              id="option8"
              autocomplete="off"
            />
            <label
              class="btn"
              for="option8"
              style="
                width: 81px;
                height: 66px;
                background-color: #f6f7f9;
                border: 1px solid #dde4ff;
                padding: 9px 0;
              "
            >
              <img src="@/assets/images/e-wallet.svg" alt="cash" />
              <span class="d-block text-secondary">E-Wallet</span>
            </label>
          </div>
        </div>

        <RouterLink
          to="/ecommerce/checkout"
          class="btn btn-primary fs-16 fw-medium w-100 py-2"
        >
          Place Order
        </RouterLink>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import QuantityCounter from "./QuantityCounter.vue";

export default defineComponent({
  name: "OrderDetails",
  components: {
    QuantityCounter,
  },
});
</script>
