// nuxtjs-vuetify/components/Pages/Users/UsersList/index.vue
<template>
  <v-card
    class="users-list-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <form class="search-box position-relative" @submit.prevent>
        <input
          type="text"
          class="input-search d-block"
          placeholder="Search user here....."
          v-model="searchTerm"
        />
        <button type="submit">
          <i class="material-symbols-outlined">search</i>
        </button>
      </form>
      <NuxtLink class="add-btn" to="/users/add-user">
        <i class="material-symbols-outlined"> add </i>
        Add New User
      </NuxtLink>
    </div>
    <div class="trezo-table-content">
      <div class="trezo-table">
        <v-table>
          <thead>
            <tr>
              <th class="text-start">User ID</th>
              <th class="text-start">User</th>
              <th class="text-start">Email</th>
              <th class="text-start">Location</th>
              <th class="text-start">Phone</th>
              <th class="text-start">Projects</th>
              <th class="text-start">Join Date</th>
              <th class="text-start">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in filteredItems" :key="item.id">
              <td>
                {{ item.userID }}
              </td>
              <td>
                <div class="customer-info d-flex align-items-center">
                  <div class="img">
                    <v-img
                      class="rounded-circle"
                      :src="item.user.image"
                      alt="user-image"
                    />
                  </div>
                  <span class="d-block text-black fw-medium">
                    {{ item.user.name }}
                  </span>
                </div>
              </td>
              <td>
                {{ item.email }}
              </td>
              <td>{{ item.location }}</td>
              <td>{{ item.phone }}</td>
              <td>{{ item.projects }}</td>
              <td>{{ item.joinDate }}</td>
              <td>
                <div class="action-buttons d-flex align-items-center">
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.view }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.edit }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.delete }}
                    </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </v-table>
        <CommonPaginationTwo items="10" />
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

import image1 from "~/assets/images/users/user6.jpg";
import image2 from "~/assets/images/users/user7.jpg";
import image3 from "~/assets/images/users/user8.jpg";
import image4 from "~/assets/images/users/user9.jpg";
import image5 from "~/assets/images/users/user10.jpg";
import image6 from "~/assets/images/users/user11.jpg";
import image7 from "~/assets/images/users/user12.jpg";
import image8 from "~/assets/images/users/user13.jpg";
import image9 from "~/assets/images/users/user14.jpg";
import image10 from "~/assets/images/users/user15.jpg";

export default defineComponent({
  name: "UsersList",
  setup() {
    const items = ref([
      {
        userID: "#JAN-158",
        user: {
          image: image1,
          name: "Marcia Baker",
        },
        email: "marcia@trezo.com",
        location: "Washington D.C",
        phone: "+1 555-445-4455",
        projects: 6,
        joinDate: "01 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-325",
        user: {
          image: image2,
          name: "Carolyn Barnes",
        },
        email: "barnes@trezo.com",
        location: "Chicago",
        phone: "+1 555-455-9966",
        projects: 10,
        joinDate: "02 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-286",
        user: {
          image: image3,
          name: "Donna Miller",
        },
        email: "donna@trezo.com",
        location: "Oklahoma City",
        phone: "+1 555-555-9922",
        projects: 6,
        joinDate: "03 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-463",
        user: {
          image: image4,
          name: "Barbara Cross",
        },
        email: "cross@trezo.com",
        location: "San Diego",
        phone: "+1 555-445-7788",
        projects: 4,
        joinDate: "04 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-491",
        user: {
          image: image5,
          name: "Rebecca Block",
        },
        email: "block@trezo.com",
        location: "Los Angeles",
        phone: "+1 555-333-2288",
        projects: 2,
        joinDate: "05 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-860",
        user: {
          image: image6,
          name: "Ramiro McCarty",
        },
        email: "ramiro@trezo.com",
        location: "Las Vegas",
        phone: "+1 555-445-4455",
        projects: 8,
        joinDate: "06 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-431",
        user: {
          image: image7,
          name: "Robert Fairweather",
        },
        email: "robert@trezo.com",
        location: "San Francisco",
        phone: "+1 555-555-9922",
        projects: 6,
        joinDate: "07 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-998",
        user: {
          image: image8,
          name: "Marcelino Haddock",
        },
        email: "haddock@trezo.com",
        location: "Washington D.C",
        phone: "+1 555-455-9966",
        projects: 9,
        joinDate: "08 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-436",
        user: {
          image: image9,
          name: "Thomas Wilson",
        },
        email: "wildon@trezo.com",
        location: "San Diego",
        phone: "+1 555-333-2288",
        projects: 5,
        joinDate: "10 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        userID: "#JAN-125",
        user: {
          image: image10,
          name: "Nathaniel Hulsey",
        },
        email: "hulsey@trezo.com",
        location: "Chicago",
        phone: "+1 555-445-7788",
        projects: 6,
        joinDate: "11 Dec 2024",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
    ]);

    const searchTerm = ref("");

    const filteredItems = computed(() => {
      return items.value.filter(
        (item: {
          userID: string;
          user: { name: string };
          email: string;
          location: string;
          phone: string;
          joinDate: string;
        }) =>
          item.userID.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.user.name
            .toLowerCase()
            .includes(searchTerm.value.toLowerCase()) ||
          item.email.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.location
            .toLowerCase()
            .includes(searchTerm.value.toLowerCase()) ||
          item.phone.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
          item.joinDate.toLowerCase().includes(searchTerm.value.toLowerCase())
      );
    });

    return {
      items,
      searchTerm,
      filteredItems,
    };
  },
});
</script>

<style lang="scss" scoped>
.users-list-card {
  padding-bottom: 8px !important;
  .trezo-table-content {
    .trezo-table {
      margin-left: -25px;
      margin-right: -25px;
      table {
        thead {
          tr {
            th {
              background-color: #ecf0ff !important;
              padding: {
                top: 13px;
                bottom: 13px;
              }
              &:first-child {
                border-top-left-radius: 0 !important;
                padding: {
                  left: 25px;
                  right: 0;
                }
              }
              &:last-child {
                border-top-right-radius: 0 !important;
                padding-right: 25px;
              }
              .v-checkbox.v-input {
                margin: -18px -9px -40px -10px;
              }
              .v-input__details {
                display: none !important;
              }
              .v-selection-control__input {
                width: 0 !important;
                height: 0 !important;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              padding: {
                top: 17px !important;
                bottom: 17px !important;
              }
              &:first-child {
                border-left-width: 0 !important;
                padding: {
                  left: 25px;
                  right: 0;
                }
              }
              &:last-child {
                padding-right: 25px;
                border-right-width: 0 !important;
              }
              .v-checkbox.v-input {
                margin: -10px -30px -32px -10px;
              }
              .v-input__details {
                display: none !important;
              }
              .v-selection-control__input {
                width: 0 !important;
                height: 0 !important;
              }
            }
            &:last-child {
              td {
                border-bottom-width: 0;
              }
            }
            &:first-child {
              td {
                border-top-width: 0;
              }
            }
          }
        }
      }
      .pagination-content {
        margin-top: 0;
        padding: 15px 20px;
        border-radius: 0 0 7px 7px;
        color: var(--blackColor) !important;
        background-color: transparent !important;
        border-top: 1px solid #eceef2;
      }
    }
  }
}
</style>

// angular-bootstrap/src/app/pages/users-page/users-list/users-list.component.ts
import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-users-list',
    standalone: true,
    imports: [RouterLink, NgIf],
    templateUrl: './users-list.component.html',
    styleUrl: './users-list.component.scss'
})
export class UsersListComponent {}
<!-- Breadcrumb -->
<div class="breadcrumb-card mb-25 d-md-flex align-items-center justify-content-between">
    <h5 class="mb-0">
        Users List
    </h5>
    <ol class="breadcrumb list-unstyled mt-0 mb-0 p-0">
        <li class="breadcrumb-item d-inline-block position-relative">
            <a routerLink="/dashboard" class="d-inline-block position-relative">
                <i class="material-symbols-outlined">
                    home
                </i>
                Dashboard
            </a>
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            Users
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            Users List
        </li>
    </ol>
</div>

<!-- Users List -->
<div class="users-list-card trezo-card table-style-two mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-header d-sm-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <form class="search-box position-relative">
                <label class="text-black">
                    <i class="material-symbols-outlined">
                        search
                    </i>
                </label>
                <input type="text" class="input-search d-block w-100 border-radius" placeholder="Search user here.....">
            </form>
        </div>
        <div class="trezo-card-subtitle">
            <a class="add-btn d-inline-block transition fw-medium border-radius" routerLink="/dashboard/users/add-user">
                <span class="d-inline-block position-relative">
                    <i class="material-symbols-outlined">
                        add
                    </i>
                    Add New User
                </span>
            </a>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="basic-table table-responsive">
            <table class="table mb-0">
                <thead>
                    <tr>
                        <th scope="col" class="fw-medium"> User ID </th>
                        <th scope="col" class="fw-medium"> User </th>
                        <th scope="col" class="fw-medium"> Email </th>
                        <th scope="col" class="fw-medium"> Location </th>
                        <th scope="col" class="fw-medium"> Phone </th>
                        <th scope="col" class="fw-medium"> Projects </th>
                        <th scope="col" class="fw-medium"> Join Date </th>
                        <th scope="col" class="fw-medium"> Action </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td> #JAN-158 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user6.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Marcia Baker </span>
                            </div>
                        </td>
                        <td> marcia&#64;trezo.com </td>
                        <td> Washington D.C </td>
                        <td> +1 555-445-4455 </td>
                        <td> 6 </td>
                        <td> 01 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-325 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user7.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Carolyn Barnes </span>
                            </div>
                        </td>
                        <td> barnes&#64;trezo.com </td>
                        <td> Chicago </td>
                        <td> +1 555-455-9966 </td>
                        <td> 10 </td>
                        <td> 02 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-286 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user8.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Donna Miller </span>
                            </div>
                        </td>
                        <td> donna&#64;trezo.com </td>
                        <td> Oklahoma City </td>
                        <td> +1 555-555-9922 </td>
                        <td> 6 </td>
                        <td> 03 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-463 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user9.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Barbara Cross </span>
                            </div>
                        </td>
                        <td> cross&#64;trezo.com </td>
                        <td> San Diego </td>
                        <td> +1 555-445-7788 </td>
                        <td> 4 </td>
                        <td> 04 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-491 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user10.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Rebecca Block </span>
                            </div>
                        </td>
                        <td> block&#64;trezo.com </td>
                        <td> Los Angeles </td>
                        <td> +1 555-333-2288 </td>
                        <td> 2 </td>
                        <td> 05 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-860 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user11.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Ramiro McCarty </span>
                            </div>
                        </td>
                        <td> ramiro&#64;trezo.com </td>
                        <td> Las Vegas </td>
                        <td> +1 555-445-4455 </td>
                        <td> 8 </td>
                        <td> 06 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-431 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user12.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Robert Fairweather </span>
                            </div>
                        </td>
                        <td> robert&#64;trezo.com </td>
                        <td> San Francisco </td>
                        <td> +1 555-555-9922 </td>
                        <td> 6 </td>
                        <td> 07 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-998 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user13.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Marcelino Haddock </span>
                            </div>
                        </td>
                        <td> haddock&#64;trezo.com </td>
                        <td> Washington D.C </td>
                        <td> +1 555-455-9966 </td>
                        <td> 9 </td>
                        <td> 08 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-436 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user14.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Thomas Wilson </span>
                            </div>
                        </td>
                        <td> wildon&#64;trezo.com </td>
                        <td> San Diego </td>
                        <td> +1 555-333-2288 </td>
                        <td> 5 </td>
                        <td> 10 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> #JAN-125 </td>
                        <td>
                            <div class="customer-info d-flex align-items-center">
                                <div class="img">
                                    <img alt="user-image" class="rounded-circle" src="images/users/user15.jpg">
                                </div>
                                <span class="d-block text-black fw-medium"> Nathaniel Hulsey </span>
                            </div>
                        </td>
                        <td> hulsey&#64;trezo.com </td>
                        <td> Chicago </td>
                        <td> +1 555-445-7788 </td>
                        <td> 6 </td>
                        <td> 11 Dec 2024 </td>
                        <td>
                            <div class="action-buttons d-flex align-items-center">
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> visibility </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> edit </i>
                                </button>
                                <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                    <i class="material-symbols-outlined"> delete </i>
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="trezo-card-pagination">
            <div class="d-md-flex align-items-center justify-content-between">
                <p class="mb-0">
                    Showing 10 of 36 results
                </p>
                <ol class="list-unstyled mb-0 p-0">
                    <li class="d-inline-block">
                        <a class="prev" routerLink=".">
                            <span class="opacity-0">
                                0
                            </span>
                            <i class="material-symbols-outlined">
                                chevron_left
                            </i>
                        </a>
                    </li>
                    <li class="d-inline-block">
                        <a routerLink="." class="active">
                            1
                        </a>
                    </li>
                    <li class="d-inline-block">
                        <a routerLink=".">
                            2
                        </a>
                    </li>
                    <li class="d-inline-block">
                        <a routerLink=".">
                            3
                        </a>
                    </li>
                    <li class="d-inline-block">
                        <a routerLink=".">
                            4
                        </a>
                    </li>
                    <li class="d-inline-block">
                        <a class="next" routerLink=".">
                            <span class="opacity-0">
                                0
                            </span>
                            <i class="material-symbols-outlined">
                                chevron_right
                            </i>
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
