// vuejs-vuetify/src/components/Modules/Tables/BasicTable/AllProjects.vue
<template>
  <v-card
    class="all-projects-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">All Projects</h5>
      <div class="d-flex align-items-center">
        <v-menu>
          <template v-slot:activator="{ props }">
            <button
              type="button"
              v-bind="props"
              class="card-header-menu border-none d-inline-block border-radius"
            >
              This Week
            </button>
          </template>
          <v-list class="menu-content">
            <button type="button" class="bg-transparent border-none">
              This Day
            </button>
            <button type="button" class="bg-transparent border-none">
              This Week
            </button>
            <button type="button" class="bg-transparent border-none">
              This Month
            </button>
            <button type="button" class="bg-transparent border-none">
              This Year
            </button>
          </v-list>
        </v-menu>
      </div>
    </div>
    <div class="trezo-table-content">
      <div class="trezo-table">
        <v-table>
          <thead>
            <tr>
              <th class="text-start">ID</th>
              <th class="text-start">Project Name</th>
              <th class="text-start">Client</th>
              <th class="text-start">Assignees</th>
              <th class="text-start">Budget</th>
              <th class="text-start">Start Date</th>
              <th class="text-start">End Date</th>
              <th class="text-start">Status</th>
              <th class="text-start">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in items.slice(0, 5)" :key="item.id">
              <td class="text-body">{{ item.id }}</td>
              <td class="text-start">
                <RouterLink to="/dashboard" class="project-name fw-medium">
                  {{ item.projectName }}
                </RouterLink>
              </td>
              <td>{{ item.client }}</td>
              <td>
                <div class="assignees d-flex align-items-center">
                  <div
                    v-for="userImg in item.assignees.images"
                    :key="userImg.id"
                  >
                    <v-img
                      :src="userImg.image"
                      class="rounded-circle"
                      alt="user-image"
                    />
                  </div>
                  <div
                    class="d-flex align-items-center justify-content-center rounded-circle bg-primary text-white fw-medium z-index"
                  >
                    {{ item.assignees.number }}
                  </div>
                </div>
              </td>
              <td class="text-body">${{ item.budget }}</td>
              <td class="text-body">{{ item.startDate }}</td>
              <td class="text-body">{{ item.endDate }}</td>
              <td>
                <span
                  class="trezo-status-badge"
                  :class="computeClass(item.status)"
                >
                  {{ item.status }}
                </span>
              </td>
              <td>
                <div class="action-buttons d-flex align-items-center">
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.view }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.edit }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.delete }}
                    </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </v-table>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  name: "AllProjects",
  setup() {
    const items = ref([
      {
        id: "#854",
        projectName: "Project CyberSphere",
        client: "NovaTech Solutions",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user11.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+10",
        },
        budget: "4,500",
        startDate: "25 Mar 2024",
        endDate: "25 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#853",
        projectName: "Digital Oasis Initiative",
        client: "AlphaWave Innovations",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user8.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+04",
        },
        budget: "6,800",
        startDate: "20 Mar 2024",
        endDate: "20 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#852",
        projectName: "CloudScape Evolution",
        client: "InnovateIQ Inc.",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user10.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+07",
        },
        budget: "2,500",
        startDate: "15 Mar 2024",
        endDate: "15 Apr 2024",
        status: "Pending",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#851",
        projectName: "Data Dynamo Drive",
        client: "BlueSky Technologies",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user13.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user14.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+15",
        },
        budget: "7,500",
        startDate: "10 Mar 2024",
        endDate: "10 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#849",
        projectName: "QuantumLeap Quest",
        client: "NexGen Systems",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user9.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
          ],
          number: "+03",
        },
        budget: "3,400",
        startDate: "05 Mar 2024",
        endDate: "05 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#849",
        projectName: "QuantumLeap Quest",
        client: "NexGen Systems",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user9.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
          ],
          number: "+03",
        },
        budget: "3,400",
        startDate: "05 Mar 2024",
        endDate: "05 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#851",
        projectName: "Data Dynamo Drive",
        client: "BlueSky Technologies",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user13.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user14.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+15",
        },
        budget: "7,500",
        startDate: "10 Mar 2024",
        endDate: "10 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#853",
        projectName: "Digital Oasis Initiative",
        client: "AlphaWave Innovations",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user8.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+04",
        },
        budget: "6,800",
        startDate: "20 Mar 2024",
        endDate: "20 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#854",
        projectName: "Project CyberSphere",
        client: "NovaTech Solutions",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user11.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+10",
        },
        budget: "4,500",
        startDate: "25 Mar 2024",
        endDate: "25 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#852",
        projectName: "CloudScape Evolution",
        client: "InnovateIQ Inc.",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user10.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+07",
        },
        budget: "2,500",
        startDate: "15 Mar 2024",
        endDate: "15 Apr 2024",
        status: "Pending",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#854",
        projectName: "Project CyberSphere",
        client: "NovaTech Solutions",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user11.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+10",
        },
        budget: "4,500",
        startDate: "25 Mar 2024",
        endDate: "25 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#853",
        projectName: "Digital Oasis Initiative",
        client: "AlphaWave Innovations",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user8.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+04",
        },
        budget: "6,800",
        startDate: "20 Mar 2024",
        endDate: "20 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#852",
        projectName: "CloudScape Evolution",
        client: "InnovateIQ Inc.",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user10.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+07",
        },
        budget: "2,500",
        startDate: "15 Mar 2024",
        endDate: "15 Apr 2024",
        status: "Pending",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#851",
        projectName: "Data Dynamo Drive",
        client: "BlueSky Technologies",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user13.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user14.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+15",
        },
        budget: "7,500",
        startDate: "10 Mar 2024",
        endDate: "10 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#849",
        projectName: "QuantumLeap Quest",
        client: "NexGen Systems",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user9.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
          ],
          number: "+03",
        },
        budget: "3,400",
        startDate: "05 Mar 2024",
        endDate: "05 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#849",
        projectName: "QuantumLeap Quest",
        client: "NexGen Systems",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user9.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
          ],
          number: "+03",
        },
        budget: "3,400",
        startDate: "05 Mar 2024",
        endDate: "05 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#851",
        projectName: "Data Dynamo Drive",
        client: "BlueSky Technologies",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user13.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user14.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+15",
        },
        budget: "7,500",
        startDate: "10 Mar 2024",
        endDate: "10 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#853",
        projectName: "Digital Oasis Initiative",
        client: "AlphaWave Innovations",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user7.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user8.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+04",
        },
        budget: "6,800",
        startDate: "20 Mar 2024",
        endDate: "20 Apr 2024",
        status: "In Progress",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#854",
        projectName: "Project CyberSphere",
        client: "NovaTech Solutions",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user15.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user11.jpg"),
            },
            {
              id: 3,
              image: require("@/assets/images/users/user6.jpg"),
            },
            {
              id: 4,
              image: require("@/assets/images/users/user9.jpg"),
            },
          ],
          number: "+10",
        },
        budget: "4,500",
        startDate: "25 Mar 2024",
        endDate: "25 Apr 2024",
        status: "Finished",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
      {
        id: "#852",
        projectName: "CloudScape Evolution",
        client: "InnovateIQ Inc.",
        assignees: {
          className: "ms-m-15",
          images: [
            {
              id: 1,
              image: require("@/assets/images/users/user10.jpg"),
            },
            {
              id: 2,
              image: require("@/assets/images/users/user12.jpg"),
            },
          ],
          number: "+07",
        },
        budget: "2,500",
        startDate: "15 Mar 2024",
        endDate: "15 Apr 2024",
        status: "Pending",
        action: {
          view: "visibility",
          edit: "edit",
          delete: "delete",
        },
      },
    ]);

    const wordConfirmed = ref("Finished");
    const wordInProgress = ref("In Progress");
    const wordPending = ref("Pending");

    const computeClass = (classValue: string) => {
      return {
        pFinished: wordConfirmed.value === classValue,
        pInProgress: wordInProgress.value === classValue,
        pPending: wordPending.value === classValue,
      };
    };

    return {
      items,
      computeClass,
    };
  },
});
</script>

<style lang="scss" scoped>
.all-projects-card {
  .trezo-table-content {
    .trezo-table {
      margin-left: -25px;
      margin-right: -25px;
      table {
        thead {
          tr {
            th {
              background-color: #ecf0ff !important;

              &:first-child {
                border-top-left-radius: 0 !important;
                padding-left: 25px;
              }
              &:last-child {
                border-top-right-radius: 0 !important;
                padding-right: 25px;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              &:first-child {
                padding-left: 25px;
                border-left-width: 0 !important;
              }
              &:last-child {
                padding-right: 25px;
                border-right-width: 0 !important;
              }
            }
            &:first-child {
              td {
                border-top-width: 0 !important;
              }
            }
          }
        }
      }
    }
  }
}
</style>

// angular-bootstrap/src/app/dashboard/project-management/all-projects/all-projects.component.ts
import { Component, HostListener } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgIf } from '@angular/common';

@Component({
    selector: 'app-all-projects',
    imports: [RouterLink, NgIf],
    templateUrl: './all-projects.component.html',
    styleUrl: './all-projects.component.scss'
})
export class AllProjectsComponent {

    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-header-menu')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <div class="trezo-card-header d-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                All Projects
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-header-menu position-relative">
                <button class="menu-btn without-border transition d-inline-block bg-transparent border-radius" (click)="toggleCardHeaderMenu()">
                    <span class="d-block position-relative">
                        This Week
                    </span>
                </button>
                <ul class="dropdown-menu border-radius border-0 show" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Day
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Week
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Month
                        </button>
                    </li>
                    <li>
                        <button type="button" class="dropdown-item d-block w-100 position-relative transition">
                            This Year
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="table-style-two">
            <div class="basic-table table-responsive">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th scope="col" class="fw-medium">
                                ID
                            </th>
                            <th scope="col" class="fw-medium">
                                Project Name
                            </th>
                            <th scope="col" class="fw-medium">
                                Client
                            </th>
                            <th scope="col" class="fw-medium">
                                Assignees
                            </th>
                            <th scope="col" class="fw-medium">
                                Budget
                            </th>
                            <th scope="col" class="fw-medium">
                                Start Date
                            </th>
                            <th scope="col" class="fw-medium">
                                End Date
                            </th>
                            <th scope="col" class="fw-medium">
                                Status
                            </th>
                            <th scope="col" class="fw-medium">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-body">#854</td>
                            <td>
                                <a routerLink="/dashboard/project-management-page/" class="project-name fw-medium">
                                    Project CyberSphere
                                </a>
                            </td>
                            <td>NovaTech Solutions</td>
                            <td>
                                <div class="assignees d-flex align-items-center">
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user15.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user11.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user6.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user9.jpg" />
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center rounded-circle bg-primary text-white fw-medium">
                                        +10
                                    </div>
                                </div>
                            </td>
                            <td class="text-body">$4,500</td>
                            <td class="text-body">25 Mar 2025</td>
                            <td class="text-body">25 Apr 2025</td>
                            <td>
                                <span class="trezo-badge pFinished">
                                    Finished
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">#853</td>
                            <td>
                                <a routerLink="/dashboard/project-management-page/" class="project-name fw-medium">
                                    Digital Oasis Initiative
                                </a>
                            </td>
                            <td>AlphaWave Innovations</td>
                            <td>
                                <div class="assignees d-flex align-items-center">
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user7.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user8.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user9.jpg" />
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center rounded-circle bg-primary text-white fw-medium">
                                        +04
                                    </div>
                                </div>
                            </td>
                            <td class="text-body">$6,800</td>
                            <td class="text-body">20 Mar 2025</td>
                            <td class="text-body">20 Apr 2025</td>
                            <td>
                                <span class="trezo-badge pInProgress">
                                    In Progress
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">#852</td>
                            <td>
                                <a routerLink="/dashboard/project-management-page/" class="project-name fw-medium">
                                    CloudScape Evolution
                                </a>
                            </td>
                            <td>InnovateIQ Inc.</td>
                            <td>
                                <div class="assignees d-flex align-items-center">
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user10.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user12.jpg" />
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center rounded-circle bg-primary text-white fw-medium">
                                        +07
                                    </div>
                                </div>
                            </td>
                            <td class="text-body">$2,500</td>
                            <td class="text-body">15 Mar 2025</td>
                            <td class="text-body">15 Apr 2025</td>
                            <td>
                                <span class="trezo-badge pPending">
                                    Pending
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">#851</td>
                            <td>
                                <a routerLink="/dashboard/project-management-page/" class="project-name fw-medium">
                                    Data Dynamo Drive
                                </a>
                            </td>
                            <td>BlueSky Technologies</td>
                            <td>
                                <div class="assignees d-flex align-items-center">
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user13.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user14.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user15.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user12.jpg" />
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center rounded-circle bg-primary text-white fw-medium">
                                        +15
                                    </div>
                                </div>
                            </td>
                            <td class="text-body">$7,500</td>
                            <td class="text-body">10 Mar 2025</td>
                            <td class="text-body">10 Apr 2025</td>
                            <td>
                                <span class="trezo-badge pInProgress">
                                    In Progress
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-body">#849</td>
                            <td>
                                <a routerLink="/dashboard/project-management-page/" class="project-name fw-medium">
                                    QuantumLeap Quest
                                </a>
                            </td>
                            <td>NexGen Systems</td>
                            <td>
                                <div class="assignees d-flex align-items-center">
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user7.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user9.jpg" />
                                    </div>
                                    <div>
                                        <img alt="user-image" class="rounded-circle" src="images/users/user6.jpg" />
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center rounded-circle bg-primary text-white fw-medium">
                                        +03
                                    </div>
                                </div>
                            </td>
                            <td class="text-body">$3,400</td>
                            <td class="text-body">05 Mar 2025</td>
                            <td class="text-body">05 Apr 2025</td>
                            <td>
                                <span class="trezo-badge pFinished">
                                    Finished
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="trezo-card-pagination">
                <div class="d-md-flex align-items-center justify-content-between">
                    <p class="mb-0">
                        Showing 5 of 36 results
                    </p>
                    <ol class="list-unstyled mb-0 p-0">
                        <li class="d-inline-block">
                            <a class="prev" routerLink=".">
                                <span class="opacity-0">
                                    0
                                </span>
                                <i class="material-symbols-outlined">
                                    chevron_left
                                </i>
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink="." class="active">
                                1
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                2
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                3
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a routerLink=".">
                                4
                            </a>
                        </li>
                        <li class="d-inline-block">
                            <a class="next" routerLink=".">
                                <span class="opacity-0">
                                    0
                                </span>
                                <i class="material-symbols-outlined">
                                    chevron_right
                                </i>
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
