// nextjs-react-bootstrap/src/app/tables/data-table/page.js
"use client";
   
import React from "react";
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Breadcrumb from 'react-bootstrap/Breadcrumb';  
import TopSellingProducts from "@/components/Tables/DataTable/TopSellingProducts";
import RecentOrders from "@/components/Tables/DataTable/RecentOrders";
import TopPerformer from "@/components/Tables/DataTable/TopPerformer";
import RecentLeads from "@/components/Tables/DataTable/RecentLeads";
import AllProjects from "@/components/Tables/DataTable/AllProjects";
import MyTasks from "@/components/Tables/DataTable/MyTasks";
import StudentsProgress from "@/components/Tables/DataTable/StudentsProgress";
import GroupLessons from "@/components/Tables/DataTable/GroupLessons";
import PerformanceOfAgents from "@/components/Tables/DataTable/PerformanceOfAgents";
import RecentCustomerRatings from "@/components/Tables/DataTable/RecentCustomerRatings";
import ToDoList from "@/components/Tables/DataTable/ToDoList";

export default function Page() {
  return (
    <>
      <div className="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4">
        <h3 className="mb-0">Data Table</h3>
 
        <Breadcrumb className="breadcrumb-page-list align-items-center mb-0 lh-1">
          <Breadcrumb.Item href="/dashboard/ecommerce/">
            <div className="d-flex align-items-center text-decoration-none">
              <i className="ri-home-4-line fs-18 text-primary me-1"></i>
              <span className="text-secondary fw-medium hover">Dashboard</span>
            </div>
          </Breadcrumb.Item>

          <Breadcrumb.Item>
            <span className="fw-medium">Tables</span>
          </Breadcrumb.Item>

          <Breadcrumb.Item active>
            <span className="fw-medium">Data Table</span>
          </Breadcrumb.Item>
        </Breadcrumb>
      </div>

      <Row>
        <Col xl={6}>
          <TopSellingProducts />
        </Col>

        <Col xl={6}>
          <RecentOrders />
        </Col>
      </Row>

      <Row>
        <Col lg={4}>
          <TopPerformer />
        </Col>

        <Col lg={8}>
          <RecentLeads />
        </Col>
      </Row>

      <AllProjects />

      <Row>
        <Col xl={6} xxl={4}>
          <MyTasks />
        </Col>

        <Col xl={6} xxl={4}>
          <StudentsProgress />
        </Col>

        <Col xl={6} xxl={4}>
          <GroupLessons />
        </Col>
      </Row>
      
      <PerformanceOfAgents />

      <Row>
        <Col xl={5}>
          <RecentCustomerRatings />
        </Col>

        <Col xl={7}>
          <ToDoList />
        </Col>
      </Row>
    </>
  );
}

// vuejs-vuetify/src/components/Modules/Tables/DataTable/index.vue
<template>
  <v-row>
    <v-col cols="12" lg="6">
      <TopSellingProducts />
    </v-col>
    <v-col cols="12" lg="6">
      <RecentOrders />
    </v-col>
    <v-col cols="12" lg="4">
      <TopPerformers />
    </v-col>
    <v-col cols="12" lg="8">
      <RecentLeads />
    </v-col>
    <v-col cols="12" lg="12">
      <AllProjects />
    </v-col>
    <v-col cols="12" lg="4">
      <MyTasks />
    </v-col>
    <v-col cols="12" lg="4">
      <StudentsProgress />
    </v-col>
    <v-col cols="12" lg="4">
      <GroupLessons />
    </v-col>
    <v-col cols="12" lg="12">
      <PerformanceOfAgents />
    </v-col>
    <v-col cols="12" lg="5">
      <RecentCustomerRatings />
    </v-col>
    <v-col cols="12" lg="7">
      <ToDoList />
    </v-col>
  </v-row>
</template>

<script>
import TopSellingProducts from "./TopSellingProducts.vue";
import RecentOrders from "./RecentOrders.vue";
import TopPerformers from "./TopPerformers.vue";
import RecentLeads from "./RecentLeads.vue";
import AllProjects from "./AllProjects.vue";
import MyTasks from "./MyTasks.vue";
import StudentsProgress from "./StudentsProgress.vue";
import GroupLessons from "./GroupLessons.vue";
import PerformanceOfAgents from "./PerformanceOfAgents.vue";
import RecentCustomerRatings from "./RecentCustomerRatings.vue";
import ToDoList from "./ToDoList.vue";

export default {
  name: "DataTable",
  components: {
    TopSellingProducts,
    RecentOrders,
    TopPerformers,
    RecentLeads,
    AllProjects,
    MyTasks,
    StudentsProgress,
    GroupLessons,
    PerformanceOfAgents,
    RecentCustomerRatings,
    ToDoList,
  },
};
</script>
