// angular-material/src/app/dashboard/helpdesk/performance-of-agents/performance-of-agents.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { NgIf } from '@angular/common';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

@Component({
    selector: 'app-performance-of-agents',
    imports: [MatCardModule, MatButtonModule, MatMenuModule, MatTableModule, MatPaginatorModule, NgIf, MatProgressSpinnerModule],
    templateUrl: './performance-of-agents.component.html',
    styleUrl: './performance-of-agents.component.scss'
})
export class PerformanceOfAgentsComponent {

    displayedColumns: string[] = ['id', 'agentName', 'totalTickets', 'openTickets', 'resolvedTickets', 'avgResolutionTime', 'satisfactionRate', 'action'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

    @ViewChild(MatPaginator) paginator!: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }

}

export interface PeriodicElement {
    id: string;
    agentName: any;
    totalTickets: number;
    openTickets: number;
    resolvedTickets: number;
    avgResolutionTime: string;
    satisfactionRate: any;
    action: any;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        id: '#854',
        agentName: {
            img: 'images/users/user12.jpg',
            name: 'Oliver Khan'
        },
        totalTickets: 230,
        openTickets: 20,
        resolvedTickets: 75,
        avgResolutionTime: '2.5 hours',
        satisfactionRate: {
            percentage: 80,
            primaryClassName: true,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#853',
        agentName: {
            img: 'images/users/user13.jpg',
            name: 'Ava Cooper'
        },
        totalTickets: 180,
        openTickets: 16,
        resolvedTickets: 35,
        avgResolutionTime: '1.4 hours',
        satisfactionRate: {
            percentage: 75,
            primaryClassName: false,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: true,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#852',
        agentName: {
            img: 'images/users/user14.jpg',
            name: 'Isabella Evans'
        },
        totalTickets: 150,
        openTickets: 35,
        resolvedTickets: 45,
        avgResolutionTime: '3.2 hours',
        satisfactionRate: {
            percentage: 80,
            primaryClassName: false,
            successClassName: true,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#851',
        agentName: {
            img: 'images/users/user15.jpg',
            name: 'Mia Hughes'
        },
        totalTickets: 75,
        openTickets: 86,
        resolvedTickets: 25,
        avgResolutionTime: '4.5 hours',
        satisfactionRate: {
            percentage: 100,
            primaryClassName: false,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: true
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#850',
        agentName: {
            img: 'images/users/user16.jpg',
            name: 'Noah Mitchell'
        },
        totalTickets: 320,
        openTickets: 90,
        resolvedTickets: 10,
        avgResolutionTime: '3.8 hours',
        satisfactionRate: {
            percentage: 80,
            primaryClassName: false,
            successClassName: false,
            orangeClassName: true,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#849',
        agentName: {
            img: 'images/users/user17.jpg',
            name: 'Sophia Carter'
        },
        totalTickets: 120,
        openTickets: 55,
        resolvedTickets: 20,
        avgResolutionTime: '5.3 hours',
        satisfactionRate: {
            percentage: 60,
            primaryClassName: true,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#849',
        agentName: {
            img: 'images/users/user17.jpg',
            name: 'Sophia Carter'
        },
        totalTickets: 120,
        openTickets: 55,
        resolvedTickets: 20,
        avgResolutionTime: '5.3 hours',
        satisfactionRate: {
            percentage: 60,
            primaryClassName: true,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#850',
        agentName: {
            img: 'images/users/user16.jpg',
            name: 'Noah Mitchell'
        },
        totalTickets: 320,
        openTickets: 90,
        resolvedTickets: 10,
        avgResolutionTime: '3.8 hours',
        satisfactionRate: {
            percentage: 80,
            primaryClassName: false,
            successClassName: false,
            orangeClassName: true,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#851',
        agentName: {
            img: 'images/users/user15.jpg',
            name: 'Mia Hughes'
        },
        totalTickets: 75,
        openTickets: 86,
        resolvedTickets: 25,
        avgResolutionTime: '4.5 hours',
        satisfactionRate: {
            percentage: 100,
            primaryClassName: false,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: true
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#852',
        agentName: {
            img: 'images/users/user14.jpg',
            name: 'Isabella Evans'
        },
        totalTickets: 150,
        openTickets: 35,
        resolvedTickets: 45,
        avgResolutionTime: '3.2 hours',
        satisfactionRate: {
            percentage: 80,
            primaryClassName: false,
            successClassName: true,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#853',
        agentName: {
            img: 'images/users/user13.jpg',
            name: 'Ava Cooper'
        },
        totalTickets: 180,
        openTickets: 16,
        resolvedTickets: 35,
        avgResolutionTime: '1.4 hours',
        satisfactionRate: {
            percentage: 75,
            primaryClassName: false,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: true,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#854',
        agentName: {
            img: 'images/users/user12.jpg',
            name: 'Oliver Khan'
        },
        totalTickets: 230,
        openTickets: 20,
        resolvedTickets: 75,
        avgResolutionTime: '2.5 hours',
        satisfactionRate: {
            percentage: 80,
            primaryClassName: true,
            successClassName: false,
            orangeClassName: false,
            purpleClassName: false,
            secondaryClassName: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    }
];
<mat-card class="table-style-two mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Performance of Agents
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="card-header-menu without-border d-inline-block border-radius">
                Last 30 Days
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            This Day
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Week
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Month
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Year
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="table-responsive">
            <table mat-table [dataSource]="dataSource">

                <!-- ID Column -->
                <ng-container matColumnDef="id">
                    <th mat-header-cell *matHeaderCellDef>
                        ID
                    </th>
                    <td mat-cell *matCellDef="let element" class="text-body">
                        {{element.id}}
                    </td>
                </ng-container>

                <!-- Agent Name Column -->
                <ng-container matColumnDef="agentName">
                    <th mat-header-cell *matHeaderCellDef>
                        Agent Name
                    </th>
                    <td mat-cell *matCellDef="let element">
                        <div class="customer-info d-flex align-items-center">
                            <div class="img">
                                <img [src]="element.agentName.img" class="rounded-circle" alt="agent-image">
                            </div>
                            <span class="d-block text-black fw-medium">
                                {{element.agentName.name}}
                            </span>
                        </div>
                    </td>
                </ng-container>

                <!-- Total Tickets Column -->
                <ng-container matColumnDef="totalTickets">
                    <th mat-header-cell *matHeaderCellDef>
                        Total Tickets
                    </th>
                    <td mat-cell *matCellDef="let element" class="text-body">
                        {{element.totalTickets}}
                    </td>
                </ng-container>

                <!-- Open Tickets Column -->
                <ng-container matColumnDef="openTickets">
                    <th mat-header-cell *matHeaderCellDef>
                        Open Tickets
                    </th>
                    <td mat-cell *matCellDef="let element" class="text-body">
                        {{element.openTickets}}
                    </td>
                </ng-container>

                <!-- Resolved Tickets Column -->
                <ng-container matColumnDef="resolvedTickets">
                    <th mat-header-cell *matHeaderCellDef>
                        Resolved Tickets
                    </th>
                    <td mat-cell *matCellDef="let element" class="text-body">
                        {{element.resolvedTickets}}
                    </td>
                </ng-container>

                <!-- Avg. Resolution Time Column -->
                <ng-container matColumnDef="avgResolutionTime">
                    <th mat-header-cell *matHeaderCellDef>
                        Avg. Resolution Time
                    </th>
                    <td mat-cell *matCellDef="let element" class="text-body">
                        {{element.avgResolutionTime}}
                    </td>
                </ng-container>

                <!-- Satisfaction Rate Column -->
                <ng-container matColumnDef="satisfactionRate">
                    <th mat-header-cell *matHeaderCellDef>
                        Satisfaction Rate
                    </th>
                    <td mat-cell *matCellDef="let element">
                        <div
                            class="circle-progress-bar position-relative"
                            *ngIf="element.satisfactionRate.primaryClassName"
                        >
                            <mat-spinner mode="determinate" value="{{element.satisfactionRate.percentage}}"></mat-spinner>
                            <span class="percentage d-block text-body">
                                {{element.satisfactionRate.percentage}}%
                            </span>
                        </div>
                        <div
                            class="circle-progress-bar purple position-relative"
                            *ngIf="element.satisfactionRate.purpleClassName"
                        >
                            <mat-spinner mode="determinate" value="{{element.satisfactionRate.percentage}}"></mat-spinner>
                            <span class="percentage d-block text-body">
                                {{element.satisfactionRate.percentage}}%
                            </span>
                        </div>
                        <div
                            class="circle-progress-bar success position-relative"
                            *ngIf="element.satisfactionRate.successClassName"
                        >
                            <mat-spinner mode="determinate" value="{{element.satisfactionRate.percentage}}"></mat-spinner>
                            <span class="percentage d-block text-body">
                                {{element.satisfactionRate.percentage}}%
                            </span>
                        </div>
                        <div
                            class="circle-progress-bar secondary position-relative"
                            *ngIf="element.satisfactionRate.secondaryClassName"
                        >
                            <mat-spinner mode="determinate" value="{{element.satisfactionRate.percentage}}"></mat-spinner>
                            <span class="percentage d-block text-body">
                                {{element.satisfactionRate.percentage}}%
                            </span>
                        </div>
                        <div
                            class="circle-progress-bar orange position-relative"
                            *ngIf="element.satisfactionRate.orangeClassName"
                        >
                            <mat-spinner mode="determinate" value="{{element.satisfactionRate.percentage}}"></mat-spinner>
                            <span class="percentage d-block text-body">
                                {{element.satisfactionRate.percentage}}%
                            </span>
                        </div>
                    </td>
                </ng-container>

                <!-- Action Column -->
                <ng-container matColumnDef="action">
                    <th mat-header-cell *matHeaderCellDef>
                        Action
                    </th>
                    <td mat-cell *matCellDef="let element">
                        <div class="action-buttons d-flex align-items-center">
                            <button type="button" mat-button>
                                <i class="material-symbols-outlined">
                                    {{element.action.view}}
                                </i>
                            </button>
                            <button type="button" mat-button>
                                <i class="material-symbols-outlined">
                                    {{element.action.edit}}
                                </i>
                            </button>
                            <button type="button" mat-button>
                                <i class="material-symbols-outlined">
                                    {{element.action.delete}}
                                </i>
                            </button>
                        </div>
                    </td>
                </ng-container>

                <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
                <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

            </table>
        </div>
        <mat-paginator [pageSizeOptions]="[6]" showFirstLastButtons></mat-paginator>
    </mat-card-content>
</mat-card>

// vuejs-vuetify/src/components/Modules/Tables/DataTable/PerformanceOfAgents.vue
<template>
  <v-card
    class="performance-of-agents-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Performance of Agents</h5>
      <div class="d-flex align-items-center">
        <v-menu>
          <template v-slot:activator="{ props }">
            <button
              type="button"
              v-bind="props"
              class="card-header-menu border-none d-inline-block border-radius"
            >
              Last 30 Days
            </button>
          </template>
          <v-list class="menu-content">
            <button type="button" class="bg-transparent border-none">
              This Day
            </button>
            <button type="button" class="bg-transparent border-none">
              This Week
            </button>
            <button type="button" class="bg-transparent border-none">
              This Month
            </button>
            <button type="button" class="bg-transparent border-none">
              This Year
            </button>
          </v-list>
        </v-menu>
      </div>
    </div>
    <div class="trezo-table-content">
      <div class="trezo-table">
        <v-table>
          <thead>
            <tr>
              <th class="text-start">ID</th>
              <th class="text-start">Agent Name</th>
              <th class="text-start">Total Tickets</th>
              <th class="text-start">Open Tickets</th>
              <th class="text-start">Resolved Tickets</th>
              <th class="text-start">Avg. Resolution Time</th>
              <th class="text-start">Satisfaction Rate</th>
              <th class="text-start">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in items.slice(0, 6)" :key="item.id">
              <td class="text-body">{{ item.id }}</td>
              <td>
                <div class="customer-info d-flex align-items-center">
                  <div class="img">
                    <v-img :src="item.agentName.image" alt="instructor-image" />
                  </div>
                  <span class="d-block text-black fw-medium">
                    {{ item.agentName.name }}
                  </span>
                </div>
              </td>
              <td class="text-body">
                {{ item.totalTickets }}
              </td>
              <td class="text-body">{{ item.openTickets }}</td>
              <td class="text-body">{{ item.resolvedTickets }}</td>
              <td class="text-body">{{ item.avgResolutionTime }}</td>
              <td>
                <v-progress-circular
                  :color="item.satisfactionRate.className"
                  :model-value="item.satisfactionRate.percentage"
                  :size="40"
                >
                  {{ item.satisfactionRate.percentage }}%
                </v-progress-circular>
              </td>
              <td>
                <div class="action-buttons d-flex align-items-center">
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.view }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.edit }}
                    </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined">
                      {{ item.action.delete }}
                    </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </v-table>
      </div>
      <PaginationTwo items="6" />
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import PaginationTwo from "@/components/Common/PaginationTwo.vue";

export default defineComponent({
  name: "PerformanceOfAgents",
  components: {
    PaginationTwo,
  },
  data() {
    return {
      items: [
        {
          id: "#854",
          agentName: {
            image: require("@/assets/images/users/user12.jpg"),
            name: "Oliver Khan",
          },
          totalTickets: 230,
          openTickets: 20,
          resolvedTickets: 75,
          avgResolutionTime: "2.5 hours",
          satisfactionRate: {
            percentage: 80,
            className: "primary",
          },
          action: {
            view: "visibility",
            edit: "edit",
            delete: "delete",
          },
        },
        {
          id: "#853",
          agentName: {
            image: require("@/assets/images/users/user13.jpg"),
            name: "Ava Cooper",
          },
          totalTickets: 180,
          openTickets: 16,
          resolvedTickets: 35,
          avgResolutionTime: "1.4 hours",
          satisfactionRate: {
            percentage: 75,
            className: "purple",
          },
          action: {
            view: "visibility",
            edit: "edit",
            delete: "delete",
          },
        },
        {
          id: "#852",
          agentName: {
            image: require("@/assets/images/users/user14.jpg"),
            name: "Isabella Evans",
          },
          totalTickets: 150,
          openTickets: 35,
          resolvedTickets: 45,
          avgResolutionTime: "3.2 hours",
          satisfactionRate: {
            percentage: 80,
            className: "success",
          },
          action: {
            view: "visibility",
            edit: "edit",
            delete: "delete",
          },
        },
        {
          id: "#851",
          agentName: {
            image: require("@/assets/images/users/user15.jpg"),
            name: "Mia Hughes",
          },
          totalTickets: 75,
          openTickets: 86,
          resolvedTickets: 25,
          avgResolutionTime: "4.5 hours",
          satisfactionRate: {
            percentage: 100,
            className: "secondary",
          },
          action: {
            view: "visibility",
            edit: "edit",
            delete: "delete",
          },
        },
        {
          id: "#850",
          agentName: {
            image: require("@/assets/images/users/user16.jpg"),
            name: "Noah Mitchell",
          },
          totalTickets: 320,
          openTickets: 90,
          resolvedTickets: 10,
          avgResolutionTime: "3.8 hours",
          satisfactionRate: {
            percentage: 80,
            className: "danger",
          },
          action: {
            view: "visibility",
            edit: "edit",
            delete: "delete",
          },
        },
        {
          id: "#849",
          agentName: {
            image: require("@/assets/images/users/user17.jpg"),
            name: "Sophia Carter",
          },
          totalTickets: 120,
          openTickets: 55,
          resolvedTickets: 20,
          avgResolutionTime: "5.3 hours",
          satisfactionRate: {
            percentage: 60,
            className: "primary",
          },
          action: {
            view: "visibility",
            edit: "edit",
            delete: "delete",
          },
        },
      ],
    };
  },
});
</script>

<style lang="scss" scoped>
.performance-of-agents-card {
  .trezo-table-content {
    .trezo-table {
      margin: {
        left: -25px;
        right: -25px;
      }
      table {
        thead {
          tr {
            th {
              background-color: #ecf0ff !important;

              &:first-child {
                border-top-left-radius: 0 !important;
                padding-left: 25px;
              }
              &:last-child {
                border-top-right-radius: 0 !important;
                padding-right: 25px;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              &:first-child {
                padding-left: 25px;
                border-left-width: 0 !important;
              }
              &:last-child {
                padding-right: 25px;
                border-right-width: 0 !important;
              }
            }
            &:first-child {
              td {
                border-top-width: 0 !important;
              }
            }
          }
        }
      }
    }
  }
}
</style>
