// react-bootstrap/src/components/Dashboard/CallCenter/CallCenterGeography/index.js
"use client";

import { Card, Dropdown, ProgressBar } from "react-bootstrap";
import { useState, useEffect } from "react";

const CallCenterGeography = () => {
  const [timeRange, setTimeRange] = useState("Last Month");
  const [locationsData, setLocationsData] = useState([]);

  // Simulate dynamic data fetching
  useEffect(() => {
    const fetchData = async () => {
      // Replace with your API call or dynamic data logic
      const data = [
        {
          country: "United States",
          calls: 1200,
          satisfaction: 90,
          image: "/images/usa.svg",
          progressBarVariant: "success",
        },
        {
          country: "Canada",
          calls: 980,
          satisfaction: 80,
          image: "/images/canada.svg",
          progressBarVariant: "info",
        },
        {
          country: "Brazil",
          calls: 850,
          satisfaction: 65,
          image: "/images/brazil.svg",
          progressBarVariant: "warning",
        },
        {
          country: "Russia",
          calls: 750,
          satisfaction: 60,
          image: "/images/russia.png",
          progressBarVariant: "success",
        },
        {
          country: "Germany",
          calls: 450,
          satisfaction: 40,
          image: "/images/germany.svg",
          progressBarVariant: "danger",
        },
      ];

      setLocationsData(data);
    };

    fetchData();
  }, [timeRange]); // Re-fetch data if timeRange changes

  return (
    <>
      <Card className="rounded-3 bg-white border-0 mb-4">
        <div className="custom-padding-30">
          <div className="d-flex justify-content-between align-items-start mb-3">
            <h3 className="mb-0 fw-semibold">Call Center Geography</h3>

            <Dropdown className="action-opt" align="end">
              <Dropdown.Toggle
                variant="link"
                className="text-decoration-none bg-transparent p-0 d-flex align-items-center text-body"
                id="dropdown-basic"
              >
                <span className="fs-14 lh-1">{timeRange}</span>{" "}
                <i className="ri-arrow-down-s-line fs-20"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                {["Last Day", "Last Week", "Last Month", "Last Year"].map(
                  (range) => (
                    <Dropdown.Item
                      key={range}
                      className="px-3 py-2 text-start"
                      onClick={() => setTimeRange(range)}
                    >
                      {range}
                    </Dropdown.Item>
                  )
                )}
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <div className="text-center" style={{ marginBottom: "50px" }}>
            <img src="/images/vector-map.png" alt="vector-map" />
          </div>

          <ul className="ps-0 mb-0 list-unstyled sales_by_locations mt-4">
            {locationsData.map((location, index) => (
              <li className="d-flex align-items-center pe-0" key={index}>
                <div className="flex-shrink-0">
                  <img
                    src={location.image}
                    className="rounded-circle"
                    alt={location.country}
                    width={30}
                    height={30}
                  />
                </div>
                <div className="flex-grow-1 ms-3">
                  <div className="d-flex justify-content-between gap-1">
                    <span className="fw-medium">{location.country}</span>
                    <span>{location.calls} calls</span>
                    <span className="fw-medium text-body">
                      {location.satisfaction}%
                    </span>
                  </div>
                  <div className="mt-1">
                    <ProgressBar
                      variant={location.progressBarVariant}
                      now={location.satisfaction}
                      style={{ height: "5px" }}
                    />
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </Card>
    </>
  );
};

export default CallCenterGeography;

// nuxtjs-bootstrap/components/Dashboard/CallCenter/CallCenterGeography.vue
<template>
  <div class="card custom-shadow rounded-3 bg-white border mb-4">
    <div class="custom-padding-30">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-4"
      >
        <h3 class="mb-0 fw-semibold">Call Center Geography</h3>

        <div
          class="dropdown select-dropdown without-border position-relative"
          style="right: -5px"
        >
          <button
            class="dropdown-toggle bg-transparent border text-body rounded-2"
            style="padding-right: 20px"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Last Year
          </button>

          <ul
            class="dropdown-menu dropdown-menu-end bg-white border-0 box-shadow py-3"
          >
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                Today
              </button>
            </li>
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                Last Week
              </button>
            </li>
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                Last Month
              </button>
            </li>
            <li>
              <button class="dropdown-item text-secondary py-2 px-3">
                Last Year
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div class="text-center" style="margin: 40px 0">
        <img src="~/assets/images/map.svg" alt="map" style="height: 187px" />
      </div>
      <ul class="ps-0 mb-0 list-unstyled sales_by_locations mt-4">
        <li class="d-flex align-items-center pe-0">
          <div class="flex-shrink-0">
            <img
              src="~/assets/images/usa.svg"
              class="wh-30 rounded-circle"
              alt="usa"
            />
          </div>
          <div class="flex-grow-1 ms-3">
            <div class="d-flex justify-content-between position-relative">
              <span class="fw-medium d-block mb-2">United States</span>
              <span class="count fw-medium text-body">90%</span>
              <span
                class="position-absolute top-50 start-50 translate-middle pb-2 fw-medium"
                >1,200 calls</span
              >
            </div>
            <div
              class="progress"
              role="progressbar"
              aria-label="Example with label"
              aria-valuenow="90"
              aria-valuemin="0"
              aria-valuemax="100"
            >
              <div class="progress-bar bg-success-60" style="width: 90%"></div>
            </div>
          </div>
        </li>
        <li class="d-flex align-items-center pe-0">
          <div class="flex-shrink-0">
            <img
              src="~/assets/images/canada.svg"
              class="wh-30 rounded-circle"
              alt="canada"
            />
          </div>
          <div class="flex-grow-1 ms-3">
            <div class="d-flex justify-content-between position-relative">
              <span class="fw-medium d-block mb-2">Canada</span>
              <span class="count fw-medium text-body">88%</span>
              <span
                class="position-absolute top-50 start-50 translate-middle pb-2 fw-medium"
                >980 calls</span
              >
            </div>
            <div
              class="progress"
              role="progressbar"
              aria-label="Example with label"
              aria-valuenow="88"
              aria-valuemin="0"
              aria-valuemax="100"
            >
              <div class="progress-bar bg-primary" style="width: 88%"></div>
            </div>
          </div>
        </li>
        <li class="d-flex align-items-center pe-0">
          <div class="flex-shrink-0">
            <img
              src="~/assets/images/brazil.svg"
              class="wh-30 rounded-circle"
              alt="brazil"
            />
          </div>
          <div class="flex-grow-1 ms-3">
            <div class="d-flex justify-content-between position-relative">
              <span class="fw-medium d-block mb-2">Brazil</span>
              <span class="count fw-medium text-body">65%</span>
              <span
                class="position-absolute top-50 start-50 translate-middle pb-2 fw-medium"
                >850 calls</span
              >
            </div>
            <div
              class="progress"
              role="progressbar"
              aria-label="Example with label"
              aria-valuenow="65"
              aria-valuemin="0"
              aria-valuemax="100"
            >
              <div class="progress-bar bg-danger" style="width: 65%"></div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CallCenterGeography",
});
</script>
