// react-material-ui/src/components/Forms/AdvancedForms/AdvancedForm.js
"use client";

import React from "react";
import {
  Grid,
  Card,
  Box,
  Typography,
  FormControl,
  TextField,
  Button,
  Checkbox,
  FormControlLabel,
  Divider,
} from "@mui/material";
import { Link } from "react-router-dom";

const AdvancedForm = () => {
  return (
    <>
      <Box component="form">
        <Card
          sx={{
            boxShadow: "none",
            borderRadius: "7px",
            mb: "25px",
            padding: { xs: "18px", sm: "20px", lg: "25px" },
          }}
          className="rmui-card"
        >
          <Box
            sx={{
              mb: "25px",
            }}
          >
            <Typography
              variant="h3"
              sx={{
                fontSize: { xs: "16px", md: "18px" },
                fontWeight: 700,
              }}
              className="text-black"
            >
              Advanced Form
            </Typography>
          </Box>

          <Grid
            container
            spacing={2}
            columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}
          >
            <Grid item xs={12} md={12} lg={12} xl={12}>
              <Box>
                <FormControl fullWidth>
                  <Typography
                    component="label"
                    sx={{
                      fontWeight: "500",
                      fontSize: "14px",
                      mb: "10px",
                      display: "block",
                    }}
                    className="text-black"
                  >
                    Email Address
                  </Typography>

                  <TextField
                    label="Enter email address"
                    variant="filled"
                    type="email"
                    id="email"
                    name="email"
                    required
                    sx={{
                      "& .MuiInputBase-root": {
                        border: "1px solid #D5D9E2",
                        backgroundColor: "#fff",
                        borderRadius: "7px",
                      },
                      "& .MuiInputBase-root::before": {
                        border: "none",
                      },
                      "& .MuiInputBase-root:hover::before": {
                        border: "none",
                      },
                    }}
                  />
                </FormControl>
              </Box>
            </Grid>

            <Grid item xs={12} md={12} lg={12} xl={12}>
              <Box>
                <FormControl fullWidth>
                  <Typography
                    component="label"
                    sx={{
                      fontWeight: "500",
                      fontSize: "14px",
                      mb: "10px",
                      display: "block",
                    }}
                    className="text-black"
                  >
                    Your Password
                  </Typography>

                  <TextField
                    label="Enter your password"
                    variant="filled"
                    type="password"
                    id="password"
                    name="password"
                    required
                    sx={{
                      "& .MuiInputBase-root": {
                        border: "1px solid #D5D9E2",
                        backgroundColor: "#fff",
                        borderRadius: "7px",
                      },
                      "& .MuiInputBase-root::before": {
                        border: "none",
                      },
                      "& .MuiInputBase-root:hover::before": {
                        border: "none",
                      },
                    }}
                  />
                </FormControl>
              </Box>
            </Grid>

            <Grid item xs={12} md={12} lg={12} xl={12}>
              <Box
                sx={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <FormControlLabel control={<Checkbox />} label="Remember me" />

                <Link to="#" className="text-primary">
                  Forgot Password?
                </Link>
              </Box>
            </Grid>

            <Grid item xs={12} md={12} lg={12} xl={12}>
              <Button
                type="submit"
                variant="contained"
                sx={{
                  textTransform: "capitalize",
                  borderRadius: "6px",
                  fontWeight: "500",
                  fontSize: "16px",
                  padding: "10px 24px",
                  color: "#fff !important",
                  boxShadow: "none",
                  display: "block",
                  width: "100%",
                }}
              >
                Sign Up
              </Button>
            </Grid>
          </Grid>

          <Divider sx={{ my: "20px" }}>or sign in with</Divider>

          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "5px",
            }}
          >
            <a
              href="https://www.facebook.com/"
              target="_blank"
              rel="noreferrer"
              style={{
                display: "inline-block",
                textAlign: "center",
                borderRadius: "100%",
                width: "30px",
                height: "30px",
                lineHeight: "30px",
                color: "#fff",
                background: "#3a559f",
              }}
            >
              <i className="ri-facebook-fill"></i>
            </a>

            <a
              href="https://twitter.com/"
              target="_blank"
              rel="noreferrer"
              style={{
                display: "inline-block",
                textAlign: "center",
                borderRadius: "100%",
                width: "30px",
                height: "30px",
                lineHeight: "30px",
                color: "#fff",
                background: "#03a9f4",
              }}
            >
              <i className="ri-twitter-x-fill"></i>
            </a>

            <a
              href="https://www.linkedin.com/"
              target="_blank"
              rel="noreferrer"
              style={{
                display: "inline-block",
                textAlign: "center",
                borderRadius: "100%",
                width: "30px",
                height: "30px",
                lineHeight: "30px",
                color: "#fff",
                background: "#007ab9",
              }}
            >
              <i className="ri-linkedin-fill"></i>
            </a>

            <a
              href="mailto:micheal@gmail.com"
              style={{
                display: "inline-block",
                textAlign: "center",
                borderRadius: "100%",
                width: "30px",
                height: "30px",
                lineHeight: "30px",
                color: "#fff",
                background: "#000",
              }}
            >
              <i className="ri-github-line"></i>
            </a>
          </Box>
        </Card>
      </Box>
    </>
  );
};

export default AdvancedForm;

// nuxtjs-vuetify/components/Modules/Forms/AdvancedElements/AdvancedForm.vue
<template>
  <div class="row">
    <div class="col-md-6">
      <v-card
        class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
      >
        <div class="v-card-header">
          <h5 class="mb-0">Advanced Form</h5>
        </div>
        <div class="advanced-form">
          <form>
            <div class="trezo-form-group">
              <v-label class="d-block fw-medium text-black">
                Email Address
              </v-label>
              <v-text-field
                :rules="[rules.required]"
                label="Enter email address"
                clearable
              ></v-text-field>
            </div>
            <div class="trezo-form-group">
              <v-label class="d-block fw-medium text-black">
                Your Password
              </v-label>
              <v-text-field
                :rules1="[rules1.required]"
                label="Enter your password"
                clearable
              ></v-text-field>
            </div>
            <div class="info d-flex justify-content-between align-items-center">
              <v-checkbox label="Remember me"> </v-checkbox>
              <NuxtLink
                to="/authentication/forgot-password"
                class="d-inline-block text-primary"
              >
                Forgot Password?
              </NuxtLink>
            </div>
            <button class="btn">Sign In</button>
            <div class="signin-with-socials text-center">
              <div class="or z-1 position-relative">
                <span class="d-inline-block"> or sign in with </span>
              </div>
              <div class="socials">
                <button type="button" class="facebook">
                  <i class="ri-facebook-fill"></i>
                </button>
                <button type="button" class="twitter">
                  <i class="ri-twitter-x-fill"></i>
                </button>
                <button type="button" class="google">
                  <i class="ri-google-fill"></i>
                </button>
                <button type="button" class="linkedin">
                  <i class="ri-linkedin-fill"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </v-card>
    </div>
  </div>
</template>

<script>
export default {
  name: "AdvancedForm",
  data: () => ({
    rules: {
      required: (value) => !!value || "Email is required",
    },
    rules1: {
      required: (value) => !!value || "Password is required",
    },
  }),
};
</script>

<style lang="scss" scoped>
.advanced-form {
  form {
    .form-group {
      .error {
        font-size: 13px;
        margin-top: 7px;
      }
    }
    .btn {
      width: 100%;
      height: auto;
      display: block;
      min-width: auto;
      margin-top: 25px;
      padding: 12px 25px;
      border-radius: 7px;
      color: var(--whiteColor);
      background-color: var(--primaryColor);
      font: {
        size: 16px;
        weight: 500;
      }
    }
    .signin-with-socials {
      margin-top: 25px;

      .or {
        span {
          background-color: var(--whiteColor);
          padding: {
            left: 25px;
            right: 25px;
          }
        }
        &::before {
          left: 0;
          right: 0;
          top: 50%;
          height: 1px;
          content: "";
          z-index: -1;
          margin-top: 2px;
          position: absolute;
          transform: translateY(-50%);
          background: var(--borderColor);
        }
      }
      .socials {
        margin-top: 15px;

        button {
          padding: 0;
          width: 30px;
          height: 30px;
          min-width: auto;
          border-radius: 50%;
          display: inline-block;
          color: var(--whiteColor);
          background-color: var(--primaryColor);
          margin: {
            left: 5px;
            right: 5px;
          }
          &:first-child {
            margin-left: 0;
          }
          &:last-child {
            margin-right: 0;
          }
          &.facebook {
            background-color: #3a559f;
          }
          &.twitter {
            background-color: rgba(15, 20, 25, 1);
          }
          &.google {
            background-color: #e02f2f;
          }
          &.linkedin {
            background-color: #007ab9;
          }
        }
      }
    }
    .v-checkbox.v-input {
      margin: -10px -30px -32px -10px;
    }
    .v-input__details {
      display: none !important;
    }
    .v-selection-control__input {
      width: 0 !important;
      height: 0 !important;
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .advanced-form {
    form {
      .btn {
        padding: 12px 25px;
        margin-top: 17px;
        font-size: 13px;
      }
      .signin-with-socials {
        margin-top: 17px;

        .or {
          span {
            padding: {
              left: 15px;
              right: 15px;
            }
          }
        }
        .socials {
          margin-top: 13px;
        }
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .advanced-form {
    form {
      .btn {
        margin-top: 20px;
      }
      .signin-with-socials {
        margin-top: 20px;
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .advanced-form {
    form {
      .btn {
        font-size: 14px;
        padding: 12px 25px;
      }
    }
  }
}

/* Min width 992px to Max width 1199px */
@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .advanced-form {
    form {
      .btn {
        font-size: 15px;
      }
    }
  }
}
</style>
