// angular-bootstrap/src/app/common/footer/footer.component.ts
import { Component } from '@angular/core';
import { CustomizerSettingsService } from '../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-footer',
    imports: [],
    templateUrl: './footer.component.html',
    styleUrl: './footer.component.scss'
})
export class FooterComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<footer
    [class.card-without-border-radius]="themeService.isCardWithoutBorderRadius()"
    [class.card-with-box-shadow]="themeService.isCardWithBoxShadow()"
    class="footer-area text-center bg-white border-top-radius"
    [class.card-borderd]="themeService.isCardBordered()"
>
    <p>
        © <span>Trezo</span> is Proudly Owned by <a href="https://envytheme.com/" target="_blank">EnvyTheme</a>
    </p>
</footer>

// nextjs-react-bootstrap/src/components/Layout/Footer.js
"use client";

import React from "react"; 

const Footer = () => {
  return (
    <>
      <div className="flex-grow-1"></div>

      <footer className="footer-area bg-white text-center rounded-top-7">
        <p className="fs-14">
          © <span className="text-primary-div">Trezo</span> is Proudly Owned by{" "}
          <a
            href="https://envytheme.com/"
            target="_blank"
            className="text-decoration-none text-primary"
          >
            EnvyTheme
          </a>
        </p>
      </footer>
    </>
  );
};

export default Footer;
