// react-bootstrap/src/components/Apps/Email/Sidebar/index.js
"use client";

import { Card, Form } from "react-bootstrap";
import { Link, useLocation } from "react-router-dom"; 

const Sidebar = () => {
  const location = useLocation();
  const pathname = location.pathname;

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <Form className="position-relative default-src-form mb-3 pb-1">
            <Form.Control
              type="text"
              className="rounded-1"
              placeholder="Search"
            />
            <span
              className="material-symbols-outlined fs-18 position-absolute start-0 translate-middle-y"
              style={{
                top: "20px",
              }}
            >
              search
            </span>
          </Form>

          <Link
            to="/apps/email/compose"
            className="btn btn-primary fs-16 fw-medium text-center d-block py-2 mb-4"
          >
            <div className="d-flex align-items-center justify-content-center py-lg-1">
              <span className="material-symbols-outlined fs-18 me-2">edit</span>
              <span>Compose</span>
            </div>
          </Link>

          <ul className="email-sidebar-nav ps-0 mb-4 list-unstyled">
            <li className="mb-3 d-flex justify-content-between align-items-center">
              <Link
                to="/apps/email/inbox"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "/apps/email/inbox" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  inbox
                </span>
                <span className="fw-medium">Inbox</span>
              </Link>
              <span className="fs-13">10</span>
            </li>

            <li className="mb-3">
              <Link
                to="/apps/email/starred"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "/apps/email/starred" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  star_rate
                </span>
                <span className="fw-medium">Started</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="/apps/email/snoozed"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "/apps/email/snoozed" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  alarm
                </span>
                <span className="fw-medium">Snoozed</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="/apps/email/sent-mail"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "/apps/email/sent-mail" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  send
                </span>
                <span className="fw-medium">Sent</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="/apps/email/draft"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "/apps/email/draft" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  draft
                </span>
                <span className="fw-medium">Drafts</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="/apps/email/important"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "/apps/email/important" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  bookmark
                </span>
                <span className="fw-medium">Important</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="#"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "#" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  auto_read_pause
                </span>
                <span className="fw-medium">Chats</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="#"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "#" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  schedule_send
                </span>
                <span className="fw-medium">Scheduled</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="#"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "#" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  live_help
                </span>
                <span className="fw-medium">Spam</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="#"
                className={`d-flex align-items-center text-decoration-none ${
                  pathname === "#" ? "active" : ""
                }`}
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  delete
                </span>
                <span className="fw-medium">Trash</span>
              </Link>
            </li>

            <li className="mb-3">
              <Link
                to="#"
                className="d-flex align-items-center text-decoration-none"
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  account_circle
                </span>
                <span className="fw-medium">Personal</span>
              </Link>
            </li>

            <li>
              <Link
                to="#"
                className="d-flex align-items-center text-decoration-none"
              >
                <span className="material-symbols-outlined fs-18 position-relative top-1 me-2">
                  trip
                </span>
                <span className="fw-medium">Company</span>
              </Link>
            </li>
          </ul>

          <button className="btn btn-outline-primary py-1 px-2 px-sm-4 fs-14 fw-medium rounded-3 hover-bg">
            <span className="py-sm-1 d-block">
              <i className="ri-add-line d-none d-sm-inline-block"></i>
              <span>Add New Label</span>
            </span>
          </button>
        </Card.Body>
      </Card>
    </>
  );
};

export default Sidebar;

// angular-tailwindcss/src/app/apps/email/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
    selector: 'app-sidebar',
    imports: [RouterLink, RouterLinkActive],
    templateUrl: './sidebar.component.html',
    styleUrl: './sidebar.component.scss'
})
export class SidebarComponent {}
<div class="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-content">
        <form class="relative mb-[20px]">
            <label class="absolute ltr:left-[13px] rtl:right-[13px] mt-[2px] text-black dark:text-white top-1/2 -translate-y-1/2">
                <i class="material-symbols-outlined !text-lg">
                    search
                </i>
            </label>
            <input type="text" class="block w-full rounded-md text-black dark:text-white bg-gray-50 dark:bg-[#15203c] border border-gray-50 dark:border-[#15203c] focus:border-primary-500 h-[40px] outline-0 transition-all text-xs placeholder:text-gray-500 dark:placeholder:text-gray-400 ltr:pl-[39px] rtl:pr-[39px] ltr:pr-[15px] rtl:pl-[15px]" placeholder="Search">
        </form>
        <a routerLink="/dashboard/apps/email/compose" class="block w-full bg-primary-500 text-white rounded-md md:text-md px-[22px] py-[12px] text-center font-medium transition-all hover:bg-primary-600">
            <span class="inline-block ltr:pl-[29px] rtl:pr-[29px] relative">
                <i class="material-symbols-outlined absolute !text-[20px] ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                    edit
                </i>
                Compose
            </span>
        </a>
        <ul class="my-[20px] md:my-[25px]">
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="/dashboard/apps/email" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-primary-500 dark:text-white transition-all hover:text-primary-500 font-medium">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        inbox
                    </i>
                    Inbox
                    <span class="block font-normal text-xs text-gray-500 dark:text-gray-400">
                        10
                    </span>
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        star_rate
                    </i>
                    Starred
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        alarm
                    </i>
                    Snoozed
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        send
                    </i>
                    Sent
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        draft
                    </i>
                    Drafts
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        bookmark
                    </i>
                    Important
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        auto_read_pause
                    </i>
                    Chats
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        schedule_send
                    </i>
                    Scheduled
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        forward_to_inbox
                    </i>
                    All Mail
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        live_help
                    </i>
                    Spam
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        delete
                    </i>
                    Trash
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        account_circle
                    </i>
                    Personal
                </a>
            </li>
            <li class="mb-[13px] md:mb-[17px] last:mb-0">
                <a routerLink="." class="flex items-center justify-between relative ltr:pl-[30px] rtl:pr-[30px] text-black dark:text-white transition-all hover:text-primary-500">
                    <i class="material-symbols-outlined !text-lg absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2">
                        trip
                    </i>
                    Company
                </a>
            </li>
        </ul>
        <button type="button" class="inline-block transition-all rounded-md font-medium px-[13px] py-[6px] text-primary-500 border border-primary-500 hover:bg-primary-500 hover:text-white">
            <span class="inline-block relative ltr:pl-[22px] rtl:pr-[22px]">
                <i class="material-symbols-outlined !text-[22px] absolute ltr:-left-[4px] rtl:-right-[4px] top-1/2 -translate-y-1/2">
                    add
                </i>
                Add New Label
            </span>
        </button>
    </div>
</div>
