// angular-bootstrap/src/app/common/internal-error/internal-error.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-internal-error',
    standalone: true,
    imports: [RouterLink],
    templateUrl: './internal-error.component.html',
    styleUrl: './internal-error.component.scss'
})
export class InternalErrorComponent {}
<!-- Breadcrumb -->
<div class="breadcrumb-card mb-25 d-md-flex align-items-center justify-content-between">
    <h5 class="mb-0">
        Internal Error
    </h5>
    <ol class="breadcrumb list-unstyled mt-0 mb-0 p-0">
        <li class="breadcrumb-item d-inline-block position-relative">
            <a routerLink="/dashboard" class="d-inline-block position-relative">
                <i class="material-symbols-outlined">
                    home
                </i>
                Dashboard
            </a>
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            Internal Error
        </li>
    </ol>
</div>

<!-- Internal Error -->
<div class="internal-error-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none text-center">
    <div class="trezo-card-content">
        <img src="images/internal-error.png" alt="internal-error-image">
        <h4>
            Looks like we have an internal error, please try again later.
        </h4>
        <p>
            But no worries! Our team is looking ever where while you wait safely.
        </p>
        <a class="btn-box border-radius d-inline-block fw-medium" routerLink="/dashboard">
            Back to Dashboard
        </a>
    </div>
</div>

// vuejs-vuetify/src/components/Modules/Errors/InternalError/index.vue
<template>
  <v-card
    class="internal-error-card border-radius d-block bg-white border-0 shadow-none text-center"
  >
    <div class="internal-error-content">
      <v-img
        src="@/assets/images/internal-error.png"
        alt="internal-error-image"
      />
      <h4>Looks like we have an internal error, please try again later.</h4>
      <p>
        But no worries! Our team is looking ever where while you wait safely.
      </p>
      <RouterLink class="btn" to="/dashboard"> Back to Dashboard </RouterLink>
    </div>
  </v-card>
</template>

<script>
export default {
  name: "InternalError",
};
</script>

<style lang="scss" scoped>
.internal-error-card {
  padding-bottom: 100px !important;

  .internal-error-content {
    .v-responsive {
      justify-content: center;
    }
    h4 {
      margin: {
        top: 30px;
        bottom: 12px;
      }
    }
    .btn {
      height: auto;
      min-width: auto;
      margin-top: 12px;
      border-radius: 7px;
      padding: 14px 25px;
      display: inline-block;
      color: var(--whiteColor);
      background-color: var(--primaryColor);
      font: {
        size: 16px;
        weight: 500;
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .internal-error-card {
    padding-bottom: 40px;

    .internal-error-content {
      h4 {
        margin-top: 25px;
      }
      .btn {
        padding: 12px 25px;
        font-size: 13px;
        margin-top: 2px;
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .internal-error-card {
    padding-bottom: 60px;

    .internal-error-content {
      .btn {
        font-size: 14px;
        margin-top: 7px;
      }
    }
  }
}

/* Min width 992px to Max width 1199px */
@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .internal-error-card {
    padding-bottom: 80px;

    .internal-error-content {
      .btn {
        font-size: 15px;
      }
    }
  }
}
</style>
