// laravel-vue/resources/components/Apps/KanbanBoard/index.vue
<template>
    <v-row>
        <v-col cols="12" lg="4">
            <v-card
                class="kanban-board-card trezo-card border-radius d-block bg-white border-0 shadow-none"
            >
                <div class="v-card-header">
                    <h5 class="mb-0">To Do</h5>
                    <v-menu>
                        <template v-slot:activator="{ props }">
                            <button
                                type="button"
                                v-bind="props"
                                class="position-relative dot-btn p-0 bg-transparent border-none"
                            >
                                <i class="ri-more-fill"></i>
                            </button>
                        </template>
                        <v-list class="menu-content">
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Select All
                            </button>
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Edit All
                            </button>
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Delete All
                            </button>
                        </v-list>
                    </v-menu>
                </div>
                <div class="board-card-content">
                    <div
                        v-for="item in toDo"
                        :key="item.id"
                        class="kanban-board-task"
                        :class="item.bgClass"
                    >
                        <div
                            class="title d-flex align-items-center justify-space-between"
                        >
                            <span class="d-block text-black fw-semibold">
                                {{ item.title }}
                            </span>
                            <button type="button">
                                <i class="material-symbols-outlined"> edit </i>
                            </button>
                        </div>
                        <p>
                            {{ item.description }}
                        </p>
                        <div
                            class="info d-flex align-items-center justify-space-between"
                        >
                            <div class="users d-flex align-items-center">
                                <v-img
                                    v-for="user in item.users"
                                    :key="user.id"
                                    :src="user.image"
                                    class="rounded-circle"
                                    alt="user-image"
                                />
                            </div>
                            <span class="days-left d-block text-secondary">
                                5 days left
                            </span>
                        </div>
                    </div>
                </div>
                <AddNewCard />
            </v-card>
        </v-col>
        <v-col cols="12" lg="4">
            <v-card
                class="kanban-board-card trezo-card border-radius d-block bg-white border-0 shadow-none"
            >
                <div class="v-card-header">
                    <h5 class="mb-0">Doing</h5>
                    <v-menu>
                        <template v-slot:activator="{ props }">
                            <button
                                type="button"
                                v-bind="props"
                                class="position-relative dot-btn p-0 bg-transparent border-none"
                            >
                                <i class="ri-more-fill"></i>
                            </button>
                        </template>
                        <v-list class="menu-content">
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Select All
                            </button>
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Edit All
                            </button>
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Delete All
                            </button>
                        </v-list>
                    </v-menu>
                </div>
                <div class="board-card-content">
                    <div
                        v-for="item in doing"
                        :key="item.id"
                        class="kanban-board-task"
                        :class="item.bgClass"
                    >
                        <div
                            class="title d-flex align-items-center justify-space-between"
                        >
                            <span class="d-block text-black fw-semibold">
                                {{ item.title }}
                            </span>
                            <button type="button">
                                <i class="material-symbols-outlined"> edit </i>
                            </button>
                        </div>
                        <p>
                            {{ item.description }}
                        </p>
                        <div
                            class="info d-flex align-items-center justify-space-between"
                        >
                            <div class="users d-flex align-items-center">
                                <v-img
                                    v-for="user in item.users"
                                    :key="user.id"
                                    :src="user.image"
                                    class="rounded-circle"
                                    alt="user-image"
                                />
                            </div>
                            <span class="days-left d-block text-danger">
                                5 days left
                            </span>
                        </div>
                    </div>
                </div>
                <AddNewCard />
            </v-card>
        </v-col>
        <v-col cols="12" lg="4">
            <v-card
                class="kanban-board-card trezo-card border-radius d-block bg-white border-0 shadow-none"
            >
                <div class="v-card-header">
                    <h5 class="mb-0">Done</h5>
                    <v-menu>
                        <template v-slot:activator="{ props }">
                            <button
                                type="button"
                                v-bind="props"
                                class="position-relative dot-btn p-0 bg-transparent border-none"
                            >
                                <i class="ri-more-fill"></i>
                            </button>
                        </template>
                        <v-list class="menu-content">
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Select All
                            </button>
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Edit All
                            </button>
                            <button
                                type="button"
                                class="bg-transparent border-none"
                            >
                                Delete All
                            </button>
                        </v-list>
                    </v-menu>
                </div>
                <div class="board-card-content">
                    <div
                        v-for="item in done"
                        :key="item.id"
                        class="kanban-board-task"
                        :class="item.bgClass"
                    >
                        <div
                            class="title d-flex align-items-center justify-space-between"
                        >
                            <span class="d-block text-black fw-semibold">
                                {{ item.title }}
                            </span>
                            <button type="button">
                                <i class="material-symbols-outlined"> edit </i>
                            </button>
                        </div>
                        <p>
                            {{ item.description }}
                        </p>
                        <div
                            class="info d-flex align-items-center justify-space-between"
                        >
                            <div class="users d-flex align-items-center">
                                <v-img
                                    v-for="user in item.users"
                                    :key="user.id"
                                    :src="user.image"
                                    class="rounded-circle"
                                    alt="user-image"
                                />
                            </div>
                            <span class="days-left d-block text-secondary">
                                5 days left
                            </span>
                        </div>
                    </div>
                </div>
                <AddNewCard />
            </v-card>
        </v-col>
    </v-row>
</template>

<script>
import { defineComponent } from "vue";
import AddNewCard from "./AddNewCard.vue";

import user6 from "../../../../public/images/users/user6.jpg";
import user7 from "../../../../public/images/users/user7.jpg";
import user8 from "../../../../public/images/users/user8.jpg";
import user9 from "../../../../public/images/users/user9.jpg";
import user10 from "../../../../public/images/users/user10.jpg";
import user11 from "../../../../public/images/users/user11.jpg";
import user12 from "../../../../public/images/users/user12.jpg";
import user13 from "../../../../public/images/users/user13.jpg";
import user14 from "../../../../public/images/users/user14.jpg";
import user15 from "../../../../public/images/users/user15.jpg";
import user16 from "../../../../public/images/users/user16.jpg";
import user17 from "../../../../public/images/users/user17.jpg";
import user18 from "../../../../public/images/users/user18.jpg";
import user19 from "../../../../public/images/users/user19.jpg";
import user20 from "../../../../public/images/users/user20.jpg";
import user21 from "../../../../public/images/users/user21.jpg";
import user22 from "../../../../public/images/users/user22.jpg";
import user23 from "../../../../public/images/users/user23.jpg";
import user24 from "../../../../public/images/users/user24.jpg";
import user25 from "../../../../public/images/users/user25.jpg";
import user26 from "../../../../public/images/users/user26.jpg";
import user27 from "../../../../public/images/users/user27.jpg";
import user28 from "../../../../public/images/users/user28.jpg";
import user29 from "../../../../public/images/users/user29.jpg";
import user30 from "../../../../public/images/users/user30.jpg";

export default defineComponent({
    name: "KanbanBoard",
    components: {
        AddNewCard,
    },
    data() {
        return {
            toDo: [
                {
                    id: 1,
                    title: `Project Requirements`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `5 days left`,
                    bgClass: `bg-purple-100`,
                    users: [
                        {
                            id: 1,
                            image: user6,
                        },
                        {
                            id: 2,
                            image: user7,
                        },
                        {
                            id: 3,
                            image: user8,
                        },
                    ],
                },
                {
                    id: 2,
                    title: `WordPress Theme`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `7 days left`,
                    bgClass: `bg-secondary-100`,
                    users: [
                        {
                            id: 1,
                            image: user9,
                        },
                        {
                            id: 2,
                            image: user10,
                        },
                    ],
                },
                {
                    id: 3,
                    title: `UX/UI Design`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `10 days left`,
                    bgClass: `bg-success-100`,
                    users: [
                        {
                            id: 1,
                            image: user11,
                        },
                        {
                            id: 2,
                            image: user12,
                        },
                        {
                            id: 3,
                            image: user13,
                        },
                    ],
                },
                {
                    id: 4,
                    title: `Project Analysis`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `14 days left`,
                    bgClass: `bg-orange-100`,
                    users: [
                        {
                            id: 1,
                            image: user14,
                        },
                        {
                            id: 2,
                            image: user15,
                        },
                    ],
                },
                {
                    id: 5,
                    title: `Competitor Research `,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `15 days left`,
                    bgClass: `bg-primary-100`,
                    users: [
                        {
                            id: 1,
                            image: user16,
                        },
                        {
                            id: 2,
                            image: user17,
                        },
                    ],
                },
            ],
            doing: [
                {
                    id: 1,
                    title: `React Template`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `3 days left`,
                    bgClass: `bg-orange-100`,
                    users: [
                        {
                            id: 1,
                            image: user18,
                        },
                        {
                            id: 2,
                            image: user19,
                        },
                    ],
                },
                {
                    id: 2,
                    title: `Laravel Project`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `5 days left`,
                    bgClass: `bg-purple-100`,
                    users: [
                        {
                            id: 1,
                            image: user20,
                        },
                        {
                            id: 2,
                            image: user21,
                        },
                        {
                            id: 3,
                            image: user22,
                        },
                    ],
                },
                {
                    id: 3,
                    title: `Project Requirements`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `7 days left`,
                    bgClass: `bg-danger-100`,
                    users: [
                        {
                            id: 1,
                            image: user23,
                        },
                    ],
                },
                {
                    id: 4,
                    title: `UX/UI Design`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `9 days left`,
                    bgClass: `bg-success-100`,
                    users: [
                        {
                            id: 1,
                            image: user24,
                        },
                        {
                            id: 2,
                            image: user25,
                        },
                    ],
                },
            ],
            done: [
                {
                    id: 1,
                    title: `Admin Template`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `3 days left`,
                    bgClass: `bg-primary-100`,
                    users: [
                        {
                            id: 1,
                            image: user26,
                        },
                        {
                            id: 2,
                            image: user27,
                        },
                        {
                            id: 3,
                            image: user28,
                        },
                    ],
                },
                {
                    id: 2,
                    title: `eCommerce Template`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `7 days left`,
                    bgClass: `bg-purple-100`,
                    users: [
                        {
                            id: 1,
                            image: user29,
                        },
                        {
                            id: 2,
                            image: user30,
                        },
                    ],
                },
                {
                    id: 3,
                    title: `Shopify Theme`,
                    description: `A brief description of the project, its objectives, and its importance to the organization.`,
                    daysLeft: `10 days left`,
                    bgClass: `bg-success-100`,
                    users: [
                        {
                            id: 1,
                            image: user11,
                        },
                        {
                            id: 2,
                            image: user12,
                        },
                        {
                            id: 3,
                            image: user13,
                        },
                    ],
                },
            ],
        };
    },
});
</script>

<style lang="scss" scoped>
.kanban-board-card {
    .v-card-header {
        margin-bottom: 22px;
    }
    .kanban-board-task {
        border: 0;
        overflow: hidden;
        border-radius: 5px;
        margin-bottom: 25px;
        padding: 25px !important;

        .title {
            margin-bottom: 15px;
            line-height: 0;
        }
        .info {
            margin-top: 20px;

            .users {
                .v-img {
                    width: 34px;
                    height: 34px;
                    margin-right: -10px;
                    border: 2px solid var(--whiteColor);

                    &:last-child {
                        margin-right: 0;
                    }
                }
            }
        }
    }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
    .kanban-board-card {
        .v-card-header {
            margin-bottom: 17px;
        }
    }
    .kanban-board-task {
        margin-bottom: 17px;
        padding: 17px !important;

        .title {
            margin-bottom: 12px;
        }
        .info {
            margin-top: 15px;

            .users {
                .v-img {
                    width: 32px;
                    height: 32px;
                }
            }
        }
    }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
    .kanban-board-card {
        .v-card-header {
            margin-bottom: 20px;
        }
        .kanban-board-task {
            margin-bottom: 20px;
            padding: 20px !important;
        }
    }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
}

/* Min width 992px to Max width 1199px */
@media only screen and (min-width: 992px) and (max-width: 1199px) {
}

/* Min width 1200px to Max width 1399px */
@media only screen and (min-width: 1200px) and (max-width: 1399px) {
}

/* Min width 1600px */
@media only screen and (min-width: 1600px) {
}
</style>

// angular-material/src/app/apps/kanban-board/kanban-board.component.ts
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatMenuModule } from '@angular/material/menu';
import { NgClass } from '@angular/common';
import { RouterLink } from '@angular/router';
import {
    CdkDragDrop,
    CdkDrag,
    CdkDropList,
    CdkDropListGroup,
    moveItemInArray,
    transferArrayItem,
} from '@angular/cdk/drag-drop';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { CustomizerSettingsService } from '../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-kanban-board',
    imports: [RouterLink, MatCardModule, MatButtonModule, MatMenuModule, CdkDropList, CdkDrag, CdkDropListGroup, NgClass, MatFormFieldModule, MatInputModule, MatSelectModule, MatDatepickerModule, MatNativeDateModule],
    templateUrl: './kanban-board.component.html',
    styleUrl: './kanban-board.component.scss'
})
export class KanbanBoardComponent {

    // To Do
    toDo : any = [
        {
            title: `Project Requirements`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `5 days left`,
            bgClass: `bg-purple-100`,
            users: [
                {
                    img: `images/users/user6.jpg`
                },
                {
                    img: `images/users/user7.jpg`
                },
                {
                    img: `images/users/user8.jpg`
                }
            ]
        },
        {
            title: `WordPress Theme`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `7 days left`,
            bgClass: `bg-secondary-100`,
            users: [
                {
                    img: `images/users/user9.jpg`
                },
                {
                    img: `images/users/user10.jpg`
                }
            ]
        },
        {
            title: `UX/UI Design`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `10 days left`,
            bgClass: `bg-success-100`,
            users: [
                {
                    img: `images/users/user11.jpg`
                },
                {
                    img: `images/users/user12.jpg`
                },
                {
                    img: `images/users/user13.jpg`
                }
            ]
        },
        {
            title: `Project Analysis`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `14 days left`,
            bgClass: `bg-orange-100`,
            users: [
                {
                    img: `images/users/user14.jpg`
                },
                {
                    img: `images/users/user15.jpg`
                }
            ]
        },
        {
            title: `Competitor Research `,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `15 days left`,
            bgClass: `bg-primary-100`,
            users: [
                {
                    img: `images/users/user16.jpg`
                },
                {
                    img: `images/users/user17.jpg`
                }
            ]
        }
    ];

    // Doing
    doing : any = [
        {
            title: `React Template`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `3 days left`,
            bgClass: `bg-orange-100`,
            users: [
                {
                    img: `images/users/user18.jpg`
                },
                {
                    img: `images/users/user19.jpg`
                }
            ]
        },
        {
            title: `Laravel Project`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `5 days left`,
            bgClass: `bg-purple-100`,
            users: [
                {
                    img: `images/users/user20.jpg`
                },
                {
                    img: `images/users/user21.jpg`
                },
                {
                    img: `images/users/user22.jpg`
                }
            ]
        },
        {
            title: `Project Requirements`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `7 days left`,
            bgClass: `bg-danger-100`,
            users: [
                {
                    img: `images/users/user23.jpg`
                }
            ]
        },
        {
            title: `UX/UI Design`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `9 days left`,
            bgClass: `bg-success-100`,
            users: [
                {
                    img: `images/users/user24.jpg`
                },
                {
                    img: `images/users/user25.jpg`
                }
            ]
        }
    ];

    // Done
    done : any = [
        {
            title: `Admin Template`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `3 days left`,
            bgClass: `bg-primary-100`,
            users: [
                {
                    img: `images/users/user26.jpg`
                },
                {
                    img: `images/users/user27.jpg`
                },
                {
                    img: `images/users/user28.jpg`
                }
            ]
        },
        {
            title: `eCommerce Template`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `7 days left`,
            bgClass: `bg-purple-100`,
            users: [
                {
                    img: `images/users/user29.jpg`
                },
                {
                    img: `images/users/user30.jpg`
                }
            ]
        },
        {
            title: `Shopify Theme`,
            description: `A brief description of the project, its objectives, and its importance to the organization.`,
            daysLeft: `10 days left`,
            bgClass: `bg-success-100`,
            users: [
                {
                    img: `images/users/user11.jpg`
                },
                {
                    img: `images/users/user12.jpg`
                },
                {
                    img: `images/users/user13.jpg`
                }
            ]
        }
    ];

    // Drag and Drop
    drop(event: CdkDragDrop<string[]>) {
        if (event.previousContainer === event.container) {
            moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
        } else {
            transferArrayItem(
                event.previousContainer.data,
                event.container.data,
                event.previousIndex,
                event.currentIndex,
            );
        }
    }

    // Popup Trigger
    classApplied = false;
    toggleClass() {
        this.classApplied = !this.classApplied;
    }

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<!-- Breadcrumb -->
<div class="breadcrumb-card mb-25 d-md-flex align-items-center justify-content-between">
    <h5 class="mb-0">
        Kanban Board
    </h5>
    <ol class="breadcrumb list-unstyled mt-0 mb-0 p-0">
        <li class="breadcrumb-item d-inline-block position-relative">
            <a routerLink="/dashboard" class="d-inline-block position-relative">
                <i class="material-symbols-outlined">
                    home
                </i>
                Dashboard
            </a>
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            Apps
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            Kanban Board
        </li>
    </ol>
</div>

<!-- Kanban Board -->
<div
    class="row"
    cdkDropListGroup
>
    <div class="col-sm-6 col-lg-4">
        <mat-card
            class="kanban-board-card mb-25 border-radius d-block bg-white border-0 shadow-none"
            [class.component-rtl-enabled]="themeService.isRTLEnabled()"
        >
            <mat-card-header>
                <mat-card-title>
                    <h5 class="mb-0">
                        To Do
                    </h5>
                </mat-card-title>
                <mat-card-subtitle>
                    <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                        <i class="ri-more-fill"></i>
                    </button>
                    <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                        <ul class="p-0 mt-0 mb-0 list-unstyled">
                            <li>
                                <button mat-menu-item>
                                    Select All
                                </button>
                            </li>
                            <li>
                                <button mat-menu-item>
                                    Edit All
                                </button>
                            </li>
                            <li>
                                <button mat-menu-item>
                                    Delete All
                                </button>
                            </li>
                        </ul>
                    </mat-menu>
                </mat-card-subtitle>
            </mat-card-header>
            <div
                cdkDropList
                [cdkDropListData]="toDo"
                (cdkDropListDropped)="drop($event)"
            >
                @for (item of toDo; track item) {
                    <mat-card-content
                        [class.component-rtl-enabled]="themeService.isRTLEnabled()"
                        [class.component-dark-theme]="themeService.isDark()"
                        class="kanban-board-task"
                        [ngClass]="item.bgClass"
                        cdkDrag
                    >
                        <div class="title d-flex align-items-center justify-content-between">
                            <span class="d-block text-black fw-semibold">
                                {{item.title}}
                            </span>
                            <button type="button" mat-button>
                                <i class="material-symbols-outlined">
                                    edit
                                </i>
                            </button>
                        </div>
                        <p>
                            {{item.description}}
                        </p>
                        <div class="info d-flex align-items-center justify-content-between">
                            <div class="users d-flex align-items-center">
                                @for (user of item.users; track user) {
                                    <img [src]="user.img" class="rounded-circle" alt="user-image">
                                }
                            </div>
                            <span class="days-left d-block text-secondary">
                                5 days left
                            </span>
                        </div>
                    </mat-card-content>
                }
            </div>
            <button class="add-new-card-btn" type="button" mat-button (click)="toggleClass()">
                <i class="material-symbols-outlined">
                    add
                </i>
                Add New Card
            </button>
        </mat-card>
    </div>
    <div class="col-sm-6 col-lg-4">
        <mat-card
            class="kanban-board-card mb-25 border-radius d-block bg-white border-0 shadow-none"
            [class.component-rtl-enabled]="themeService.isRTLEnabled()"
        >
            <mat-card-header>
                <mat-card-title>
                    <h5 class="mb-0">
                        Doing
                    </h5>
                </mat-card-title>
                <mat-card-subtitle>
                    <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                        <i class="ri-more-fill"></i>
                    </button>
                    <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                        <ul class="p-0 mt-0 mb-0 list-unstyled">
                            <li>
                                <button mat-menu-item>
                                    Select All
                                </button>
                            </li>
                            <li>
                                <button mat-menu-item>
                                    Edit All
                                </button>
                            </li>
                            <li>
                                <button mat-menu-item>
                                    Delete All
                                </button>
                            </li>
                        </ul>
                    </mat-menu>
                </mat-card-subtitle>
            </mat-card-header>
            <div
                cdkDropList
                [cdkDropListData]="doing"
                (cdkDropListDropped)="drop($event)"
            >
                @for (item of doing; track item) {
                    <mat-card-content
                        [class.component-rtl-enabled]="themeService.isRTLEnabled()"
                        [class.component-dark-theme]="themeService.isDark()"
                        class="kanban-board-task"
                        [ngClass]="item.bgClass"
                        cdkDrag
                    >
                        <div class="title d-flex align-items-center justify-content-between">
                            <span class="d-block text-black fw-semibold">
                                {{item.title}}
                            </span>
                            <button type="button" mat-button>
                                <i class="material-symbols-outlined">
                                    edit
                                </i>
                            </button>
                        </div>
                        <p>
                            {{item.description}}
                        </p>
                        <div class="info d-flex align-items-center justify-content-between">
                            <div class="users d-flex align-items-center">
                                @for (user of item.users; track user) {
                                    <img [src]="user.img" class="rounded-circle" alt="user-image">
                                }
                            </div>
                            <span class="days-left d-block text-danger">
                                5 days left
                            </span>
                        </div>
                    </mat-card-content>
                }
            </div>
            <button class="add-new-card-btn" type="button" mat-button (click)="toggleClass()">
                <i class="material-symbols-outlined">
                    add
                </i>
                Add New Card
            </button>
        </mat-card>
    </div>
    <div class="col-sm-6 col-lg-4">
        <mat-card
            class="kanban-board-card mb-25 border-radius d-block bg-white border-0 shadow-none"
            [class.component-rtl-enabled]="themeService.isRTLEnabled()"
        >
            <mat-card-header>
                <mat-card-title>
                    <h5 class="mb-0">
                        Done
                    </h5>
                </mat-card-title>
                <mat-card-subtitle>
                    <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                        <i class="ri-more-fill"></i>
                    </button>
                    <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                        <ul class="p-0 mt-0 mb-0 list-unstyled">
                            <li>
                                <button mat-menu-item>
                                    Select All
                                </button>
                            </li>
                            <li>
                                <button mat-menu-item>
                                    Edit All
                                </button>
                            </li>
                            <li>
                                <button mat-menu-item>
                                    Delete All
                                </button>
                            </li>
                        </ul>
                    </mat-menu>
                </mat-card-subtitle>
            </mat-card-header>
            <div
                cdkDropList
                [cdkDropListData]="done"
                (cdkDropListDropped)="drop($event)"
            >
                @for (item of done; track item) {
                    <mat-card-content
                        [class.component-rtl-enabled]="themeService.isRTLEnabled()"
                        [class.component-dark-theme]="themeService.isDark()"
                        class="kanban-board-task"
                        [ngClass]="item.bgClass"
                        cdkDrag
                    >
                        <div class="title d-flex align-items-center justify-content-between">
                            <span class="d-block text-black fw-semibold">
                                {{item.title}}
                            </span>
                            <button type="button" mat-button>
                                <i class="material-symbols-outlined">
                                    edit
                                </i>
                            </button>
                        </div>
                        <p>
                            {{item.description}}
                        </p>
                        <div class="info d-flex align-items-center justify-content-between">
                            <div class="users d-flex align-items-center">
                                @for (user of item.users; track user) {
                                    <img [src]="user.img" class="rounded-circle" alt="user-image">
                                }
                            </div>
                            <span class="days-left d-block text-primary">
                                5 days left
                            </span>
                        </div>
                    </mat-card-content>
                }
            </div>
            <button class="add-new-card-btn" type="button" mat-button (click)="toggleClass()">
                <i class="material-symbols-outlined">
                    add
                </i>
                Add New Card
            </button>
        </mat-card>
    </div>
</div>

<!-- Add New Popup -->
<div
    class="add-new-popup"
    [class.active]="classApplied"
>
    <div class="popup-dialog">
        <mat-card class="border-radius d-block bg-white border-0 shadow-none">
            <mat-card-header>
                <mat-card-title>
                    <h5 class="mb-0">
                        Add New Card
                    </h5>
                </mat-card-title>
                <mat-card-subtitle>
                    <button
                        mat-button
                        (click)="toggleClass()"
                    >
                        <i class="ri-close-fill"></i>
                    </button>
                </mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Card Name
                            </label>
                            <mat-form-field>
                                <mat-label>
                                    Title
                                </mat-label>
                                <input matInput placeholder="E.g. Trezo Dashboard">
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Card Description
                            </label>
                            <mat-form-field>
                                <mat-label>Type here....</mat-label>
                                <textarea matInput></textarea>
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Team Members
                            </label>
                            <mat-form-field>
                                <mat-label>
                                    Select
                                </mat-label>
                                <mat-select multiple>
                                    <mat-option value="one">
                                        Sarah Johnson
                                    </mat-option>
                                    <mat-option value="two">
                                        Michael Smith
                                    </mat-option>
                                    <mat-option value="three">
                                        Emily Brown
                                    </mat-option>
                                    <mat-option value="four">
                                        Jason Lee
                                    </mat-option>
                                    <mat-option value="five">
                                        Ashley Davis
                                    </mat-option>
                                    <mat-option value="six">
                                        Mark Thompson
                                    </mat-option>
                                </mat-select>
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Deadline Date
                            </label>
                            <mat-form-field>
                                <mat-label>Choose a date</mat-label>
                                <input matInput [matDatepicker]="deadlineDatePicker">
                                <!-- <mat-hint>MM/DD/YYYY</mat-hint> -->
                                <mat-datepicker-toggle matIconSuffix [for]="deadlineDatePicker"></mat-datepicker-toggle>
                                <mat-datepicker #deadlineDatePicker></mat-datepicker>
                            </mat-form-field>
                        </div>
                    </div>
                </div>
                <div class="btn-box">
                    <button
                        mat-button
                        (click)="toggleClass()"
                        color="warn"
                    >
                        Cancel
                    </button>
                    <button
                        mat-button
                        color="primary"
                    >
                        <i class="material-symbols-outlined">
                            add
                        </i>
                        Create
                    </button>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
</div>
