// vuejs-tailwindcss/src/components/Others/MyProfile/TotalProjects.vue
<template>
  <div
    class="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md"
  >
    <div class="trezo-card-content">
      <span class="block"> Total Projects </span>
      <h5 class="text-[20px] mt-[3px] mb-0">22.5k+</h5>
      <div
        class="flex items-center justify-center mx-auto text-secondary-500 bg-secondary-100 dark:bg-[#15203c] w-[77px] h-[77px] my-[15px] rounded-full"
      >
        <i class="material-symbols-outlined !text-[32px]"> auto_stories </i>
      </div>
      <div class="flex items-center justify-between text-sm">
        <span class="block"> This Month </span>
        <span class="leading-none text-success-600">
          <i class="material-symbols-outlined !text-[20px]"> trending_up </i>
        </span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TotalProjects",
});
</script>

// react-nextjs-tailwindcss/src/components/Dashboard/ProjectManagement/ProjectsOverview/TotalProjects.tsx
"use client";

import React from "react";

const TotalProjects: React.FC = () => {
  return (
    <>
      <div className="bg-primary-50 dark:bg-[#15203c] rounded-md py-[22px] px-[20px]">
        <div className="flex items-center">
          <div className="text-primary-500 leading-none ltr:mr-[10px] rtl:ml-[10px]">
            <i className="material-symbols-outlined !text-5xl">folder_open</i>
          </div>
          <div>
            <span className="block">Total Projects</span>
            <h5 className="mb-0 text-[20px] mt-[2px]">1235</h5>
          </div>
        </div>
        <div className="mt-[15px] sm:mt-[25px] flex items-center justify-between">
          <span className="block text-sm">Projects this month</span>
          <span className="inline-block text-sm text-success-700 py-[1px] px-[8.3px] border border-success-300 bg-success-100 rounded-xl">
            +10%
          </span>
        </div>
      </div>
    </>
  );
};

export default TotalProjects;
