// laravel-vue/resources/components/Dashboard/Crypto/CryptoRankings.vue
<template>
    <v-card
        class="crypto-rankings-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Crypto Rankings</h5>
            <v-menu>
                <template v-slot:activator="{ props }">
                    <button
                        type="button"
                        v-bind="props"
                        class="card-header-menu border-none d-inline-block border-radius"
                    >
                        Oct 01 - Oct 31, 2024
                    </button>
                </template>
                <v-list class="menu-content">
                    <button type="button" class="bg-transparent border-none">
                        Sep 01 - Sep 30, 2024
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        Aug 01 - Aug 31, 2024
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        Jul 01 - Jul 31, 2024
                    </button>
                </v-list>
            </v-menu>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Cryptocurrency</th>
                            <th>Market Cap</th>
                            <th>Price</th>
                            <th>24h Change %</th>
                            <th>7d Change %</th>
                            <th>Value 24h</th>
                            <th>Circulating Supply</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in items.slice(0, 6)" :key="item.rank">
                            <td class="text-body">
                                {{ item.rank }}
                            </td>
                            <td>
                                <div
                                    class="customer-info d-flex align-items-center"
                                >
                                    <div class="img">
                                        <v-img
                                            :src="item.cryptocurrency.image"
                                            alt="cryptocurrency-image"
                                        />
                                    </div>
                                    <span class="d-block fw-medium">
                                        {{ item.cryptocurrency.name }}
                                        <span class="text-body fw-normal">
                                            ({{
                                                item.cryptocurrency
                                                    .abbreviation
                                            }})
                                        </span>
                                    </span>
                                </div>
                            </td>
                            <td class="fw-medium">
                                {{ item.market_cap }}
                            </td>
                            <td class="fw-medium">
                                {{ item.price }}
                            </td>
                            <td class="fw-medium">
                                <span
                                    class="change_24h up"
                                    v-if="item.change_24h.up"
                                >
                                    {{ item.change_24h.number }}
                                </span>
                                <span
                                    class="change_24h down"
                                    v-if="item.change_24h.down"
                                >
                                    {{ item.change_24h.number }}
                                </span>
                            </td>
                            <td class="fw-medium">
                                <span
                                    class="change_7d up"
                                    v-if="item.change_7d.up"
                                >
                                    {{ item.change_7d.number }}
                                </span>
                                <span
                                    class="change_7d down"
                                    v-if="item.change_7d.down"
                                >
                                    {{ item.change_7d.number }}
                                </span>
                            </td>
                            <td class="fw-medium">
                                {{ item.value_24h }}
                            </td>
                            <td class="fw-medium">
                                {{ item.circulating_supply }}
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
            <PaginationTwo items="6" />
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";
import PaginationTwo from "../../Common/PaginationTwo.vue";

import bitcoin from "../../../../public/images/cryptocurrencies/bitcoin.svg";
import ethereum from "../../../../public/images/cryptocurrencies/ethereum.svg";
import binance from "../../../../public/images/cryptocurrencies/binance.svg";
import tether from "../../../../public/images/cryptocurrencies/tether.svg";
import xrp from "../../../../public/images/cryptocurrencies/xrp.svg";
import solana from "../../../../public/images/cryptocurrencies/solana.svg";
import usdc from "../../../../public/images/cryptocurrencies/usdc.png";
import dogecoin from "../../../../public/images/cryptocurrencies/dogecoin.png";
import toncoin from "../../../../public/images/cryptocurrencies/toncoin.png";
import cardano from "../../../../public/images/cryptocurrencies/cardano.png";
import tron from "../../../../public/images/cryptocurrencies/tron.png";
import avalanche from "../../../../public/images/cryptocurrencies/avalanche.png";

export default defineComponent({
    name: "CryptoRankings",
    components: {
        PaginationTwo,
    },
    data() {
        return {
            items: [
                {
                    rank: 1,
                    cryptocurrency: {
                        image: bitcoin,
                        name: "Bitcoin",
                        abbreviation: "BTC",
                    },
                    market_cap: "$520B",
                    price: "$27,500",
                    change_24h: {
                        number: "+2.3%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+10.2%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$35B",
                    circulating_supply: "19M BTC",
                },
                {
                    rank: 2,
                    cryptocurrency: {
                        image: ethereum,
                        name: "Ethereum",
                        abbreviation: "ETH",
                    },
                    market_cap: "$210B",
                    price: "$1,750",
                    change_24h: {
                        number: "-1.2%",
                        up: false,
                        down: true,
                    },
                    change_7d: {
                        number: "+6.3%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$20B",
                    circulating_supply: "120M ETH",
                },
                {
                    rank: 3,
                    cryptocurrency: {
                        image: binance,
                        name: "Binance",
                        abbreviation: "BNB",
                    },
                    market_cap: "$40B",
                    price: "$250",
                    change_24h: {
                        number: "+1.5%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+7.8%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$1.8B",
                    circulating_supply: "160M BNB",
                },
                {
                    rank: 4,
                    cryptocurrency: {
                        image: tether,
                        name: "Tether",
                        abbreviation: "USDT",
                    },
                    market_cap: "$83B",
                    price: "$1.00",
                    change_24h: {
                        number: "+0.01%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+0.02%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$45B",
                    circulating_supply: "83B USDT",
                },
                {
                    rank: 5,
                    cryptocurrency: {
                        image: xrp,
                        name: "XRP",
                        abbreviation: "XRP",
                    },
                    market_cap: "$25B",
                    price: "$0.50",
                    change_24h: {
                        number: "+0.9%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "-8.6%",
                        up: false,
                        down: true,
                    },
                    value_24h: "$2.2B",
                    circulating_supply: "50B XRP",
                },
                {
                    rank: 6,
                    cryptocurrency: {
                        image: solana,
                        name: "Solana",
                        abbreviation: "SOL",
                    },
                    market_cap: "$12B",
                    price: "$35",
                    change_24h: {
                        number: "+5.8%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+15.5%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$3.5B",
                    circulating_supply: "400M SOL",
                },
                {
                    rank: 7,
                    cryptocurrency: {
                        image: usdc,
                        name: "USDC",
                        abbreviation: "USDC",
                    },
                    market_cap: "$36B",
                    price: "$0.9999",
                    change_24h: {
                        number: "+0.01%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+0.02%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$4B",
                    circulating_supply: "36 USDC",
                },
                {
                    rank: 8,
                    cryptocurrency: {
                        image: dogecoin,
                        name: "Dogecoin",
                        abbreviation: "DOGE",
                    },
                    market_cap: "$17B",
                    price: "$0,1221",
                    change_24h: {
                        number: "-0.56%",
                        up: false,
                        down: true,
                    },
                    change_7d: {
                        number: "-3.57%",
                        up: false,
                        down: true,
                    },
                    value_24h: "$85B",
                    circulating_supply: "146M DOGE",
                },
                {
                    rank: 9,
                    cryptocurrency: {
                        image: toncoin,
                        name: "Toncoin",
                        abbreviation: "TON",
                    },
                    market_cap: "$14B",
                    price: "$5.82",
                    change_24h: {
                        number: "+0.13%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+0.88%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$21B",
                    circulating_supply: "25M TON",
                },
                {
                    rank: 10,
                    cryptocurrency: {
                        image: cardano,
                        name: "Cardano",
                        abbreviation: "ADA",
                    },
                    market_cap: "$13B",
                    price: "$0,3884",
                    change_24h: {
                        number: "-0.59%",
                        up: false,
                        down: true,
                    },
                    change_7d: {
                        number: "-1.80%",
                        up: false,
                        down: true,
                    },
                    value_24h: "$32B",
                    circulating_supply: "86M ADA",
                },
                {
                    rank: 11,
                    cryptocurrency: {
                        image: tron,
                        name: "TRON",
                        abbreviation: "TRX",
                    },
                    market_cap: "$130B",
                    price: "$0.1554",
                    change_24h: {
                        number: "+0.17%",
                        up: true,
                        down: false,
                    },
                    change_7d: {
                        number: "+0.02%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$33B",
                    circulating_supply: "86M TRX",
                },
                {
                    rank: 12,
                    cryptocurrency: {
                        image: avalanche,
                        name: "Avalanche",
                        abbreviation: "AVAX",
                    },
                    market_cap: "$11B",
                    price: "$28.77",
                    change_24h: {
                        number: "-0.08%",
                        up: false,
                        down: true,
                    },
                    change_7d: {
                        number: "+0.51%",
                        up: true,
                        down: false,
                    },
                    value_24h: "$32B",
                    circulating_supply: "40M AVAX",
                },
            ],
        };
    },
});
</script>

<style lang="scss" scoped>
.crypto-rankings-card {
    .trezo-table-content {
        .trezo-table {
            background: transparent !important;
            table {
                thead {
                    tr {
                        background-color: transparent !important;
                        th {
                            font-size: 12px;
                            text-align: end !important;
                            color: var(--bodyColor);
                            background-color: transparent !important;
                            padding: {
                                top: 0 !important;
                                bottom: 7px !important;
                            }
                            &:first-child {
                                text-align: start !important;
                                padding: {
                                    left: 0 !important;
                                    right: 0 !important;
                                }
                            }
                            &:nth-child(2) {
                                padding-left: 10px !important;
                                text-align: start !important;
                            }
                            &:last-child {
                                padding-right: 0 !important;
                            }
                        }
                    }
                }
                tbody {
                    tr {
                        td {
                            text-align: end !important;
                            border: {
                                left-width: 0 !important;
                                right-width: 0 !important;
                            }
                            padding: {
                                top: 10px !important;
                                bottom: 10px !important;
                            }
                            .customer-info {
                                .img {
                                    width: 22px;
                                    border-radius: 0;

                                    img {
                                        border-radius: 0;
                                        margin-bottom: -3px;
                                    }
                                }
                                span {
                                    margin-left: 8px;

                                    span {
                                        font-size: 12px;
                                        margin-left: 0;
                                    }
                                }
                            }
                            &:first-child {
                                text-align: start !important;
                                padding: {
                                    left: 0 !important;
                                    right: 0 !important;
                                }
                            }
                            &:nth-child(2) {
                                padding-left: 10px !important;
                                text-align: start !important;
                            }
                            &:last-child {
                                padding-right: 0 !important;
                            }
                        }
                    }
                }
            }
        }
    }
    &.component-rtl-enabled {
        .mat-mdc-card-content {
            .mat-mdc-table {
                &.mdc-data-table__table {
                    .mat-mdc-header-row {
                        .mat-mdc-header-cell {
                            &:first-child {
                                padding: {
                                    left: 20px;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                padding: {
                                    right: 20px;
                                    left: 0;
                                }
                            }
                        }
                    }
                    .mdc-data-table__content {
                        .mat-mdc-row {
                            .mat-mdc-cell {
                                .customer-info {
                                    span {
                                        margin: {
                                            left: 0;
                                            right: 8px;
                                        }
                                        span {
                                            margin-right: 0;
                                        }
                                    }
                                }
                                &:first-child {
                                    padding: {
                                        left: 20px;
                                        right: 0;
                                    }
                                }
                                &:last-child {
                                    padding: {
                                        right: 20px;
                                        left: 0;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
    .crypto-rankings-card {
        .v-card-header {
            display: block;
            h5 {
                margin-bottom: 5px;
            }
        }
        &.component-rtl-enabled {
            .mat-mdc-card-content {
                .mat-mdc-table {
                    &.mdc-data-table__table {
                        .mat-mdc-header-row {
                            .mat-mdc-header-cell {
                                &:first-child {
                                    padding: {
                                        left: 17px;
                                    }
                                }
                                &:last-child {
                                    padding: {
                                        right: 17px;
                                    }
                                }
                            }
                        }
                        .mdc-data-table__content {
                            .mat-mdc-row {
                                .mat-mdc-cell {
                                    &:first-child {
                                        padding: {
                                            left: 17px;
                                        }
                                    }
                                    &:last-child {
                                        padding: {
                                            right: 17px;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
    .crypto-rankings-card {
        .v-card-header {
            display: flex;
            h5 {
                margin-bottom: 0;
            }
        }
        &.component-rtl-enabled {
            .mat-mdc-card-content {
                .mat-mdc-table {
                    &.mdc-data-table__table {
                        .mat-mdc-header-row {
                            .mat-mdc-header-cell {
                                &:first-child {
                                    padding: {
                                        left: 1720pxpx;
                                    }
                                }
                                &:last-child {
                                    padding: {
                                        right: 20px;
                                    }
                                }
                            }
                        }
                        .mdc-data-table__content {
                            .mat-mdc-row {
                                .mat-mdc-cell {
                                    &:first-child {
                                        padding: {
                                            left: 20px;
                                        }
                                    }
                                    &:last-child {
                                        padding: {
                                            right: 20px;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
</style>

// react-material-ui/src/components/Dashboard/Crypto/CryptoRankings/index.js
"use client";

import React, { useState } from "react";
import {
  Card,
  Box,
  Typography,
  Menu,
  MenuItem,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableFooter,
  TablePagination,
  TableRow,
  Paper,
  IconButton,
  TableHead,
} from "@mui/material";
import { useTheme } from "@mui/material/styles";
import KeyboardArrowLeft from "@mui/icons-material/KeyboardArrowLeft";
import KeyboardArrowRight from "@mui/icons-material/KeyboardArrowRight";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import styles from "./CryptoRankings.module.css";

function TablePaginationActions({ count, page, rowsPerPage, onPageChange }) {
  const theme = useTheme();

  const handleBackButtonClick = (event) => {
    onPageChange(event, page - 1);
  };

  const handleNextButtonClick = (event) => {
    onPageChange(event, page + 1);
  };

  return (
    <Box
      sx={{
        flexShrink: 0,
        display: "flex",
        gap: "10px", 
      }}
      className="ml-15"
    >
      <IconButton
        onClick={handleBackButtonClick}
        disabled={page === 0}
        aria-label="previous page"
        sx={{
          borderRadius: "4px",
          padding: "4px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowRight />
        ) : (
          <KeyboardArrowLeft />
        )}
      </IconButton>

      <IconButton
        onClick={handleNextButtonClick}
        disabled={page >= Math.ceil(count / rowsPerPage) - 1}
        aria-label="next page"
        sx={{
          borderRadius: "4px",
          padding: "4px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowLeft />
        ) : (
          <KeyboardArrowRight />
        )}
      </IconButton>
    </Box>
  );
}

function createData(
  id,
  cryptocurrencyImg,
  cryptocurrencyName,
  cryptocurrencyAbbreviation,
  marketCap,
  price,
  change24h,
  change7d,
  value24h,
  circulatingSupply
) {
  return {
    id,
    cryptocurrencyImg,
    cryptocurrencyName,
    cryptocurrencyAbbreviation,
    marketCap,
    price,
    change24h,
    change7d,
    value24h,
    circulatingSupply,
  };
}

const rows = [
  createData(
    "1",
    "/images/cryptocurrencies/bitcoin.svg",
    "Bitcoin",
    "BTC",
    "$520B",
    "$27,500",
    "+2.3%",
    "+10.2%",
    "$35B",
    "19M BT"
  ),

  createData(
    "2",
    "/images/cryptocurrencies/ethereum.svg",
    "Ethereum",
    "ETH",
    "$210B",
    "$1,750",
    "-1.2%",
    "+6.3%",
    "$20B",
    "120M ETH"
  ),
  createData(
    "3",
    "/images/cryptocurrencies/binance.svg",
    "Binance",
    "BNB",
    "$40B",
    "$250",
    "+1.5%",
    "+7.8%",
    "$1.8B",
    "160M BNB"
  ),
  createData(
    "4",
    "/images/cryptocurrencies/tether.svg",
    "Tether",
    "USDT",
    "$83B",
    "$1.00",
    "+0.01%",
    "+0.02%",
    "$45B",
    "83B USDT"
  ),
  createData(
    "5",
    "/images/cryptocurrencies/xrp.svg",
    "XRP",
    "XRP",
    "$25B",
    "$0.50",
    "+0.9%",
    "-8.6%",
    "$2.2B",
    "50B XRP"
  ),
  createData(
    "6",
    "/images/cryptocurrencies/solana.svg",
    "Solana",
    "SOL",
    "$12B",
    "$35",
    "+5.8%",
    "+15.5%",
    "$3.5B",
    "400M SOL"
  ),
  createData(
    "7",
    "/images/cryptocurrencies/usdc.png",
    "USDC",
    "USDC",
    "$36B",
    "$0.9999",
    "+0.01%",
    "+0.02%",
    "$4B",
    "36 USDC"
  ),
  createData(
    "8",
    "/images/cryptocurrencies/dogecoin.png",
    "Dogecoin",
    "DOGE",
    "$17B",
    "$0,1221",
    "-0.56%",
    "-3.57%",
    "$85B",
    "146M DOGE"
  ),
  createData(
    "9",
    "/images/cryptocurrencies/toncoin.png",
    "Toncoin",
    "TON",
    "$14B",
    "$5.82",
    "+0.13%",
    "+0.88%",
    "$21B",
    "25M TON"
  ),
  createData(
    "10",
    "/images/cryptocurrencies/cardano.png",
    "Cardano",
    "ADA",
    "$13B",
    "$0,3884",
    "-0.59%",
    "-1.80%",
    "$32B",
    "86M ADA"
  ),
  createData(
    "11",
    "/images/cryptocurrencies/tron.png",
    "TRON",
    "TRX",
    "$130B",
    "$0.1554",
    "+0.17%",
    "+0.02%",
    "$33B",
    "86M TRX"
  ),
  createData(
    "12",
    "/images/cryptocurrencies/avalanche.png",
    "Avalanche",
    "AVAX",
    "$11B",
    "$28.77",
    "-0.08%",
    "+0.51%",
    "$32B",
    "40M AVAX"
  ),
].sort((a, b) => (a.id < b.id ? 1 : 1));

const CryptoRankings = () => {
  const [anchorEl, setAnchorEl] = useState(null);
  const open = Boolean(anchorEl);
  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };
  const handleClose = () => {
    setAnchorEl(null);
  };

  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(6);
  const emptyRows =
    page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: "25px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Crypto Rankings
          </Typography>

          <Box>
            <IconButton
              onClick={handleClick}
              size="small"
              aria-controls={open ? "account-menu" : undefined}
              aria-haspopup="true"
              aria-expanded={open ? "true" : undefined}
              sx={{
                borderRadius: "0px",
                padding: "1px 2px",
                fontSize: "14px",
              }}
            >
              Oct 01 - Oct 31, 2024{" "}
              <KeyboardArrowDownIcon sx={{ fontSize: "20px" }} />
            </IconButton>

            <Menu
              anchorEl={anchorEl}
              id="account-menu"
              open={open}
              onClose={handleClose}
              onClick={handleClose}
              PaperProps={{
                elevation: 0,

                sx: {
                  overflow: "visible",
                  boxShadow: "0 4px 45px #0000001a",
                  mt: 0,
                  "& .MuiAvatar-root": {
                    width: 32,
                    height: 32,
                    ml: -0.5,
                    mr: 1,
                  },
                },
              }}
              transformOrigin={{ horizontal: "right", vertical: "top" }}
              anchorOrigin={{ horizontal: "right", vertical: "bottom" }}
            >
              <MenuItem>Sep 01 - Sep 30, 2024</MenuItem>
              <MenuItem>Aug 01 - Aug 31, 2024</MenuItem>
              <MenuItem>Jul 01 - Jul 31, 2024</MenuItem>
            </Menu>
          </Box>
        </Box>

        {/* Table */}
        <TableContainer
          component={Paper}
          sx={{
            boxShadow: "none",
            borderRadius: "0",
          }}
          className="rmui-table"
        >
          <Table sx={{ minWidth: 850 }} className={styles.crTable}>
            <TableHead>
              <TableRow>
                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                  }}
                  className="border-bottom"
                >
                  Rank
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                  }}
                  className="border-bottom"
                >
                  Cryptocurrency
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                  }}
                  className="border-bottom"
                >
                  Market Cap
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                  }}
                  className="border-bottom"
                >
                  Price
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                  }}
                  className="border-bottom"
                >
                  24h Change %
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                  }}
                  className="border-bottom"
                >
                  7d Change %
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                  }}
                  className="border-bottom"
                >
                  Value 24h
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                  }}
                  className="border-bottom"
                >
                  Circulating Supply
                </TableCell>
              </TableRow>
            </TableHead>

            <TableBody>
              {(rowsPerPage > 0
                ? rows.slice(
                    page * rowsPerPage,
                    page * rowsPerPage + rowsPerPage
                  )
                : rows
              ).map((row) => (
                <TableRow key={row.id}>
                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.id}
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                    }}
                    className="text-black border-bottom"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: "10px",
                      }}
                    >
                      <img
                        src={row.cryptocurrencyImg}
                        alt="Product"
                        width={22}
                        height={22}
                        style={{ borderRadius: "100px" }}
                      />

                      <Typography
                        sx={{
                          fontWeight: "500",
                        }}
                      >
                        {row.cryptocurrencyName}{" "}
                        <Typography
                          component="span"
                          sx={{ fontWeight: "400", fontSize: "12px" }}
                          className="text-body"
                        >
                          {row.cryptocurrencyAbbreviation}
                        </Typography>
                      </Typography>
                    </Box>
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.marketCap}
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.price}
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.change24h}
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.change7d}
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.value24h}
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                    }}
                    className="text-black border-bottom"
                  >
                    {row.circulatingSupply}
                  </TableCell>
                </TableRow>
              ))}
              {emptyRows > 0 && (
                <TableRow style={{ height: 53 * emptyRows }}>
                  <TableCell className="border-bottom" colSpan={8} />
                </TableRow>
              )}
            </TableBody>

            <TableFooter>
              <TableRow>
                <TablePagination
                  rowsPerPageOptions={[5, 10, 25, { label: "All", value: -1 }]}
                  colSpan={8}
                  count={rows.length}
                  rowsPerPage={rowsPerPage}
                  page={page}
                  slotProps={{
                    select: {
                      inputProps: {
                        "aria-label": "rows per page",
                      },
                      native: true,
                    },
                  }}
                  onPageChange={handleChangePage}
                  onRowsPerPageChange={handleChangeRowsPerPage}
                  ActionsComponent={TablePaginationActions}
                  sx={{
                    border: "none",
                    ".MuiToolbar-root": {
                      minHeight: "auto",
                      marginTop: "15px",
                    },
                  }}
                />
              </TableRow>
            </TableFooter>
          </Table>
        </TableContainer>
      </Card>
    </>
  );
};

export default CryptoRankings;
