// nuxtjs-bootstrap/components/Pages/Ecommerce/OrderDetails/ShippingDetails.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-4">
      <h3 class="mb-3">Shipping Details</h3>
      <div class="d-flex align-items-center mb-2">
        <span class="text-secondary">Shipping Date:</span>
        <span class="ms-1">25 Nov 2024 10:30 AM</span>
      </div>
      <div class="d-flex align-items-center mb-2">
        <span class="text-secondary">Email:</span>
        <span class="ms-1">example@trezo.com</span>
      </div>
      <div class="d-flex align-items-center mb-2">
        <span class="text-secondary">Phone:</span>
        <span class="ms-1">+1 444 333 5566</span>
      </div>
      <div class="d-flex mb-0">
        <span class="text-secondary">Address:</span>
        <span class="ms-1">789 Pine St, Villageton, England</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ShippingDetails",
});
</script>

// react-nextjs-material-ui/src/components/eCommerce/OrderDetails/ShippingDetails.tsx
"use client";

import React from "react";
import { Card, Box, Typography } from "@mui/material";

const ShippingDetails: React.FC = () => {
  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "20px",
          }}
          className="text-black"
        >
          Shipping Details
        </Typography>

        <Box>
          <Box mt="8px">
            <span className="text-black">Shipping Date:</span> 25 Nov 2024 10:30
            AM
          </Box>

          <Box mt="8px">
            <span className="text-black">Email:</span> example@trezo.com
          </Box>

          <Box mt="8px">
            <span className="text-black">Phone:</span> +1 444 333 5566
          </Box>

          <Box mt="8px">
            <span className="text-black">Address:</span> 789 Pine St,
            Villageton, England
          </Box>
        </Box>
      </Card>
    </>
  );
};

export default ShippingDetails;
