// react-nextjs-tailwindcss/src/components/Dashboard/Marketing/Highlights.tsx
"use client";

import React from "react";
import Image from "next/image";

interface HighlightData {
  icon: string;
  title: string;
  value: string;
  trend: "up" | "down";
  trendIcon: string;
  trendColor: string;
}

const highlightData: HighlightData[] = [
  {
    icon: "/images/icons/star.svg",
    title: "Average Client Rating",
    value: "4.9/5.0",
    trend: "up",
    trendIcon: "arrow_upward",
    trendColor: "text-success-600",
  },
  {
    icon: "/images/icons/instagram.svg",
    title: "Instagram Followers",
    value: "630K",
    trend: "down",
    trendIcon: "arrow_downward",
    trendColor: "text-orange-600",
  },
  {
    icon: "/images/icons/google2.svg",
    title: "Google Ads CPC",
    value: "$3.58",
    trend: "up",
    trendIcon: "arrow_upward",
    trendColor: "text-success-600",
  },
];

const Highlights: React.FC = () => {
  return (
    <>
      <div className="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
        <div className="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
          <div className="trezo-card-title">
            <h5 className="mb-0">Highlights</h5>
          </div>
          <div className="trezo-card-subtitle">
            <span className="block">Last 7 days</span>
          </div>
        </div>

        <div className="trezo-card-content">
          <ul>
            {highlightData.map((highlight, index) => (
              <li
                key={index}
                className="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[14px] mb-[14px] last:border-none last:mb-0 last:pb-0"
              >
                <div className="relative ltr:pl-[23px] rtl:pr-[23px]">
                  <Image
                    src={highlight.icon}
                    className="absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2"
                    alt={highlight.title}
                    width={17}
                    height={17}
                  />
                  {highlight.title}
                </div>
                <span className="block relative font-medium text-black dark:text-white ltr:pl-[20px] rtl:pr-[20px]">
                  <i
                    className={`material-symbols-outlined ${highlight.trendColor} !text-[18px] absolute ltr:left-0 rtl:right-0 top-1/2 -translate-y-1/2`}
                  >
                    {highlight.trendIcon}
                  </i>
                  {highlight.value}
                </span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  );
};

export default Highlights;

// angular-material/src/app/dashboard/marketing/highlights/highlights.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-highlights',
    imports: [MatCardModule],
    templateUrl: './highlights.component.html',
    styleUrl: './highlights.component.scss'
})
export class HighlightsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="highlights-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Highlights
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <span class="d-block text-body">
                Last 7 days
            </span>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <ul class="m-0 p-0 list-unstyled">
            <li class="d-flex align-items-center justify-content-between">
                <span class="title d-block position-relative">
                    <img src="images/icons/star.svg" alt="star">
                    Average Client Rating
                </span>
                <span class="trending d-block fw-medium text-black position-relative">
                    <i class="material-symbols-outlined">
                        arrow_upward
                    </i>
                    4.9/5.0
                </span>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <span class="title d-block position-relative">
                    <img src="images/icons/instagram.svg" alt="instagram">
                    Instagram Followers
                </span>
                <span class="trending down d-block fw-medium text-black position-relative">
                    <i class="material-symbols-outlined">
                        arrow_downward
                    </i>
                    630K
                </span>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <span class="title d-block position-relative">
                    <img src="images/icons/google2.svg" alt="google2">
                    Google Ads CPC
                </span>
                <span class="trending d-block fw-medium text-black position-relative">
                    <i class="material-symbols-outlined">
                        arrow_upward
                    </i>
                    $3.58
                </span>
            </li>
        </ul>
    </mat-card-content>
</mat-card>
