// nuxtjs-bootstrap/components/Dashboard/eCommerce/SalesByLocations.vue
<template>
  <div class="card bg-white border-0 rounded-3 mb-4">
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-4"
      >
        <h3 class="mb-0">Sales by Locations</h3>

        <div class="dropdown action-opt">
          <button
            class="btn bg-transparent p-0"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <MoreHorizontalIcon class="more-horizontal"></MoreHorizontalIcon>
          </button>

          <ul
            class="dropdown-menu dropdown-menu-end bg-white border box-shadow"
          >
            <li>
              <a class="dropdown-item" href="javascript:;">
                <ClockIcon class="clock"></ClockIcon>
                Today
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <PieChartIcon class="pie-chart"></PieChartIcon>
                Last 7 Days
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <RotateCwIcon class="rotate-cw"></RotateCwIcon>
                Last Month
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <CalendarIcon class="calendar"></CalendarIcon>
                Last 1 Year
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <BarChartIcon class="bar-chart"></BarChartIcon>
                All Time
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <EyeIcon class="eye"></EyeIcon>
                View
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="javascript:;">
                <TrashIcon class="trash"></TrashIcon>
                Delete
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="text-center mb-4">
        <img src="~/assets/images/map.svg" alt="map" />
      </div>
      <ul class="ps-0 mb-0 list-unstyled sales_by_locations mt-4">
        <li
          class="d-flex align-items-center"
          v-for="(country, index) in countries"
          :key="index"
        >
          <div class="flex-shrink-0">
            <img
              :src="country.image"
              class="wh-30 rounded-circle"
              :alt="country.name"
            />
          </div>
          <div class="flex-grow-1 ms-3">
            <span class="fw-medium d-block mb-2">{{ country.name }}</span>
            <div
              class="progress"
              role="progressbar"
              :aria-valuenow="country.progress"
              aria-valuemin="0"
              aria-valuemax="100"
            >
              <div
                class="progress-bar"
                :style="{ width: country.progress + '%' }"
              >
                <span class="count fw-medium text-body">
                  {{ country.progress }}%
                </span>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import image1 from "~/assets/images/usa.svg";
import image2 from "~/assets/images/germany.svg";
import image3 from "~/assets/images/united-kingdom.svg";
import image4 from "~/assets/images/canada.svg";
import image5 from "~/assets/images/portugal.svg";
import image6 from "~/assets/images/spain.svg";

const countries = [
  {
    name: "United States",
    image: image1,
    progress: 85,
  },
  {
    name: "Germany",
    image: image2,
    progress: 75,
  },
  {
    name: "United Kingdom",
    image: image3,
    progress: 40,
  },
  {
    name: "Canada",
    image: image4,
    progress: 10,
  },
  {
    name: "Portugal",
    image: image5,
    progress: 5,
  },
  {
    name: "Spain",
    image: image6,
    progress: 15,
  },
];
</script>

// react-bootstrap/src/components/Dashboard/eCommerce/SalesByLocations/index.js
"use client";

import { Dropdown, Card, ProgressBar } from "react-bootstrap";

const salesData = [
  {
    name: "United States",
    salesPercentage: 85,
    flag: "/images/usa.svg",
  },
  {
    name: "Germany",
    salesPercentage: 75,
    flag: "/images/germany.svg",
  },
  {
    name: "United Kingdom",
    salesPercentage: 40,
    flag: "/images/united-kingdom.svg",
  },
  {
    name: "Canada",
    salesPercentage: 10,
    flag: "/images/canada.svg",
  },
  {
    name: "Portugal",
    salesPercentage: 5,
    flag: "/images/portugal.svg",
  },
  {
    name: "Spain",
    salesPercentage: 15,
    flag: "/images/spain.svg",
  },
];

const SalesByLocations = () => {
  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-4">
            <h3 className="mb-0">Sales by Locations</h3>

            <Dropdown className="action-opt">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="bg-transparent p-0"
              >
                <i className="material-symbols-outlined">more_horiz</i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">schedule</i>
                  Today
                </Dropdown.Item>
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">pie_chart</i>
                  Last 7 Days
                </Dropdown.Item>
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">refresh</i>
                  Last Month
                </Dropdown.Item>
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">calendar_today</i>
                  Last 1 Year
                </Dropdown.Item>
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">bar_chart</i>
                  All Time
                </Dropdown.Item>
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">visibility</i>
                  View
                </Dropdown.Item>
                <Dropdown.Item href="#">
                  <i className="material-symbols-outlined">delete</i>
                  Delete
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <div className="text-center" style={{ marginBottom: '36px' }}>
            <img src='/images/vector-map.png' alt="vector-map" />
          </div>

          <ul className="ps-0 mb-0 list-unstyled sales_by_locations">
            {salesData.map((location, index) => (
              <li key={index} className="d-flex align-items-center">
                <div className="flex-shrink-0">
                  <img
                    src={location.flag}
                    className="rounded-circle"
                    alt={location.name}
                    width={30}
                    height={30}
                  />
                </div>
                <div className="flex-grow-1 ms-3">
                  <span className="fw-medium d-block mb-2">
                    {location.name}
                  </span>

                  <div>
                    <ProgressBar now={location.salesPercentage} />
                    <span className="count fw-medium text-body">
                      {location.salesPercentage}%
                    </span>
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </Card.Body>
      </Card>
    </>
  );
};

export default SalesByLocations;
