// nextjs-react-bootstrap/src/components/Dashboard/Hospital/HospitalEarnings/index.js
"use client";

import React, { useEffect, useState } from "react";
import { Row, Col, Card, Form } from "react-bootstrap";
import Image from "next/image";

const HospitalEarnings = () => {
  const [Chart, setChart] = useState();
  useEffect(() => {
    import("react-apexcharts").then((mod) => {
      setChart(() => mod.default);
    });
  }, []);

  const series = [
    {
      name: "Earnings",
      data: [3, 7, 7, 10, 9, 11, 20],
    },
  ];

  const options = {
    chart: {
      zoom: {
        enabled: false,
      },
      toolbar: {
        show: false,
      },
    },
    colors: ["#3584FC"],
    dataLabels: {
      enabled: false,
    },
    grid: {
      show: false,
      borderColor: "#ECEEF2",
    },
    stroke: {
      curve: "straight",
      width: 1,
    },
    xaxis: {
      categories: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      axisTicks: {
        show: false,
        color: "#ECEEF2",
      },
      axisBorder: {
        show: false,
        color: "#ECEEF2",
      },
      labels: {
        show: false,
        style: {
          colors: "#8695AA",
          fontSize: "12px",
        },
      },
    },
    yaxis: {
      show: false,
      labels: {
        formatter: (val) => {
          return "$" + val + "k";
        },
        style: {
          colors: "#64748B",
          fontSize: "12px",
        },
      },
      axisBorder: {
        show: false,
        color: "#ECEEF2",
      },
      axisTicks: {
        show: false,
        color: "#ECEEF2",
      },
    },
    legend: {
      show: false,
      position: "top",
      fontSize: "12px",
      horizontalAlign: "left",
      itemMargin: {
        horizontal: 8,
        vertical: 0,
      },
      labels: {
        colors: "#64748B",
      },
      markers: {
        size: 7,
        offsetX: -2,
        offsetY: -0.5,
        shape: "diamond",
      },
    },
  };

  return (
    <>
      <Card
        className="border-0 rounded-3 mb-4"
        style={{ backgroundColor: "#FFF5ED" }}
      >
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-30">
            <h3 className="mb-0">Hospital Earnings</h3>

            <Form.Select
              className="month-select form-control p-0 h-auto border-0 w-90 bg-transparent"
              aria-label="Default select example"
            >
              <option defaultValue="0">This Week</option>
              <option defaultValue="1">Last Month</option>
              <option defaultValue="2">Last Year</option>
            </Form.Select>
          </div>

          <Row className="align-items-center">
            <Col lg={5}>
              <div className="hospital-img pt-3 pb-4 text-center">
                <Image
                  src="/images/hospital.png"
                  alt="hospital"
                  width={280}
                  height={280}
                />
              </div>
            </Col>

            <Col lg={7}>
              <Row>
                <Col sm={6} xl={12} xxl={6}>
                  <Card className="bg-white p-4 border-0 rounded-3 mb-4 exchange-for-dark">
                    <h2 className="fs-24 fw-medium mb-1">$120,000</h2>
                    <p className="fs-12 mb-0">
                      Total Profit{" "}
                      <span className="text-danger ms-1">
                        {" "}
                        <i className="ri-arrow-down-fill"></i>5%
                      </span>
                    </p>
                  </Card>
                </Col>

                <Col sm={6} xl={12} xxl={6}>
                  <Card className="bg-white p-4 border-0 rounded-3 mb-4 exchange-for-dark">
                    <h2 className="fs-24 fw-medium mb-1">$80,000</h2>
                    <p className="fs-12 mb-0">
                      Total Costs{" "}
                      <span className="text-success ms-1">
                        {" "}
                        <i className="ri-arrow-up-fill"></i>3%
                      </span>
                    </p>
                  </Card>
                </Col>

                <Col sm={12}>
                  <div className="position-relative z-1">
                    <Card className="bg-white p-4 border-0 rounded-3 mb-0 exchange-for-dark">
                      <Row className="align-items-center">
                        <Col lg={7}>
                          <h2 className="fs-24 fw-medium mb-1">$900,000</h2>
                          <p className="fs-12 mb-0">
                            Total Earnings{" "}
                            <span className="text-success ms-1">
                              {" "}
                              <i className="ri-arrow-up-fill"></i>3%
                            </span>
                          </p>
                        </Col>

                        <Col lg={5}>
                          <div style={{ margin: "-30px -10px -30px 0" }}>
                            {Chart && (
                              <Chart
                                options={options}
                                series={series}
                                type="area"
                                height={95}
                              />
                            )}
                          </div>
                        </Col>
                      </Row>
                    </Card>

                    <div className="bg-white bg-opacity-75 p-2 p-md-3 mx-3 mx-md-5 rounded-bottom-3 exchange-for-dark"></div>
                  </div>
                </Col>
              </Row>
            </Col>
          </Row>
        </Card.Body>
      </Card>
    </>
  );
};

export default HospitalEarnings;

// laravel-vue/resources/components/Dashboard/Hospital/HospitalEarnings.vue
<template>
    <v-card
        class="hospital-earnings-card trezo-card border-radius d-block border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Hospital Earnings</h5>
            <v-menu>
                <template v-slot:activator="{ props }">
                    <button
                        type="button"
                        v-bind="props"
                        class="card-header-menu border-none p-0 d-inline-block border-radius"
                    >
                        This Week
                    </button>
                </template>
                <v-list class="menu-content">
                    <button type="button" class="bg-transparent border-none">
                        This Day
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Week
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Month
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Year
                    </button>
                </v-list>
            </v-menu>
        </div>
        <div class="hospital-earnings-card-content">
            <div class="row align-items-center">
                <div class="col-lg-5">
                    <div class="image text-center">
                        <v-img
                            src="/images/hospital.png"
                            alt="hospital-image"
                            class="justify-content-center"
                        />
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="content">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="box bg-white border-radius">
                                    <h3 class="fw-medium">$120,000</h3>
                                    <div class="d-flex align-items-center">
                                        <span class="d-block text-body">
                                            Total Profit
                                        </span>
                                        <span
                                            class="info-badge text-danger fw-medium position-relative"
                                        >
                                            <i class="ri-arrow-down-fill"></i>
                                            5%
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="box bg-white border-radius">
                                    <h3 class="fw-medium">$80,000</h3>
                                    <div class="d-flex align-items-center">
                                        <span class="d-block text-body">
                                            Total Costs
                                        </span>
                                        <span
                                            class="info-badge text-success fw-medium position-relative"
                                        >
                                            <i class="ri-arrow-up-fill"></i>
                                            3%
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div
                                    class="item bg-white border-radius position-relative"
                                >
                                    <h3 class="fw-medium">
                                        $900,000
                                        <span
                                            class="text-success position-relative"
                                        >
                                            <i class="ri-arrow-up-fill"></i>
                                            12%
                                        </span>
                                    </h3>
                                    <span class="d-block text-body">
                                        Total Earnings
                                    </span>
                                    <div class="chart">
                                        <apexchart
                                            type="area"
                                            height="95"
                                            :options="hospitalEarnings"
                                            :series="earnings"
                                        ></apexchart>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
    name: "HospitalEarnings",
    setup() {
        const earnings = ref([
            {
                name: "Earnings",
                data: [3, 7, 7, 10, 9, 11, 20],
            },
        ]);
        const hospitalEarnings = ref({
            chart: {
                type: "area",
                height: 95,
                zoom: {
                    enabled: false,
                },
                toolbar: {
                    show: false,
                },
            },
            colors: ["#3584FC"],
            dataLabels: {
                enabled: false,
            },
            grid: {
                show: false,
                borderColor: "#ECEEF2",
            },
            stroke: {
                curve: "straight",
                width: 1,
            },
            xaxis: {
                categories: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                axisTicks: {
                    show: false,
                    color: "#ECEEF2",
                },
                axisBorder: {
                    show: false,
                    color: "#ECEEF2",
                },
                labels: {
                    show: false,
                    style: {
                        colors: "#8695AA",
                        fontSize: "12px",
                    },
                },
            },
            yaxis: {
                // tickAmount: 6,
                show: false,
                // max: 150,
                // min: 0,
                labels: {
                    formatter: (val) => {
                        return "$" + val + "k";
                    },
                    style: {
                        colors: "#64748B",
                        fontSize: "12px",
                    },
                },
                axisBorder: {
                    show: false,
                    color: "#ECEEF2",
                },
                axisTicks: {
                    show: false,
                    color: "#ECEEF2",
                },
            },
            legend: {
                show: false,
                position: "top",
                fontSize: "12px",
                horizontalAlign: "left",
                itemMargin: {
                    horizontal: 8,
                    vertical: 0,
                },
                labels: {
                    colors: "#64748B",
                },
                markers: {
                    size: 7,
                    offsetX: -2,
                    offsetY: -0.5,
                    shape: "diamond",
                },
            },
        });

        return {
            earnings,
            hospitalEarnings,
        };
    },
});
</script>

<style lang="scss" scoped>
.hospital-earnings-card {
    background-color: #fff5ed !important;

    .hospital-earnings-card-content {
        .image {
            margin: {
                top: 8.5px;
                right: -8px;
                bottom: 8.5px;
            }
        }
        .content {
            padding-left: 15px;

            .box {
                padding: 17.5px 25px;
                margin-bottom: 25px;

                h3 {
                    font-size: 24px;
                    margin-bottom: 5px;
                }
                .info-badge {
                    padding-left: 15px;
                    margin-left: 8px;
                    font-size: 12px;

                    i {
                        left: 0;
                        top: 50%;
                        font-size: 14px;
                        position: absolute;
                        transform: translateY(-50%);
                    }
                }
            }
            .item {
                padding: 25px;
                margin-bottom: 15px;

                h3 {
                    font-size: 24px;
                    margin-bottom: 5px;

                    span {
                        padding-left: 15px;
                        font-size: 12px;
                        top: -4px;

                        i {
                            left: 0;
                            top: 50%;
                            font-size: 14px;
                            position: absolute;
                            transform: translateY(-50%);
                        }
                    }
                }
                &::before {
                    left: 0;
                    right: 0;
                    content: "";
                    height: 15px;
                    bottom: -15px;
                    opacity: 0.65;
                    position: absolute;
                    border-radius: 0 0 7px 7px;
                    background: var(--whiteColor);
                    margin: {
                        left: 25px;
                        right: 25px;
                    }
                }
                .chart {
                    top: 50%;
                    right: 20px;
                    margin-top: 5px;
                    max-width: 150px;
                    position: absolute;
                    transform: translateY(-50%);
                }
            }
        }
    }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
    .hospital-earnings-card {
        .hospital-earnings-card-content {
            .image {
                margin: {
                    top: 0;
                    right: 0;
                    bottom: 17px;
                }
            }
            .content {
                padding-left: 0;

                .box {
                    padding: 15px 17px;
                    margin-bottom: 15px;

                    h3 {
                        font-size: 20px;
                    }
                }
                .item {
                    padding: 15px 17px;

                    h3 {
                        font-size: 20px;
                    }
                    &::before {
                        margin: {
                            left: 17px;
                            right: 17px;
                        }
                    }
                    .chart {
                        right: 10px;
                        max-width: 120px;
                    }
                }
            }
        }
    }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
    .hospital-earnings-card {
        .hospital-earnings-card-content {
            .image {
                margin: {
                    bottom: 20px;
                }
            }
            .content {
                .box {
                    padding: {
                        left: 20px;
                        right: 20px;
                    }
                }
                .item {
                    padding: {
                        left: 20px;
                        right: 20px;
                    }
                    .chart {
                        right: 15px;
                    }
                }
            }
        }
    }
}
</style>
