// react-nextjs-tailwindcss/src/components/Dashboard/Podcast/Featured.tsx
"use client";

import React, { useState, useEffect } from "react";
import Image from "next/image";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination } from "swiper/modules";

// Define types for the featured item
type FeaturedItem = {
  title: string;
  description: string;
  host: string;
  guest: string;
  audioSrc: string;
  imageSrc: string;
  stats: {
    listens: string;
    likes: string;
    shares: string;
  };
};

// Define types for the audio state
type AudioState = {
  progress: number;
  currentTime: string;
  duration: string;
};

const Featured: React.FC = () => {
  const [featuredItems] = useState<FeaturedItem[]>([
    {
      title: "Mastering Digital Marketing",
      description:
        "Learn the latest digital marketing strategies with insights from SEO expert James Lee.",
      host: "Sarah J.",
      guest: "James Lee, SEO Expert",
      audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
      imageSrc: "/images/featured/featured1.png",
      stats: {
        listens: "8,200",
        likes: "1,500",
        shares: "350",
      },
    },
    {
      title: "Content Marketing Essentials",
      description:
        "This episode covers creating impactful content that resonates with audiences.",
      host: "Sarah J.",
      guest: "James Lee, SEO Expert",
      audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
      imageSrc: "/images/featured/featured2.png",
      stats: {
        listens: "8,200",
        likes: "1,500",
        shares: "350",
      },
    },
    {
      title: "Social Media Trends",
      description:
        "Learn the latest digital marketing strategies with insights from SEO expert James Lee.",
      host: "Sarah J.",
      guest: "James Lee, SEO Expert",
      audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
      imageSrc: "/images/featured/featured3.png",
      stats: {
        listens: "8,200",
        likes: "1,500",
        shares: "350",
      },
    },
  ]);

  const [currentlyPlaying, setCurrentlyPlaying] = useState<number | null>(null);
  const [audioStates, setAudioStates] = useState<{ [key: number]: AudioState }>(
    {}
  );
  const [waveHeights, setWaveHeights] = useState<{ [key: number]: number[] }>(
    {}
  );

  useEffect(() => {
    if (currentlyPlaying !== null) {
      const interval = setInterval(() => {
        setWaveHeights((prev) => {
          const newWaveHeights = { ...prev };
          newWaveHeights[currentlyPlaying] = Array(50)
            .fill(0)
            .map(() => Math.random() * 30);
          return newWaveHeights;
        });
      }, 100); // Update wave heights every 100ms
      return () => clearInterval(interval);
    }
  }, [currentlyPlaying]);

  const handlePlayPause = (index: number) => {
    const audioElement = document.getElementById(
      `audio-${index}`
    ) as HTMLAudioElement;

    if (currentlyPlaying !== null && currentlyPlaying !== index) {
      const previousAudioElement = document.getElementById(
        `audio-${currentlyPlaying}`
      ) as HTMLAudioElement;
      previousAudioElement.pause();
      previousAudioElement.currentTime = 0;
      setCurrentlyPlaying(null);
    }

    if (audioElement.paused) {
      audioElement.play();
      setCurrentlyPlaying(index);
    } else {
      audioElement.pause();
      setCurrentlyPlaying(null);
    }
  };

  const handleTimeUpdate = (index: number) => {
    const audioElement = document.getElementById(
      `audio-${index}`
    ) as HTMLAudioElement;
    const currentTime = audioElement.currentTime;
    const duration = audioElement.duration;
    const progress = (currentTime / duration) * 100;

    setAudioStates((prev) => ({
      ...prev,
      [index]: {
        progress,
        currentTime: formatTime(currentTime),
        duration: formatTime(duration),
      },
    }));
  };

  const handleLoadedMetadata = (index: number) => {
    const audioElement = document.getElementById(
      `audio-${index}`
    ) as HTMLAudioElement;
    const duration = audioElement.duration;

    setAudioStates((prev) => ({
      ...prev,
      [index]: {
        ...prev[index],
        duration: formatTime(duration),
      },
    }));
  };

  const handleEnded = (index: number) => {
    setCurrentlyPlaying(null);
    setAudioStates((prev) => ({
      ...prev,
      [index]: {
        ...prev[index],
        progress: 0,
        currentTime: "0:00",
      },
    }));
  };

  const formatTime = (time: number): string => {
    const minutes = Math.floor(time / 60);
    const seconds = Math.floor(time % 60);
    return `${minutes}:${seconds < 10 ? "0" : ""}${seconds}`;
  };

  return (
    <div
      className="trezo-card p-[20px] md:p-[25px] rounded-md relative z-[1]"
      style={{
        background: "linear-gradient(84deg, #23272E 3.5%, #526077 94.93%)",
      }}
    >
      <div className="trezo-card-header mb-[12px] flex items-center justify-between">
        <div className="trezo-card-title">
          <span className="inline-block text-xs text-white font-medium py-[1.5px] px-[15px] rounded-[30px] bg-gray-600">
            Featured
          </span>
        </div>
      </div>

      <div className="trezo-card-content relative">
        <Swiper
          slidesPerView={1}
          spaceBetween={10}
          pagination={{
            clickable: true,
          }}
          modules={[Pagination]}
          className="podcast-featured-slides"
        >
          {featuredItems.map((item, index) => (
            <SwiperSlide key={index}>
              <div className="grid grid-cols-1 md:grid-cols-2">
                <div>
                  <h1 className="text-[22px] md:text-2xl text-white font-medium mb-[7px]">
                    {item.title}
                  </h1>

                  <p className="md:max-w-[370px] text-gray-200">
                    {item.description}
                  </p>

                  <div className="-mt-[5px]">
                    <div className="inline-block text-gray-50 ltr:mr-[5px] rtl:ml-[5px] rounded-[30px] py-[3.5px] px-[12.5px] border border-gray-500 mt-[10px]">
                      <span className="text-white font-semibold">Host:</span>{" "}
                      {item.host}
                    </div>
                    <div className="inline-block text-gray-50 ltr:mr-[5px] rtl:ml-[5px] rounded-[30px] py-[3.5px] px-[12.5px] border border-gray-500 mt-[10px]">
                      <span className="text-white font-semibold">Guest:</span>{" "}
                      {item.guest}
                    </div>
                  </div>

                  <div
                    className="mt-[20px] md:mt-[30px] md:max-w-[370px]"
                    data-player
                    id={`musicPlayer-${index}`}
                  >
                    <audio
                      id={`audio-${index}`}
                      src={item.audioSrc}
                      onEnded={() => handleEnded(index)}
                      onTimeUpdate={() => handleTimeUpdate(index)}
                      onLoadedMetadata={() => handleLoadedMetadata(index)}
                    ></audio>
                    <div className="flex items-center gap-[15px]">
                      <button
                        type="button"
                        className="playPauseBtn flex items-center justify-center w-[44px] h-[44px] text-xl transition-all text-primary-500 bg-primary-200 rounded-full hover:bg-primary-500 hover:text-white dark:bg-dark"
                        onClick={() => handlePlayPause(index)}
                      >
                        <span className="playPauseIcon">
                          {currentlyPlaying === index ? "⏸" : "▶"}
                        </span>
                      </button>
                      
                      <div className="relative z-[1] grow">
                        <span className="current-time block ltr:text-left rtl:text-right text-white">
                          {audioStates[index]?.currentTime || "0:00"}
                        </span>
                        <span className="duration block ltr:text-right rtl:text-left text-white">
                          {audioStates[index]?.duration || "0:00"}
                        </span>
                        <div className="progress mt-[5px] h-[4px] w-full relative rounded-[30px] bg-gray-400">
                          <div
                            className="progress-bar bg-primary-500 h-full rounded-[30px]"
                            style={{
                              width: `${audioStates[index]?.progress || 0}%`,
                            }}
                          ></div>
                        </div>
                        <div className="wave-container flex items-center absolute rtl:left-0 rtl:right-0 bottom-0 -z-[1]">
                          {Array(50)
                            .fill(0)
                            .map((_, i) => (
                              <span
                                key={i}
                                className="wave-bar w-[2px] h-[30px] ltr:ml-px rtl:mr-px ltr:md:ml-[2.5px] rtl:md:mr-[2.5px] ltr:xl:ml-[3px] rtl:xl:mr-[3px] ltr:first:ml-0 rtl:first:mr-0 bg-gray-600 transition-all"
                                style={{
                                  height: `${waveHeights[index]?.[i] || 10}px`,
                                }}
                              ></span>
                            ))}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="text-center mx-auto mt-[20px] md:mt-0 md:max-w-[332.5px]">
                  <Image
                    src={item.imageSrc}
                    alt="featured-image"
                    width={332.5}
                    height={200}
                  />
                </div>
              </div>
              <div className="md:flex items-center md:mt-[20px] lg:mt-[9px] gap-[20px]">
                <div className="inline-block relative ltr:pl-[40px] rtl:pr-[40px] mt-[15px] ltr:mr-[15px] rtl:ml-[15px] ltr:md:mr-0 rtl:md:ml-0 md:mt-0">
                  <div className="ltr:left-0 rtl:right-0 absolute top-1/2 -translate-y-1/2 !text-3xl text-primary-400">
                    <i className="ri-customer-service-line"></i>
                  </div>
                  <span className="block font-medium text-xs text-gray-200">
                    Listens
                  </span>
                  <h6 className="mb-0 font-medium text-white text-base">
                    {item.stats.listens}
                  </h6>
                </div>
                <div className="inline-block relative ltr:pl-[40px] rtl:pr-[40px] mt-[15px] ltr:mr-[15px] rtl:ml-[15px] ltr:md:mr-0 rtl:md:ml-0 md:mt-0">
                  <div className="ltr:left-0 rtl:right-0 absolute top-1/2 -translate-y-1/2 !text-3xl text-primary-400">
                    <i className="ri-thumb-up-line"></i>
                  </div>
                  <span className="block font-medium text-xs text-gray-200">
                    Likes
                  </span>
                  <h6 className="mb-0 font-medium text-white text-base">
                    {item.stats.likes}
                  </h6>
                </div>
                <div className="inline-block relative ltr:pl-[40px] rtl:pr-[40px] mt-[15px] ltr:mr-[15px] rtl:ml-[15px] ltr:md:mr-0 rtl:md:ml-0 md:mt-0">
                  <div className="ltr:left-0 rtl:right-0 absolute top-1/2 -translate-y-1/2 !text-3xl text-primary-400">
                    <i className="ri-share-line"></i>
                  </div>
                  <span className="block font-medium text-xs text-gray-200">
                    Shares
                  </span>
                  <h6 className="mb-0 font-medium text-white text-base">
                    {item.stats.shares}
                  </h6>
                </div>
                <div className="inline-block relative ltr:pl-[40px] rtl:pr-[40px] mt-[15px] ltr:mr-[15px] rtl:ml-[15px] ltr:md:mr-0 rtl:md:ml-0 md:mt-0">
                  <div className="ltr:left-0 rtl:right-0 absolute top-1/2 -translate-y-1/2 !text-3xl text-primary-400">
                    <i className="ri-bookmark-line"></i>
                  </div>
                  <span className="block font-medium text-xs text-gray-200">
                    Save for
                  </span>
                  <h6 className="mb-0 font-medium text-white text-base">
                    Later
                  </h6>
                </div>
              </div>
            </SwiperSlide>
          ))}
        </Swiper>
      </div>

      <div className="absolute -z-[1] bottom-0 ltr:right-0 rtl:left-0 rtl:-scale-x-[1]">
        <Image
          src="/images/featured/featured-shape.png"
          alt="shape-image"
          width={200}
          height={200}
        />
      </div>
    </div>
  );
};

export default Featured;

// vuejs-vuetify/src/components/Dashboard/Podcast/Featured.vue
<template>
  <div
    class="border-0 rounded-3 border position-relative z-1 play-for-rtl"
    style="background: linear-gradient(84deg, #23272e 3.5%, #526077 94.93%)"
  >
    <div class="swiper-pagination-mastering-digital-marketing"></div>
    <Swiper
      :slidesPerView="1"
      :spaceBetween="25"
      :centeredSlides="false"
      :preventClicks="true"
      :loop="false"
      :autoplay="{
        delay: 15000,
        disableOnInteraction: true,
        pauseOnMouseEnter: true,
      }"
      :pagination="{
        el: '.swiper-pagination-mastering-digital-marketing',
        clickable: true,
      }"
      :modules="modules"
      class="mastering-digital-marketing-slide"
    >
      <SwiperSlide v-for="(slide, index) in slides" :key="index">
        <div class="px-4" style="padding-top: 37px; padding-bottom: 24px">
          <span
            class="bg-body-color-50 d-inline-block text-white fd-12 fw-medium rounded-pill mb-2"
            style="padding: 0 11px"
          >
            {{ slide.tag }}
          </span>
          <h3 class="fs-28 fw-medium text-white mb-1">
            {{ slide.title }}
          </h3>
          <p class="text-light" style="max-width: 370px; margin-bottom: 18px">
            {{ slide.description }}
          </p>
          <div class="d-flex flex-wrap ga-2 align-items-center">
            <div
              class="d-flex align-items-center rounded-pill"
              style="border: 1px solid #64748b; padding: 3.5px 12px"
            >
              <span class="fs-14 fw-semibold text-white">Host:</span>
              <span class="ms-2 text-white">{{ slide.host }}</span>
            </div>
            <div
              class="d-flex align-items-center rounded-pill"
              style="border: 1px solid #64748b; padding: 3.5px 12px"
            >
              <span class="fs-14 fw-semibold text-white">Guest:</span>
              <span class="ms-2 text-white">{{ slide.guest }}</span>
            </div>
          </div>

          <div class="audio-player-for-wave" style="padding: 47px 0">
            <div class="d-sm-flex align-items-center">
              <button
                class="play-button border-0 rounded-circle d-inline-block"
                style="
                  background-color: #c2cdff;
                  width: 44px;
                  height: 44px;
                  line-height: 43px;
                "
                @click="togglePlayPause(index)"
              >
                <i
                  class="play-icon text-primary fs-28 position-relative"
                  style="left: 2px"
                  :class="{
                    'ri-pause-fill': slide.isPlaying,
                    'ri-play-fill': !slide.isPlaying,
                  }"
                ></i>
              </button>
              <div class="ms-sm-3 mt-3 mt-sm-0">
                <div
                  class="d-flex align-items-center justify-content-between width-form-mobile"
                  style="width: 325px"
                >
                  <div class="wave-container d-flex align-items-end">
                    <span
                      v-for="(bar, barIndex) in 70"
                      :key="barIndex"
                      class="wave-bar"
                      :class="{ 'wave-animation': slide.isPlaying }"
                    ></span>
                  </div>
                  <span class="duration text-white">
                    {{ formatTime(slide.currentTime) }}
                  </span>
                </div>
                <div
                  class="progress"
                  role="progressbar"
                  aria-label="Audio Progress"
                  style="height: 4px; background-color: #8695aa"
                >
                  <div
                    class="progress-bar"
                    :style="{ width: `${slide.progress}%`, height: '4px' }"
                  ></div>
                </div>
              </div>
            </div>
            <audio
              :ref="`audioElement${index}`"
              class="audio-element"
              :src="slide.audioSrc"
              @timeupdate="updateProgress(index)"
              @ended="onAudioEnded(index)"
            ></audio>
          </div>

          <div class="d-flex flex-wrap ga-4 align-items-center">
            <div class="d-flex align-items-center">
              <div class="flex-shrink-0">
                <i
                  class="ri-customer-service-line fs-28 text-primary lh-1 position-relative top-2"
                ></i>
              </div>
              <div class="flex-grow-1 ms-10">
                <span class="text-light fs-12 fw-semibold lh-1">Listens</span>
                <span class="d-block text-white fs-14 fw-medium lh-1">
                  {{ slide.listens }}
                </span>
              </div>
            </div>
            <div class="d-flex align-items-center">
              <div class="flex-shrink-0">
                <i
                  class="ri-thumb-up-line fs-28 text-primary lh-1 position-relative top-2"
                ></i>
              </div>
              <div class="flex-grow-1 ms-10">
                <span class="text-light fs-12 fw-semibold lh-1">Likes</span>
                <span class="d-block text-white fs-14 fw-medium lh-1">
                  {{ slide.likes }}
                </span>
              </div>
            </div>
            <div class="d-flex align-items-center">
              <div class="flex-shrink-0">
                <i
                  class="ri-share-line fs-28 text-primary lh-1 position-relative top-2"
                ></i>
              </div>
              <div class="flex-grow-1 ms-10">
                <span class="text-light fs-12 fw-semibold lh-1">Shares</span>
                <span class="d-block text-white fs-14 fw-medium lh-1">
                  {{ slide.shares }}
                </span>
              </div>
            </div>
            <div class="d-flex align-items-center">
              <div class="flex-shrink-0">
                <i
                  class="ri-bookmark-line fs-28 text-primary lh-1 position-relative top-2"
                ></i>
              </div>
              <div class="flex-grow-1 ms-10">
                <span class="text-light fs-12 fw-semibold lh-1">Save for</span>
                <span class="d-block text-white fs-14 fw-medium lh-1">
                  Later
                </span>
              </div>
            </div>
          </div>
        </div>
        <v-img
          :src="slide.imageSrc"
          class="position-absolute bottom-0 end-0 z-n1 for-rtl-shape d-none d-md-block"
          alt="shape"
        />
      </SwiperSlide>
    </Swiper>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Autoplay, Pagination } from "swiper/modules";

export default defineComponent({
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Featured",
  components: {
    Swiper,
    SwiperSlide,
  },
  setup() {
    const slides = ref([
      {
        tag: "Featured",
        title: "Mastering Digital Marketing",
        description:
          "Learn the latest digital marketing strategies with insights from SEO expert James Lee.",
        host: "Sarah J.",
        guest: "James Lee, SEO Expert",
        audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
        imageSrc: require("@/assets/images/shape-15.png"),
        listens: 8200,
        likes: 1500,
        shares: 350,
        isPlaying: false,
        currentTime: 0,
        progress: 0,
      },
      {
        tag: "Featured",
        title: "Content Marketing Essentials",
        description:
          "This episode covers creating impactful content that resonates with audiences.",
        host: "Tom R.",
        guest: "Lisa Kim",
        audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
        imageSrc: require("@/assets/images/shape-16.png"),
        listens: 8200,
        likes: 1500,
        shares: 350,
        isPlaying: false,
        currentTime: 0,
        progress: 0,
      },
      {
        tag: "Featured",
        title: "Social Media Trends",
        description:
          "Learn the latest digital marketing strategies with insights from SEO expert James Lee.",
        host: "Amanda G.",
        guest: "David Chen",
        audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
        imageSrc: require("@/assets/images/shape-17.png"),
        listens: 8200,
        likes: 1500,
        shares: 350,
        isPlaying: false,
        currentTime: 0,
        progress: 0,
      },
    ]);

    const togglePlayPause = (index: number) => {
      const audioElement = document.querySelectorAll("audio")[
        index
      ] as HTMLAudioElement;
      if (audioElement) {
        slides.value.forEach((slide, i) => {
          if (i !== index) slide.isPlaying = false;
        });

        if (audioElement.paused) {
          audioElement.play();
          slides.value[index].isPlaying = true;
        } else {
          audioElement.pause();
          slides.value[index].isPlaying = false;
        }
      }
    };

    const updateProgress = (index: number) => {
      const audioElement = document.querySelectorAll("audio")[
        index
      ] as HTMLAudioElement;
      if (audioElement) {
        slides.value[index].progress =
          (audioElement.currentTime / audioElement.duration) * 100;
        slides.value[index].currentTime = audioElement.currentTime;
      }
    };

    const onAudioEnded = (index: number) => {
      slides.value[index].isPlaying = false;
      slides.value[index].progress = 0;
      slides.value[index].currentTime = 0;
    };

    const formatTime = (time: number) => {
      const minutes = Math.floor(time / 60);
      const seconds = Math.floor(time % 60);
      return `${minutes}:${seconds.toString().padStart(2, "0")}`;
    };

    return {
      slides,
      togglePlayPause,
      updateProgress,
      onAudioEnded,
      formatTime,
      modules: [Autoplay, Pagination],
    };
  },
});
</script>

<style scoped>
.wave-bar {
  width: 2px;
  height: 25px;
  background-color: #c2cdff;
  margin-left: 2px;
  animation: wave-animation 1s infinite ease-in-out;
  animation-play-state: paused;
}
.wave-bar:nth-child(odd) {
  animation-delay: 0.2s;
}
.wave-bar:nth-child(even) {
  animation-delay: 0.4s;
}
@keyframes wave-animation {
  0%,
  100% {
    transform: scaleY(1);
  }
  50% {
    transform: scaleY(2);
  }
}
.wave-animation {
  animation-play-state: running;
}
.text-primary {
  color: #605dff !important;
}
.text-light {
  --bs-text-opacity: 1;
  color: #d5d9e2 !important;
}
.progress-bar {
  display: flex;
  flex-direction: column;
  justify-content: center;
  overflow: hidden;
  text-align: center;
  white-space: nowrap;
  background-color: #0d6efd;
  transition: var(--transition);
}
</style>
