// angular-bootstrap/src/app/apps/to-do-list/to-do-list.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CustomizerSettingsService } from '../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-to-do-list',
    imports: [RouterLink],
    templateUrl: './to-do-list.component.html',
    styleUrl: './to-do-list.component.scss'
})
export class ToDoListComponent {

    // Popup Trigger
    classApplied = false;
    toggleClass() {
        this.classApplied = !this.classApplied;
    }

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<!-- Breadcrumb -->
<div class="breadcrumb-card mb-25 d-md-flex align-items-center justify-content-between">
    <h5 class="mb-0">
        To Do List
    </h5>
    <ol class="breadcrumb list-unstyled mt-0 mb-0 p-0">
        <li class="breadcrumb-item d-inline-block position-relative">
            <a routerLink="/dashboard" class="d-inline-block position-relative">
                <i class="material-symbols-outlined">
                    home
                </i>
                Dashboard
            </a>
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            Apps
        </li>
        <li class="breadcrumb-item d-inline-block position-relative">
            To Do List
        </li>
    </ol>
</div>

<!-- To Do List -->
<div
    class="apps-to-do-list-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <div class="trezo-card-header d-sm-flex align-items-center justify-content-between">
        <div class="trezo-card-title">
            <form class="search-box position-relative">
                <label class="text-black">
                    <i class="material-symbols-outlined">
                        search
                    </i>
                </label>
                <input type="text" class="input-search d-block w-100 border-radius" placeholder="Search task here.....">
            </form>
        </div>
        <div class="trezo-card-subtitle">
            <button class="add-btn d-inline-block transition fw-medium border-radius" type="button" (click)="toggleClass()">
                <span class="d-inline-block position-relative">
                    <i class="material-symbols-outlined">
                        add
                    </i>
                    Add New Task
                </span>
            </button>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="table-style-two">
            <div class="basic-table table-responsive">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th scope="col" class="fw-medium">
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </th>
                            <th scope="col" class="fw-medium">
                                ID
                            </th>
                            <th scope="col" class="fw-medium">
                                Task Title
                            </th>
                            <th scope="col" class="fw-medium">
                                Assigned To
                            </th>
                            <th scope="col" class="fw-medium">
                                Due Date
                            </th>
                            <th scope="col" class="fw-medium">
                                Priority
                            </th>
                            <th scope="col" class="fw-medium">
                                Status
                            </th>
                            <th scope="col" class="fw-medium">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body">
                                #854
                            </td>
                            <td>
                                <span class="d-block fw-medium text-body">
                                    Network Infrastructure
                                </span>
                            </td>
                            <td>
                                Oliver Clark
                            </td>
                            <td class="text-body">
                                30 Apr 2025
                            </td>
                            <td class="text-body">
                                High
                            </td>
                            <td>
                                <span class="trezo-badge">
                                    Finished
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body">
                                #853
                            </td>
                            <td>
                                <span class="d-block fw-medium text-body">
                                    Cloud Migration
                                </span>
                            </td>
                            <td>
                                Ethan Baker
                            </td>
                            <td class="text-body">
                                25 Apr 2025
                            </td>
                            <td class="text-body">
                                Low
                            </td>
                            <td>
                                <span class="trezo-badge pending">
                                    Pending
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body">
                                #852
                            </td>
                            <td>
                                <span class="d-block fw-medium text-body">
                                    Website Revamp
                                </span>
                            </td>
                            <td>
                                Sophia Carter
                            </td>
                            <td class="text-body">
                                20 Apr 2025
                            </td>
                            <td class="text-body">
                                Medium
                            </td>
                            <td>
                                <span class="trezo-badge inProgress">
                                    In Progress
                                </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #851 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> Mobile Application </span>
                            </td>
                            <td> Ava Cooper </td>
                            <td class="text-body"> 15 Apr 2025 </td>
                            <td class="text-body"> High </td>
                            <td>
                                <span class="trezo-badge"> Finished </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #850 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> System Deployment </span>
                            </td>
                            <td> Isabella Evans </td>
                            <td class="text-body"> 10 Apr 2025 </td>
                            <td class="text-body"> Low </td>
                            <td>
                                <span class="trezo-badge cancelled"> Cancelled </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #849 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> Hotel Management System </span>
                            </td>
                            <td> Shawn Kennedy </td>
                            <td class="text-body"> 30 Apr 2025 </td>
                            <td class="text-body"> High </td>
                            <td>
                                <span class="trezo-badge"> Finished </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #848 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> Send Proposal to APR Ltd </span>
                            </td>
                            <td> Roberto Cruz </td>
                            <td class="text-body"> 25 Apr 2025 </td>
                            <td class="text-body"> Low </td>
                            <td>
                                <span class="trezo-badge pending"> Pending </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #847 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> Python Upgrade </span>
                            </td>
                            <td> Juli Johnson </td>
                            <td class="text-body"> 20 Apr 2025 </td>
                            <td class="text-body"> Medium </td>
                            <td>
                                <span class="trezo-badge inProgress"> In Progress </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #846 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> Schedule meeting with Trezo </span>
                            </td>
                            <td> Catalina Engles </td>
                            <td class="text-body"> 15 Apr 2025 </td>
                            <td class="text-body"> High </td>
                            <td>
                                <span class="trezo-badge"> Finished </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-check mb-0">
                                    <input class="form-check-input" type="checkbox">
                                </div>
                            </td>
                            <td class="text-body"> #845 </td>
                            <td>
                                <span class="d-block fw-medium text-body"> Engineering Lite Touch </span>
                            </td>
                            <td> Louis Nagle </td>
                            <td class="text-body"> 10 Apr 2025 </td>
                            <td class="text-body"> Low </td>
                            <td>
                                <span class="trezo-badge cancelled"> Cancelled </span>
                            </td>
                            <td>
                                <div class="action-buttons d-flex align-items-center">
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> visibility </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> edit </i>
                                    </button>
                                    <button type="button" class="p-0 bg-transparent d-inline-block lh-1 border-0">
                                        <i class="material-symbols-outlined"> delete </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Add New Popup -->
<div
    class="add-new-popup"
    [class.active]="classApplied"
>
    <div class="popup-dialog">
        <div class="trezo-card w-100 border-radius d-block bg-white border-0 shadow-none">
            <div class="trezo-card-header d-flex align-items-center justify-content-between">
                <div class="trezo-card-title">
                    <h5 class="mb-0">
                        Add New Task
                    </h5>
                </div>
                <div class="trezo-card-subtitle">
                    <button
                        (click)="toggleClass()"
                        class="p-0 border-0 lh-1 bg-transparent transition"
                    >
                        <i class="ri-close-fill"></i>
                    </button>
                </div>
            </div>
            <div class="trezo-card-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Task Name
                            </label>
                            <input type="text" class="form-control" placeholder="Task name">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Assigned To
                            </label>
                            <select class="form-select">
                                <option selected>
                                    Select
                                </option>
                                <option value="1">
                                    Shawn Kennedy
                                </option>
                                <option value="2">
                                    Roberto Cruz
                                </option>
                                <option value="3">
                                    Juli Johnson
                                </option>
                                <option value="4">
                                    Catalina Engles
                                </option>
                                <option value="5">
                                    Louis Nagle
                                </option>
                                <option value="6">
                                    Michael Marquez
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Due Date
                            </label>
                            <input type="date" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Priority
                            </label>
                            <select class="form-select">
                                <option selected>
                                    Select
                                </option>
                                <option value="1">
                                    High
                                </option>
                                <option value="2">
                                    Medium
                                </option>
                                <option value="3">
                                    Low
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Status
                            </label>
                            <select class="form-select">
                                <option selected>
                                    Select
                                </option>
                                <option value="1">
                                    In Progress
                                </option>
                                <option value="2">
                                    Pending
                                </option>
                                <option value="3">
                                    Completed
                                </option>
                                <option value="4">
                                    Not Started
                                </option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="btn-box">
                    <button
                        (click)="toggleClass()"
                        class="warn d-inline-block fw-medium border-0 border-radius transition"
                    >
                        Cancel
                    </button>
                    <button class="primary d-inline-block fw-medium border-0 border-radius transition">
                        <span class="position-relative d-inline-block">
                            <i class="material-symbols-outlined">
                                add
                            </i>
                            Create
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

// laravel-vue/resources/components/Apps/ToDoList/index.vue
<template>
    <v-card
        class="to-do-list-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <form class="search-box position-relative" @submit.prevent>
                <input
                    type="text"
                    class="input-search d-block"
                    placeholder="Search task here....."
                    v-model="searchTerm"
                />
                <button type="submit">
                    <i class="material-symbols-outlined">search</i>
                </button>
            </form>
            <AddNewTask />
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th class="text-start">
                                <v-checkbox color="primary"></v-checkbox>
                            </th>
                            <th class="text-start">ID</th>
                            <th class="text-start">Ticket Title</th>
                            <th class="text-start">Assigned To</th>
                            <th class="text-start">Due Date</th>
                            <th class="text-start">Priority</th>
                            <th class="text-start">Status</th>
                            <th class="text-start">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in filteredItems" :key="item.id">
                            <td><v-checkbox color="primary"></v-checkbox></td>
                            <td class="text-start">
                                {{ item.id }}
                            </td>
                            <td>
                                <span class="d-block fw-medium text-body">
                                    {{ item.taskTitle }}
                                </span>
                            </td>
                            <td>{{ item.assignedTo }}</td>
                            <td>{{ item.dueDate }}</td>
                            <td>{{ item.priority }}</td>
                            <td>
                                <span
                                    class="trezo-status-badge"
                                    :class="computeClass(item.status)"
                                >
                                    {{ item.status }}
                                </span>
                            </td>
                            <td>
                                <div
                                    class="action-buttons d-flex align-items-center"
                                >
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.view }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.edit }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.delete }}
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref, computed } from "vue";
import AddNewTask from "./AddNewTask.vue";

export default defineComponent({
    name: "ToDoList",
    components: {
        AddNewTask,
    },
    setup() {
        const items = ref([
            {
                id: "#854",
                taskTitle: "Network Infrastructure",
                assignedTo: "Oliver Clark",
                dueDate: "30 Apr 2024",
                priority: "High",
                status: "Finished",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#853",
                taskTitle: "Cloud Migration",
                assignedTo: "Ethan Baker",
                dueDate: "25 Apr 2024",
                priority: "Low",
                status: "Pending",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#852",
                taskTitle: "Website Revamp",
                assignedTo: "Sophia Carter",
                dueDate: "20 Apr 2024",
                priority: "Medium",
                status: "In Progress",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#851",
                taskTitle: "Mobile Application",
                assignedTo: "Ava Cooper",
                dueDate: "15 Apr 2024",
                priority: "High",
                status: "Finished",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#850",
                taskTitle: "System Deployment",
                assignedTo: "Isabella Evans",
                dueDate: "10 Apr 2024",
                priority: "Low",
                status: "Cancelled",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#849",
                taskTitle: "Hotel Management System",
                assignedTo: "Shawn Kennedy",
                dueDate: "30 Apr 2024",
                priority: "High",
                status: "Finished",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#848",
                taskTitle: "Send Proposal to APR Ltd",
                assignedTo: "Roberto Cruz",
                dueDate: "25 Apr 2024",
                priority: "Low",
                status: "pending",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#847",
                taskTitle: "Python Upgrade",
                assignedTo: "Juli Johnson",
                dueDate: "20 Apr 2024",
                priority: "Medium",
                status: "In Progress",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#846",
                taskTitle: "Schedule meeting with Trezo",
                assignedTo: "Catalina Engles",
                dueDate: "15 Apr 2024",
                priority: "High",
                status: "Finished",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#845",
                taskTitle: "Engineering Lite Touch",
                assignedTo: "Louis Nagle",
                dueDate: "10 Apr 2024",
                priority: "Low",
                status: "Cancelled",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
        ]);

        const searchTerm = ref("");

        const filteredItems = computed(() => {
            return items.value.filter(
                (item) =>
                    item.id
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.taskTitle
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.assignedTo
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.dueDate
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.priority
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.status
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase())
            );
        });

        const wordConfirmed = ref("Finished");
        const wordPending = ref("Pending");
        const wordInProgress = ref("In Progress");
        const wordRejected = ref("Cancelled");

        const computeClass = (classValue) => {
            return {
                confirmed: wordConfirmed.value === classValue,
                inProgress: wordInProgress.value === classValue,
                pending: wordPending.value === classValue,
                rejected: wordRejected.value === classValue,
            };
        };

        return {
            items,
            searchTerm,
            filteredItems,
            computeClass,
        };
    },
});
</script>

<style lang="scss" scoped>
.to-do-list-card {
    .trezo-table-content {
        .trezo-table {
            margin-left: -25px;
            margin-right: -25px;
            table {
                thead {
                    tr {
                        th {
                            background-color: #ecf0ff !important;
                            padding: {
                                top: 13px;
                                bottom: 13px;
                            }
                            &:first-child {
                                border-top-left-radius: 0 !important;
                                padding: {
                                    left: 25px;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                border-top-right-radius: 0;
                                padding-right: 25px;
                            }
                            .v-checkbox.v-input {
                                margin: -26px -33px -30px -7px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                    }
                }
                tbody {
                    tr {
                        td {
                            &:first-child {
                                border-left-width: 0 !important;
                                padding: {
                                    left: 25px !important;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                padding-right: 25px;
                                border-right-width: 0 !important;
                            }
                            .v-checkbox.v-input {
                                margin: -10px -30px -30px -7px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                    }
                }
            }
        }
    }
    .add-new-task-btn {
        height: auto;
        min-width: auto;
        font-weight: 500;
        padding: 5px 13px;
        border-radius: 7px;
        display: inline-block;
        color: var(--primaryColor);
        border: 1px solid var(--primaryColor);
        position: relative;
        padding-left: 30px;
        margin: {
            top: 15px;
        }
        i {
            top: 50%;
            left: 7px;
            font-size: 22px;
            position: absolute;
            transform: translateY(-50%);
        }
    }
}

// Max Width 767px
@media only screen and (max-width: 767px) {
    .to-do-list-card {
        .v-card-header {
            display: block;
            .search-box {
                margin-bottom: 12px;
            }
        }
    }
}
</style>
