// react-material-ui/src/components/Dashboard/Marketing/CostPerClick/index.js
"use client";

import { Card, Box, Typography } from "@mui/material";

const CostPerClick = () => {
  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: "10px",
            gap: "10px",
          }}
        >
          <div>
            <Typography sx={{ display: "block", mb: "6px" }}>
              Cost Per Click
            </Typography>
            <Typography
              component="h3"
              sx={{
                fontSize: { xs: "20px", md: "28px", lg: "32px" },
                mb: "0",
                fontWeight: 700,
                lineHeight: "1",
              }}
            >
              $0.15
            </Typography>
          </div>
          <img
            src="/images/icons/call-to-action.gif"
            alt="call-to-action"
            width={60}
            height={60}
            className="-mr-10"
          />
        </Box>

        <Typography
          component="span"
          className="text-danger"
          sx={{
            bgcolor: "#ffe1dd",
            border: "1px solid #ffcea9",
            borderRadius: "100px",
            fontSize: "13px",
            padding: "2.5px 8px",
            display: "inline-block",
            lineHeight: "1",
          }}
        >
          -0.04%
        </Typography>

        <Typography
          component="span"
          sx={{
            display: "block",
            fontSize: "12px",
            mt: "10px",
          }}
        >
          vs previous 30 days
        </Typography>
      </Card>
    </>
  );
};

export default CostPerClick;

// angular-tailwindcss/src/app/dashboard/marketing/cost-per-click/cost-per-click.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-cost-per-click',
    imports: [],
    templateUrl: './cost-per-click.component.html',
    styleUrl: './cost-per-click.component.scss'
})
export class CostPerClickComponent {}
<div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-content">
        <div class="flex items-center justify-between mb-[10px]">
            <div>
                <span class="block mb-[6px]">
                    Cost Per Click
                </span>
                <h3 class="leading-none text-xl md:text-2xl lg:text-3xl mb-0">
                    $0.15
                </h3>
            </div>
            <img src="images/icons/call-to-action.gif" class="w-[60px] ltr:-mr-[10px] rtl:-ml-[10px]" alt="call-to-action">
        </div>
        <span class="inline-block text-xs px-[9px] text-orange-700 border border-orange-300 bg-orange-100 text-sm rounded-[100px]">
            -0.04%
        </span>
        <span class="block text-xs mt-[10px]">
            vs previous 30 days
        </span>
    </div>
</div>
