// angular-tailwindcss/src/app/dashboard/lms/top-instructors/top-instructors.component.ts
import { Component, HostListener } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgIf } from '@angular/common';

@Component({
    selector: 'app-top-instructors',
    imports: [RouterLink, NgIf],
    templateUrl: './top-instructors.component.html',
    styleUrl: './top-instructors.component.scss'
})
export class TopInstructorsComponent {

    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-dropdown')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div class="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
        <div class="trezo-card-title">
            <h5 class="mb-0">
                Top Instructors
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-dropdown relative">
                <button type="button" class="trezo-card-dropdown-btn inline-block transition-all text-[26px] text-gray-500 dark:text-gray-400 leading-none hover:text-primary-500" (click)="toggleCardHeaderMenu()">
                    <i class="ri-more-fill"></i>
                </button>
                <ul class="trezo-card-dropdown-menu transition-all bg-white shadow-3xl rounded-md top-full py-[15px] absolute ltr:right-0 rtl:left-0 w-[195px] z-[5] dark:bg-dark dark:shadow-none" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Day
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Week
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Month
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Year
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content -mx-[20px] md:-mx-[25px]">
        <div class="table-responsive overflow-x-auto">
            <table class="w-full">
                <thead class="text-black dark:text-white">
                    <tr>
                        <th class="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                            Name
                        </th>
                        <th class="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                            Courses
                        </th>
                        <th class="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                            Ratings
                        </th>
                    </tr>
                </thead>
                <tbody class="text-black dark:text-white">
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="flex items-center">
                                <div class="w-[44px] h-[44px] ltr:mr-[12px] rtl:ml-[12px]">
                                    <img src="images/users/user13.jpg" class="rounded-full inline-block" alt="user-image">
                                </div>
                                <div>
                                    <span class="block font-medium">
                                        Olivia Clark
                                    </span>
                                    <span class="text-gray-500 dark:text-gray-400 block mt-px">
                                        Big Data
                                    </span>
                                </div>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <span class="text-gray-500 dark:text-gray-400">
                                55
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="text-[15px] leading-none text-orange-400">
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="flex items-center">
                                <div class="w-[44px] h-[44px] ltr:mr-[12px] rtl:ml-[12px]">
                                    <img src="images/users/user16.jpg" class="rounded-full inline-block" alt="user-image">
                                </div>
                                <div>
                                    <span class="block font-medium">
                                        Ava Turner
                                    </span>
                                    <span class="text-gray-500 dark:text-gray-400 block mt-px">
                                        UX/UI
                                    </span>
                                </div>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <span class="text-gray-500 dark:text-gray-400">
                                120
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="text-[15px] leading-none text-orange-400">
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-half-fill"></i>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="flex items-center">
                                <div class="w-[44px] h-[44px] ltr:mr-[12px] rtl:ml-[12px]">
                                    <img src="images/users/user17.jpg" class="rounded-full inline-block" alt="user-image">
                                </div>
                                <div>
                                    <span class="block font-medium">
                                        Lucas Morgan
                                    </span>
                                    <span class="text-gray-500 dark:text-gray-400 block mt-px">
                                        Developer
                                    </span>
                                </div>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <span class="text-gray-500 dark:text-gray-400">
                                86
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="text-[15px] leading-none text-orange-400">
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-line"></i>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="flex items-center">
                                <div class="w-[44px] h-[44px] ltr:mr-[12px] rtl:ml-[12px]">
                                    <img src="images/users/user18.jpg" class="rounded-full inline-block" alt="user-image">
                                </div>
                                <div>
                                    <span class="block font-medium">
                                        Isabella Cooper
                                    </span>
                                    <span class="text-gray-500 dark:text-gray-400 block mt-px">
                                        Designer
                                    </span>
                                </div>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <span class="text-gray-500 dark:text-gray-400">
                                75
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                            <div class="text-[15px] leading-none text-orange-400">
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-fill"></i>
                                <i class="ri-star-half-fill"></i>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="px-[20px] md:px-[25px] pt-[12px] md:pt-[14px] flex items-center justify-between">
            <p class="mb-0 text-sm">
                Items per pages: <strong>5</strong>
            </p>
            <div class="flex items-center">
                <p class="mb-0 text-sm">
                    1 – 5 of 10
                </p>
                <ol class="ltr:ml-[10px] rtl:mr-[10px]">
                    <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                        <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                            <span class="opacity-0">
                                0
                            </span>
                            <i class="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                                chevron_left
                            </i>
                        </a>
                    </li>
                    <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                        <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                            <span class="opacity-0">
                                0
                            </span>
                            <i class="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                                chevron_right
                            </i>
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

// react-nextjs-tailwindcss/src/components/Dashboard/LMS/TopInstructors.tsx
"use client";

import React, { useState } from "react";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";
import Image from "next/image";

type Instructor = {
  id: number;
  name: string;
  specialization: string;
  image: string;
  courses: number;
  ratings: number; // Number of full ratings out of 5
};

const initialInstructors: Instructor[] = [
  {
    id: 1,
    name: "Olivia Clark",
    specialization: "Big Data",
    image: "/images/users/user13.jpg",
    courses: 55,
    ratings: 5,
  },
  {
    id: 2,
    name: "Ava Turner",
    specialization: "UX/UI",
    image: "/images/users/user16.jpg",
    courses: 120,
    ratings: 4.5,
  },
  {
    id: 3,
    name: "Lucas Morgan",
    specialization: "Developer",
    image: "/images/users/user17.jpg",
    courses: 86,
    ratings: 4,
  },
  {
    id: 4,
    name: "Isabella Cooper",
    specialization: "Designer",
    image: "/images/users/user18.jpg",
    courses: 75,
    ratings: 4.5,
  },
  {
    id: 5,
    name: "Sophia Brown",
    specialization: "Marketing",
    image: "/images/users/user19.jpg",
    courses: 98,
    ratings: 5,
  },
  {
    id: 6,
    name: "Olivia Clark",
    specialization: "Big Data",
    image: "/images/users/user20.jpg",
    courses: 55,
    ratings: 5,
  },
  {
    id: 7,
    name: "Lucas Morgan",
    specialization: "Developer",
    image: "/images/users/user21.jpg",
    courses: 86,
    ratings: 4,
  },
  {
    id: 8,
    name: "Ava Turner",
    specialization: "UX/UI",
    image: "/images/users/user22.jpg",
    courses: 120,
    ratings: 4.5,
  },
];

const ITEMS_PER_PAGE = 4;

const TopInstructors: React.FC = () => {
  // selectedOption state
  const [selectedOption, setSelectedOption] = useState<string>("Last 6 Months");

  const handleSelect = (option: string) => {
    setSelectedOption(option);
    console.log(`Selected option: ${option}`); // Add your logic here
  };

  // Table
  const [currentPage, setCurrentPage] = useState(1);
  const totalPages = Math.ceil(initialInstructors.length / ITEMS_PER_PAGE);

  const displayedInstructors = initialInstructors.slice(
    (currentPage - 1) * ITEMS_PER_PAGE,
    currentPage * ITEMS_PER_PAGE
  );

  const handlePageChange = (direction: "prev" | "next") => {
    setCurrentPage((prev) => {
      if (direction === "prev" && prev > 1) return prev - 1;
      if (direction === "next" && prev < totalPages) return prev + 1;
      return prev;
    });
  };

  return (
    <>
      <div className="trezo-card bg-white dark:bg-[#0c1427] mb-[25px] p-[20px] md:p-[25px] rounded-md">
        <div className="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
          <div className="trezo-card-title">
            <h5 className="mb-0">Top Instructors</h5>
          </div>

          <div className="trezo-card-subtitle">
            <Menu as="div" className="trezo-card-dropdown relative">
              <MenuButton className="trezo-card-dropdown-btn inline-block transition-all text-[26px] text-gray-500 dark:text-gray-400 leading-none hover:text-primary-500">
                <i className="ri-more-fill"></i>
              </MenuButton>

              <MenuItems
                transition
                className=" transition-all bg-white shadow-3xl rounded-md top-full py-[15px] absolute ltr:right-0 rtl:left-0 w-[195px] z-[50] dark:bg-dark dark:shadow-none data-[closed]:scale-95 data-[closed]:transform data-[closed]:opacity-0 data-[enter]:duration-100 data-[leave]:duration-75 data-[enter]:ease-out data-[leave]:ease-in"
              >
                {["This Day", "This Week", "This Month", "This Year"].map(
                  (option) => (
                    <MenuItem
                      key={option}
                      as="div"
                      className={`block w-full transition-all text-black cursor-pointer ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black ${
                        selectedOption === option ? "font-semibold" : ""
                      }`}
                      onClick={() => handleSelect(option)}
                    >
                      {option}
                    </MenuItem>
                  )
                )}
              </MenuItems>
            </Menu>
          </div>
        </div>

        <div className="trezo-card-content -mx-[20px] md:-mx-[25px]">
          <div className="table-responsive overflow-x-auto">
            <table className="w-full">
              <thead className="text-black dark:text-white">
                <tr>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Name
                  </th>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Courses
                  </th>
                  <th className="font-medium ltr:text-left rtl:text-right px-[20px] py-[11px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 bg-primary-50 dark:bg-[#15203c] whitespace-nowrap">
                    Ratings
                  </th>
                </tr>
              </thead>

              <tbody className="text-black dark:text-white">
                {displayedInstructors.map((instructor) => (
                  <tr key={instructor.id}>
                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <div className="flex items-center">
                        <div className="w-[44px] h-[44px] ltr:mr-[12px] rtl:ml-[12px]">
                          <Image
                            src={instructor.image}
                            className="rounded-full inline-block"
                            alt={`${instructor.name}`}
                            width={44}
                            height={44}
                          />
                        </div>
                        <div>
                          <span className="block font-medium">
                            {instructor.name}
                          </span>
                          <span className="text-gray-500 dark:text-gray-400 block mt-px">
                            {instructor.specialization}
                          </span>
                        </div>
                      </div>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <span className="text-gray-500 dark:text-gray-400">
                        {instructor.courses}
                      </span>
                    </td>

                    <td className="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[15px] md:ltr:first:pl-[25px] md:rtl:first:pr-[25px] ltr:first:pr-0 rtl:first:pl-0 border-b border-gray-100 dark:border-[#172036]">
                      <div className="text-[15px] leading-none text-orange-400">
                        {Array.from({ length: 5 }, (_, i) =>
                          i < Math.floor(instructor.ratings) ? (
                            <i key={i} className="ri-star-fill"></i>
                          ) : instructor.ratings > i ? (
                            <i key={i} className="ri-star-half-fill"></i>
                          ) : (
                            <i key={i} className="ri-star-line"></i>
                          )
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="px-[20px] md:px-[25px] pt-[12px] md:pt-[14px] flex items-center justify-between">
            <p className="mb-0 text-sm">
              Items per pages: <strong>{ITEMS_PER_PAGE}</strong>
            </p>

            <div className="flex items-center">
              <p className="mb-0 text-sm">
                {" "}
                {ITEMS_PER_PAGE * (currentPage - 1) + 1} –{" "}
                {Math.min(
                  ITEMS_PER_PAGE * currentPage,
                  initialInstructors.length
                )}{" "}
                of {initialInstructors.length}
              </p>

              <ol className="ltr:ml-[10px] rtl:mr-[10px]">
                <li className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                  <button
                    className="w-[31px] h-[31px] block leading-[31px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500"
                    disabled={currentPage === 1}
                    onClick={() => handlePageChange("prev")}
                  >
                    <span className="opacity-0">0</span>
                    <i className="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                      chevron_left
                    </i>
                  </button>
                </li>
                <li className="inline-block mx-[2px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                  <button
                    className="w-[31px] h-[31px] block leading-[31px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500"
                    disabled={currentPage === totalPages}
                    onClick={() => handlePageChange("next")}
                  >
                    <span className="opacity-0">0</span>
                    <i className="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                      chevron_right
                    </i>
                  </button>
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TopInstructors;
